wasm/vm_num_test.go
about issue #6 : I started writing some tests , let me know what you think.
I have a question about testing "signed" operations; how do you manage it when the stack can contain only uint64 values ?
=> add some tests for num instructions 

wasm/buildoptions/callstack_overflow_disabled.go, wasm/buildoptions/callstack_overflow_enabled.go, wasm/buildoptions/stackoverflow.go, wasm/naivevm/vm_stack.go, wasm/naivevm/vm_stack_test.go, wasm/wazeroir/interpreter.go, wasm/wazeroir/interpreter_test.go
This removes risk of compilation drift by removing the option to disable stack overflow protection.
=> Removes option to disable stack overflow guard

README.md
=> Update REAMDE to reflect the JIT engine status.

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: support select instruction

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_value_location_amd64.go
=> jit: support Swap instruction

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: add support for i32,f32,f64 const instructions.

wasm/wat/lexer.go, wasm/wat/lexer_test.go
This changes the lex API to return the line and column number it stopped
at. This removes a lot of redundant formatting code and allow users to
control error formatting centrally.
=> Centralizes error handling of line and column numbers 

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_value_location_amd64.go, wasm/wazeroir/compiler.go, wasm/wazeroir/interpreter.go, wasm/wazeroir/operations.go, wasm/wazeroir/signature.go
per https://github.com/tetratelabs/wazero/pull/86#discussion_r774400193
=> ir: rename sign{ful,less} -> signed,unsigned

wasm/jit/RATIONALE.md, wasm/jit/engine.go, wasm/jit/engine_test.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_value_location_amd64.go
per https://github.com/tetratelabs/wazero/pull/86#discussion_r774401112
=> jit: remove 'current' prefixes on engine

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_value_location_amd64.go, wasm/wazeroir/compiler.go, wasm/wazeroir/signature.go
=> jit: support for load{8,16,32}

wasm/jit/jit_amd64.go
=> jit: fix comments on load code generations.

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: support for less than equal for floats.

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
This completes the support of add/sub operations for all types!
=> jit: add more test cases for add/sub operations.

wasm/jit/compiler.go, wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: support for Ge instruction

wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: enhance doc for mul

wasm/jit/compiler.go, wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: support for clz, ctz and popcnt

wasm/jit/compiler.go, wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/wazeroir/interpreter.go, wasm/wazeroir/operations.go
=> jit: support for various float operations part2

wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
This PR completes the baseline implementation of float operations.
=> jit: support for integer truncation from floats

wasm/jit/engine_test.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
part of #100, and introduce some utility func. Plus I deleted some of the non-representative tests which I initially wrote to test JIT's feasibility.
=> jit: refactor tests

README.md
Thanks for this awesome project ✨
=> docs: fix fibonacci example link

wasi/wasi.go
=> wasi: typo fix (#156)

.gitattributes
=> Ignore spectest cases from lang stat

wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit: implement memory.size in assembly.

RATIONALE.md, wasm/jit/jit_amd64.go, wasm/store.go, wasm/store_test.go
=> Add limits on number of function instances in a store

tests/bench/bench_fac_iter_test.go, tests/codec/codec_test.go
=> build: 'make test' available on arm64

examples/fibonacci_test.go, examples/file_system_test.go, examples/host_func_test.go, examples/stdio_test.go, tests/bench/bench_test.go, tests/engine/adhoc_test.go, tests/spectest/spec_test.go, tests/wasi/wasi_test.go
=> Use goembed for all tests

wasm/jit/jit_amd64.s, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64.s, wasm/jit/jit_test.go, wasm/jit/jit_value_location.go, wasm/jit/jit_value_location_amd64.go, wasm/jit/jit_value_location_arm64.go, wasm/jit/jit_value_location_test.go
This commit builds the scaffold for arm64 JIT engine.
Notably, we can run go test ./wasm/jit/... and pass some
GOARCH independent tests on arm64.
part of #187
=> jit: scaffold arm64 JIT engine

wasm/jit/compiler.go, wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go
=> jit: refactor documentation on compiler interface

wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go, wasm/jit/jit_value_location_arm64.go
=> jit(arm64): support for const operations

wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go, wasm/jit/jit_value_location.go, wasm/jit/jit_value_location_amd64.go, wasm/jit/jit_value_location_arm64.go, wasm/jit/jit_value_location_test.go
=> jit(arm64): support Add, Mul, Sub operations

wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go
=> jit(arm64): support for eq, ne, and eqz

RATIONALE.md, wasm/internal/wazeroir/compiler.go, wasm/jit/compiler.go, wasm/jit/engine.go, wasm/jit/engine_test.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go, wasm/jit/jit_value_location.go, wasm/jit/jit_value_location_test.go
part of #187 
there's some of overlaps with amd64, but I intentionally not share the code,
as they are slightly different, and I'm not sure if the new JIT target (e.g. RISCV)
can reuse the code.
=> jit(arm64): support for br, br_if and labels

.gitattributes, CONTRIBUTING.md
we forgot this some time ago. This is exactly the same as func-e
=> Adds CONTRIBUTING template

tests/bench/bench_test.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go
=> jit(amd64): less instruction memory bounds check

.github/workflows/commit.yaml, tests/spectest/spec_test.go
=> Fix path to spec tests

.github/workflows/commit.yaml, wasm/interpreter/interpreter.go
=> interpreter: simplify Copysign

wasm/internal/wazeroir/operations.go, wasm/jit/engine.go, wasm/jit/engine_test.go, wasm/jit/jit_amd64.go, wasm/jit/jit_amd64_test.go, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go
=> jit(arm64): support for memory loads/stores

wasm/jit/jit_amd64.go
=> jit(amd64): less instructions after growing value stack

wasi/strings.go, wasi/strings_test.go, wasi/wasi.go, wasi/wasi_test.go
This PR implements `environ_get` and `environ_sizes_get`.
=> wasi: Implement environ_get and environ_sizes_get API

wasm/jit/jit_amd64.go, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go, wasm/mempage.go, wasm/mempage_test.go
=> jit(arm64): support for memory size/grow, host functions

wasm/jit/engine.go, wasm/jit/jit_amd64.go, wasm/jit/jit_arm64.go, wasm/jit/jit_arm64_test.go, wasm/jit/jit_other.go, wasm/jit/jit_value_location_arm64.go, wasm/jit/jit_value_location_arm64_test.go
=> jit(arm64): support for clz, ctz, popcnt, div, rem

internal/wasi/wasi.go, internal/wasi/wasi_test.go, wasi/wasi.go
Will do rebase and update the docs after the refactoring PR is merged
=> wasi: Implement proc_exit

RATIONALE.md, README.md, internal/moremath/moremath.go
=> doc: fix drifts

wasi.go
=> wasi: env initialization fix

internal/wasm/jit/jit_amd64_test.go, internal/wasm/jit/jit_arm64.go, internal/wasm/jit/jit_arm64_test.go
=> jit(arm64): support for conversion instructions

internal/wasm/jit/jit_amd64.go
previous
```
if type == uninitialized {
exit invalid_call
}
if type != expected {
exit type_mismatch
}
call func
```
now:
```
if type != expected {
if type == uninitialied {
exit invalid_call
} else {
exit type_mismatch
}
}
call func
```
therefore less cycles consumed on the regular case (which should be easy to predict the branch)
=> jit(amd64): less instructions on call/call_indirect

internal/wasm/interpreter/interpreter.go, internal/wasm/jit/engine.go, wasm/wasm.go
=> fix float32

internal/wasm/jit/engine.go, internal/wasm/jit/engine_test.go, internal/wasm/jit/jit_amd64.go, internal/wasm/jit/jit_amd64_test.go, internal/wasm/jit/jit_arm64.go, internal/wasm/jit/jit_arm64_test.go, internal/wasm/jit/jit_value_location.go, internal/wasm/jit/jit_value_location_amd64.go, internal/wasm/jit/jit_value_location_arm64.go
=> jit(arm64): support for call_indirect and br_table

internal/wasi/RATIONALE.md, internal/wasi/wasi.go, internal/wasi/wasi_test.go
This PR backfills the docs and the tests of part of existing WASI APIs.
=> wasi: backfill docs and tests of fd_close fd_prestat_get fd_prestat_dir_name fd_read

wasi.go, wasm.go, wasm_test.go
=> Backfills integration tests of WithName to ensure bug is fixed

.github/workflows/commit.yaml, Makefile, internal/wasm/jit/jit_amd64_test.go, internal/wasm/jit/jit_arm64.go, internal/wasm/jit/jit_arm64_test.go, internal/wasm/jit/jit_test.go, internal/wasm/jit/jit_value_location.go, internal/wasm/jit/jit_value_location_amd64.go
=> Enable linter on arm64

.github/workflows/commit.yaml, .github/workflows/examples.yaml, internal/wasm/jit/engine.go, internal/wasm/jit/engine_test.go, internal/wasm/jit/jit_amd64_test.go, tests/bench/bench_fac_iter_test.go, tests/codec/codec_test.go, tests/engine/adhoc_test.go, tests/spectest/spec_test.go
=> Adds Windows CI Job

README.md
=> Reflect JIT availability on Windows in README

internal/wasi/wasi_test.go, internal/wasm/global.go, internal/wasm/host.go, internal/wasm/interpreter/interpreter_test.go, internal/wasm/jit/engine_test.go, internal/wasm/memory.go, internal/wasm/memory_test.go, internal/wasm/module.go, internal/wasm/store.go, internal/wasm/store_test.go, tests/spectest/spec_test.go, wasi.go, wasm_test.go
=> Make store's fields private

internal/wasm/host.go, internal/wasm/store_test.go, tests/spectest/spec_test.go
=> Remove spectest-only APIs.

internal/wasm/store.go, tests/spectest/spec_test.go
=> Remove the last spectest-only API

internal/wasm/global.go, internal/wasm/host.go, internal/wasm/store.go, internal/wasm/store_test.go
=> Unexport moduleInstance.GetExport and remove test-only store.getExport

internal/wasm/features.go
iota abbreviation works well with bit shifts as well
=> Simplify features const declarations

config_supported.go, config_unsupported.go, tests/engine/adhoc_test.go, tests/engine/concurrency_test.go
Adds tests/engine/concurrency_test.go
=> Adds tests for multiple goroutines

internal/wasm/jit/engine.go, internal/wasm/jit/engine_test.go, internal/wasm/jit/jit_amd64.go, internal/wasm/jit/jit_amd64.s, internal/wasm/jit/jit_amd64_test.go, internal/wasm/jit/jit_arm64.go, internal/wasm/jit/jit_arm64.s, internal/wasm/jit/jit_arm64_test.go, internal/wasm/jit/jit_other.go, internal/wasm/jit/jit_test.go
Also fixes some residual use of the word "vm"
=> Fixes inconsistent initialization in compileBrTable test

internal/wasm/store.go
=> Inline moduleInstance.addExport

internal/wasm/func_validation.go, internal/wasm/func_validation_test.go, internal/wasm/instruction.go, internal/wasm/interpreter/interpreter.go, internal/wasm/jit/jit_amd64.go, internal/wasm/module.go, internal/wasm/module_test.go, tests/README.md, tests/post1_0/post1_0_test.go, tests/spectest/spec_test.go, wasm.go
=> Polishes in preparation of first post 1.0 feature

internal/wasm/host.go, internal/wasm/store.go
this uses concurrent "put if absent" for the store.modules map, so that two can't reserve the same name while another is initializing.
=> Ensures no race condition adding a module of the same name

internal/wasi/fs.go, internal/wasi/fs_test.go, internal/wasi/wasi.go, internal/wasi/wasi_test.go, wasi/wasi.go
This PR implements `fd_seek` API.
=> WASI: Implement fd_seek

internal/wasm/store.go, internal/wasm/store_test.go
=> Fix duplicated increments on dependantCounts.

internal/wasm/jit/jit_amd64.go, internal/wasm/jit/jit_amd64_test.go
This removes all the copy-and-pasted assembler code and
centralizes the usage of golang-asm in jit_amd64.go
In follow-up PRs, I will share majority of unit tests in amd64_test.go
with arm64 and introduce assembler interface.
=> Refactor amd64 JIT compiler

internal/wasi/wasi.go, internal/wasi/wasi_test.go
Fixes #370 Thanks to @pims for such a good capture of what to fix!
```bash
$ go run cmd/cli.go hello.gr.wasm
==== Environment: ====
bar=baz
took: 248.835102ms
```
=> wasi: fixes bad stubs

internal/wasm/jit/engine.go
=> Adds notes about edge cases during moduleEngine.Close

internal/wasm/jit/arch_amd64.s, internal/wasm/jit/arch_arm64.s, internal/wasm/jit/jit_controlflow_test.go, internal/wasm/jit/jit_conversion_test.go, internal/wasm/jit/jit_initialization_test.go, internal/wasm/jit/jit_memory_test.go, internal/wasm/jit/jit_numeric_test.go, internal/wasm/jit/jit_post1_0_test.go, internal/wasm/jit/jit_stack_test.go, internal/wasm/jit/jit_value_location_test.go
=> jit: remove unnecessary build tags

internal/wasm/jit/mmap_windows.go
per advice from @wdvxdr1123
Fixes #377
=> windows: avoids GetLastError as goroutine != thread

README.md
=> Reflect scratch test change on README

README.md
Thanks @jcchavezs for noticing the bad links and also the cryptic way
operating systems were defined.
=> readme: elaborates SCRATCH and fixes broken links

internal/asm/amd64/impl.go, internal/asm/amd64_debug/impl_test.go, internal/wasm/jit/jit_numeric_test.go
=> asm(amd64): ROL and ROR on Register To Memory type.

.github/workflows/commit.yaml
=> pin wabt to eliminate spectest fail

api/wasm.go, internal/wasm/text/func_parser.go, internal/wasm/text/func_parser_test.go, tests/spectest/spec_test.go
This helps us prioritize text format features
=> wat: syncs spectest with latest text decoder

README.md, internal/wasm/jit/RATIONALE.md
=> Update jit/RATIONALE.md and README.md to reflect hand made assembler 

examples/basic/add_test.go, examples/multiple-results/multiple-results_test.go, examples/replace-import/replace-import_test.go, examples/wasi/cat_test.go
thanks for noticing this @mathetake
=> Fixes godoc links in example tests

examples/README.md, examples/basic/README.md, examples/basic/add.go, examples/basic/add_test.go, examples/import-go/.gitignore, examples/import-go/README.md, examples/import-go/age-calculator.go, examples/import-go/age-calculator_test.go, examples/multiple-results/multiple-results.go, examples/multiple-results/multiple-results_test.go, examples/replace-import/replace-import.go, examples/replace-import/replace-import_test.go, examples/wasi/cat.go, examples/wasi/cat_test.go, internal/wasm/func_validation.go, internal/wasm/text/func_parser.go, internal/wasm/text/func_parser_test.go, wasi/example_test.go, wasi/usage_test.go, wasi/wasi.go
This shows how to define, export and import functions written in Go.
Fixes #464
=> Adds import-go example

Makefile
=> Run asm integration tests correctly

internal/integration_test/engine/adhoc_test.go
Previously, we haven't had the tests to verify that memory bounds check work correctly 
with memory capacity configuration. Notably, this ensures that memory access offsets 
larger than size but less than capacity actually result in memory out of bounds access.
=> Adds ad-hoc test on bounds check with memory capacity config

api/wasm.go, api/wasm_test.go, internal/wasm/gofunc.go, internal/wasm/gofunc_test.go
thx @anuraaga for noticing the bug
=> Fixes coverage on externref/uintptr

wasm_test.go
=> Actually splits test case runs for runtime TestClose.

RATIONALE.md, internal/wasm/module.go, internal/wasm/table.go, internal/wasm/table_test.go
=> Adds limit on the number of tables per module

internal/wasm/table.go
=> Remove drifted comment on Reference Type

config.go, config_test.go, internal/wasm/features.go, internal/wasm/features_test.go, internal/wasm/func_validation.go, internal/wasm/func_validation_test.go, internal/wasm/instruction.go
=> Adds SIMD opcodes and feature flag

README.md, site/config.toml, site/content/history.md, site/layouts/partials/menu.html
This adds a submenu for community, filing GH and the history into it.
The same surgery should work for future submenus, for example,
compatibility and docs.
=> site: Adds first submenu for Community

.github/workflows/spectest.yaml, README.md
=> Adds badges on README

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Copied from [func-e](https://github.com/tetratelabs/func-e/tree/master/.github/ISSUE_TEMPLATE) with bug-report fairly heavily modified to reflect reproduction / environment of wazero. Environment in particular I might have missed something, let me know what would be helpful there.
=> Adds issue templates

internal/asm/amd64/impl_test.go, internal/asm/arm64/impl_test.go, internal/engine/compiler/compiler_controlflow_test.go, internal/engine/compiler/compiler_conversion_test.go, internal/engine/compiler/compiler_initialization_test.go, internal/engine/compiler/compiler_memory_test.go, internal/engine/compiler/compiler_numeric_test.go, internal/engine/compiler/compiler_post1_0_test.go, internal/engine/compiler/compiler_stack_test.go, internal/engine/compiler/impl_amd64_test.go, internal/engine/interpreter/interpreter_test.go, internal/integration_test/asm/amd64_debug/impl_test.go, internal/integration_test/asm/arm64_debug/impl_test.go, internal/modgen/modgen_test.go, internal/wasm/binary/const_expr_test.go, internal/wasm/binary/data_test.go, internal/wasm/binary/element_test.go, internal/wasm/func_validation_test.go, internal/wasm/module_test.go, internal/wasm/store_test.go, internal/wasm/table_test.go, internal/wasmdebug/debug_test.go, internal/wazeroir/compiler_test.go, internal/wazeroir/signature_test.go, sys/sys_test.go, wasi/usage_test.go, wasi/wasi_test.go, wasm_test.go
One of these happened to be what I saw first when looking for a pattern for defining tests, but it doesn't seem to be the correct pattern. We need to fix these to prevent confusion when people add tests for the first time.
=> Use correct pattern for table tests everywhere

internal/engine/interpreter/interpreter.go
Braces in switch case statements are optional in Go as a new block is automatically created. The `gocritic` lint rule flags them probably due to the extra indent that they introduce. A few of the other case statements seem to already miss the braces so this makes them all consistent.
=> Removes braces from case blocks.

config.go, config_supported.go, config_unsupported.go, internal/wasm/instruction.go
- Adds doc to a few public APIs that didn't have them
- Moves docs about groups of items so that they don't get assigned to an item as its godoc
- Fixes a method name typo
=> Small cleanups to docs

config.go, config_supported.go, config_unsupported.go
Otherwise looks like this: https://pkg.go.dev/github.com/tetratelabs/wazero#NewRuntimeConfig
=> Tweaks doc for NewRuntimeConfig to describe API behavior

site/content/specs.md
=> site: reflect 2.0 impl on specs page

internal/engine/interpreter/interpreter.go
=> interpreter: consolidate function call logics

internal/wasm/features.go, site/content/specs.md
=> doc: remove oudated comment on 2.0

internal/engine/compiler/compiler_initialization_test.go, internal/engine/compiler/compiler_value_location.go, internal/engine/compiler/compiler_value_location_test.go
=> compiler: fix stackPointerCeil calculation

config_supported.go, internal/engine/compiler/arch_amd64.go, internal/engine/compiler/arch_arm64.go, internal/engine/compiler/arch_other.go
=> compiler: cleanup arch specific files

examples/wasi/README.md
=> example(wasi): fixes link drifts

api/wasm.go, config.go, internal/wasm/module_exports.go, internal/wasm/module_exports_test.go
=> Adds ExportedFunctions API on CompiledModule.

internal/wasm/store.go, internal/wasm/store_test.go
=> Fixes error message on validate/applyData elements

internal/wasm/table.go, internal/wasm/table_test.go
=> Allow externref in table validation

internal/engine/interpreter/interpreter.go, internal/wazeroir/format.go
=> interpreter: remove unnecessary pc advancing in V128ITruncSatFromF

internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
=> func_validation: do not modify original types in unreachable state

internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
=> validation: correct expected types on loop with params

internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
=> validation: not modify loop block type on unreachable br_table

internal/engine/compiler/arch.go, internal/engine/compiler/arch_amd64.go, internal/engine/compiler/arch_arm64.go, internal/engine/compiler/compiler_stack_test.go, internal/engine/compiler/compiler_value_location.go, internal/engine/compiler/compiler_value_location_test.go, internal/engine/compiler/impl_vec_amd64.go, internal/engine/compiler/impl_vec_amd64_test.go
=> amd64: fixes i64x2.shr_s on CX register allocation

internal/engine/compiler/compiler.go, internal/engine/compiler/compiler_controlflow_test.go, internal/engine/compiler/engine.go, internal/engine/compiler/impl_amd64.go, internal/engine/compiler/impl_arm64.go, internal/testing/enginetest/enginetest.go
=> compiler: support for Wasm-implemented host functinos

examples/multiple-results/multiple-results.go
=> example: adds missing error check 

internal/engine/compiler/impl_amd64.go, internal/engine/compiler/impl_arm64.go, internal/testing/enginetest/enginetest.go
=> Fixes function calls / memory access with wasm-implemented host functions 

README.md, site/content/_index.md
=> Fixes doc drifts on NewRuntimeConfig

runtime.go, runtime_test.go
Similar to other methods taking `ctx`
=> Accept nil ctx in NewRuntime

README.md, examples/allocation/tinygo/greet.go, examples/wasi/cat.go, site/content/_index.md
We neglected to update this, which has led to some blogs not knowing the latest news.
=> Adds 1.0 release plan to README and site

experimental/compilation_cache_example_test.go
=> Adds Example on compilation cache.

site/content/languages/_index.md, site/content/languages/tinygo.md
This adds my private notes about how to figure out syscalls. Hopefully, they help people.
=> site: elaborates how syscalls work in TinyGo

site/content/languages/tinygo.md
=> site: more TinyGo feedback

experimental/compilation_cache.go, experimental/compilation_cache_example_test.go, experimental/compilation_cache_test.go, internal/integration_test/bench/bench_test.go, internal/integration_test/filecache/filecache_test.go
=> exp: create the compilation cache dir when not exist

README.md
we switched off the text format in our website, but hadn't here
see #771
=> Matches README with website

imports/go/example/stars_test.go
As noted in the godoc, this is not because we expect it to be fast,
rather for folks doing internal work to quickly tell if something might
help or not.
=> Adds gojs benchmark

internal/engine/compiler/engine_cache.go, internal/engine/compiler/engine_cache_test.go
Hopefully this can help us narrow down flakes like https://github.com/tetratelabs/wazero/runs/8199081288?check_suite_focus=true
=> compilationcache: improves error messages

.github/ISSUE_TEMPLATE/feature-request.md, site/content/languages/go.md, site/content/specs.md
mainly to get commit count higher
=> docs: fixes fuzz from last merge

internal/engine/compiler/impl_amd64.go
=> amd64: delete stale comment

api/wasm.go, internal/wasm/memory.go, internal/wasm/memory_test.go
=> Add Memory.WriteString

runtime_test.go
I want to hold the my Context and use it in the host funtion call, So I add a holder funtion to hold the Context instance.
I think this is a feature, Please review it.
=> Adds test to ensure custom contexts are usable

imports/wasi_snapshot_preview1/fs.go, imports/wasi_snapshot_preview1/fs_test.go
This avoids memory copying in default configuration where stdout/stderr are discarded. This helps avoid performance impact when console logging happens, but intentionally discarded.
=> Special cases io.Discard on fd_write

imports/wasi_snapshot_preview1/wasi_bench_test.go
This benchmark hadn't been run recently and it broke. This sorts it out.
=> Fixes wasi benchmark

Makefile, internal/version/testdata/main.go
=> switches to gosimports for grouping

internal/wasm/store.go, internal/wasm/store_test.go
Signed-off-by: Clifton Kaznocha <ckaznocha@users.noreply.github.com>
=> Optimize setting the ModuleInstance.DataInstances

Vagrantfile
=> ci: fix DNS issue with FreeBSD VM

internal/engine/compiler/engine.go
=> compiler: small optimization on CompileModule

builder.go, config_test.go, experimental/experimental_test.go, experimental/listener.go, experimental/listener_example_test.go, experimental/listener_test.go, experimental/logging/log_listener_example_test.go, imports/assemblyscript/assemblyscript_test.go, imports/emscripten/emscripten_test.go, imports/wasi_snapshot_preview1/wasi_test.go, internal/engine/compiler/arch_amd64.go, internal/engine/compiler/arch_arm64.go, internal/engine/compiler/arch_other.go, internal/engine/compiler/compiler_bench_test.go, internal/engine/compiler/compiler_drop_test.go, internal/engine/compiler/compiler_test.go, internal/engine/compiler/engine.go, internal/engine/compiler/engine_test.go, internal/engine/compiler/impl_amd64.go, internal/engine/compiler/impl_arm64.go, internal/engine/interpreter/interpreter.go, internal/engine/interpreter/interpreter_test.go, internal/integration_test/bench/hostfunc_bench_test.go, internal/integration_test/spectest/spectest.go, internal/testing/enginetest/enginetest.go, internal/wasm/engine.go, internal/wasm/store_test.go, runtime.go, runtime_test.go
=> compiler: adds support for FunctionListeners

.github/workflows/commit.yaml
=> ci: fixes cache key on Minmal Fuzzing

api/wasm.go
Signed-off-by: Clifton Kaznocha <ckaznocha@users.noreply.github.com>
=> Fix typos in examples

Makefile, internal/integration_test/fuzz/fuzz/Cargo.toml, internal/integration_test/fuzz/fuzz/build.rs, internal/integration_test/fuzz/fuzz/fuzz_targets/validation.rs, internal/integration_test/fuzz/wazerolib/lib.go, internal/integration_test/fuzz/wazerolib/nodiff.go, internal/integration_test/fuzz/wazerolib/nodiff_test.go, internal/integration_test/fuzz/wazerolib/validate.go, internal/integration_test/fuzz/wazerolib/validate_test.go, internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
=> fuzz: adds validation target for maybe invalid module compilation

internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
=> validation: not panic with redundant Else instrs

internal/engine/compiler/engine.go
If this code is too deep for such comments, feel free to close no worries. Happened to be something mysterious I ran into in first iterations of #892
=> Add a note about the offset requirement in moduleEngine struct

internal/engine/compiler/engine.go, internal/wasm/store.go
=> Deletes unused ModuleInstance.Types

.github/workflows/commit.yaml, .github/workflows/examples.yaml, .github/workflows/spectest.yaml
=> ci: do not cancel other workflows 

internal/wasmdebug/dwarf.go, internal/wasmdebug/dwarf_test.go
=> dwarf: ensure Goroutine-safety in DWARFLines.Line function

cmd/wazero/wazero.go, cmd/wazero/wazero_test.go
=> cmd: enable DWARF by default

internal/wasm/store.go
=> Fix racy first instantiation

internal/wasm/binary/decoder_test.go, internal/wasm/binary/function.go, internal/wasm/binary/function_test.go
following suggestion from #930
=> Cache FunctionType key in the binary pkg

internal/engine/compiler/compiler_controlflow_test.go
this has been flaky since #894 
=> compiler: fix flaky TestCompiler_compileCallIndirect

.github/workflows/commit.yaml
=> Fixes wasmedge installation

cmd/wazero/go.mod, cmd/wazero/wazero.go, cmd/wazero/wazero_test.go, internal/version/version.go
=> cli: adds version command

internal/engine/compiler/engine_cache.go, internal/engine/compiler/engine_cache_test.go, internal/wasm/host.go, internal/wasm/host_test.go, internal/wasm/module.go
=> Disable comp cache for host modules

internal/asm/arm64/consts.go, internal/asm/arm64/impl.go, internal/asm/arm64/impl_1_test.go
=> asm(arm64): adds UDF instruction

imports/wasi_snapshot_preview1/fs.go, imports/wasi_snapshot_preview1/fs_test.go, internal/sys/fs.go
This fixes and backfills tests for open flags, notably O_CREAT. I verified this with TinyGo tests, which now proceed when attempting to create new files.
```bash
$ wazero run -hostlogging=filesystem -mount=.:/ os.wasm -test.v
==> wasi_snapshot_preview1.fd_prestat_get(fd=3)
<== (prestat={pr_name_len=1},errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_dir_name(fd=3)
<== (path=/,errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_get(fd=4)
<== (prestat=,errno=EBADF)
==> wasi_snapshot_preview1.path_unlink_file(fd=3,path=tmp/_os_test_TestTempDir)
<== errno=ENOENT
==> wasi_snapshot_preview1.path_remove_directory(fd=3,path=tmp/_os_test_TestTempDir)
<== errno=ENOENT
==> wasi_snapshot_preview1.fd_fdstat_get(fd=3)
<== (stat={filetype=DIRECTORY,fdflags=APPEND,fs_rights_base=,fs_rights_inheriti …
```
=> wasi: fixes open flags

internal/testing/enginetest/enginetest.go
=> enginetest: fixes panic om memory def

internal/engine/compiler/engine_cache.go, internal/engine/compiler/engine_cache_test.go
=> cache: fixes deadlock in version mismatch

internal/integration_test/engine/adhoc_test.go
Closes https://github.com/tetratelabs/wazero/issues/420
=> Ensures user-defined primitive types are usable in host func signatures

internal/engine/compiler/engine.go, internal/engine/compiler/engine_cache.go, internal/engine/interpreter/interpreter.go, internal/wasm/host.go, internal/wasm/module.go, internal/wasm/store.go
=> Moves more func inst fields to comptime objects

.github/workflows/commit.yaml, Makefile, cache.go, config.go, runtime.go, runtime_test.go
Fixes #1020 which has been introduced recently
=> Fixes race on engine creation with Cache API

.github/workflows/commit.yaml, Makefile, cache.go, cache_test.go, config.go, config_test.go, runtime.go, runtime_test.go
=> Separate interpreter and engine per wazero.cache impl

.github/workflows/integration.yaml
=> ci: adds automated Ziglang Stdlib integration test 

examples/basic/add.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
Use `flag` to parse positional arguments (avoiding `os.Args` out of bounds panics) and return friendly errors:
```
$ go run .
2023/01/12 16:38:57 failed to read arguments: must specify two command line arguments
exit status 1
$ go run . 1 foo
2023/01/12 16:39:00 failed to read arguments: strconv.ParseUint: parsing "foo": invalid syntax
exit status 1
$ go run . 1 2
1 + 2 = 3
```
Edit: switched to log.Panicf per feedback below.
=> examples/basic: parse positional arguments with flags

imports/wasi_snapshot_preview1/fs.go, imports/wasi_snapshot_preview1/fs_test.go, internal/syscallfs/syscall_windows.go, internal/syscallfs/syscallfs.go
This adds the fd_sync syscall:
https://github.com/WebAssembly/WASI/blob/snapshot-01/phases/snapshot/docs.md#-fd_syncfd-fd---errno
=> fs: Adds fd_sync

api/wasm.go, config.go, config_example_test.go, config_test.go, runtime.go
Add support to Custom Sections to the public API. 
Please do let me know if I put everything in the right places and especially if something is missing, I am justing getting started learning my way through the codebase :)
=> CompiledModule: export Custom Sections

.github/workflows/integration.yaml
=> ci: adds TinyGo stdlib integration test 

examples/allocation/zig/README.md, imports/wasi_snapshot_preview1/example/README.md, site/content/languages/_index.md, site/content/languages/zig.md
Docs for the Zig section of the website. I am new to Zig so please do add your notes :)
=> docs: add zig section 

imports/wasi_snapshot_preview1/fs.go, imports/wasi_snapshot_preview1/fs_unit_test.go
=> wasi: fixes flag logic that didn't OR correctly

.github/workflows/integration.yaml
part of #1029, extracted from #1057 
=> ci: runs Zig stdlib tests on mac and windows

.github/workflows/integration.yaml, imports/wasi_snapshot_preview1/fs.go, imports/wasi_snapshot_preview1/fs_test.go, internal/gojs/testdata/writefs/main.go, internal/platform/open_file_windows.go, internal/platform/separator.go, internal/platform/separator_test.go, internal/platform/separator_windows.go, internal/platform/stat.go, internal/platform/stat_bsd.go, internal/platform/stat_linux.go, internal/platform/stat_test.go, internal/platform/stat_unsupported.go, internal/platform/stat_windows.go, internal/sysfs/dirfs.go, internal/sysfs/dirfs_test.go, internal/sysfs/sysfs.go, internal/sysfs/unsupported.go, internal/wasi_snapshot_preview1/errno.go, site/content/specs.md
=> wasi: implements link related system calls

.github/workflows/integration.yaml
=> ci: runs TinyGo stdlib tests on mac and windows

RATIONALE.md, fsconfig.go
from a discussion with @achille-roussel
=> Adds rationale about WASI vs os.DirFS

.github/workflows/integration.yaml, internal/wasi_snapshot_preview1/errno.go
=> wasi: returns ELOOP properly

.github/workflows/integration.yaml, RATIONALE.md, imports/go/README.md, internal/gojs/errno.go, internal/gojs/errno_test.go, internal/gojs/fs.go, internal/gojs/goarch/wasm.go, internal/gojs/js.go, internal/gojs/runtime.go, internal/gojs/state.go, internal/gojs/syscall.go, internal/integration_test/vs/bench.go, internal/leb128/leb128.go, internal/platform/open_file_windows.go, internal/platform/stat_windows.go, internal/sys/fs.go, site/content/languages/go.md
Signed-off-by: Adrian Cole <adrian@tetrate.io>
=> gojs: backfills errno tests and updates links

Makefile, internal/engine/compiler/arch_other.s
=> Adds asmfmt in make format

internal/platform/platform_test.go
=> platform: add test on archRequirementsVerified

internal/platform/time_windows.go
Performance counter should be scaled by performance frequency to convert to nanoseconds.
Signed-off-by: Egon Elbre <egonelbre@gmail.com>
=> wasi: fix nanotime, scale QPC value correctly on Windows

.github/workflows/integration.yaml
=> ci: enables wasi-testsuite on Windows

internal/engine/compiler/engine.go, internal/engine/interpreter/interpreter.go, internal/wasm/engine.go, internal/wasm/store.go, internal/wasm/store_test.go
=> Removes unnecessary Engine.CreateElementInstance

internal/wazeroir/compiler.go
```
_compile-10     917ms ± 1%     902ms ± 2%   -1.71%  (p=0.000 n=17+18)
_compile-10     609MB ± 0%     607MB ± 0%   -0.43%  (p=0.000 n=20+20)
_compile-10     9.39M ± 0%     7.68M ± 0%  -18.28%  (p=0.000 n=20+20)
```
=> wazeroir: avoids allocation in applyToStack

internal/wazeroir/compiler.go
counterpart to #1139 in IR.
```
_compile-10     1.04s ± 2%     1.03s ± 1%  -0.88%  (p=0.000 n=18+17)
_compile-10     646MB ± 0%     639MB ± 0%  -1.11%  (p=0.000 n=18+19)
_compile-10     10.7M ± 0%     10.6M ± 0%  -1.39%  (p=0.000 n=20+20)
```
=> wazeroir: reuses bytes.Reader

internal/wazeroir/compiler.go
```
_compile-10     886ms ± 0%     876ms ± 1%  -1.11%  (p=0.000 n=20+19)
_compile-10     597MB ± 0%     589MB ± 0%  -1.25%  (p=0.000 n=20+20)
_compile-10     7.40M ± 0%     7.22M ± 0%  -2.46%  (p=0.000 n=20+20)
```
=> wazeroir: reduces allocations with controlFrames

site/content/community/users.md
Adding waPC to the list of wazero users. Thank you, Wazero team!
/cc: @codefromthecrypt
=> Adding waPC to general purpose plugins list

site/content/community/users.md
thanks @antJack @taoyuanyuan and recently @evacchi for the long term collaboration on this.
=> site: adds mosn as a user

imports/wasi_snapshot_preview1/wasi_bench_test.go
Before, we only tested wrapped filesystems implemented with `fs.FS`. This adds our native filesystem type, showing the current benchmarks are about the same for reading a directory, but a lot faster for stat.
```
goos: darwin
goarch: arm64
Benchmark_ArgsEnviron
Benchmark_ArgsEnviron/args_get
Benchmark_ArgsEnviron/args_get-12         	17580879	        68.80 ns/op	      24 B/op	       2 allocs/op
Benchmark_ArgsEnviron/args_sizes_get
Benchmark_ArgsEnviron/args_sizes_get-12   	20259232	        58.81 ns/op	      24 B/op	       2 allocs/op
Benchmark_ArgsEnviron/environ_get
Benchmark_ArgsEnviron/environ_get-12      	16558956	        71.14 ns/op	      24 B/op	       2 allocs/op
Benchmark_ArgsEnviron/environ_sizes_get …
```
=> wasi: updates benchmark to uses sysfs

site/content/community/users.md
thanks to @daixiang0 @ItalyPaleAle @yaron2 and @evacchi for the help on this. dapr 1.10 includes wazero support by default. See https://github.com/dapr/samples/pull/122
=> site: adds dapr to users

site/content/community/users.md
thanks @samyfodil for the permission to add this exciting section!
=> site: adds taubyte to new cloud platform category

site/content/community/users.md
if you look at [scale's site](https://scale.sh/docs/getting-started/quick-start) it is actually more like a FaaS thing. cc @ShivanshVij
=> site: move scale to better section

internal/platform/utimes_darwin.go, internal/platform/utimes_darwin.s, internal/platform/utimes_linux.go, internal/platform/utimes_test.go, internal/platform/utimes_unsupported.go
=> implement futimens on Darwin and Linux

RATIONALE.md, internal/platform/bench_test.go, internal/platform/utimes_darwin.go, internal/platform/utimes_test.go
thx @mathetake for clarifying this!
=> platform: adds notes about darwin and CGO

cmd/wazero/wazero_test.go
Interesting issue due to a lot of weird interactions between
path handling and system defaults.
The test will pass outside of CI (e.g. on my local machine),
because usually you will run this on C:\, which is the root
of your filesystem.
However, GitHub Actions mounts the test filesystem on D:,
causing the path handling routines to miss it.
You can simulate this even if you don't have a second drive:
assuming you have `wazero` under `%USERPROFILE%\Devel\wazero`
subst X: %USERPROFILE%\Devel
cd X:\wazero
make test
However, we are ignoring path information because:
```go
func WithWorkdir(ctx context.Context, workdir string) context.Context {
// Ensure if used on windows, the input path is translated to a POSIX one.
workdir = workdir[len(filepath.VolumeName(workdir)):]
```
strips the Volume …
=> fix: --experimental-workdir test case on Windows

.github/workflows/integration.yaml
=> ci: adds integration test on Go(Js)

internal/wasm/module.go
I believe these are the remnants from Wat parser era
=> Removes unused function types on encoder/decoder

fsconfig.go
cc @jerbob92 who was asking about windows mounts.. which was a good question as we didn't document it!
=> documents WithDirMount wrt windows

site/content/_index.md
=> chore: fixes syntax in home site

site/content/community/users.md
@codefromthecrypt do you want me to also add [pdfium-cli](https://github.com/klippa-app/pdfium-cli)? It's just using go-pdfium but it does bring Wazero to end users.
=> Add go-pdfium to users

config.go, config_test.go, internal/platform/time.go, internal/platform/time_test.go, internal/sys/fs.go, internal/sys/fs_test.go, internal/sys/sys.go, internal/sys/sys_test.go
=> Stop using pointer of function pointers in sys.Context

site/content/community/users.md
Signed-off-by: C.C <fanweixiao@gmail.com>
Update users.md
=> add YoMo project to users.md

site/content/community/users.md
As kindly suggested by @codefromthecrypt
=> add github.com/stealthrocket/wazergo to the list of libraries using wazero

internal/wasm/module_instance_test.go
=> Fixes race in TestModuleInstance_CloseModuleOnCanceledOrTimeout

internal/wasm/func_validation.go
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      117.0µ ± 0%   114.4µ ± 7%  -2.24% (p=0.026 n=7)
Compilation/without_extern_cache-10   2.282m ± 0%   2.276m ± 0%  -0.30% (p=0.004 n=7)
geomean                               516.8µ        510.2µ       -1.27%
Compilation/with_extern_cache-10      38.38Ki ± 0%   38.36Ki ± 0%       ~ (p=0.053 n=7)
Compilation/without_extern_cache-10   1.216Mi ± 0%   1.215Mi ± 0%       ~ (p=0.073 n=7)
geomean                               218.6Ki        218.5Ki …
```
=> Reuses stack in requireStackValues of func validation

internal/asm/arm64/impl.go
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      215.1m ± 0%   194.5m ± 0%  -9.56% (p=0.001 n=7)
Compilation_sqlite3/interpreter-10   62.53m ± 1%   62.37m ± 1%       ~ (p=0.710 n=7)
geomean                              116.0m        110.1m       -5.02%
Compilation_sqlite3/compiler-10      51.90Mi ± 0%   51.90Mi ± 0%       ~ (p=0.805 n=7)
Compilation_sqlite3/interpreter-10   51.76Mi ± 0%   51.76Mi ± 0%       ~ (p=0.620 n=7)
geomean                              51.83Mi        51.83Mi       -0.00%
│ …
```
=> asm/arm64: avoids using unnecessary map access

internal/wasm/binary/decoder.go, internal/wasm/binary/memory_test.go
=> Fixes memory capacity with max larger than limit

internal/engine/compiler/engine.go
looks like -race failing on the main after #1363
=> compiler: fixes false-positive invalid ptr detection in -race

internal/asm/amd64/impl.go
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 3950X 16-Core Processor            
Compilation/without_extern_cache-32   3.895m ± 1%   3.806m ± 3%  -2.29% (p=0.011 n=7)
Compilation_sqlite3/compiler-32       410.6m ± 3%   398.0m ± 2%  -3.06% (p=0.007 n=7)
geomean                               39.99m        38.92m       -2.68%
Compilation/without_extern_cache-32   664.4Ki ± 0%   664.4Ki ± 0%       ~ (p=0.710 n=7)
Compilation_sqlite3/compiler-32       49.40Mi ± 0%   49.40Mi ± 0%       ~ (p=0.620 n=7)
geomean …
```
=> asm/amd64: optimizes maybeNOPPadding if conds

internal/asm/amd64/impl.go, internal/asm/amd64/impl_1_test.go
this is a vestige from the golang-asm era
=> asm/amd64: removes enablePadding flag

.github/workflows/integration.yaml
started running, but failing randomly :D 
https://github.com/tetratelabs/wazero/actions/runs/4804810021/jobs/8550649684
=> ci: try enabling Windows on wasip1 test

internal/engine/interpreter/interpreter.go, internal/engine/interpreter/interpreter_test.go
I forgot committing the change of interpreter in #1419
=> interpreter: refactors around FunctionDefinition

internal/gojs/fs.go, internal/platform/file.go, internal/sys/fs.go, internal/sysfs/sysfs.go
=> Adds platform.File.Chmod

imports/wasi_snapshot_preview1/fs.go, internal/gojs/fs.go, internal/platform/file.go, internal/platform/file_test.go, internal/sys/fs.go, internal/sysfs/sysfs.go, internal/sysfs/sysfs_test.go
=> Adds Sync to platform.File

imports/wasi_snapshot_preview1/fs.go, internal/gojs/fs.go, internal/platform/file.go, internal/platform/file_test.go, internal/platform/stat_test.go, internal/sys/fs.go
=> Adds Truncate to platform.File

internal/integration_test/engine/threads_test.go, internal/wasm/binary/memory.go, internal/wasm/binary/memory_test.go
So sorry, I completely forgot to address this issue from @ncruces 
https://github.com/tetratelabs/wazero/pull/1460#discussion_r1193557372
=> Require max size for shared memory

internal/engine/compiler/impl_amd64.go
I've been looking at compiled code (amd64) and noticed out-of-bounds checks in `compileMemoryAccessCeilSetup` account for quite a bit of runtime, so I set out to try and optimize them a bit.
Basically on every instruction that might trap, we currently compile the trap and skip over it if a condition is met. This blows up compiled code significantly if there are a lot of instructions that might trap.
I kept pretty much the same logic, but cache a trap's address the first time it's compiled, and on future appearances directly jump into the previously compiled trap if the condition is *not* met.
This should not affect code generated for functions that either don't trap at all, or that trap only once (I tried not to make those worse). Functions that trap a lot get the benefit.
I'm making this …
=> compiler(amd64): generate trap exit code once

internal/integration_test/vs/wasmedge/go.mod
=> vs: fixes wasmedge version

internal/engine/compiler/impl_amd64.go
This uses a conditional move to find the maximum and removes one of the bounds checks thanks to it.
The difference is pretty negligible in my [`speedtest1`](https://github.com/ncruces/go-sqlite3/tree/main/vfs/tests/speedtest1) SQLite benchmark, but measurable:
```sh
speedtest1 % (cd ~/wazero; git switch main)
speedtest1 % go test -bench=. -benchtime=50x -count=10 --memdb | tee before.txt
speedtest1 % (cd ~/wazero; git switch traps)
speedtest1 % go test -bench=. -benchtime=50x -count=10 --memdb | tee trap.txt
```
Benchstat results:
```sh
goos: darwin
goarch: amd64
pkg: github.com/ncruces/go-sqlite3/vfs/tests/speedtest1
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
│ before.txt  │             after.txt              │
_speedtest1-12 …
```
=> compiler(amd64): eliminate a bounds check in memory copy

site/content/community/users.md
Finally found a few free cycles to take care of this! 🙇
=> site: add wzprof to the list of community projects

internal/engine/compiler/impl_amd64.go
This trades an unneeded XOR for one less jump.
Confirmed clang does the same tradeoff.
At this point, it looks like I'm playing for commit count.
OTOH I assume these code blocks _will_ be reused in the new compiler (SSA optimization works at a different level).
=> compiler(amd64): avoid unnecessary jump in signed remainder

Makefile, internal/integration_test/fuzz/README.md
=> fuzz: pass rss_limit_mb flag to avoid OOM

RATIONALE.md
While working on #1529, I noticed our RATIONALE was backwards around dot entries. Shortly after it was written, WASI mandated dot entries despite knowing problems with them for over three years. Our implementation switched as well, to pass the wasi-testsuite. This collects all relevant notes as they affect all design points around portable directory iteration, especially when it comes to supporting wasip1 and wasip>1.
=> Fixes drift in RATIONALE about readdir and dot entries

imports/wasi_snapshot_preview1/wasi_bench_test.go
The benchmark for `fd_readdir` has been broken for a while. We need to fix this before releasing to ensure we know the performance after various recent work.
I ran this benchmark now vs 34324031cb6d1f4b96ff706c72acd054fc70d6fd, which was before we started changing the readdir impl.
A later PR will correct the performance by being more like the former <1.2.0 impl.
```
goos: darwin
goarch: arm64
│ before-refactor.txt │              now.txt               │
│       sec/op        │   sec/op     vs base               │
_fdReaddir/embed.FS-12                          2.255µ ± 7%   2.879µ ± 6%  +27.70% (p=0.002 n=6)
_fdReaddir/embed.FS_-_two_calls-12              2.897µ ± 1%   3.606µ ± 3%  +24.50% (p=0.002 n=6) …
```
=> wasi: fixes fd_readdir bench

RATIONALE.md, config.go
=> Adds more links to rationale about start functions

Makefile, experimental/sys/syscall_errno.go, experimental/sys/syscall_errno_notwindows.go, experimental/sys/syscall_errno_plan9.go, experimental/sys/syscall_errno_windows.go, imports/wasi_snapshot_preview1/sock.go, internal/sock/sock_plan9.go, internal/sock/sock_supported.go, internal/sys/fs.go, internal/sysfs/dirfs.go, internal/sysfs/file_test.go, internal/sysfs/file_unix.go, internal/sysfs/file_unsupported.go, internal/sysfs/file_windows.go, internal/sysfs/ino.go, internal/sysfs/ino_plan9.go, internal/sysfs/ino_windows.go, internal/sysfs/nonblock_plan9.go, internal/sysfs/nonblock_unix.go, internal/sysfs/nonblock_windows.go, internal/sysfs/osfile.go, internal/sysfs/rename_plan9.go, internal/sysfs/stat_bsd.go, internal/sysfs/stat_linux.go, internal/sysfs/stat_unsupported.go, internal/sysfs/stat_windows.go, internal/sysfs/unlink.go, internal/sysfs/unlink_plan9.go, internal/sysfs/unlink_windows.go
=> Supports compilation with GOOS=plan9

.github/workflows/integration.yaml
=> ci: runs Standard Library Integration Tests on main

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/regalloc/api.go, internal/engine/wazevo/backend/regalloc/api_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/testcases/testcases.go, internal/engine/wazevo/wazevo_test.go, internal/engine/wazevo/wazevoapi/offsetdata.go, internal/engine/wazevo/wazevoapi/offsetdata_test.go
=> wazevo: adds support for calling imported functions

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/arm64/abi_go_entry_arm64.go, internal/engine/wazevo/backend/isa/arm64/abi_go_entry_arm64.s, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/machine.go, internal/engine/wazevo/backend/machine_test.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/call_engine_test.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/entrypoint_arm64.go, internal/engine/wazevo/entrypoint_others.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/testcases/testcases.go, internal/engine/wazevo/wazevo_test.go, internal/engine/wazevo/wazevoapi/exitcode.go, internal/engine/wazevo/wazevoapi/offsetdata.go, internal/engine/wazevo/wazevoapi/offsetdata_test.go
=> wazevo: adds support for memory.grow,size instructions

internal/engine/compiler/engine.go, internal/engine/interpreter/interpreter.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/frontend/lower_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/engine/wazevo/testcases/testcases.go, internal/engine/wazevo/wazevoapi/offsetdata.go, internal/engine/wazevo/wazevoapi/offsetdata_test.go, internal/wasm/engine.go, internal/wasm/store.go, internal/wasm/store_test.go
=> wazevo: adds support for imported memory

internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go, internal/engine/wazevo/backend/machine.go, internal/engine/wazevo/backend/machine_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/hostmodule.go, internal/engine/wazevo/hostmodule_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/engine/wazevo/wazevo_test.go, internal/engine/wazevo/wazevoapi/exitcode.go, internal/engine/wazevo/wazevoapi/exitcode_test.go, internal/engine/wazevo/wazevoapi/offsetdata.go
=> wazevo: adds support for host functions

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/ssa/pass_test.go, internal/engine/wazevo/testcases/testcases.go
=> wazevo: adds support for store instructions

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go, internal/engine/wazevo/backend/regalloc/coloring_test.go, internal/engine/wazevo/backend/regalloc/reg.go, internal/engine/wazevo/backend/regalloc/reg_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go
=> regalloc: enforces unique definition of virtual regs

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
for consistency with other instructions.
#1496
=> wazevo(arm64): consolidates fcel for single/double precisions

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/engine/wazevo/testcases/testcases.go
=> wazevo: adds support for calling imported-exported func

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go
=> wazevo: adds support for imported-exported memory

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo: fixes the format of fpumov64/128

internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/regalloc/api.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/ssa/builder.go
=> wazevo: passes address, binary, data, nop, etc spec tests

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go
=> wazevo: passes local_get.wast

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/basic_block.go, internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/builder_test.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/ssa/pass.go, internal/engine/wazevo/ssa/pass_test.go
=> wazevo: pass memory_size.wast

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/ssa/basic_block.go, internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/builder_test.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/ssa/pass.go, internal/integration_test/spectest/spectest.go
=> wazevo: pass memory_grow.wast

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go
=> wazevo: pass br, break-drop, and block spectests

internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/ssa/builder.go
=> wazevo: passes fac spectest

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/wasm/store.go
=> wazevo: passes start spectest

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/wazevoapi/exitcode.go
=> wazevo: passes traps, conversions spectest

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/coloring.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/ssa/pass.go, internal/engine/wazevo/ssa/vs.go, internal/engine/wazevo/wazevoapi/debug_consts.go
=> wazevo: removes unused SSA insts, centralizes debug toggles

internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/wazevoapi/debug_consts.go
=> wazevo: adds disassemblable machine code option for debugging

internal/engine/wazevo/backend/regalloc/api.go, internal/engine/wazevo/backend/regalloc/api_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/assign_test.go, internal/engine/wazevo/wazevoapi/debug_consts.go
=> wazevo(regalloc): support for spill on function pointer of indirect call

internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc_test.go
=> wazevo(arm64): fixes spill/reload logic

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/regalloc/api.go, internal/engine/wazevo/backend/regalloc/api_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/assign_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(regalloc): refactors assignment logic to isolate spill handling

internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_test.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/regalloc/api_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/assign_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go, internal/engine/wazevo/backend/regalloc/spill_handler.go, internal/engine/wazevo/backend/regalloc/spill_handler_test.go, internal/engine/wazevo/e2e_test.go
This make it pass "skip-stack-guard-page" spectest!!
#1496
=> wazevo(regalloc): support for reg spills

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_constant.go
=> wazevo(arm64): adds fast path for loading zero f32/64

internal/engine/wazevo/backend/isa/arm64/lower_constant.go
=> wazevo(arm64): use real reg to load f32/64 zeros

internal/engine/wazevo/e2e_test.go, internal/integration_test/spectest/v2/spec_test.go, internal/integration_test/spectest/v2/spectest.go
=> wazevo: adds test harness for v2 spectests

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_constant.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/isa/arm64/util_test.go, internal/engine/wazevo/backend/machine.go, internal/engine/wazevo/backend/machine_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/wazevoapi/debug_options.go
=> wazevo: adds tests for high register pressure

site/content/community/users.md
It took too long to get this added. Impart ❤️ wazero!
=> Add Impart Security to the users page

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
=> wazevo: adds tests for high register pressure: part2

internal/engine/wazevo/backend/abi.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call.go, internal/engine/wazevo/backend/isa/arm64/abi_go_entry.go, internal/engine/wazevo/backend/isa/arm64/abi_go_entry_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc_test.go, internal/integration_test/fuzz/fuzz/fuzz_targets/wazero_abi.rs
=> wazevo(arm64): fixes Go entry ABI for arbitrary # of params/results

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(arm64): fixes constant call argument inlining

internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
=> wazevo(arm64): fixes extended load sizes

internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go
=> wazevo: fixes extended register operands for arm64, imported memory size type

internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/testcases/testcases.go
=> wazevo(frontend): fix if-end nesting unreachable if-else-end

internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_test.go
=> wazevo: sets finalizers on executables

internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
=> wazevo(arm64): fixes shifted register operands

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go
=> wazevo: passes multiple return spectests

internal/engine/compiler/engine_test.go, internal/engine/interpreter/interpreter_test.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/module_engine.go, internal/integration_test/engine/adhoc_test.go, internal/integration_test/engine/hammer_test.go, internal/testing/enginetest/enginetest.go
=> wazevo: supports for LookupFunction API

internal/engine/wazevo/call_engine.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/integration_test/engine/adhoc_test.go
=> wazevo: fixes re-exported function imports

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/wazevoapi/debug_options.go
follow-up to #1496. Passes simd_bitwise.
=> wazevo: passes simd_bitwise spec tests

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/testcases/testcases.go
=> wazevo(arm64): fixes VBitselect translation

internal/engine/wazevo/engine.go, internal/integration_test/engine/hammer_test.go, internal/integration_test/engine/memleak_test.go
=> wazevo: passes hammer and memleak tests

internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/coloring.go, internal/integration_test/engine/adhoc_test.go
but I found another failing case which I will resolve in the next few days
#1496
=> wazevo: passes huge stack integration tests

internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call.go, internal/engine/wazevo/backend/isa/arm64/abi_test.go, internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
=> wazevo(arm64): remove allocInstrAfterRegalloc API for simplicity

internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble.go, internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble_test.go, internal/integration_test/engine/adhoc_test.go
=> wazevo: passes many params/results tests

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble.go, internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble_test.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/arm64/abi_test.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go, internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go, internal/integration_test/engine/adhoc_test.go
=> wazevo: passes all many params/results tests

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go
continues #1496, passes simd_cmp family of tests.
also checked against `DeterministicCompilationVerifierEnabled`
=> wazevo: passes simd_cmp spec tests

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go, internal/integration_test/spectest/spectest.go
=> wazevo: passes simd f32/f64 cmp, rounding, pmax+pmin spec tests

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go
- wazevo: passes simd f32/f64 trunc sat spec tests
- wazevo: conversions spec tests
continues #1496
=> wazevo: passes simd f32/f64 trunc + conversions spec tests

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_cache.go, internal/engine/wazevo/engine_cache_test.go, internal/engine/wazevo/wazevo_test.go, internal/integration_test/filecache/filecache_test.go
=> wazevo: adds support for file cache 

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine_cache.go, internal/engine/wazevo/engine_cache_test.go
=> wazevo: save source map in file cache

internal/engine/wazevo/engine.go, internal/engine/wazevo/wazevoapi/debug_options.go
=> wazevo: fixes deterministic compilation verifier

internal/engine/wazevo/e2e_test.go
=> wazevo: enables v2 sign-extension-ops tests

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/lower.go
=> wazevo: passes ref_null spec test

internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_test.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/wazevo_test.go, internal/engine/wazevo/wazevoapi/exitcode.go, internal/engine/wazevo/wazevoapi/offsetdata.go
=> wazevo: passes table.size spec test

internal/engine/wazevo/call_engine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_test.go, internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/wazevo_test.go, internal/engine/wazevo/wazevoapi/exitcode.go, internal/engine/wazevo/wazevoapi/offsetdata.go
=> wazevo: passes ref_func spectest

internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go
=> wazevo: passes table_fill spectest

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): fixes 64-bit div/rem zero div check

internal/engine/wazevo/engine.go, internal/engine/wazevo/engine_cache.go, internal/engine/wazevo/engine_cache_test.go, internal/engine/wazevo/engine_test.go, internal/engine/wazevo/module_engine.go, internal/engine/wazevo/module_engine_test.go, internal/engine/wazevo/wazevo_test.go, internal/integration_test/engine/memleak_test.go
=> wazevo: fixes memory leak 

internal/filecache/file_cache_test.go
no idea how it got into the file
=> filecache: removes unnecessary build tag in test

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): fixes Rotl translation not to override rm

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/lower_constant.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/util_test.go, internal/integration_test/fuzz/wazerolib/nodiff_test.go
=> wazevo(arm64): mandates SSA type spec on tmp VReg

internal/engine/wazevo/backend/isa/arm64/instr.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding.go, internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/instructions.go
=> wazevo: passes simd_i16x8_q15mulr_sat_s spec test

internal/integration_test/fuzz/README.md, internal/integration_test/fuzz/fuzz/fuzz_targets/memory_no_diff.rs, internal/integration_test/fuzz/fuzz/fuzz_targets/no_diff.rs, internal/integration_test/fuzz/fuzz/fuzz_targets/wazero_abi.rs
cc @evacchi this allows you to run fuzzing with SIMD enabled.
=> fuzz: enable SIMD for wazevo

internal/integration_test/fuzz/README.md
=> fuzz: documents to use --sanitizer=none

Makefile
=> fuzz: add `--sanitizer=none` to Makefile

internal/engine/wazevo/backend/regalloc/coloring.go, internal/engine/wazevo/backend/regalloc/coloring_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(regalloc): reduces the complexity

internal/engine/wazevo/backend/isa/arm64/abi.go, internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go, internal/engine/wazevo/backend/regalloc/assign_test.go, internal/engine/wazevo/backend/regalloc/coloring.go, internal/engine/wazevo/backend/regalloc/coloring_test.go, internal/engine/wazevo/backend/regalloc/reg.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go, internal/integration_test/engine/memleak_test.go
=> wazevo(regalloc): reduces map usages

internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/coloring.go
=> wazevo(regalloc): removes unnecessary validation pass 

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/coloring.go, internal/engine/wazevo/backend/regalloc/coloring_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(regalloc): makes coloring faster

site/content/community/users.md
Add wazero-emscripten-embind to list of Wazero users
=> Add wazero-emscripten-embind to users page

internal/engine/wazevo/backend/regalloc/assign.go, internal/engine/wazevo/backend/regalloc/assign_test.go, internal/engine/wazevo/backend/regalloc/coloring.go, internal/engine/wazevo/backend/regalloc/coloring_test.go, internal/engine/wazevo/backend/regalloc/interval_tree.go, internal/engine/wazevo/backend/regalloc/interval_tree_test.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go
=> wazevo(regalloc): refactors data structure on live ranges

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go, internal/engine/wazevo/backend/isa/arm64/util_test.go, internal/engine/wazevo/ssa/instructions.go
=> wazevo: reduces map usages

internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/compiler_lower.go, internal/engine/wazevo/backend/isa/arm64/machine.go, internal/engine/wazevo/backend/isa/arm64/machine_test.go, internal/engine/wazevo/backend/regalloc/interval_tree.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go, internal/engine/wazevo/ssa/basic_block.go, internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/instructions.go, internal/engine/wazevo/wazevoapi/pool.go
=> wazevo: pass reset func to NewPool

internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(regalloc): removes map usage of phi tracking

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/compiler.go, internal/engine/wazevo/backend/isa/arm64/lower_constant_test.go, internal/engine/wazevo/backend/regalloc/reg.go, internal/engine/wazevo/backend/regalloc/reg_test.go
=> wazevo(backend): makes VRegID continuous

internal/engine/wazevo/backend/regalloc/reg.go, internal/engine/wazevo/backend/regalloc/regalloc.go, internal/engine/wazevo/backend/regalloc/regalloc_test.go
=> wazevo(regalloc): deletes unnecessary kills info

internal/engine/wazevo/call_engine.go, internal/engine/wazevo/call_engine_test.go
=> wazevo: adds 16 bytes to the new stack size

internal/engine/wazevo/ssa/basic_block.go
=> wazevo(ssa): resets loop header flag

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): use tmp regs to store values used during branches

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go, internal/engine/wazevo/backend/isa/arm64/util_test.go
=> wazevo(arm64): fixes tmp register types

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): fixes copyToTmp 

internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/type.go
=> wazevo(ssa): resets nextVariable

internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go, internal/engine/wazevo/backend/isa/arm64/machine.go
=> wazevo(arm64): reuses queue in addr lowering

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): fixes lowerSelectVec

internal/engine/wazevo/backend/isa/arm64/lower_instr.go, internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
=> wazevo(arm64): fixes Vector select

internal/engine/wazevo/backend/regalloc/regalloc.go
=> wazevo(regalloc): set reg usage flag in swaps

Makefile, internal/integration_test/fuzz/Cargo.lock, internal/integration_test/fuzz/fuzz/Cargo.toml, internal/integration_test/fuzz/fuzz/fuzz_targets/wazero_abi.rs, internal/integration_test/fuzz/fuzz/tests/sigstack.rs, internal/integration_test/fuzz/wazerolib/lib.go, internal/integration_test/fuzz/wazerolib/lib_test.go
This took me at least 3 months since the first encounter to figure out what's going on.
=> fuzz: ensures the alternate stack for signal handling 

internal/engine/wazevo/backend/isa/arm64/lower_constant.go, internal/engine/wazevo/backend/isa/arm64/lower_instr.go
Although this doesn't come with any noticeable perf improvements,
this reduces the size of the compiled executable of Zig stdlib 1MB out of 80MB.
=> wazevo(arm64): lower constant bitwise ops with bitmask immeidates

internal/engine/wazevo/backend/regalloc/regalloc.go
in order to just be less error prone
=> regaclloc: uses Pool for blockStates

internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/backend/isa/amd64/operands.go
=> wazevo(amd64): fixes a typo

internal/engine/compiler/impl_amd64.go
Sorry forgot this ><
Not sure it would manifest as #1936 but hoping it is since it's fundamental brokenness
=> threads: load memory bounds directly with shared memory for amd64

internal/engine/wazevo/backend/isa/amd64/lower_mem.go, internal/engine/wazevo/backend/isa/amd64/lower_mem_test.go, internal/engine/wazevo/backend/isa/amd64/machine_test.go, internal/engine/wazevo/backend/isa/amd64/operands.go
add address mode lowering/folding with tests
=> wazevo(amd64): amode lowering

internal/integration_test/fuzz/fuzz/build.rs, internal/integration_test/fuzz/fuzz/fuzz_targets/memory_no_diff.rs, internal/integration_test/fuzz/fuzz/fuzz_targets/no_diff.rs, internal/integration_test/fuzz/wazerolib/nodiff.go
=> fuzz: enables threads by default

internal/engine/wazevo/backend/isa/amd64/lower_mem.go, internal/engine/wazevo/backend/isa/amd64/lower_mem_test.go, internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
=> wazevo(amd64): amode lowering, delete redundant tests, invalid SSA form

internal/engine/wazevo/frontend/frontend.go, internal/engine/wazevo/frontend/lower.go
=> wazevo(frontend): do not reload memory base/len when shared

internal/engine/wazevo/backend/isa/amd64/abi_go_call.go, internal/engine/wazevo/backend/isa/amd64/abi_go_call_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/backend/isa/amd64/machine_pro_epi_logue.go, internal/engine/wazevo/backend/isa/amd64/stack.go, internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go, internal/engine/wazevo/call_engine.go, internal/engine/wazevo/call_engine_test.go, internal/engine/wazevo/e2e_test.go
=> wazevo(amd64): stack grow support

internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/testcases/testcases.go
- wazevo(amd64): float copysign
=> wazevo(amd64): support for copysign

internal/engine/wazevo/backend/isa/amd64/instr.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/e2e_test.go
=> wazevo(amd64): bitcast, fpromote, fdemote

RATIONALE.md, README.md, experimental/sys/file.go, experimental/sys/fs.go, fsconfig.go
=> typo: compatability->compatibility

internal/engine/wazevo/module_engine.go
=> wazevo: fixes newAlignedOpaque not to use unsafe

internal/engine/wazevo/backend/isa/amd64/instr.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/backend/isa/amd64/machine_vec.go, internal/engine/wazevo/e2e_test.go, internal/integration_test/spectest/v2/spec_test.go
=> wazevo(amd64): completes all v2 specification

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/testcases/testcases.go
=> wazevo(amd64): lower Icmp(Band(x,y), 0) to one TEST

internal/engine/wazevo/backend/isa/amd64/machine.go
now I can see the block level perf
=> wazevo(amd64): support for perfmap

internal/engine/wazevo/backend/backend_test.go, internal/engine/wazevo/engine.go, internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/pass.go, internal/engine/wazevo/ssa/pass_blk_layouts.go, internal/engine/wazevo/ssa/pass_blk_layouts_test.go, internal/engine/wazevo/ssa/pass_cfg.go, internal/engine/wazevo/ssa/pass_cfg_test.go, internal/engine/wazevo/ssa/vs.go
=> wazevo(ssa): refactors pass execution

internal/engine/wazevo/backend/regalloc/regalloc.go
necessary piece to https://github.com/tetratelabs/wazero/pull/2094
=> wazevo(regalloc): finalize start regs on preds allocation

internal/integration_test/fuzzcases/fuzzcases_test.go, internal/wasm/func_validation.go
found in https://github.com/tetratelabs/wazero/actions/runs/8135070073/job/22228998097
=> validation: return error on unknown opcode after misc prefix

internal/engine/wazevo/backend/isa/amd64/instr.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/backend/isa/amd64/machine_regalloc.go, internal/engine/wazevo/backend/isa/amd64/machine_regalloc_test.go, internal/engine/wazevo/e2e_test.go
=> wazevo(amd64): support for atomic stores

internal/engine/wazevo/frontend/frontend_test.go, internal/engine/wazevo/frontend/lower.go, internal/engine/wazevo/ssa/builder.go, internal/wasm/func_validation.go, internal/wasm/module.go
amd64: 8485519->8478767 = 6752 bytes
arm64: 8632852->8624468 = 8384 bytes
=> wazevo(frontend): fast pass for static local searches

internal/engine/wazevo/backend/isa/arm64/lower_mem.go, internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
=> wazevo(arm64): simplifies lowerLoadSplat

internal/engine/wazevo/backend/isa/amd64/instr.go, internal/engine/wazevo/backend/isa/amd64/instr_encoding.go, internal/engine/wazevo/backend/isa/amd64/machine.go, internal/engine/wazevo/e2e_test.go, internal/engine/wazevo/wazevo_test.go, internal/integration_test/engine/threads_test.go, internal/integration_test/spectest/threads/spec_test.go
=> wazevo(amd64): complete threads spec

internal/integration_test/fuzz/fuzz/fuzz_targets/validation.rs, internal/integration_test/fuzz/wazerolib/validate.go, internal/wasm/func_validation.go, internal/wasm/func_validation_test.go
https://github.com/tetratelabs/wazero/actions/runs/8242242934/job/22540898762
=> validation: handles edge case of unexpected else

internal/engine/wazevo/backend/isa/arm64/machine_relocation.go
This identifies the root cause for #2158
=> wazevo(arm64): adds assertion on too large relocations

internal/wasm/memory.go, internal/wasm/memory_test.go, internal/wasm/module_instance.go
this simplifies the discussion around https://github.com/tetratelabs/wazero/pull/2157 cc @anuraaga @ncruces
=> threads: stop explicit use of mmap for shared memory

internal/platform/mmap_unix.go, internal/platform/mmap_unsupported.go, internal/platform/mmap_windows.go, internal/platform/platform.go
=> threads: remove dead code

internal/engine/wazevo/backend/isa/arm64/machine.go
Fixes #2179  This small bug took me the entire two days to figure out...
=> compiler(arm64): fixes B.cond offset limits

internal/engine/interpreter/interpreter.go, internal/engine/wazevo/engine.go, internal/integration_test/engine/hammer_test.go
Fixes #2190 #2192. Thank you for reporting @martinlakov
=> Fixes race condition in concurrent engine usage

internal/engine/wazevo/engine_test.go
=> Fixes flaky TestEngine_sortedCompiledModules

internal/engine/wazevo/ssa/builder.go, internal/engine/wazevo/ssa/pass.go
This makes the compilation slightly faster, but almost identical 
while having the map-free code.
=> ssa: removes redundantParameterIndexToValue map

.github/workflows/commit.yaml
=> ci: cleanup vs directory

experimental/importresolver_example_test.go
Compile once and reuse.
See #2294
Signed-off-by: Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>
=> Improve ImportResolver example

site/content/community/users.md
Hi.  I'm happy to announce the release of Modus, an open source WASM-based serverless framework powered in-part by Wazero.  Thanks for all the amazing work you've put in to Wazero, and thanks in advance for adding us to the list!
=> Add Modus to "who's using wazero" list

site/content/community/users.md
Oops! With #2333 I added Modus to the wrong section of the users page.  Fixed.
I also adjusted the table layout and fixed a typo.
=> Fix users list

.github/workflows/integration.yaml
=> Fixes libsodium workflow
