- wasm/vm.go
This `RuntimeData` can be used to persist runtime status  for `wasm`.
> add RuntimeData field to VirtualMachine

- wasm/module.go
- wasm/module_test.go
Hi @mathetake! First of all, nice work with this project!
I tried running a rust-compiled hello world program with the `wasm32-wasi` target, started adding the required methods into the `wasi` package, and was pretty excited to get it working, but then kept getting a `function signature mismatch` panic from the `callIndirect` function in `vm_call.go`. It took me quite a while to debug, and I got to understand the wasm binary format way better because of it, but finally found the culprit:
There's a classic bug in the code that populates the table index space. This loop:
```go
for i, b := range elem.Init {
table[i+offset] = &b
}
```
Takes the pointer of the temporary variable, which is reused on every iteration. The fix is just to use `table[i+offset] = &elem.Init[i]`.
Hope you see this …
> Fix table index bug

- wasm/engine.go
- wasm/naivevm/vm.go
- wasm/store.go
This completes the migration for moving all the interpreter specific logics under `Engine` interface.
> Add Compile method on Engine interface.

- LICENSE
- Makefile
- NOTICE
- README.md
- examples/fibonacci_test.go
- examples/file_system_test.go
- examples/host_func_test.go
- examples/stdio_test.go
- examples/trap_test.go
- go.mod
- wasi/wasi.go
- wasm/const_expr.go
- wasm/naivevm/vm.go
- wasm/naivevm/vm_call.go
- wasm/naivevm/vm_control.go
- wasm/naivevm/vm_memory.go
- wasm/naivevm/vm_stack.go
- wasm/section.go
- wasm/segment.go
- wasm/spectests/spec_test.go
- wasm/store.go
- wasm/type.go
- wasm/value.go
This renames the project to wazero, which emphasizes that this runtime
has no platform depedencies (notably CGO). To avoid having users change
their imports twice, this also changes the org to "tetratelabs" ahead of
transfer.
Exciting times ahead, wazeros!
> Renames to tetratelabs/wazero

- .github/workflows/commit.yaml
- Makefile
spectests are derived from a remote location. This tests files checked
in match the commit. This also ensures the target to do so works.
> Ensures pre-commit check verifies spectest coherence

- go.mod
- wasm/buildoptions/callstack_overflow_disabled.go
- wasm/buildoptions/callstack_overflow_enabled.go
- wasm/buildoptions/debug_disabled.go
- wasm/buildoptions/debug_enabled.go
I believe this is the way to enable both go1.16 and go1.17+ support.
> build: go 1.16 support by adding +build comments alongside go:build ones

- .github/workflows/commit.yaml
- go.mod
This ensures we temporarily support go 1.16 per #37
Notably, this does not attempt to run linters or other optional tasks as we use go 1.17 features such as `go run` against a versioned tag.
> Ensures CI tests with Go 1.16

- README.md
- examples/fibonacci_test.go
- examples/file_system_test.go
- examples/host_func_test.go
- examples/stdio_test.go
- examples/trap_test.go
As per #49, this commit uses wazeroir in examples to showcase that it is the default engine we recommend.
> Use wazeroir in examples.

- Makefile
- bench/debug_bench_test.go
I believe that this shows the cost factor of const vs var vs object
field guards on debug flags. Particularly, const can only be set via
build flags, var (and obj) via ldflags or config. There are usability
impacts so, this can help show impact.
This uses `Fprintf`, not something more arbitrary like 1+1 to show
relative impact as almost all debug guards cover a printf.
My analysis:
On my laptop, the guard on true cost is small, like 0.05ns, but in CI it
can accumulate to almost 0.18ns. If these are in extremely large loops it
could be a factor to consider retaining debug flag as compilation only
(a build flag). For example, 5-20k checks would accumulate to a
microsecond.
Besides this overhead in large loops (or inner loops), the other main
factor is that restricting to compilation means …
> Adds benchmarks around debug flags

- wasm/optcode.go
This starts to document opcodes by choosing some of the harder ones first
> Documents structured control instructions

- wasm/module.go
- wasm/module_test.go
- wasm/section.go
This simplifies the header checks as they are ASCII so can be compared easier.
This also defocuses internal code from `io.Reader` as it is unimportant as `wasm.Reader` doesn't need to be exported: since it doesn't need to be exported, functions that require `io.Reader` will already fail compilation upon not implemented at the call site.
> Adds header decoding tests and simplifies

- wasm/jit/engine.go
- wasm/jit/engine_test.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_value_location_amd64.go
- wasm/jit/jit_value_location_amd64_test.go
This commit resolves one TODO for growing stack automatically 
when the engine enters new JITed function frames and sees the necessity
to grow the stack.
part of #65.
> jit: grow stack automatically. 

- wasm/wat/lexer.go
- wasm/wat/lexer_test.go
It seems strange to me to intentionally allow NULL byte in the middle of comments and strings, but that's allowed by spec! This switches the malformed test to use 0x80 which is invalid unicode.
> Allows NULL per spec

- wasm/jit/RATIONALE.md
- wasm/jit/engine.go
- wasm/jit/engine_test.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64.s
- wasm/jit/jit_amd64_test.go
- wasm/jit/jit_value_location_amd64.go
- wasm/jit/jit_value_location_amd64_test.go
- Renamed `*BaseStack*` -> `*StackBase*`
- Prefixed all the reserved registers with `reservedRegisterFor`
> Refactor namings around engine and registers

- wasm/wat/lexer.go
- wasm/wat/lexer_test.go
- wasm/wat/module.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
- wasm/wat/types.go
This builds on the lexing layer to parse the WebAssembly Text Format.
The PR after this will convert the following text format to a `wasm.Module`
```wat
(module
(import "" "hello" (func $hello))
(start $hello)
)
```
> Adds initial WebAssembly Text Format (%.wat) parser

- wasm/jit/engine.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
- wasm/store.go
- wasm/type.go
- wasm/wazeroir/compiler.go
- wasm/wazeroir/interpreter.go
- wasm/wazeroir/signature.go
Since there is no ambiguity in FunctionType about it being types, this
removes the suffix Type from its fields. I wouldn't do this, if for
example, there were mixed fields (ex type names). However, as it is, I
think this is less stuttering so overall better.
> Removes suffix Type from fields in FunctionType

- .github/workflows/commit.yaml
Looks like a cache is so old that it doesn't contain any cache for goimports and golangci-lint
> Update Go cache in Pre-commit

- wasm/segment.go
- wasm/store.go
It is easier to reason with the function type index as a number instead
of a pointer. It is also easier to unit test. We don't need the second
pointer guard because the import definition already checks the type (ex
func vs table) first.
This also fixes a typo
> TypeIndexPtr -> FuncTypeIndex

- .github/workflows/commit.yaml
> ci: include Job ID and Go version in the cache key.

- wasm/leb128/leb128.go
- wasm/leb128/leb128_test.go
- wasm/wat/convert_test.go
- wasm/wat/names.go
- wasm/wat/names_test.go
I'd like to test the output vs another tool, but it seems like perhaps the name section is encoded differently in wabt, ex maybe they strip the leading '$'. I'd like to get a binary dump of some name section from maybe wasm-tools and/or wabt to compare both against the spec and the values encoded for the same input.
```
(module $simple
(import "" "hello" (func $hello))
(start $hello)
)
```
> Adds custom name section encoder

- wasm/wat/lexer.go
- wasm/wat/names_test.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
- wasm/wat/types.go
This generifies some parser state so that it can be reused next for
parsing parameter names. This also cleans up some ++ stuff.
> Text Format: reduces the amount of parsing state

- wasm/jit/compiler.go
- wasm/jit/engine.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
> jit: support for and, or, xor, shl, shr, rotl and rotr operations

- wasm/wat/names_test.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
This begins support of real functions as before we hard-coded all are
nullary (void in void out). As there's a lot of refactoring left to do,
this starts only by supporting inlined type (signatures) for imported
functions. This does not handle inlined parameter names which are a bit
complicated so would make the PR too hard to review.
> wat: support import functions with inlined types

- wasm/wat/convert.go
- wasm/wat/names_test.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
- wasm/wat/type_parser.go
- wasm/wat/type_parser_test.go
- wasm/wat/types.go
This change does two things:
* enforces field names are first or not present
* Ex. (func $main) $main is the name of the func field
* enforces the order requirements of the type grammar. (param)* result?
* To reduce complexity, this logic is extracted to type_parser.
There is still 100pct coverage except TODO and panics
Extracting typeParser resulted in a performance decrease on the trivial benchmark because it initializes, but never needs a type parser. I think this is ok because in real life, %.wat files with anything non-trivial will end up with at least a few types.
decrease in speed
```
BenchmarkTextToBinaryExample/vs_wat.parseModule-16    	 1429618	       832.1 ns/op	     568 B/op	      23 allocs/op
BenchmarkTextToBinaryExample/vs_wat.parseModule-16    	 1293886	       977.1 ns/op …
```
> wat: enforces signature order

- wasm/wat/convert.go
- wasm/wat/names_test.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
- wasm/wat/type_parser.go
- wasm/wat/types.go
This refactors the code in preparation of parsing module types. There is
a lot of nuance around type signatures, so this restructures the code to
fit that idea and enhances the documentation in preparation.
> wat: refactors in preparation of module defined types

- wasm/wat/bind.go
- wasm/wat/bind_test.go
- wasm/wat/convert.go
- wasm/wat/convert_test.go
- wasm/wat/lexer.go
- wasm/wat/numbers.go
- wasm/wat/numbers_test.go
- wasm/wat/parser.go
- wasm/wat/parser_test.go
- wasm/wat/types.go
Before, we punted symbolic index binding until we converted into binary
format. This put logic in an awkward spot, which was ok if only the
start function, but not for generic index handling (such as type
binding).
This pulls a new file out for handling bindings, and also eagerly
validates numbers when we read an index. Most importantly, this binds
symbolic identifiers to numeric offsets on parse, which matches how
they work at runtime.
> wat: refactors symbolic index identifier handling

- wasm/store.go
- wasm/store_test.go
Hi, Thanks for developing a great wasm runtime!
This PR fixes `panic: assignment to entry in nil map` that occurs when `AddGlobal()`, `AddTableInstance()` or `AddMemoryInstance()` is called before `AddHostFunction()`.
This panic does not occur when `AddHostFunction()` called, because `ModuleInstance` is initialized with `Exports` field in `AddHostFunction()` as follows. This PR makes sure that other functions are initialized with `Exports` field as well.
https://github.com/tetratelabs/wazero/blob/6a309797efa5361f45c6a5cb64d567ecf5ceb16d/wasm/store.go#L1637
> Initialize module instance with `Exports` map

- wasm/names.go
- wasm/names_test.go
- wasm/section.go
This completes the codec for the binary name section, leaving some TODOs
for a rainy day.
> Finishes binary custom name section codec

- wasm/module.go
- wasm/module_test.go
- wasm/names.go
- wasm/names_test.go
- wasm/section.go
- wasm/store.go
- wasm/wat/convert.go
- wasm/wat/convert_test.go
`Store.Instantiate` needs the name section when building function
instances. Before, we had to lazy decode this as it wasn't decoded along
with the other data defined by the binary format. This acknowledges that
the name section is a standard field and top-levels it in the
`wasm.Module` type. It clarifies that anything else will stay in the
`Module.CustomSections` until we support more of them (perhaps Dwarf).
This also renames `CustomNameSection` to `NameSection` because the
standard refers it that way. It is the "name section", just for whatever
reason, they decided to store it as a custom section.
Nice side effects include centralization logic of binary decoding, and
also no more double-encoding of names from the text format. Before this
change, when converting text to binary, we had …
> Centralizes name section encoding and usage

- wasm/module.go
- wasm/section.go
- wasm/segment.go
- wasm/store.go
- wasm/wat/convert.go
- wasm/wat/convert_test.go
This flattens the type hierarchy of Export and Import a little as it
felt easier to reason with considering there are only 4 kinds.
This also dodges the Segment suffix because that only applies to
"element" and "data"
> Flattens Export and Import and dodges Segment suffix

- wasm/errors.go
- wasm/jit/engine.go
- wasm/jit/engine_test.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
- wasm/spectests/cases/call_indirect.wast
- wasm/spectests/spec_test.go
- wasm/store.go
- wasm/wazeroir/interpreter.go
This commit centralizes which runtime errors are possibly returned by engines, 
and document all of them on under which condition they occur.
Notably, now our spectest for `assert_trap` not only checks if the runtime returns error,
but also checks the type of error. This way, we can ensure that 
interpreter and JIT engines return exactly the same error for the same condition.
In order to achieve that, I found some discrepancies in the semantics between 
JIT and interpreter and resolved them. Notably, I refactored the code for division and 
remainder calculation in JIT so that they are alined with interpreter and spectests.
> Consolidate runtime errors

- wasm/module.go
- wasm/text/bind.go
- wasm/text/bind_test.go
- wasm/text/parser.go
- wasm/text/parser_test.go
- wasm/text/type_parser.go
- wasm/text/types.go
- wasm/text/types_test.go
> An identifier context is well-formed if no index space contains duplicate identifiers.
We weren't checking this, and now we are!. This comes at a cost, though,
but I don't see a good alternative to initializing maps wrt uniqueness.
```
BenchmarkCodecExample/text.DecodeModule
BenchmarkCodecExample/text.DecodeModule-16           	   78700	     14460 ns/op	    7328 B/op	     323 allocs/op
```
After
```
BenchmarkCodecExample/text.DecodeModule
BenchmarkCodecExample/text.DecodeModule-16           	   74214	     16921 ns/op	    8288 B/op	     333 allocs/op
```
See https://www.w3.org/TR/wasm-core-1/#text-context
> Enforces uniqueness within symbolic indices

- bench/bench_fac_iter_test.go
- go.mod
- go.sum
- wasm/internal/example/example_test.go
While both wasmer-go and wasmtime-go end up using wasm-tools for text
compilation, they do it slightly differently. This adds a dimension for
wasmer.
```
BenchmarkCodecExample/wat2wasm_via_text.DecodeModule->binary.EncodeModule
BenchmarkCodecExample/wat2wasm_via_text.DecodeModule->binary.EncodeModule-16         	   60103	     19967 ns/op	   12600 B/op	     456 allocs/op
BenchmarkCodecExample/wat2wasm_vs_wasmtime.Wat2Wasm
BenchmarkCodecExample/wat2wasm_vs_wasmtime.Wat2Wasm-16                               	   32911	     35606 ns/op	    1744 B/op	       3 allocs/op
BenchmarkCodecExample/wat2wasm_vs_wasmer.Wat2Wasm
BenchmarkCodecExample/wat2wasm_vs_wasmer.Wat2Wasm-16                                 	   31758	     37278 ns/op	    1776 B/op	       6 allocs/op
```
I also added this to the …
> adds wasmer comparison in benchmarks

- bench/bench_test.go
- wasm/jit/engine.go
- wasm/jit/engine_test.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
This commit refactors the code around function calls/returns and
reduces the generated instructions. Notably resolves #173 and skips
the module context switch which is supposed to happen on function 
entry and return. Given that, in almost all use cases, users instantiate
single Wasm binary and run the functions from it rather than doing
import/export on multiple binaries, the context switch almost never 
happens. therefore the branch prediction on whether or not 
skipping context switch code should be almost always correct.
As a result, the cost of function calls decreases up to 35% as 
you can see the bench mark result below where the bench case 
is "recursive" fibonacci function which is call heavy.
```
name                       old time/op    new time/op    delta …
```
> jit: refactor calling convention for less instructions in function calls

- RATIONALE.md
- wasm/binary/types.go
- wasm/engine.go
- wasm/interpreter/interpreter.go
- wasm/jit/engine.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
- wasm/mempage.go
- wasm/mempage_test.go
- wasm/store.go
This commit consolidates the logic and constants around memory pages,
and memory grow, size operations. Prior to this, memory.grow and size were
implemented in each engine and embedded deeply inside of runtime, which
made it impossible for us to write unit tests on it.
> Consolidate memory consts and grow operation

- RATIONALE.md
- tests/README.md
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
- wasm/store.go
- wasm/store_test.go
This PR add more documentations on wazero specific limits,
and impose the limitation in the module instantiation phase.
Also, this backfills tests for executeConstantExpression and buildGlobalInstances
and fixed a bug in the former.
The implementation on the function value stack height limit will be in a followup PR
as it would be rather large change.
> Add wazero specific limitations

- wasm/interpreter/interpreter.go
> interpreter: fix truncation to pass spectests on arm64

- .github/workflows/commit.yaml
- examples/stdio_test.go
This commit adds a CI job for running test on arm64 arch with qemu. The idea 
is just building test binaries with `go test -c` on amd64, not arm64 and 
running  these built test binaries inside the emulation.  This would reduce
the cost of build time in emulation.
> ci: add arm64 test job

- tests/engine/adhoc_test.go
- tests/engine/testdata/imported_and_exported_func.wat
- wasm/interpreter/interpreter.go
This PR fixes a bug that interpreter crashes when it calls such a guest function that was imported from the host into a wasm module, but was exported to the host again. This is an interpreter-only bug and JIT has been correctly handling this without problem.
Please note that this PR alone will not allow us to test the WASI APIs by calling such "imported and exported back" WASI API functions. It turned out that there is another issue. See #195
> Fix interpreter cannot call "imported-and-exported-back" function

- wasm/text/decoder.go
- wasm/text/decoder_test.go
- wasm/text/func_parser.go
- wasm/text/func_parser_test.go
- wasm/text/memory_parser.go
- wasm/text/type_parser.go
This moves logic to func_parser.go, which allows us to keep a coherent
function index when parsing code.
> text: fixes code section ID parsing a function

- tests/bench/interface_bench_test.go
as a reference to #204 
Here's the result (for 5 times), and this shows that there's certain overhead in the interface usage
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkInterfaceVSUnexport/interface-32         	  533025	      2370 ns/op	       0 B/op	       0 allocs/op
BenchmarkInterfaceVSUnexport/struct-32            	 1485394	       819.6 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	command-line-arguments	4.205s
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 3950X 16-Core Processor            
BenchmarkInterfaceVSUnexport/interface-32         	  452220	      2328 ns/op	       0 B/op	       0 allocs/op
BenchmarkInterfaceVSUnexport/struct-32            	 1499652	       798.9 ns/op	       0 B/op	       0 allocs/op
PASS
ok …
```
> Add struct vs interface access bench

- tests/engine/adhoc_test.go
- wasm/interpreter/interpreter.go
- wasm/jit/engine.go
- wasm/module.go
- wasm/module_test.go
- wasm/store_test.go
This PR fixes that `float32` parameters were not correctly passed to the host function.
> Fix float32-type parameter not working for host function

- wasm/jit/jit_arm64.go
- wasm/jit/jit_arm64_test.go
Hello, The JIT support for Arm64 is really nice!
This PR adds support of `and`, `or`, and `xor` instruction for Arm64 JIT.
This might be a part of #187.
I have implemented this with reference to the x86 JIT code.
If you have any concerns about this, I would appreciate your review comments!
> jit(arm64): support for and, or, and xor

- wasm/jit/jit_arm64.go
- wasm/jit/jit_arm64_test.go
Hello, Let me try to add more instruction support in the continuation of #225.
This PR adds support of `shl`, `shr`, `rotl`, and `rotr` instruction for Arm64 JIT.
This might be a part of https://github.com/tetratelabs/wazero/issues/187.
> jit(arm64): support for shl, shr, rotl, and rotr

- wasm/binary/decoder.go
- wasm/binary/decoder_test.go
- wasm/binary/encoder.go
- wasm/binary/section.go
- wasm/binary/section_test.go
- wasm/module.go
- wasm/module_test.go
- wasm/store.go
- wasm/text/decoder.go
- wasm/text/decoder_test.go
- wasm/text/errors.go
- wasm/text/func_parser.go
- wasm/text/func_parser_test.go
- wasm/text/index_namespace.go
- wasm/text/memory_parser_test.go
- wasm/text/type_parser_test.go
- wasm/text/typeuse_parser.go
- wasm/text/typeuse_parser_test.go
This consolidates more code around SectionID, notably consistently
getting and using section ID length. This also enforces rules in text
parsing such as up to one memory, and imported functions can't be
defined after regular ones.
> Adds Module.SectionSize and constrains text parsing rules

- wasm/binary/decoder.go
- wasm/binary/decoder_test.go
- wasm/binary/encoder.go
- wasm/binary/encoder_test.go
- wasm/binary/names.go
- wasm/binary/names_test.go
- wasm/binary/section.go
- wasm/module.go
- wasm/module_test.go
- wasm/store.go
- wasm/text/decoder.go
Per #232, we will be unexporting fields only used during instantiate. Any
additional custom sections are unusable otherwise, so this skips them.
In doing so, this eliminates a length check bug, some TODO and some
logic that enforced strict name uniqueness even though that only rule
only applied to the name section.
Note: this doesn't restrict future use of custom sections, ex for DWARF,
just we don't buffer sections we don't use anymore.
See https://www.w3.org/TR/wasm-core-1/#custom-section%E2%91%A0
> Removes CustomSection except NameSection

- wasm/jit/compiler.go
- wasm/jit/engine.go
- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
- wasm/jit/jit_arm64.go
- wasm/jit/jit_arm64_test.go
exception are `popValueOnRegister`, `popTwoValuesOnRegisters` and `allocateRegister` and they are left with TODO
> jit(arm64): Add common 'compile'/'maybeCompile' prefix

- wasm/jit/jit_amd64.go
- wasm/jit/jit_amd64_test.go
> jit(amd64): less instructions for memory bounds check: part 2

- api/host.go
- examples/host_func_test.go
- examples/simple_test.go
- tests/bench/bench_test.go
- tests/engine/adhoc_test.go
- tests/spectest/spec_test.go
- wasi/wasi.go
- wasi/wasi_test.go
- wasm/api.go
- wasm/engine.go
- wasm/host.go
- wasm/host_test.go
- wasm/interpreter/interpreter_test.go
- wasm/jit/engine.go
- wasm/store.go
- wasm/store_test.go
This adds two interfaces with only one implementation each, used to
decouple end-user code from internals.
* wasm.HostFunctionCallContext - allows access to go Context and Memory
* wasm.Memory - read/write standard types and arbitrary data
This currently ports existing code to use the interfaces. It is true
that over time we can use structs instead of interfaces internally to
save a pointer reference in WASI call sites. However, I'm choosing not
to do this right now, as it is more important to see the interfaces
work. We should defer optimizing towards structs until after we
repackage implementations under the "internal" directory.
Fixes #204
> Adds host function interfaces

- README.md
- examples/simple_test.go
- internal/wasi/wasi.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- store.go
- tests/engine/adhoc_test.go
This allows users to decouple from wazero code when authoring host
functions. Notably, this allows them to opt out of using a context, or
only using a Go context instead of HostFunctionCallContext.
This backfills docs on how to write host functions (in simple terms).
Finally, this does not optimize engines to avoid propagating context or
looking up memory if it would never be used. That could be done later.
> Removes requirement to pass a HostFunctionCallContext

- internal/wasi/wasi_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- store.go
- store_test.go
- tests/spectest/spec_test.go
- wasi.go
- wasi_test.go
- wasm/wasm.go
This adds `StoreConfig.Context` to centralize assignment of the initial
context used implicitly by the WebAssembly 1.0 (MVP) start function and
also the WASI snapshot-01 "_start" exported function. This also
backfills tests and comments around propagation.
> wasi: ensure the context used for _start is consistent

- README.md
- examples/add_test.go
- examples/fibonacci_test.go
- examples/host_func_test.go
- examples/wasi_test.go
- internal/wasm/host.go
- store_test.go
- tests/bench/bench_fac_iter_test.go
- tests/bench/bench_test.go
- tests/codec/codec_test.go
- tests/engine/adhoc_test.go
- wasi.go
- wasm/wasm.go
Before, we emulated the map api by returning `fn, ok` to tell if a
function was there or not. This made a lot of cruft vs returning `nil`
instead, especially as many times configuration of functions is near
where they are called in the source (so they aren't likely to be nil).
> Makes API easier by returning nil when a function isn't available

- README.md
- internal/wasm/jit/engine.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_other.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/engine/adhoc_test.go
- tests/spectest/spec_test.go
This commit completes the baseline single pass JIT engine for arm64 target.
The implementation passes 100% of specification tests and all the e2e tests
that have been used for amd64. Notably, the engine is stable under high
concurrency where multiple gorutines are holding stores and each of them
has Wasm execution environment.
One thing to note is that  the assembler (golang-asm) is not goroutine-safe,
so we have to take a lock on the assembler usage, therefore the compilation 
cannot scale to multiple CPU cores. This will be resolved once we build our
homemade assembler in #233.
resolves #187
> Complete JIT compilation engine for arm64 target.

- internal/wasi/wasi.go
- internal/wasi/wasi_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- store_test.go
- tests/spectest/spec_test.go
- wasi.go
- wasm/wasm.go
This adds a function to get an exported memory by name, allowing end
users to check ahead of time if memory writes might fail. This also
renames memory.len to size to as that's what the spec calls it.
> Adds ModuleExports.Memory and renames Memory.Len to Memory.Size

- internal/wasi/wasi.go
- internal/wasi/wasi_test.go
This PR backfills the docs and tests of `fd_write`, and backfills the tests of `fd_read`.
> wasi: backfill docs and tests of fd_read and fd_write

- wasm.go
- wasm_test.go
This adds `ModuleConfig.Validate()` as needed by wapc-go to ensure a
module instantiated many times later is checked first. This is a method
of config in case we later add the ability to force a format. For now,
it relies on detection and the call-site only use binary anyway.
> Adds ModuleConfig.Validate() to allow pre-flight checks on source

- wasm.go
- wasm_test.go
PR #281 allowed repetitive use of the same module config to avoid
re-decoding the same wasm. However, it is possible that configuration is
renamed in separate goroutines. This makes caching safer by restoring
the `WithName` function deleted earlier. By using this, a configuration
and its cache state are cloned, and doing that is thread safe.
> Restores ModuleConfig.WithName to support cloned Wasm

- README.md
- examples/add_test.go
- examples/fibonacci_test.go
- examples/host_func_test.go
- examples/wasi_test.go
- internal/wasm/host.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/bench/bench_fac_iter_test.go
- tests/bench/bench_test.go
- tests/codec/codec_test.go
- tests/engine/adhoc_test.go
- tests/spectest/spec_test.go
- wasi.go
- wasm/wasm.go
- wasm/wasm_test.go
- wasm_test.go
This moves code for `ValueType` constants public, so that we can
verify function signatures. To achieve this without complicating
function calls this makes `Function` and `HostFunction` `interface`
instead of `func` types.
Note: We'll also need `ValueType` when re-introducing a Globals API.
To keep complexity down in consideration that there are only 4 types, I
copied the constants into the internalwasm package. This reduces the
import complexity otherwise would have caused.
> Exports wasm.ValueType and makes Functions interfaces for signature verification

- internal/wasi/wasi_test.go
- internal/wasm/host.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/store.go
This pushes parameter length validation to inside the engine to avoid bugs. Formerly, we were inconsistent checking this depending on whether the function was Wasm or not.
This also replicates the tests for interpreter to JIT and renames `interpreter.interpreter` to `interpreter.engine` for consistency
> Pushes param length validation to engine

- internal/wasi/wasi.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/binary/export.go
- internal/wasm/binary/export_test.go
- internal/wasm/binary/import.go
- internal/wasm/binary/import_test.go
- internal/wasm/binary/section_test.go
- internal/wasm/host.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/text/decoder.go
- internal/wasm/text/decoder_test.go
- tests/codec/codec_test.go
- tests/spectest/spec_test.go
This centralizes our management of external types by choosing the word
"external" also used in the spec instead of defining the same constants
for imports vs exports. One advantage is more coherent reference
searching as constants are no longer split. Another is future work can
use a single "kind" type to manage namespace length checks.
> Folds ImportKind and ExportKind into ExternType

- internal/wasm/counts.go
- internal/wasm/counts_test.go
- internal/wasm/module.go
Right now, it is a lot of copy/paste to decode inlined import
abbreviation with the same parser as module-defined ones. The primary
reason for this is that the import section is only guaranteed before
module-defined *after* expanding abbreviations. For example,
`(func (import "foo" "bar") ...` follows imports and may be followed by
any number of abbreviations. This means you can't know the end of
imports until you see the first `(func` which doesn't abbreviate one.
While certain external types, namely memory and table, can only be
imported once, this also applies to globals.
This change makes counting the current imports a `func() uint32` so that
it can be decoupled and used for any external type. Other PRs can
simplify memory and table which can only be imported once, but the
general …
> Adds import count functions to unlock shared text decoding

- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/text/decoder.go
- internal/wasm/text/func_parser.go
- internal/wasm/text/memory_parser.go
- internal/wasm/text/type_parser.go
- internal/wasm/text/typeuse_parser.go
This changes the string value of "mem" to "memory" so that the same
constants currently used for error context can also be used for field
parsing dispatch.
> text: changes string value of externtype "mem" to "memory"

- internal/wasm/engine.go
- internal/wasm/func_validation.go
- internal/wasm/func_validation_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/jit/compiler.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/spectest/spec_test.go
- wasm.go
This PR refactors store.go and adds store.ReleaseModuleInstance.
Notably, this removes the "rollback" functions in InstantiateModule
which we had used to rollback the mutated state when we encounter
the initialization failure. Instead, we separate out the validation from
initialization and migrate most of the validation logics into module.go
As for ReleaseModuleInstance, that is necessary to complete #293,
will be leveraged to make it possible for store to be used for long-running
processes and environment.
> Refactors store and adds ReleaseModuleInstance.

- internal/wasm/text/decoder.go
- internal/wasm/text/func_parser.go
- internal/wasm/text/func_parser_test.go
- internal/wasm/text/index_namespace.go
- internal/wasm/text/index_namespace_test.go
- internal/wasm/text/memory_parser_test.go
- internal/wasm/text/type_parser_test.go
- internal/wasm/text/typeuse_parser.go
- internal/wasm/text/typeuse_parser_test.go
The current section index is typically only read when there is an
unresolved reference. This pushes evaluation until when it is needed,
which simpilifies tracking and reduces arity of callbacks.
> text: defers evaluation of current section index

- README.md
- config_supported.go
This simplifies state management and the amount of terminology end-users
need to learn by using one concept `Runtime` instead of two: `Engine`
and `Store`. This bridges the concepts to the specification by still
having `wazero.Runtime` implement `wasm.Store`.
The net result is that we can know for sure which "engine" is used when
decoding. This allows us a lot of flexibility especially pre-compilation
when JIT is possible.
This also changes the default to JIT based on compiler flags so that
downstream projects like wapc-go don't have to do this individually
(including tracking of which OS+Arch have JIT).
Finally, this uses more go-idiomatic terms like `New` instead of
`Instantiate`.
```go
// before: to force a specific compilation strategy
store, err := …
```
> Combines Store+Engine into Runtime

- internal/wasm/jit/engine.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64_test.go
Previously, we allocate stacks per engine, therefore there were no
allocation overhead for each function call. Since #287, we create
stack per store.Call and resulted in increasing the cost of each
store.Call. This commit reduces the pre-allocation stack size
so that we could reduce the each store.Call.
> jit: reduce the cost of each function call

- .github/workflows/commit.yaml
- config_supported.go
- config_unsupported.go
- go.mod
- internal/wasm/buildoptions/debug_disabled.go
- internal/wasm/buildoptions/debug_enabled.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64.s
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64.s
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_other.go
- internal/wasm/jit/jit_value_location.go
- internal/wasm/jit/jit_value_location_amd64.go
- internal/wasm/jit/jit_value_location_arm64.go
- internal/wasm/jit/jit_value_location_test.go
- internal/wasm/jit/mmap.go
- vs/bench_fac_iter_test.go
- vs/codec_test.go
- vs/go.mod
We temporarily supported go 1.16 to allow migration. By setting the
floor to 1.17, we can improve performance and focus on only two versions
(1.17 and soon 1.18).
See https://go.googlesource.com/proposal/+/refs/changes/78/248178/1/design/40724-register-calling.md
See #37
> Sets floor go version to 1.17

- .github/workflows/commit.yaml
- Makefile
- internal/wasm/jit/engine.go
- vs/bench_fac_iter_test.go
This commit adds `bench.check` make target to ensure that JIT is the 
fastest engine among others.  There was a performance degration 
in #287 which has been resolved in #316, but only found manually.
The target sets a linker flag in vs/bench_test.go which results in running 
`TestFacIter_JIT_Fastest`  instead of `BenchmarkFacIter_Invoke`. 
The `bench` make target doesn't set the flag so 
`BenchmarkFacIter_Invoke` is run and produces rich benchmark output 
into stdout and doesn't run `TestFacIter_JIT_Fastest.
> ci: add bench.check target to ensure JIT is the fastest 

- README.md
We've already removed the jargon `engine` from public API so this makes REAMDE aligned with it.
> Remove engine from README

- internal/wasi/wasi.go
- internal/wasi/wasi_test.go
- wasi/wasi.go
This stubs all of the known WASI functions so that runtimes like Grain can compile even if they don't use them.
See:
https://github.com/meshx-org/meshx-old/blob/197aa5f7f84f4decc9587cf3477ba378ee68778f/crates/meshx_wasm_runner/src/syscalls/wasi.rs
https://github.com/WebAssembly/WASI/blob/snapshot-01/phases/snapshot/docs.md
https://github.com/pgavlin/warp/blob/2bac1014889b11205d410a6c0930b036067c0e61/wasi/module_definition.go
https://github.com/ziglang/zig/blob/master/lib/std/os/wasi.zig
> Stubs WASI functions for GrainLang

- internal/wasi/wasi_test.go
- internal/wasm/global.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- wasi.go
- wasm.go
- wasm/wasm.go
This removes more exports and adds a toehold test for
`ReleaseModuleInstance` so that it can later be completed for both
wasm and host modules.
> Reduces exports and prepares ReleaseModuleInstance for testing

- internal/wasm/host.go
- internal/wasm/store.go
- wasi.go
This unravels host module instantiation a little. Particularly it is more obvious that some preparation can be done prior to mutating the store. There may be future possibilities from here.
> untangles host module instantiation

- .github/workflows/commit.yaml
- Makefile
I'm frequently forgetting that `check` doesn't lint arm64. This fixes that.
The reason is we have a very large amount of code similar between amd64 and arm64 and `make check` linting both reduces the things you have to remember.
> Ensures check lints

- internal/wasi/wasi.go
- internal/wasm/binary/types.go
- internal/wasm/gofunc.go
- internal/wasm/gofunc_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/text/type_parser.go
- internal/wazeroir/compiler.go
- internal/wazeroir/signature.go
This flattens `FunctionInstance.FunctionType` into `Type` and `TypeID`
fields, where the former is known prior to instantiation. This helps
pave a way for integration between Wasm declared and host defined
modules.
This also clarifies that `FunctionInstance.String` was used as a lookup
key, by renaming and caching its impl. While at it, I renamed "null" to
"v" in its output as I had been using v for void noticing others were
doing that also. Moreover, null is easy to misunderstand as a bug.
> Flattens FunctionInstance FunctionType field

- internal/wasm/jit/jit_amd64_test.go
The previous test is not representative and flaky (#328), so this simplifies
the test similar to arm64 one. Now the test is thread-safe (t.Pararell doesn't
crash the test). Therefore I believe this fixes  #328
> Simplify compileBrTable test for amd64

- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_amd64_test.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_arm64_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/engine/concurrency_test.go
This makes sure that concurrent use of Instantiate and
ReleaseModuleInstance is goroutine-safe. 
Note that it is still not safe to expose Release in the public API
as we haven't taken into account the outstanding calls. That
would be addressed in the follow-up commit.
part of #293.
> Enable concurrent instantiation, and release

- internal/wasm/store.go
- internal/wasm/store_test.go
This decouples global, table and memory instances from
store, and now only ModuleInstances are holding references
to these types.
This is a follow-up on [the comment by @codefromthecrypt ](https://github.com/tetratelabs/wazero/pull/342#pullrequestreview-901580527) in #342
> Decouples global, table and memory instance from store.

- README.md
- builder.go
- builder_test.go
- config.go
- examples/add_test.go
- examples/fibonacci_test.go
- examples/file_system_test.go
- examples/host_func_test.go
- examples/simple_test.go
- examples/stdio_test.go
- examples/wasi_test.go
- internal/wasm/host_test.go
- tests/bench/bench_test.go
- tests/engine/adhoc_test.go
- tests/post1_0/post1_0_test.go
- vs/bench_fac_iter_test.go
- vs/codec_test.go
- wasi.go
- wasi_test.go
- wasm.go
- wasm/wasm.go
- wasm_test.go
This reverts `Runtime.NewModule` back to `InstantiateModule` as it calls
more attention to the registration aspect of it, and also makes a chain
of `NewXX` more clear. This is particularly helpful as this change
introduces `ModuleBuilder` which is created by `NewModuleBuilder`.
`ModuleBuilder` is a way to define a WebAssembly 1.0 (20191205) in Go.
The first iteration allows setting the module name and exported
functions. The next PR will add globals.
Ex. Below defines and instantiates a module named "env" with one function:
```go
hello := func() {
fmt.Fprintln(stdout, "hello!")
}
_, err := r.NewModuleBuilder("env").ExportFunction("hello", hello).Instantiate()
```
If the same module may be instantiated multiple times, it is more efficient to separate steps. Ex.
```go
env, err := …
```
> Runtime.NewModule -> InstantiateModule and adds ModuleBuilder

- builder.go
- wasi.go
- wasi_test.go
- wasm.go
- wasm_test.go
The best way to reduce performance impact of instantiating a module
multiple times is lowering it to wazero's IR or even generating
assembly. This renames `DecodeModule` to `CompileModule` to allow that
sort of side-effect to be obvious even if it isn't currently
implemented.
> Renames Runtime.DecodeModule to CompileModule

- config.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/encoder.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/binary/export.go
- internal/wasm/binary/export_test.go
- internal/wasm/binary/global.go
- internal/wasm/binary/global_test.go
- internal/wasm/binary/import.go
- internal/wasm/binary/import_test.go
- internal/wasm/binary/limits.go
- internal/wasm/binary/memory.go
- internal/wasm/binary/names.go
- internal/wasm/binary/section.go
- internal/wasm/binary/types.go
- internal/wasm/features.go
- internal/wasm/func_validation.go
- internal/wasm/func_validation_test.go
- internal/wasm/host_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/text/decoder.go
- wasm/wasm.go
Before, we denied mutable globals when mutable-global=false, when really
that flag is about import/export. This fixes the flag so that it
disables externalizing a mutable global. Non-exported mutable globals
are common as implenented by compilers such as Emscripten.
See https://github.com/emscripten-core/emscripten/blob/main/system%2Flib%2Fcompiler-rt%2Fstack_ops.S
> Adds global binary encoder and fixes scope of mutable-global flag

- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wazeroir/compiler.go
This commit fixes a few bugs in engine.Release, and backfills 
unittests. Notably, moduleEngines must not release the imported
functions. 
> Fix Release for engines

- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_arm64_test.go
> Prevent callFrame and value stack from allocated on gorutine stack

- internal/wasm/engine.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/module_context.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/engine/adhoc_test.go
- tests/engine/concurrency_test.go
- wasm/wasm.go
This commit adds Module.Close API, which can be used to indicate that
the module will no longer be used and setting finalizers for the allocated
resources. Notably, this will set finalizers on compiledFunction to deallocate
mapped memory regions as well as removing them from the store-wide
storage. As a result, users can re-instantiate a module for the same name
while having the safety -- Calling Module.Close is safe even when there are
outstanding function calls as we never explicitly deallocate but indirectly
do that via Goruntine's finalizers.
partially resolves: #293 
> Adds Module.Close API based on runtime.Finalizer

- internal/wasm/memory.go
- internal/wasm/memory_test.go
This PR fixes a bug on bound checking of a memory instance.
Signed-off-by: Takaya Saeki <abc.tkys+pub@gmail.com>
> Fix overflow on MemoryInstance.hasSize

- internal/wasm/engine.go
- internal/wasm/global_test.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/mmap.go
- internal/wasm/jit/mmap_test.go
- internal/wasm/jit/mmap_windows.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/spectest/spec_test.go
- wasm_test.go
Before, if there was an unexpected panic on munmap of a code section,
we'd only see "invalid argument" and have to guess why. This propagates
context and stubs out the finalizer so we can test a better error, like:
"jit: failed to munmap code segment for test.function[0]: invalid argument"
This also attempts to improve troubleshooting time by making all module
instantiation that used empty module name, use the test name instead.
> Propagates module name to module engine panic nicer

- internal/wasm/module_context.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/engine/adhoc_test.go
- wasm/wasm.go
Before, we only handled errors internally and swallowed them when re-exporting to the public API.
> Propagates error return Close to public API

- .github/workflows/commit.yaml
1.18 has been released today! https://go.dev/blog/go1.18
> ci: test on Go 1.18

- internal/leb128/leb128.go
- internal/leb128/leb128_test.go
- internal/wasm/engine.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_amd64.go
- internal/wasm/jit/jit_arm64.go
- internal/wasm/jit/jit_controlflow_test.go
- internal/wasm/jit/jit_initialization_test.go
- internal/wasm/jit/jit_test.go
- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/table.go
- internal/wasm/table_test.go
- tests/spectest/spec_test.go
- wasm.go
This enforces all ElementSegment rules prior to creating a new module
engine. This allows flexibility and less errors inside that function.
This also uses interface as table element to pass tests with -race
> Adds stricter enforcement of Table element validation.

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- Makefile
- go.mod
We should be able to build locally, including running `make check`, if
using Go 1.18, but that's not possible, yet. Meanwhile, I added notes
and updated tooling versions.
> Updates tooling versions and makes notes about Go 1.18

- README.md
- internal/wasm/table.go
As we approach 1.0, we should allow end users to know what they are
getting into. This shows the support policy intent of wazero.
> Adds support policy scaffolding

- README.md
This is as much to reduce confusion for us as it is to reduce confusion for end users, due to the last standard being published over two years ago, yet most compilers targeting >1.0 features by default.
> Adds description of WebAssembly feature status

- internal/wasi/fs.go
- internal/wasi/wasi.go
- internal/wasi/wasi_test.go
Extracts some of #362 so that the PR is less dense with unrelated changes.
Other WASI API changes were made in a way fused with fs changes, which means they are pinned to the other PR.
> wasi: clarifies errno results of FdPrestatGet and PathOpen

- README.md
This formalizes that completing all WASI APIs is an anti-goal as the
abstraction includes abandoned features.
Fixes #271
> Moves WASI status to the top-level README and reformats motivation

- .github/workflows/commit.yaml
- README.md
> CI: change non-amd64 job into scratch platform tests

- .github/workflows/commit.yaml
For example, we've seen `WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested` for arm64 emulation
> ci: suppress WARNING on emulation

- README.md
> Hide WASI system call lists by default in README

- internal/wasi/wasi.go
- internal/wasi/wasi_test.go
- wasi.go
This moves test-only overrides out of config in preparation of
normalized configuration. This also simplifies error tests by using the
API directly for all cases except exit.
> wasi: moves test-only overrides out of config, simplifies error tests

- vs/bench_fac_iter_test.go
- vs/go.mod
- vs/go.sum
[go-wasm3](https://github.com/matiasinsaurralde/go-wasm3) is the first implementation to beat wazero at a benchmark. Its
initialization time is less than half our time in our bench case. While
wazero JIT is still faster at runtime in our tests, it is great to have
such a strong competitor in OSS!
Thanks very much to @birros for making the go-wasm3 project. Hopefully,
it can be updated to latest wasm3 so that things are completely fair!
```
goos: darwin
goarch: amd64
pkg: github.com/tetratelabs/wazero/vs
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkFacIter_Init
BenchmarkFacIter_Init/Interpreter
BenchmarkFacIter_Init/Interpreter-16         	   82864	     14101 ns/op
BenchmarkFacIter_Init/JIT
BenchmarkFacIter_Init/JIT-16                 	    5263	    236023 ns/op …
```
> Adds VS go-wasm3

- internal/wasi/wasi_test.go
- internal/wasm/module_context.go
- internal/wasm/module_context_test.go
- internal/wasm/module_test.go
- internal/wasm/store_test.go
- internal/wasm/sys.go
- internal/wasm/sys_test.go
This backfills tests that ModuleContext.Close ends up calling
`Store.CloseModule` and `SysContext.Close`.
> Adds tests to cover ModuleContext.Close

- RATIONALE.md
- internal/wasi/wasi.go
- wasi.go
- wasi_test.go
Currently, we have custom code in wapc-go because our library forces a
failure when a module that uses WASI doesn't define a "_start" function.
Using the same pragmatism that resulted in us not enforcing the WASI
table, this makes the "_start" function optional. This doesn't add a
flag as the spec is not a proper version anyway (snapshot-01), so
there's no need to further complicate configuration.
If a "_start" function exists, we enforce it is of the proper signature
and succeeds. Otherwise, we allow it to be absent.
> wasi: stops enforcing _start function export

- RATIONALE.md
- tests/engine/concurrency_test.go
This refactors the concurrent close tests to use barriers, as opposed to time or offsets to implement phases. In doing so, it is easier to reason with and debuggable without changing the sleep value.
> Refactors concurrent close tests

- internal/testing/enginetest/enginetest.go
- internal/wasi/wasi_test.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/arch_arm64.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/module.go
- internal/wasm/store.go
This deduplicates Engine tests so that there's less chance of copy/paste
errors and less requirement to use ad-hoc tests which are outside the
relevant source tree.
> Deduplicates internalwasm.Engine tests

- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/store_test.go
This changes the way the JIT engine is tested by focusing on two areas:
* Did NewModuleEngine set a finalizer for each compiled function
correctly?
* Did ModuleEngine.Close remove its compiled function correctly?
A later change will do parallel tests for both engines and won't have to
at the same time check how finalizers work.
> Refactors JIT tests to not be concurrent.

- RATIONALE.md
- internal/testing/hammer/hammer.go
- internal/wasm/store_test.go
- tests/engine/hammer_test.go
This extracts `hammer.Hammer` as a utility for re-use, notably adding a
feature that ensures all tests run concurrently. Before, tests start in
a loop that could be delayed due to goroutine sheduling.
> Extracts hammer.Hammer and adds atomic release of goroutines

- internal/wasm/module_context.go
- internal/wasm/module_context_test.go
- internal/wasm/store_test.go
- tests/engine/adhoc_test.go
- tests/engine/hammer_test.go
- wasm/wasm.go
This exposes `wasm.Module.Name()` so that it is more coherent to
redefine a module with the same name, or know the name to import.
This uses that to port existing tests to use the new hammer
infrastructure (without module name collision).
> Adds Module.Name and ports all hammer tests to the same impl

- config.go
- config_test.go
- internal/wasi/wasi_test.go
- internal/wasm/binary/decoder.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/binary/import.go
- internal/wasm/binary/memory.go
- internal/wasm/binary/memory_test.go
- internal/wasm/binary/section.go
- internal/wasm/binary/section_test.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/text/decoder.go
- internal/wasm/text/decoder_test.go
- internal/wasm/text/memory_parser.go
- internal/wasm/text/memory_parser_test.go
- tests/bench/memory_bench_test.go
- tests/spectest/spec_test.go
- vs/codec_test.go
- wasm.go
- wasm_test.go
This allows users to reduce the memory limit per module below 4 Gi. This
is often needed because Wasm routinely leaves off the max, which implies
spec max (4 Gi). This uses Ki Gi etc in error messages because the spec
chooses to, though we can change to make it less awkward.
This also fixes an issue where we instantiated an engine inside config.
Fixes #417
> Makes memory limit configurable and a compile error

- .github/workflows/commit.yaml
- internal/testing/enginetest/enginetest.go
OK this fails on imported calls on both interpreter and JIT (in the enginetest which is missing something). Also JIT fails on another test due to subtracting from a zero PC
> Attempts to not mutate FunctionInstance on export

- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/module_context.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- tests/engine/adhoc_test.go
- wasi/wasi.go
- wasi/wasi_test.go
This moves the responsibility to close a module from the engine to the
context. The reason for this is that the engine is what defines the
function. When a module is closed, it is often from an imported host
function. If it is on the module engine, it is easy to accidentally
close an imported module.
This refactors the WASI tests also, to ensure they aren't cheating too
much. This allows us to know for example "proc_exit" works without too
much trouble.
> Moves close responsibility to the module context

- internal/testing/enginetest/enginetest.go
- internal/wasm/host.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/jit/engine.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasmdebug/debug.go
- internal/wasmdebug/debug_test.go
- tests/engine/adhoc_test.go
This changes panics to be more consistent between engines and adds
signature information as it is commonly a problem.
Ex.
```
integer divide by zero (recovered by wazero)
wasm stack trace:
wasi_snapshot_preview1.fd_write(i32,i32,i32,i32) i32
x.y()
```
Note: This took out the rust-like index numbers on the stack trace and
also calls it stack trace not backtrace as that's more usual in Go.
> Extracts stack trace formatting logic and adds more context

- builder.go
- builder_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/jit/engine_test.go
- internal/wasm/module.go
- internal/wasm/store_test.go
- wasm_test.go
This adds functions to configure memory with ModuleBuilder. This uses
two functions, ExportMemory and ExportMemoryWithMax, as working with
uint32 pointers is awkward.
See https://github.com/summerwind/the-art-of-webassembly-go/issues/1
> Adds ModuleBuilder.ExportMemory and ExportMemoryWithMax

- builder.go
- builder_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/jit/engine_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- wasm_test.go
I think this is the last to port @summerwind's lovely codebase
See https://github.com/summerwind/the-art-of-webassembly-go/issues/1
> Adds ModuleBuilder.ExportGlobalXXX to configure constants

- RATIONALE.md
- builder.go
- builder_test.go
- config.go
- internal/ieee754/ieee754.go
- internal/leb128/leb128.go
- internal/leb128/leb128_test.go
- internal/wasm/binary/const_expr.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/binary/global_test.go
- internal/wasm/counts_test.go
- internal/wasm/global_test.go
- internal/wasm/host_test.go
- internal/wasm/memory.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/table.go
- internal/wasm/table_test.go
- tests/spectest/spec_test.go
- wasm_test.go
Global constants can be defined in wasm or in ModuleBuilder. In either
case, they end up being decoded and interpreted during instantiation.
This chooses signed encoding to avoid surprises. A more comprehensive
explanation was added to RATIONALE.md, but the motivation was a global
100 coming out negative.
> Consistently uses LEB128 signed encoding for global constants

- examples/host_func_test.go
The vm has been handled before, here should be the module.
> Fix example typo

- config.go
- config_test.go
- examples/file_system_test.go
- examples/host_func_test.go
- examples/replace_test.go
- examples/stdio_test.go
- wasm.go
- wasm_test.go
Before, complicated wasm could be hard to implement, particularly as it
might have cyclic imports. This change allows users to re-map imports to
untangle any cycles or to break up monolithic modules like "env".
Ex.
```go
// Instantiate a function that closes the module under "assemblyscript.abort".
host, err := r.NewModuleBuilder("assemblyscript").
ExportFunction("abort", func(m api.Module, messageOffset, fileNameOffset, line, col uint32) {
_ = m.CloseWithExitCode(255)
}).Instantiate()
require.NoError(t, err)
defer host.Close()
// Compile code that needs the function "env.abort".
code, err := r.CompileModule([]byte(`(module
(import "env" "abort" (func $~lib/builtins/abort (param i32 i32 i32 i32)))
(export "abort" (func 0)) ;; exports the import for testing
)`))
require.NoError(t, err)
// …
```
> Adds ModuleConfig.WithImport and WithImportModule

- Makefile
otherwise CI never ends as in #446
> Set timeout for 'make test'

- go.mod
- internal/asm/amd64/assembler.go
- internal/asm/amd64/consts.go
- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_test.go
- internal/asm/amd64_debug/debug_assembler.go
- internal/asm/amd64_debug/golang_asm.go
- internal/asm/arm64/assembler.go
- internal/asm/arm64/consts.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_test.go
- internal/asm/arm64_debug/debug_assembler.go
- internal/asm/arm64_debug/golang_asm.go
- internal/asm/arm64_debug/impl_test.go
- internal/asm/assembler.go
- internal/asm/golang_asm/golang_asm.go
- internal/asm/impl.go
- internal/u64/u64.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_controlflow_test.go
- internal/wasm/jit/jit_impl_amd64_test.go
- internal/wasm/jit/jit_impl_arm64.go
- internal/wasm/jit/jit_impl_arm64_test.go
- internal/wasm/jit/jit_initialization_test.go
- internal/wasm/jit/jit_numeric_test.go
- internal/wasm/jit/jit_test.go
This commit implements all the arm64 instruction encodings necessary 
for our JIT compiler and replaces the golang-asm assembler with our
handmade assembler on arm64 platform. Notably, this allows us to do 
concurrent compilations. 
This closes #233 combined with #406.
> asm: complete arm64 instruction encodings for homemade assembler

- Makefile
this has been missing since we introduced bench.check :D
> ci: run benches under tests/ dir in bench.check

- internal/asm/amd64/impl.go
- internal/wasm/jit/arch.go
- internal/wasm/jit/arch_amd64.s
- internal/wasm/jit/arch_arm64.s
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_controlflow_test.go
- internal/wasm/jit/jit_impl_amd64.go
- internal/wasm/jit/jit_impl_arm64.go
- internal/wasm/jit/jit_initialization_test.go
- internal/wasm/jit/jit_memory_test.go
- internal/wasm/jit/jit_test.go
This commit decouples the *wasm.ModuleInstance from the compiled code.
This is necessary to reuse same machine code for multiple module instances
originating from the same binary (or text), which is a necessary mechanism for
compilation caches I will do in the next PRs.
> jit: decouple compiled code from moduleInstance's pointer

- tests/bench/bench_test.go
Hasn't been iterated via `b.N` 😄 
> Fix broken base64 bench

- builder.go
- config.go
- examples/replace-import/replace-import.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wazeroir/compiler_test.go
- tests/bench/bench_test.go
- tests/engine/adhoc_test.go
- wasi/usage_test.go
- wasi/wasi_test.go
- wasm.go
- wasm_test.go
Thanks to #454, now the compiled binary (code segment) can be reused for
multiple module instances originating from the same source (wasm.Module).
This commit introduces the caching mechanism on engine where it caches
compiled functions keyed on `wasm.Module`. As a result, this allows us to
do the fast module instantiation from the same *CompiledCode.
In order to release the cache properly, this also adds `Close` method 
on CompiledCode.
Here's some bench result for instantiating multiple modules from the same CompiledCode:
```
name                           old time/op    new time/op    delta
Initialization/interpreter-32    2.84ms ± 3%    0.06ms ± 1%  -97.73%  (p=0.008 n=5+5)
Initialization/jit-32            10.7ms ±18%     0.1ms ± 1%  -99.52%  (p=0.008 n=5+5)
name …
```
> Add compilation cache functionality and Close on CompiledCode.

- builder_test.go
- go.mod
- go.sum
- internal/asm/amd64_debug/impl_test.go
- internal/asm/arm64_debug/impl_test.go
- internal/leb128/leb128_test.go
- internal/testing/require/require.go
- internal/testing/require/require_test.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine_test.go
- internal/wasm/jit/jit_controlflow_test.go
- internal/wasm/jit/jit_global_test.go
- internal/wasm/jit/jit_impl_amd64_test.go
- internal/wasm/jit/jit_initialization_test.go
- internal/wasm/jit/jit_memory_test.go
- internal/wasm/jit/jit_numeric_test.go
- internal/wasm/jit/jit_stack_test.go
- internal/wasm/jit/jit_value_location_test.go
- internal/wasm/module_context_test.go
- internal/wasm/store_test.go
- internal/wasm/sys_test.go
- internal/wasm/text/memory_parser_test.go
- internal/wasm/text/type_parser_test.go
- internal/wasm/text/typeuse_parser_test.go
- internal/wazeroir/compiler_test.go
- tests/post1_0/multi-value/multi_value_test.go
- tests/spectest/spec_test.go
- wasm_test.go
This implements our own assertion library so that we can remove the
testify dependency. I've changed a lot of call sites so that we only
have to maintain a minimal amount of assertions.
One tradeoff here besides the code added.. While this does not bring
in a diff dependency, it also doesn't do diffs. In practice, I think this is
ok, but we could consider adding diffs if our IDEs aren't smart enough
later.
> Removes testify dependency

- example_test.go
- examples/basic/add_test.go
- examples/import-go/age-calculator_test.go
- examples/multiple-results/multiple-results_test.go
- examples/replace-import/replace-import_test.go
- examples/wasi/cat_test.go
- internal/testing/maintester/maintester.go
- sys/sys.go
- wasi/example_test.go
- wasm.go
- wasm_test.go
Before, we tested the examples/ directory using "ExampleXX", but this is
not ideal because it literally embeds the call to `main` into example
godoc output. This stops doing that for a different infrastructure.
This also makes sure there's a godoc example for both the main package
and wasi, so that people looking at https://pkg.go.dev see something and
also a link to our real examples directory.
> Changes how examples are tested, and fixes ExitError bug

- wasi/wasi.go
- wasi/wasi_bench_test.go
- wasi/wasi_test.go
This flattens the unexported interface as there's no plans to export it.
That these are separate knowing that is not helpful.
> wasi: flattens interface into struct functions

- internal/testing/require/require.go
source
```
func Test_a(t *testing.T) {
a(t)
}
func a(t *testing.T) {
b(t)
}
func b(t *testing.T) {
require.Equal(t, 0, 1)
}
```
Before:
```
=== RUN   Test_a
/home/mathetake/wazero/internal/wasm/jit/require.go:294: expected 0, but was 1
engine_test.go:26
engine_test.go:22
engine_test.go:18
```
After:
```
--- FAIL: Test_a (0.00s)
require.go:294: expected 0, but was 1
/home/mathetake/wazero/internal/wasm/jit/engine_test.go:26
/home/mathetake/wazero/internal/wasm/jit/engine_test.go:22
/home/mathetake/wazero/internal/wasm/jit/engine_test.go:18
```
This allows me to do easy navigation like before with testify
> require: make stack file names absolute

- README.md
There is a common confusion that WebAssembly is W3C, so WASI must also
be. However, this isn't the case and The Bytecode Alliance doesn't
describe itself in that way either. This change should help set context
so that people know what is likely to be a "real standard" vs a valuable
part of the greater WebAssembly ecosystem.
See https://github.com/bytecodealliance/governance
> Updates the README to help clarify that WASI is not W3C

- builder.go
- builder_test.go
- config.go
- internal/integration_test/spectest/spec_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/host.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine.go
- internal/wasm/jit/engine_test.go
- internal/wasm/module.go
- wasm.go
- wasm_test.go
This commit allows CompiledCode to be re-used regardless of 
the existence of import replacement configs for instantiation. 
In order to achieve this, we introduce `ModuleID`, which is sha256
checksum calculated on source bytes, as a key for module compilation 
cache. Previously, we used`*wasm.Module` as keys for caches which 
differ before/after import replacement.
> Use same CompiledCode for import replacement

- internal/wasm/module.go
- internal/wasm/module_test.go
Previously, when searching the signature of imported function start section,
we haven't skipped non-function imports for indexes.
> Fix validate start section with imports

- internal/modgen/modgen.go
- internal/modgen/modgen_test.go
- internal/wasm/module.go
This commit adds the random module generator for compiler testing.
Notably, it only generates valid and (supposedly) compilable Wasm modules.
Generating such random sources/programs and using them for testing or 
fuzzing compilers is the widely known way of securing and hardening them [1,2].
This commit only creates random modules where functions do not have
any meaningful body. That will be resolved in a subsequent commit
as the implementation for generating random function body could be
huge.
Note that the implementation has already found a bug #485, and can be
easily integrated with the [fuzzing feature of Go 1.18](https://tip.golang.org/doc/fuzz/):
```go
func FuzzCompiler(f *testing.F) {
r := wazero.NewRuntimeWithConfig(wazero.NewRuntimeConfig().
WithFeatureMultiValue(true)) …
```
> Adds random module generator for fuzzing the compiler

- api/wasm.go
- internal/integration_test/engine/adhoc_test.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/text/func_parser.go
- internal/wasm/text/func_parser_test.go
- internal/wazeroir/compiler_test.go
This adds Memory.IndexByte which allows efficent scanning for a
delimiter, ex NUL(0) in null-terminated strings.
This also adds an ad-hoc test to ensure we can export memory functions
such as grow. While this is implicitly in the spectests, it is easier to
find in the ad-hoc tests.
> Adds Memory.IndexByte and memory grow example

- Makefile
`$<` as we currently have only returns one of the matched files, meaning that currently `build.examples` doesn't build all the matched examples. `$^` returns all of them, so I added a for loop through that so they're all built.
> Fix build.examples so it builds all examples

- .github/workflows/commit.yaml
- Makefile
- config.go
- internal/integration_test/vs/bench_fac_test.go
- internal/integration_test/vs/bench_test.go
- internal/integration_test/vs/go.mod
- internal/integration_test/vs/go.sum
- internal/integration_test/vs/runtime.go
- internal/integration_test/vs/wasm3_test.go
- internal/integration_test/vs/wasmedge_test.go
- internal/integration_test/vs/wasmer_test.go
- internal/integration_test/vs/wasmtime_test.go
- internal/wasm/engine.go
This adds WasmEdge-go to the list of benchmarks and also extracts out compile from instantiate as users like wapc-go instantiate the same module multiple times.
Right now, only wazero is the only option that can do this without crashing, but we can update the code for the alternatives if the bugs are ever fixed.
```
BenchmarkFac_Compile/wasmtime-go-16         	  120554	      8508 ns/op	       8 B/op	       1 allocs/op
BenchmarkFac_Compile/wazero-interpreter-16  	   79351	     14140 ns/op	    9661 B/op	     320 allocs/op
BenchmarkFac_Compile/wazero-jit-16          	   10000	    100324 ns/op	   59818 B/op	    1203 allocs/op
BenchmarkFac_Compile/wasm3-go-16            	  447822	      2637 ns/op	      48 B/op	       3 allocs/op
BenchmarkFac_Compile/WasmEdge-go-16         	 5915394 …
```
> Adds vs benchmark WasmEdge and splits compile from instantiate

- Makefile
- internal/integration_test/vs/bench_test.go
whoops.
works again
```bash
$ make bench.check
wazero-jit         1022.99 ns/call
wasmer-go          1392.13 ns/call
wasm3-go           2074.38 ns/call
wasmtime-go        2501.56 ns/call
wazero-interpreter 6936.58 ns/call
WasmEdge-go        9801.48 ns/call
--snip--
```
> Fixes where vs benchmark stopped running after drift

- internal/wasm/binary/decoder.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/section.go
- internal/wasm/binary/section_test.go
- internal/wasm/features.go
- internal/wasm/features_test.go
- internal/wasm/func_validation.go
- internal/wasm/func_validation_test.go
- internal/wasm/instruction.go
- internal/wasm/module.go
- internal/wasm/module_test.go
> Bulk memory binary encoding and validation

- internal/integration_test/vs/wasmtime/go.mod
- internal/integration_test/vs/wasmtime/go.sum
I looked and there are no API changes that affect our benchmarks. The performance isn't notably different either.
> bench: bumps wasmtime-go

- builder.go
- builder_test.go
- config.go
- config_test.go
- internal/integration_test/spectest/encoder_test.go
- internal/integration_test/spectest/spectest.go
- internal/integration_test/vs/codec.go
- internal/integration_test/vs/codec_test.go
- internal/modgen/modgen.go
- internal/modgen/modgen_test.go
- internal/wasm/binary/decoder.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/import.go
- internal/wasm/binary/import_test.go
- internal/wasm/binary/memory.go
- internal/wasm/binary/memory_test.go
- internal/wasm/binary/section.go
- internal/wasm/binary/section_test.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store_test.go
- internal/wasm/text/decoder.go
- internal/wasm/text/decoder_test.go
- internal/wasm/text/memory_parser.go
- internal/wasm/text/memory_parser_test.go
- internal/wazeroir/compiler_test.go
- wasm.go
- wasm_test.go
`Runtime.WithMemoryCapacityPages` is a function that determines memory
capacity in pages (65536 bytes per page). The inputs are the min and
possibly nil max defined by the module, and the default is to return
the min.
Ex. To set capacity to max when exists:
```golang
c.WithMemoryCapacityPages(func(minPages uint32, maxPages *uint32) uint32 {
if maxPages != nil {
return *maxPages
}
return minPages
})
```
Note: This applies at compile time, ModuleBuilder.Build or Runtime.CompileModule.
Fixes #500
> Adds Runtime.WithCapacityPages to avoid allocations during runtime.

- README.md
- builder_test.go
- config.go
- config_supported.go
- config_test.go
- config_unsupported.go
- examples/multiple-results/multiple-results.go
- internal/integration_test/bench/bench_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/post1_0/bulk-memory-operations/spec_test.go
- internal/integration_test/post1_0/multi-value/spec_test.go
- internal/integration_test/post1_0/nontrapping-float-to-int-conversion/spec_test.go
- internal/integration_test/post1_0/sign-extension-ops/spec_test.go
- internal/integration_test/vs/codec.go
- internal/integration_test/vs/codec_test.go
- internal/integration_test/vs/runtime.go
- internal/modgen/modgen_test.go
- internal/wasm/binary/function_test.go
- internal/wasm/features.go
- internal/wasm/features_test.go
- internal/wasm/gofunc_test.go
- internal/wasm/text/decoder_test.go
- internal/wasm/text/func_parser_test.go
- internal/wasm/text/type_parser_test.go
- internal/wasm/text/typeuse_parser_test.go
- internal/wazeroir/compiler_test.go
- wasm.go
- wasm_test.go
WebAssembly Core Working Draft 1 recently came out. Before that, we had
a toe-hold feature bucked called FinishedFeatures. This replaces
`RuntimeConfig.WithFinishedFeatures` with `RuntimeConfig.WithWasmCore2`.
This also adds `WithWasmCore1` for those who want to lock into 1.0
features as opposed to relying on defaults.
This also fixes some design debt where we hadn't finished migrating
public types that require constructor functions (NewXxx) to interfaces.
By using interfaces, we prevent people from accidentally initializing
key configuration directly (via &Xxx), causing nil field refs. This also
helps prevent confusion about how to use the type (ex pointer or not) as
there's only one way (as an interface).
See https://www.w3.org/blog/news/archives/9509
See …
> Changes RuntimeConfig to an interface and exposes WithWasmCore2

- builder.go
- builder_test.go
- config.go
- config_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/vs/runtime.go
- wasm.go
- wasm_test.go
This makes wazero.CompiledCode an interface instead of a struct to
prevent it from being used incorrectly. For example, even though the
fields are not exported, someone can mistakenly instantiate this
when it is a struct, and in doing so violate internal assumptions.
Follow-up from #518 and the next and final PR will be ModuleConfig.
> Makes wazero.CompiledCode an interface instead of a struct

- config.go
- config_test.go
- wasm.go
- wasm_test.go
This makes wazero.ModuleConfig an interface instead of a struct to
prevent it from being used incorrectly. For example, even though the
fields are not exported, someone can mistakenly instantiate this
when it is a struct, and in doing so violate internal assumptions.
This also fixes a mutability bug in the implementation.
Follow-up from #519 and the last in this series
> Makes ModuleConfig an interface and fixes mutability bug

- RATIONALE.md
It has happened a couple times where folks have suggested options pattern, probably guessing we didn't have it in the past or explicitly remove it. All the API decisions were quite thought through, and particularly options, but that wasn't obvious if you read the rationale. This adds the rationale into the repo to help conserve time. Instead of spending time re-explaining why options isn't used here, we can spend the same time on more pressing and important design or maintenance issues.
Closes #480
> Documents why we don't use Option pattern

- internal/wasm/memory.go
Before that change it was possible to overwrite content out of specified range.
See #527
> Fix bytes capacity on Read

- internal/wasm/binary/data.go
- internal/wasm/binary/element.go
Reflect the changes for https://github.com/WebAssembly/spec/commit/1ffb924e94856e89f787fc2000fa4c5dc069a24f
> Use leb128 u32 for data/element segment prefixes

- api/wasm.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/interpreter/interpreter_test.go
- internal/wasm/jit/engine_test.go
- internal/wasm/memory.go
- internal/wasm/module.go
By testing the side-effects of Memory.Read, we ensure users who control
the underlying memory capacity can use the returned slice for
write-through access to Wasm addressible memory. Notably, this allows a
shared fixed length data structure to exist with a pointer on the Go
side and a memory offset on the Wasm side.
Thanks to @inkeliz for this idea and help on the code.
Fixes #525
> Documents Memory.Read as a way to share memory between Go and Wasm

- api/wasm.go
- internal/wasm/interpreter/interpreter.go
- internal/wasm/jit/engine.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
This exports an API which allows host-defined functions access to
increase the memory size.
Fixes #483
> Exposes api.Memory Grow

- .gitattributes
Also removes unused linguist setting for stats
When developing on Windows, git will often give warnings like
`warning: CRLF will be replaced by LF in internal/wasm/text/decoder.go.`
and `make format` touches all files causing a huge "no-op diff" where git is seeing different line endings, but they don't actually show up in a PR.
I've generally not been able to have good results on developing on Windows without this `.gitattributes` line to force LF-always, which is appropriate for any modern codebase (even Windows ones :-) )
> Sets lf line endings in gitattributes.

- internal/wasm/call_context.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- wasm.go
- wasm_test.go
Fixes #382
It can be tedious to close many modules that have been instantiated, particularly when they are not instantiated in a scope where it is appropriate to use `defer`. `Runtime.Close` closes all the modules in a runtime's store, in reverse order of instantiation. I am wondering whether we should provide a version of this that takes an exit code like the `Module` version or if that would be overkill. It wouldn't be hard to add that if we need it here.
To keep track of order, `moduleNames` changes from a map to a slice - with a huge number of modules this could reduce instantiation performance. If this seems like it needs to be avoided, I can use a separate field instead, which would be something like inlining a linked map of modules into the store.
Also because Go locks aren't …
> Adds Runtime.Close

- README.md
- api/wasm.go
- builder.go
- config.go
- example_test.go
- examples/allocation/rust/greet.go
- examples/allocation/tinygo/greet.go
- examples/basic/add.go
- examples/import-go/age-calculator.go
- examples/multiple-results/multiple-results.go
- examples/replace-import/replace-import.go
- examples/wasi/cat.go
- experimental/listener_test.go
- experimental/sys_test.go
- wasi/example_test.go
- wasi/wasi.go
- wasm.go
This removes tedium in our examples and docs by using `Runtime.Close`
instead of tracking everything. Internal tests still track too much, but
anyway at least this stops suggesting others should do it.
This also changes our examples to use log.PanicXX so that the line
number goes into the console output.
> Makes all examples and docs use Runtime.Close

- .github/workflows/commit.yaml
- Makefile
- internal/asm/arm64/impl.go
> ci: upgrade golangci-lint, enable matrix on check job

- sys/sys.go
- sys/sys_test.go
- wasm_test.go
Allows use with test assertions like `require.ErrorIs`, which delegates to `errors.Is` both here and in testify.
Cleans up a related TODO.
> Implements errors.Is for sys.ExitError

- internal/integration_test/fs/fs_test.go
- internal/integration_test/fs/testdata/animals.txt
Fixes #408
This implements `fs.Fs` and `io.Reader` / `io.Seeker` by calling into exported wasm functions that delegate to wasi. This let's use add integration tests that target `fs.Fs` as a generic mechanism for accessing files - in this PR we execute `iotest.TestReader` which runs some tests verifying the operation of a `Reader`. Because we haven't implemented `fd_stat` in wasi yet, this does not implement `File.Stat()` yet.
https://cs.opensource.google/go/go/+/master:src/testing/iotest/reader.go;l=136
> Adds test delegating to iotest against a wasi fs.Fs implementation

- internal/asm/amd64/assembler.go
- internal/asm/amd64/consts.go
- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_test.go
- internal/asm/arm64/assembler.go
- internal/asm/arm64/consts.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_test.go
I was looking into possibly bringing in func-e's linting config. There are currently tons of failures so may proceed with that very gradually. One easy one that particularly spams the console is not liking package names with underscores. Here we are already aliasing in all the imports anyways so it seems OK to let the packages match the folder name.
> Renames asm packages to match folder name

- Makefile
- netlify.toml
- site/config.toml
- site/layouts/partials/extended_head.html
links in the header pointed to the wrong images. the footer was missing the GA tag.
> site: fixes header and footer

- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
- internal/integration_test/asm/amd64_debug/impl_test.go
- internal/wazeroir/compiler.go
If the call_indirect's offset register is the same as the calling-convention
reserved register, the function call target address resulted in the wrong 
address and therefore segfault.
Fixes partially #526 
> compiler: fixes calling convention violation.

- wasi/wasi.go
- wasi/wasi_test.go
As pointed in https://github.com/tetratelabs/wazero/issues/526#issuecomment-1134034760, 
swift wasm binaries require clock_resg_get to return SUCCESS to run without unreachable.
For now, we temporarily fix the value `1000` to nanosec, and later we will do the overhaul on this
together with `ClockTimeGet` as these two implementations must be well aligned.
> wasi: returns fixed resolutin via ClockResGet

- internal/asm/amd64/consts.go
- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/integration_test/asm/amd64_debug/golang_asm.go
- internal/integration_test/asm/amd64_debug/impl_test.go
This resolves `revive` linter errors in the amd64 package related to
- No ALL_CAPS constants (REG_AX -> RegAX)
- Doc on all exported members
All the code changes are automatic with GoLand's renaming functionality. The docs on the instruction names essentially map from go asm to amd64 asm (by reading https://www.felixcloutier.com/x86/index.html) which I think best explains how each instruction works.
@mathetake If this PR / pattern makes sense, I will send one for arm64 too.
> Follows go style for amd64 constants.

- internal/moremath/moremath.go
- internal/moremath/moremath_test.go
I was randomly looking at this file where GoLand was flagging the `f != -0 && f != 0`. 
In Go, the `-0` literal is actually positive zero
https://github.com/golang/go/issues/2196
So GoLand suggested simplifying since the code repeats the same check twice effectively.
I added tests to verify the desired behavior of preserving sign bit for negative zero is happening. If the intention of `f != -0` was a performance optimization for that case, we don't have it, but negative zero should be rare enough to not worry about it I guess.
> Adds tests for sign bit preservation for moremath rounding functions.

- .github/workflows/commit.yaml
- .gitignore
- Makefile
- codecov.yml
This adds coverage the same way as works in func-e, just that there are
slightly different conventions here wrt packages to ignore. Notably, we
should not run coverage using integration tests or examples as they give
false positives.
Once this merges, it is ready for codecov!
```bash
$ make coverage
make coverage
ok  	github.com/tetratelabs/wazero	1.211s	coverage: 20.7% of statements in ./, ./api/, ./assemblyscript/, ./experimental/, ./internal/asm/, ./internal/asm/amd64/, ./internal/asm/arm64/, ./internal/buildoptions/, ./internal/engine/compiler/, ./internal/engine/interpreter/, ./internal/ieee754/, ./internal/leb128/, ./internal/modgen/, ./internal/moremath/, ./internal/sys/, ./internal/u64/, ./internal/wasm/, ./internal/wasm/binary/, ./internal/wasm/text/, ./internal/wasmdebug/, …
```
> Adds coverage logic customized from func-e

- api/wasm.go
- assemblyscript/assemblyscript.go
- builder.go
- config.go
- experimental/listener.go
- sys/sys.go
- wasi/errno.go
- wasi/wasi.go
- wasm.go
I researched what is available for improving godoc. Notably, this does
the following on every non-internal go file (tests excluded).
* consolidates links where there's a better single one
* wraps See where there are multiple relevant links
* reduces use of Note: where possible
* Uses preformatting for bullets similar to gob
* Uses titles where appropriate
I looked into it and while there are many ways to re-render godoc into
markdown, there are limited options on what to do in godoc itself. There
are tricks implicitly used where preformatting (tab indent) is used to
avoid having to add extra lines everywhere. This is done in gob, for
example.
See https://go.dev/src/encoding/gob/doc.go
See https://github.com/fluhus/godoc-tricks/blob/master/doc.go
See #426
> Improves godoc formatting

- RATIONALE.md
- wasi/wasi.go
- wasi/wasi_test.go
We only support clock IDs REALTIME and MONOTONIC, while some runtimes support all IDs, not all. The next version of WASI removes the other IDs anyways
https://github.com/WebAssembly/WASI/pull/197
https://github.com/bytecodealliance/wasmtime/blob/8b48ce7fb79c7e36748e2e1a90be3bdf7d65cbce/crates/wasi-common/src/snapshots/preview_1.rs#L249
Monotonic is not mockable, unlike realtime. I had first toyed with the idea of having the mock return `time.Time` instead of the unixnow value itself to support both but realized that there is no way to create a static monotonic `time.Time` in Go anyways. So allowing that would probably require instead to use the current function but provide it the `clockID` parameter. This didn't feel very useful so I …
> Implements clock ID support for getting time/res in wasi

- .github/workflows/commit.yaml
- .github/workflows/spectest.yaml
- config_supported.go
- config_unsupported.go
- internal/engine/compiler/arch.go
- internal/engine/compiler/arch_amd64.go
- internal/engine/compiler/arch_arm64.go
- internal/engine/compiler/engine_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/engine/hammer_test.go
- internal/platform/mmap.go
- internal/platform/mmap_test.go
- internal/platform/mmap_unsupported.go
- internal/platform/mmap_windows.go
- internal/platform/platform.go
This narrows to what the `internal/platform` package supports, which is
currently bound by Go SDK source that include `Mprotect` or windows.
Ex. `zsyscall_linux_amd64.go` includes `Mprotect`, but
`zsyscall_freebsd_amd64.go` does not.
This should prevent errors like below, by allowing `wazero.NewRuntime()`
to properly fallback to the interpreter.
```
.../mmap.go:74:16: undefined: syscall.Mprotect
```
A later change will implement FreeBSD. This is just here to ensure users
don't crash on unexpected OS.
See #607
> Narrows compiler support to operating systems currently known to work

- codecov.yml
We only use codecov as a UI. It is alarming to see red on commit, so
disabling this.
> Disables codecov commit status

- api/wasm.go
- assemblyscript/assemblyscript.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- wasi_snapshot_preview1/wasi.go
- wasi_snapshot_preview1/wasi_bench_test.go
- wasi_snapshot_preview1/wasi_test.go
Memory.IndexByte is unneeded with better understanding of write-through
on Memory.Read. Removing this also helps usher folks into the myriad of
Go utilities that are compatable with []byte.
This also reduces the complexity of WASI which didn't need to re-buffer
random reads (also due to above).
> Replaces Memory.IndexByte with stronger documentation on Read

- RATIONALE.md
- config.go
- config_test.go
- internal/platform/time.go
- internal/platform/time_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- wasi_snapshot_preview1/wasi_test.go
This ensures fake clocks increment so that compilers that implement
sleep with them don't spin.
This also fixes a mutability bug in config where we weren't really doing
clone properly because map references are shared.
> Makes fake clocks increment and fixes mutability bug

- .github/workflows/commit.yaml
default installs too many things we don't need and causes flakes. This could be refactored
later to use GH release assets to get the libraries instead, but this should help for now.
See https://github.com/tetratelabs/wazero/runs/6929850638?check_suite_focus=true
> benchmarks: reduces heft of WasmEdge install

- internal/asm/arm64/consts.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_vec_arm64.go
- internal/integration_test/spectest/v2/spec_test.go
This implements vector comparison instructions for 
arm64 backend.
part of #484
> arm64: implement vector comparisons 

- internal/asm/arm64/consts.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_vec_arm64.go
- internal/integration_test/spectest/v2/spec_test.go
This implements floating point SIMD arithmetics and rounding
instructions for arm64 backend.
Notably, now arm64 passes `simd_f32x4_arith.json`, `simd_f64x2_arith`,
`simd_f64x2`, `simd_f32x4`, `simd_f32x4_rounding`, `simd_f64x2_rounding`
spectests.
> arm64: FP SIMD arithmetic/rounding instructions

- internal/asm/amd64/impl.go
- internal/asm/arm64/assembler.go
- internal/asm/arm64/consts.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_vec_arm64.go
- internal/integration_test/asm/arm64_debug/debug_assembler.go
- internal/integration_test/asm/arm64_debug/golang_asm.go
- internal/integration_test/asm/arm64_debug/impl_test.go
- internal/integration_test/spectest/v2/spec_test.go
This implements SIMD integer arithmetic instructions for arm64 backend.
Notably, now the engine passes  `simd_**_arith`, `simd_**_arith2`, and
`simd_**_sat_arith` spectests.
part of #484
> arm64: implement SIMD Integer arithmetics

- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_vec_arm64.go
- internal/integration_test/spectest/v2/spec_test.go
This implements pmin, pmax and dot SIMD instructions for
arm64 backend.
part of #484
> arm64: dot and pseudo min/max instructions

- internal/engine/compiler/impl_vec_amd64.go
- internal/engine/compiler/impl_vec_amd64_test.go
This fixes amd64's compileV128NegFloat so that the impl won't be
affected by the previous values on the temporary vector register.
This was a flaky bug found in 
* https://github.com/tetratelabs/wazero/runs/6977169039?check_suite_focus=true
* https://github.com/tetratelabs/wazero/runs/6958490906?check_suite_focus=true
> amd64,simd: fix occational partial failure of FP neg. 

- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
This existed to line the impl with golang-asm but yeah needless 
> arm64: remove NOP insertion at the beginning

- RATIONALE.md
- assemblyscript/assemblyscript.go
- config.go
- config_test.go
- examples/wasi/cat.go
- examples/wasi/cat_test.go
- experimental/fs.go
- experimental/fs_example_test.go
- experimental/fs_test.go
- internal/integration_test/fs/fs_test.go
- internal/integration_test/spectest/spectest.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- internal/testing/fs/fs.go
- internal/testing/fs/fs_test.go
- internal/testing/require/require.go
- internal/wasm/call_context.go
- internal/wasm/call_context_test.go
- internal/wasm/namespace_test.go
- internal/wasm/store_test.go
- wasi_snapshot_preview1/wasi.go
- wasi_snapshot_preview1/wasi_test.go
This removes `WithWorkDirFS` and any other attempts to resolve the current directory (".") in host functions. This is a reaction to reality of compilers who track this inside wasm (not via host functions). One nice side effect is substantially simpler internal implementation of file-systems.
This also allows `experimental.WithFS` to block file access via passing nil.
---
Before, wazero's API included a `WithWorkDirFS`, which allowed control over which file a relative path such as "./config.yml" resolved to, independent of the root file system. This intended to help separate concerns like mutability of files, but it didn't work and is removed here.
Compilers that target wasm act differently with regard to the working directory. For example, while `GOOS=js` uses host functions to track the …
> Removes WithWorkDirFS and "." resolution

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/arm64/impl.go
- internal/engine/compiler/compiler_conditional_save_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_vec_amd64.go
- internal/engine/compiler/impl_vec_arm64.go
Previously I had the assumption that we have always free registers for conditional value 
saving in compileLoadConditionalRegisterToGeneralPurposeRegister, but that is not the case 
when the conditional flag was created by floating-point comparison instructions.
Fixes #665 
> compiler: always allocate register to save conditional values

- assemblyscript/assemblyscript.go
- assemblyscript/assemblyscript_test.go
- builder.go
- experimental/fs_example_test.go
- internal/integration_test/vs/runtime.go
- internal/sys/fs.go
- internal/sys/sys.go
- internal/wasm/call_context.go
- namespace.go
- runtime.go
- runtime_test.go
- wasi_snapshot_preview1/clock.go
- wasi_snapshot_preview1/poll.go
- wasi_snapshot_preview1/poll_test.go
- wasi_snapshot_preview1/wasi.go
- wasi_snapshot_preview1/wasi_test.go
This consolidates to use EBADF in places go uses it in syscalls to
reduce where we formally returned both bool and err. This also removes
the redundant panic type handling as go will already panic with a
similar message.
> Removes redundant error handling

- .github/workflows/commit.yaml
- .github/workflows/internal-images.yml
- .github/workflows/spectest.yaml
This adds an image sync script similar to what we had in func-e as the amount of matrix jobs that use qemu are hitting problems.
Ex several jobs have failed today pulling the binfmt image.
```
Run docker/setup-qemu-action@v2
Docker info
Pulling binfmt Docker image
/usr/bin/docker pull tonistiigi/binfmt:latest
Error response from daemon: unauthorized: authentication required
Error: The process '/usr/bin/docker' failed with exit code 1
```
> adds image syncer

- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
This is the first bug found by wazero-fuzz repository:
```wat
(module
(type (func))
(func (type 0)
br 0 ;; return the function, therefore the following instructions are unreachable.
block
br 1 ;; <------------ this is unreachable and must be ignored, not causing panic :D 
end))
```
> ir: correctly ignore unreachable br/br_if

- internal/wasm/binary/element.go
- internal/wasm/binary/element_test.go
Even though this is in practice will never be used as of 2.0 since the only thing they could do is to add null references into the table (which is by default), this is allowed in spec but not fully covered. I found this via wazero-fuzz.
> binary: allow externref in element segments

- internal/engine/compiler/impl_arm64.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
Fixes the second bug found by wazero-fuzz. Previously, Drop instructions on the
vector values were wrongly translated and resulted in panic both on amd64 and arm64,
though that is not covered by spectes and practically doesn't appear in the real world program. 
> ir: fixes a range for drop operation on vector values

- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
Found via wazero-fuzz, though in practice this will unlikely happen:
```wat
(module
(type (;0;) (func (param i32)))
(func (;0;) (type 0) (param i32)
local.get 0
local.tee 0
local.tee 0
br_table 0 (;@0;) 0 (;@0;)
block (result i32)  ;; label = @1
local.get 0
br_table 1 (;@0;) 1 (;@0;)
i32.const 0
end
drop)
(export "r" (func 0)))
```
Similar to #682 
> ir: correctly ignores unreachable br_table instructions

- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
> ir: correctly ignores unreachable br_table instructions (part2)

- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/store_test.go
> Read unsigned leb128 for the index of ref.func in global initializer

- config.go
- config_test.go
- experimental/log_listener.go
- internal/wasm/function_definition.go
- internal/wasm/function_definition_test.go
Exported functions are easier to use as a map vs making the callers do
it.
> Makes ExportedFunctions unique

- builder_test.go
- experimental/log_listener_test.go
- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/integration_test/vs/runtime.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/binary/code.go
- internal/wasm/binary/encoder.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/counts.go
- internal/wasm/counts_test.go
- internal/wasm/function_definition.go
- internal/wasm/function_definition_test.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wazeroir/compiler.go
This removes the constraint of a module being exclusively wasm or host
functions. Later pull requests can optimize special imports to be
implemented in wasm, particularly useful for disabled logging callbacks.
> Supports mix of wasm and go funcs in the same module

- internal/engine/compiler/compiler_numeric_test.go
- internal/engine/compiler/impl_amd64.go
> amd64: correctly select sign of zeros on f64/32 min/max

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/spectest.yaml
- go.mod
Now that Go 1.19 has been released officially, it's time to
set our floor version of Go to 1.18 following our support policy.
> Set floor on Go 1.18

- assemblyscript/assemblyscript_test.go
- config.go
- config_test.go
- internal/platform/crypto.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- wasi_snapshot_preview1/random_test.go
- wasi_snapshot_preview1/wasi_test.go
This changes the default random source to provide deterministic values
similar to how nanotime and walltime do. This also prevents any worries
about if wasm can deplete the host's underlying source of entropy.
> Switches default random source to deterministic

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_2_test.go
- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
Previously, regardless of the value types, i've been using MOVQ to load/store the value from/to stack.
That was unnecessarily costly as i32 and f32 values don't need to move higher 32-bits.
> amd64: do not load/store higher bits of 32-bit int/float

- RATIONALE.md
- wasi_snapshot_preview1/fs.go
- wasi_snapshot_preview1/fs_test.go
These are to handle corner cases described in [`io.Reader`](https://pkg.go.dev/io#Reader).
For a partial read `readv` really shouldn't continue reading into the following buffer.
And according to [`io.Reader`](https://pkg.go.dev/io#Reader), callers should handle any read bytes before considering the error.
> Fix fdRead: handle io.Reader corner cases

- internal/engine/compiler/impl_arm64.go
The counterpart of #742 in arm64
> arm64: do not load/store higher bits of 32-bit int/float

- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
as of #743 #742 , store into the value stack only stores lower 32-bits,
so we have to drop the higher 32-bits.
> compiler: drop higher bits on table index

- internal/integration_test/vs/wasmer/wasmer.go
- internal/integration_test/vs/wasmer/wasmer_test.go
- internal/integration_test/vs/wasmtime/go.mod
- internal/integration_test/vs/wasmtime/go.sum
- internal/integration_test/vs/wasmtime/wasmtime.go
- internal/integration_test/vs/wasmtime/wasmtime_test.go
Enable for Wasmer, as confirmed that the version we use has arm64 support.
Enable for Wasmtime after bumping to a version which supports arm64.
Don't enable for wasm-edge as they don't support arm64/darwin.
> Enable comparative benchmark builds on darwin/aarch64 (ie Apple Silicon)

- internal/integration_test/bench/hostfunc_bench_test.go
Follow-up on #756 
This adds the benchmarks to measure the cost of host calls
between Wasm implemented vs Host implemented.
```
goos: darwin
goarch: arm64
BenchmarkHostFunctionCall
BenchmarkHostFunctionCall/call_go_host
BenchmarkHostFunctionCall/call_go_host-10         	 1328292	       904.5 ns/op
BenchmarkHostFunctionCall/call_wasm_host
BenchmarkHostFunctionCall/call_wasm_host-10       	 5341951	       221.4 ns/op
```
```
goos: linux
goarch: amd64
BenchmarkHostFunctionCall/call_go_host-32         	  495591	      2356 ns/op	    1464 B/op	      14 allocs/op
BenchmarkHostFunctionCall/call_wasm_host-32       	 2382007 …
```
> bench: compare host call costs on Wasm-impl vs Go-impl

- examples/allocation/rust/README.md
- site/content/history.md
- site/content/languages/_index.md
- site/content/languages/rust.md
- site/content/languages/tinygo.md
This adds more notes on TinyGo thanks to feedback from  @aykevl @dgryski @dkegel-fastly @hunjixin and @mathetake
This also starts rust notes. cc @clarkmcc
> site: elaborates concurrency and TinyGo notes; adds Rust notes

- site/config.toml
- site/content/_index.md
We've had feedback the languages page is hard to find. We also notice
the majority of wazero users use TinyGo and probably no one uses
primarily `%.wat`. This redoes the home page to reflect that.
Note: This doesn't add a drop-down for language yet, as to do that we
need to fix mobile. Currently mobile concatenates all drop-downs, so it
would fill up the screen as we add new languages.
> site: promotes languages and tinygo

- internal/compilationcache/file_cache.go
- internal/compilationcache/file_cache_test.go
This allows us to avoid crashes with `GOARCH=amd64 make test` after running `make test` on M1 Mac
> filecache: include GOOS/GOARCH in the key

- site/content/languages/_index.md
- site/content/languages/go.md
- site/content/languages/rust.md
- site/content/languages/tinygo.md
- site/content/specs.md
This consolidates copy/pasted notes into the main languages page, and
elaborates more general concerns than existed before.
> site: Adds content to languages page

- internal/engine/compiler/impl_amd64.go
> amd64: remove redundant ADD in GlobalGet/Set

- internal/engine/compiler/compiler.go
- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/interpreter/interpreter.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
- internal/wazeroir/format.go
- internal/wazeroir/operations.go
This commit changes `wazeroir.OperationSwap` to `OperationSet` which is the 
combination of OperationSwap and Drop in the previous implementation.
Previously, `OperationSwap` was always followed by `OperationDrop` on the swapped value on top.
Because of that, we had a redundant register allocation in Swap.
As a result, we use only one register in `OperationSet` which is a part of translations of
`local.tee` and `local.set`.
> Change OperationSwap to OperationSet

- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
To reduce the redundant instructions and register usage on the hot path.
> compiler: hold stack base pointers in bytes, not index to the stack slice

- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/integration_test/engine/adhoc_test.go
This fixes a bug introduced in #761 where the reuse of the api.Function
causes some trouble around module context initialization.
> compiler: zero-initializes moduleInstanceAddress of call engine

- examples/README.md
I don't remember when it's gone, but yeah it doesn't exist anymore 
> example: remove deprecated replace-import example link

- README.md
- site/content/_index.md
This week, we switched some of the README instructions from standalone
wasm to TinyGo, but not all of them. TinyGo requires features not in
WebAssembly 1.0 and also requires WASI even if your code doesn't use it.
Thanks @basvanbeek for reporting!
> Fixes README and site which doesn't configure TinyGo deps

- go.mod
Fixes #789
See https://go.dev/ref/mod#go-mod-file-retract
> Retracts tags before v1.0.0-beta.2

- README.md
- go.mod
- site/content/_index.md
This switches our pre-release nomenclature from "beta" to pre-release
("pre") as we are otherwise unable to rank higher than a broken tag and
still be compatible with go mod's naming conventions (semver).
See https://go.dev/blog/module-mirror-launch
Fixes https://github.com/tetratelabs/wazero/issues/789
> Switches from "beta" to "pre"

- site/content/languages/go.md
There're no branches or tags on that repo. Must have slipped in accidentally.
> languages/go: fix wasmexport proposal link

- site/content/languages/go.md
The [link syntax](https://gohugo.io/content-management/cross-references/) in
hugo is different from GitHub markdown.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> docs: correct link to tinygo page

- README.md
local path should be braced with `()`
> doc: fixes the link to imports pkg

- internal/buildoptions/debug_disabled.go
- internal/buildoptions/debug_enabled.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/impl_amd64.go
- internal/wasm/func_validation.go
- internal/wasmdebug/debug.go
- internal/wazeroir/compiler.go
This has existed since the beginning, but I have never used recently 
since it's used everywhere and stdout gets pretty messy if enabled.
> Delete buildoptions pkg

- site/content/languages/go.md
One reality of wasm compilers is that they are incomplete and often have bugs. While I don't want our site to become overwhelmed with instructions, it is helpful I think to have tips on how to do routine changes to the compiler, at least how to test them.
This is for Go, and I'll also add one on TinyGo as in both cases, it might not be obvious that you need may need to rebuild the binary in order to test changes, and if you do it may be difficult to figure out how.
> site: adds instructions on how to hack go

- imports/wasi_snapshot_preview1/clock.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/errno.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/sock.go
- imports/wasi_snapshot_preview1/sock_test.go
- imports/wasi_snapshot_preview1/wasi.go
- site/content/languages/tinygo.md
- site/content/specs.md
This catches up with latest WASI drift.
> wasi: stubs sock_accept and removes things removed from WASI

- builder.go
- example_test.go
- examples/allocation/tinygo/greet.go
- examples/basic/add.go
- experimental/fs_example_test.go
- experimental/listener_example_test.go
- experimental/logging/log_listener_example_test.go
- imports/assemblyscript/assemblyscript.go
- imports/assemblyscript/assemblyscript_example_test.go
- imports/emscripten/emscripten.go
- imports/emscripten/emscripten_example_test.go
- imports/emscripten/emscripten_test.go
- imports/wasi_snapshot_preview1/example/cat.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/integration_test/bench/bench_test.go
- internal/integration_test/bench/codec_test.go
- internal/integration_test/fs/fs_test.go
This adds an easier interface to those configuring infrastructural host imports such as WASI, and never unloading them except as a side effect of closing the runtime.
Ex.
```diff
-       if _, err := wasi_snapshot_preview1.Instantiate(ctx, r); err != nil {
-               log.Panicln(err)
-       }
+       wasi_snapshot_preview1.MustInstantiate(ctx, r)
```
> Adds MustInstantiate to host imports

- api/wasm.go
- config.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/wasm/call_context.go
- internal/wasm/memory.go
- internal/wasm/memory_definition.go
- internal/wasm/memory_definition_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- runtime.go
- runtime_test.go
It is more often the case that projects are enabling a freestanding target, and that may or may not have an exporting memory depending on how that's interpreted. This adds the ability to inspect memories similar to how you can already inspect compiled code prior to instantiation. For example, you can enforce an ABI constraint that "memory" must be exported even if WASI is not in use.
Here's an example of validating both a function and a memory are exported prior to instantiating the guest.
```go
const (
FuncHandle = "handle"
Memory = "memory"
)
// validateGuestModule ensures the guest exports features the host ABI requires.
func validateGuestModule(guest wazero.CompiledModule) error {
if handle, ok := guest.ExportedFunctions()[FuncHandle]; !ok {
return fmt.Errorf("wasm: guest doesn't …
```
> Adds MemoryDefinition to CompiledModule and Memory

- .github/workflows/internal-images.yml
I randomly noticed this action start failing on my fork after I pushed main to it recently to verify some other workflows. Having repository-scoped ghcr images is relatively recent so maybe this can be migrated to it - it would allow forks to behave the same as this repo. Or if intentionally using global don't have to make this change and I could send another PR with an `if repo == tetratelabe/wazero` condition to the job instead
> Use repo-scoped image for internal build image

- config.go
- examples/import-go/age-calculator.go
- examples/namespace/counter.go
- experimental/logging/log_listener_test.go
- imports/assemblyscript/assemblyscript_example_test.go
- imports/emscripten/emscripten_example_test.go
- internal/engine/compiler/engine_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/vs/wasmedge/wasmedge.go
- internal/integration_test/vs/wasmer/wasmer.go
- internal/integration_test/vs/wasmtime/wasmtime.go
- internal/sys/fs.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/binary/encoder_test.go
- internal/wasm/function_definition_test.go
- internal/wasm/global.go
- internal/wasm/gofunc.go
- internal/wasm/gofunc_test.go
- internal/wasm/host_test.go
- internal/wasm/memory.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wazeroir/compiler_test.go
- runtime.go
- runtime_test.go
This restores the ability to leave out the initial context parameter when defining functions with reflection. This is important because some projects are porting from a different library to wazero, and all the alternatives are not contextualized.
For example, this project is porting envoy host functions, and the original definitions (in mosn) don't have a context parameter. By being lenient, they can migrate easier.
See https://github.com/cisco-open/nasp/blob/6b813482b6177385311fdfc42d92a9d3e096b8f2/pkg/proxywasm/wazero/imports_v1.go
> Restores ability to define host functions w/o context via reflection

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/spectest.yaml
- README.md
- cmd/wazero/wazero.go
- go.mod
- imports/go/example/stars/go.mod
- internal/compilationcache/file_cache_test.go
- internal/integration_test/vs/time/go.mod
- internal/integration_test/vs/wasmedge/go.mod
- internal/integration_test/vs/wasmer/go.mod
- internal/integration_test/vs/wasmtime/go.mod
- internal/version/testdata/go.mod
This enforces that wazero will build and operate one version behind Go's support policy, making wazero's Go policy effectively three versions.
This is to allow libraries with wider Go policies to be able to use wazero. Specifically, mosn is the first to need this.
> Extends build compatability to one version behind Go's support policy

- internal/ieee754/ieee754.go
- internal/leb128/leb128.go
- internal/leb128/leb128_test.go
- internal/wasm/binary/const_expr.go
- internal/wasm/binary/element.go
- internal/wasm/func_validation.go
- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/table.go
- internal/wazeroir/compiler.go
This resoles #835 by factoring out the ieee754 and leb128 binary decoding, creating functions to decode from byte slices in addition to `io.ByteReader`s.
Once I started looking closer at how these functions are used I realized there are several places where passing the reader made sense. I've called the functions that decode from a byte slice `Load{numeric type}` and swapped them out anywhere a `*bytes.Reader` was being created for a single use.
Time spent creating readers no longer shows up in my profile.
> add ieee754 and leb128 byte slice funcs

- internal/engine/compiler/engine.go
- internal/integration_test/bench/bench_test.go
- internal/wasm/module.go
Before:
```sh
❯ go test -benchmem -memprofile memprofile.out -cpuprofile profile.out -run=^$ -bench ^BenchmarkInitialization/compiler$ github.com/tetratelabs/wazero/internal/integration_test/bench
goos: darwin
goarch: arm64
BenchmarkInitialization/compiler-10                64510             17417 ns/op          145950 B/op        128 allocs/op
PASS
ok      github.com/tetratelabs/wazero/internal/integration_test/bench   1.600s
```
After:
```sh
❯ go test -benchmem -memprofile memprofile.out -cpuprofile profile.out -run=^$ -bench ^BenchmarkInitialization/compiler$ github.com/tetratelabs/wazero/internal/integration_test/bench
goos: darwin
goarch: arm64 …
```
> Optimize compiler.(*engine).NewModuleEngine

- internal/integration_test/bench/bench_test.go
- internal/wasm/module.go
- internal/wasm/namespace.go
- internal/wasm/namespace_test.go
- internal/wasm/store.go
The check in module initialization to ensure a uniqueness of a module name in a a namespace does a linear scan of a string slice. Because the namespace needs to be fully locked during this check it means module initializations slows down as you have more active modules. This change replaces the linear scan with a map lookup. I've added a benchmark to track the performance of having multiple simiultainus module instances.
Before:
```
❯ go test -benchmem -memprofile memprofile.out -cpuprofile profile.out -blockprofile blockprofile.out -run=^$ -bench ^BenchmarkInitialization github.com/tetratelabs/wazero/internal/integration_test/bench
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz …
```
> Replace module name check linear scan with map lookup

- internal/gojs/misc_test.go
- internal/gojs/state.go
- internal/gojs/testdata/gc/main.go
- internal/gojs/testdata/main.go
I was attempting to use gojs with a binary that read from stdin, did some
transformations, then printed to stdout. This worked or small inputs, but for 
larger values would panic like:
runtime: g 5: unexpected return pc for syscall/js.Value.Call called from 0x18ca120
<memory addresses & stack>
syscall/js.Value.Call({{}, 0x1720028, 0x141c0001}, {0x0, 0x0}, {0x0, 0x0, 0x0})
/usr/local/go/src/syscall/js/js.go:384 +0x35 fp=0x8327d0 sp=0x832710 pc=0x16e50035
created by runtime.createfing
/usr/local/go/src/runtime/mfinal.go:157 +0x5
After some debugging, I traced it to gojs.FinalizeRef being called for idJsFs
when a GC is triggered after stdout/stderr is used. I've included a small test
that triggers the same issue (and and is fixed by the same patch). The 
testcase fails with:
runtime error: …
> gojs: gc fix refcount issue

- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_4_test.go
This is mainly so we can tell if changing this will work. e.g. if 20 bits are enough for #847
> Adds more context for ADR offset overrun

- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_4_test.go
> arm64: adds support for large in-block jumps with ADR

- Makefile
- internal/platform/mmap_unsupported.go
noticed via https://github.com/benthosdev/benthos/commit/456ab2a87cddb3808d2297033f61e655882c26b8
> Fixes builds on compiler-unsupported platoforms

- RATIONALE.md
- api/wasm.go
- sys/error.go
We made some decisions around encoding last year, but we didn't detail why. This leads to questions.
e.g. https://gophers.slack.com/archives/C040AKTNTE0/p1668883638982119
> Adds rationale for api.ValueType encoding

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/sys/fs.go
This adds path_filestat_get which is needed for PDFium and zig's fstatatWasi.
https://github.com/ziglang/zig/blob/aea617c60be848ed372343e08465bb0ac6cb7b85/lib/std/os.zig#L4171
The original source of this was written by @jerbob92
> wasi: adds path_filestat_get

- api/wasm.go
- builder_test.go
- imports/assemblyscript/assemblyscript.go
- imports/emscripten/emscripten.go
- imports/wasi_snapshot_preview1/args.go
- imports/wasi_snapshot_preview1/clock.go
- imports/wasi_snapshot_preview1/environ.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/random.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/gojs/runtime.go
- internal/gojs/spfunc/spfunc_test.go
- internal/gojs/syscall.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/integration_test/vs/runtime.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/gofunc.go
- internal/wasm/gofunc_test.go
This fixes a bug where function call results used the same slice (in the compiler engine). This was due to it being a write-through of a shared stack. What happens is a user of a first result can corrupt the next, or possibly worse:
```go
results, err := fn.Call(ctx, 1)
results2, err := fn.Call(ctx, 2)
results[0] = 255 // affects results2[0]
```
The safe approach is to always copy-out (internally). However, stack re-use was an optimization to avoid copying. To pay for the copy-out, this optimizes the signatures of `api.GoFunction` and `api.GoModuleFunction` as described below. As these are low-level interfaces, most users will have no impact to this change. I'll help port things on github that use them, though.
The general idea is that if we want to make Function.Call safe (ex copy-out …
> Optimizes GoModuleFunction signature and ensures function result slices are unique

- api/wasm.go
- api/wasm_test.go
This is another tricky part of our API, and I realized that we should've documented it at least until we ever have change the API. Thank @jerbob92 to raise this up.
> api: adds Encode and Decode functions for int32 and uint32

- internal/integration_test/bench/codec_test.go
- internal/integration_test/spectest/spectest.go
- internal/wasm/binary/custom.go
- internal/wasm/binary/decoder.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/counts.go
- internal/wasm/module.go
- runtime.go
Disabled by default, and will be only enabled true if DWARF trace option is on (which will be added later)
> binary: adds custom section decoder

- config.go
- config_test.go
- imports/wasi_snapshot_preview1/args.go
- imports/wasi_snapshot_preview1/environ.go
- imports/wasi_snapshot_preview1/wasi.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/gojs/argsenv.go
- internal/sys/sys.go
- internal/sys/sys_test.go
While most compilers will only read args/environ once, tools like WAGI make heavy use of environment, possibly dozens of long variables. This optimizes both args and environ for this reason and also to setup for optimizing other functions.
Here are the notable changes:
* eagerly coerce to byte slices instead of strings
* re-use null terminated length for writing values
* avoid loops that call mem.WriteXXX internally
Before:
```
Benchmark_ArgsEnviron
Benchmark_ArgsEnviron/args_get
Benchmark_ArgsEnviron/args_get-16         	 6147727	       187.9 ns/op	      72 B/op	       5 allocs/op
Benchmark_ArgsEnviron/args_sizes_get
Benchmark_ArgsEnviron/args_sizes_get-16   	11869351	       100.7 ns/op	      24 B/op	       2 allocs/op
Benchmark_ArgsEnviron/environ_get …
```
> wasi: optimizes args/environ parsing

- README.md
As of https://github.com/tetratelabs/wazero/pull/791, this section hasn't been maintained nor tested at all. Plus the sentence sounds weird as we no longer have `The former example is a pure function.` on the previous section.
> Deletes drifted Deep dive section in REAMDE

- imports/emscripten/emscripten.go
- internal/engine/compiler/engine.go
- internal/wasm/store.go
- internal/wasm/store_test.go
Ref #889 
This further reduces the allocation during instantiation:
```
$ benchstat old.txt new.txt                                                                                                                    
Initialization/interpreter-10             23.7µs ±11%    22.7µs ± 8%    ~     (p=0.421 n=5+5)
Initialization/interpreter-multiple-10    10.8µs ± 7%    11.2µs ± 7%    ~     (p=0.548 n=5+5)
Initialization/compiler-10                33.1µs ± 2%    32.9µs ± 1%    ~     (p=0.905 n=5+4)
Initialization/compiler-multiple-10       15.0µs ± 9%    16.0µs ±16%    ~     (p=0.421 n=5+5)
Initialization/interpreter-10              141kB ± 0% …
```
> Removes ModuleInstance.TypeIDsIndex to reduce allocations

- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_post1_0_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
Ref #889 
This further reduces the allocations during instantiation
```
$ benchstat old_re2.txt new_re2.txt
Initialization/interpreter-10              136µs ± 2%     137µs ± 2%    ~     (p=0.222 n=5+5)
Initialization/interpreter-multiple-10    62.5µs ±17%    67.4µs ±13%    ~     (p=0.421 n=5+5)
Initialization/compiler-10                 167µs ± 5%     156µs ± 4%  -6.66%  (p=0.008 n=5+5)
Initialization/compiler-multiple-10       44.1µs ± 8%    43.0µs ± 9%    ~     (p=0.548 n=5+5)
Initialization/interpreter-10              550kB ± 0%     550kB ± 0%    ~     (p=0.881 n=5+5)
Initialization/interpreter-multiple-10     551kB ± 0%     551kB ± 0% …
```
> compiler: make moduleContext.functions non-pointer slice

- imports/wasi_snapshot_preview1/fs.go
I did not find an authoratative reference in the wasi snapshot 1 docs, but based on the wasi-libc implementation [1] these should not be individual values but a bitmask.
[1] https://github.com/WebAssembly/wasi-libc/blob/3a261b03809018ceae294e9062cde0758b55b61a/libc-bottom-half/headers/public/wasi/api.h#L891-L921
> Use shifted iota for wasiFdflags values

- internal/integration_test/bench/bench_test.go
- internal/wasm/namespace.go
- internal/wasm/namespace_test.go
During module close the module name needs to be removed from the module list in the namespace. Previously the time complexity of deleting a name was O(n). This change replaces the name slice with a doubly linked list for O(1) deletion while preserving the reverse insert order.
This change further reduces the lock contention when lots of modules are created and closed.
Blocking profile before:
Blocking profile after:
Signed-off-by: Clifton Kaznocha <ckaznocha@users.noreply.github.com>
> Reduce lock contention during module close

- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter_test.go
This changes the log listener to assume a value is signed instead of unsigned, as it leads to logs looking more correct than the other way around. Notably, values that are often negative, such as seek offset, look better without a lot of downside.
discussed with @anuraaga
> Makes log listener default to signed interpretation

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/spectest.yaml
fixes a bug on main branch trigger https://github.com/tetratelabs/wazero/actions/runs/3646111475/workflow
> ci: fixes group for main branch commit trigger

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/spectest.yaml
- internal/integration_test/spectest/spectest.go
- internal/wasm/call_context.go
- internal/wasm/namespace.go
- internal/wasm/namespace_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
This change consolidates the two maps on the namespace into one while preserving the O(1) add/delete operations. I realized after introducing the linked list the second map was no longer needed.
I've also added an atomic to track the closed state and the namespace no longer allocates a new map when being closed per suggestion by @codefromthecrypt. `addModule` has been renamed to `setModule` and its signature updated to return an error because its no longer safe to add a module who's name has not already been created. The rest of the methods which did not return an error have become no-op after the namespace is closed. Happy to revise that if they should be updated to return errors.
Added test cases for closed namespaces to ensure namespace.go still has 100% coverage.
> Simplify namespace

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
```bash
$ go test -run='^$' -bench '^Benchmark_fdWrite$' -count=5 > old.txt
$ go test -run='^$' -bench '^Benchmark_fdWrite$' -count=5 > new.txt
name                    old time/op  new time/op  delta
_fdWrite/io.Writer-16    138ns ± 1%   132ns ± 3%  -3.95%  (p=0.008 n=5+5)
_fdWrite/io.Discard-16   137ns ± 6%   139ns ± 4%    ~     (p=0.421 n=5+5)
```
> wasi: improves fd_write perf when not discarded

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
```bash
$ go test -run='^$' -bench '^Benchmark_fdRead$' -count=5 > old.txt
$ go test -run='^$' -bench '^Benchmark_fdRead$' -count=5 > new.txt
name             old time/op  new time/op  delta
_fdRead/1x8-16    157ns ± 5%   133ns ± 1%  -15.34%  (p=0.008 n=5+5)
_fdRead/2x16-16   193ns ± 6%   155ns ± 1%  -19.77%  (p=0.008 n=5+5)
```
> wasi: optimize and benchmark fd_read

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
It is likely we'll have to special-case real files in wasi, as wasi-libc makes behavioral choices based on presence of non-zero inode data. This adds a defensive benchmark, so that we know what our performance base case is. This adds both real and fake file systems as both patterns are in use today.
```bash
$ go test -run='^$' -bench '^Benchmark_fdReaddir$'
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_fdReaddir/embed.FS-16         	  457398	      2416 ns/op
Benchmark_fdReaddir/os.DirFS-16         	   45662	     26271 ns/op
PASS
ok  	github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1	35.632s
```
See https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-17 and …
> wasi: benchmarks fd_readdir for both real and fake file systems

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/sys/fs.go
```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
Benchmark_pathFilestat
Benchmark_pathFilestat/embed.FS_fd=root
Benchmark_pathFilestat/embed.FS_fd=root-16         	  410125	      2712 ns/op	     144 B/op	       6 allocs/op
Benchmark_pathFilestat/embed.FS_fd=directory
Benchmark_pathFilestat/embed.FS_fd=directory-16    	  461304	      2717 ns/op	     160 B/op	       8 allocs/op
Benchmark_pathFilestat/os.DirFS_fd=root
Benchmark_pathFilestat/os.DirFS_fd=root-16         	   58639	     21299 ns/op	     408 B/op	       8 allocs/op
Benchmark_pathFilestat/os.DirFS_fd=directory
Benchmark_pathFilestat/os.DirFS_fd=directory-16    	   56630	     21274 ns/op	     456 B/op
```
> wasi: skips fd allocation on path_filestat_get and backfills benchmarks

- internal/gojs/compiler_test.go
- internal/gojs/fs_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/testdata/sub/test.txt
- internal/sys/testdata/test.txt
`os.DirFS` ironically doesn't implement `fs.ReadDirFS`, so we cannot open a directory this way. This blindly attempts to open "." regardless of if the `fs.FS` implementation is a `fs.ReadDirFS` or not, and if successful, enforces that the file returned is a directory. If not, a fake directory is returned.
Doing so allows real stat to be returned for root, and also a chance to know if a filesystem configured is real or not. Later, we'll need this to implement open flags.
> wasi: ensure someone can tell if root is a real file

- RATIONALE.md
- experimental/fs_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/testdata/sub/sub/test.txt
At the moment, the only pre-open support we have is the file system itself (root a.k.a. / or file-descriptor 3). We may in the future add the ability to pre-open sockets, but in any case, this is where we are today.
This change hardens logic around fd_preXXX functions, ensuring they only work on actual pre-opens. This also fixes the path returned in filestat as we sometimes returned a full path, when typically the basename is the only part that can be returned.
> wasi: enforce fd_preXXX functions only work on pre-opened files

- internal/engine/compiler/engine.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store.go
This reduces the memory pressure at instantiation slightly 
#889 
```
Initialization/interpreter-10             35.5µs ± 1%    34.5µs ± 1%  -2.73%  (p=0.000 n=10+8)
Initialization/interpreter-multiple-10    13.7µs ± 4%    13.7µs ± 8%    ~     (p=0.684 n=10+10)
Initialization/compiler-10                27.1µs ±49%    24.9µs ±49%    ~     (p=0.165 n=10+10)
Initialization/compiler-multiple-10       12.3µs ± 5%    12.1µs ± 4%    ~     (p=0.247 n=10+10)
Initialization/interpreter-10              141kB ± 0%     139kB ± 0%  -1.27%  (p=0.000 n=10+10)
Initialization/interpreter-multiple-10     142kB ± 0%     140kB ± 0% …
```
> Removes unused FunctionInstance.LocalTypes

- internal/wasm/call_context.go
- internal/wasm/store_test.go
I think this is a remnant since a while and no we don't need it 
> Removes importedFn

- internal/wasm/binary/value.go
> Fixes unnecessary allocation in decodeValueTypes

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/platform/bench_test.go
- internal/platform/platform.go
- internal/platform/terminal.go
- internal/platform/terminal_bsd.go
- internal/platform/terminal_linux.go
- internal/platform/terminal_test.go
- internal/platform/terminal_unsupported.go
- internal/platform/terminal_windows.go
- internal/sys/fs.go
- internal/sys/fs_test.go
This uses ioctl syscalls or appropriate alternative, to detect if stdin/out/err are character devices or not. This caches the result, to ensure performance is ok at runtime as executing stat can approach microsecond overhead.
Fixes #928
> wasi: detect if stdio are char devices instead of assuming

- internal/leb128/leb128.go
- internal/leb128/leb128_alloc_test.go
This is a hot pass during compilation. Found while doing #936, and raised this as a separate PR.
```
benchstat leb128_old.txt leb128_new.txt
name             old time/op    new time/op    delta
LoadUint32-10      41.8ns ± 1%    12.0ns ± 0%   -71.35%  (p=0.000 n=10+10)
LoadUint64-10      4.96ns ± 0%    4.95ns ± 0%      ~     (p=0.813 n=9+9)
LoadInt32-10       42.1ns ± 2%    12.4ns ± 0%   -70.56%  (p=0.000 n=10+10)
LoadInt64-10       41.7ns ± 1%    12.4ns ± 0%   -70.27%  (p=0.000 n=10+10)
DecodeUint32-10    38.4ns ± 1%    17.3ns ± 1%   -55.03%  (p=0.000 n=10+10)
DecodeInt32-10     39.3ns ± 1%    17.8ns ± 0%   -54.59%  (p=0.000 n=10+9)
DecodeInt64-10     39.3ns ± 0%    17.6ns ± 0%   -55.28%  (p=0.000 n=10+10)
name             old alloc/op   new alloc/op   delta
LoadUint32-10       28.0B ± 0% …
```
> leb128: no allocations in decoding

- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
This allows wasm to close stdio file descriptors such as STDOUT(1). This will not close the underlying host resource as that would break a lot of folks doing logging to the console.
Thanks a lot to @vyskocilm for making this easy to identify and fix!
```bash
$ cat > fclose.c <<EOF
#include <stdlib.h>
#include <stdio.h>
int main() {
int ret = fclose(stdin);
if (ret != 0) {
perror("fclose <stdin>");
}
exit(ret);
}
EOF
$ zig cc --target=wasm32-wasi fclose.c -o fclose.wasm
$ go build -o wazero ./cmd/wazero/...
$ ./wazero run fclose.wasm
```
Fixes #953
> wasi: allows closing stdio file descriptors

- cmd/wazero/testdata/cat/.gitignore
- cmd/wazero/testdata/cat/cat.go
- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
This changes the CLI to detect if GOOS=js is likely in use and switches accordingly. This makes it easier to find bugs and may eventually lead to go being able to swap out node.js for wazero. This adds 1.5-2MB to the binary depending on ldflags.
Note: GOOS=js a.k.a. gojs isn't complete, yet, so this helps identify that as well. For example, similar to WASI there's no support for mkdir yet.
```bash
$ GOOS=js GOARCH=wasm go test -o os.wasm -c os
$ wazero run os.wasm -test.v
=== RUN   TestExpand
--- PASS: TestExpand (0.00s)
=== RUN   TestConsistentEnviron
--- PASS: TestConsistentEnviron (0.00s)
=== RUN   TestUnsetenv
--- PASS: TestUnsetenv (0.00s)
=== RUN   TestClearenv
--- PASS: TestClearenv (0.00s)
=== RUN   TestLookupEnv
--- PASS: TestLookupEnv (0.00s)
=== RUN   TestEnvironConsistency
--- …
```
> cli: allows use of GOOS=js

- experimental/logging/log_listener.go
- imports/assemblyscript/assemblyscript_test.go
- imports/wasi_snapshot_preview1/args_test.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/environ_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/proc_test.go
- imports/wasi_snapshot_preview1/random_test.go
- imports/wasi_snapshot_preview1/sched_test.go
- imports/wasi_snapshot_preview1/sock_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- imports/wasi_snapshot_preview1/wasi_test.go
- internal/testing/proxy/proxy.go
- internal/testing/require/require.go
This makes it easier to do maintenance by hiding the implementation details of using a proxy module to test host modules. What happens is we skip logging of these proxy modules, which makes it easier to see what log affects a change has.
> Hides internal logging

- RATIONALE.md
- internal/engine/compiler/RATIONALE.md
> doc: document why it's safe against async preemption

- internal/gojs/argsenv.go
- internal/gojs/custom/names.go
- internal/gojs/goarch/wasm.go
- internal/gojs/goos/js.go
- internal/gojs/runtime.go
- internal/gojs/syscall.go
- internal/gojs/util/util.go
- internal/gojs/util/util_test.go
`GOARCH=wasm GOOS=js` defines parameter names in go source, and they are indirectly related to the wasm parameter "sp". This creates a pseudo name section so that we can access the parameter names. The alternative would be adding a hack to normal FunctionDefinition, only used for gojs.
> gojs: extracts parameter names into a pseudo name section

- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/random.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/logging/logging.go
- internal/testing/proxy/proxy.go
- internal/wasi_snapshot_preview1/wasi.go
- internal/wasm/host_test.go
This changes the listener signature to accept context and calling
module, so that all possible parameters and results can be logged. This
also changes the logging listener to make parameters visible when
logging results.
This infrastructure supports some helpful use cases, such as logging
WASI result parameters, such as the prestat path, which is only knowable
after the function has been called. The context parameter supposed
reading results of gojs functions, which are stored host-side in a go
context object.
Future pull requests will complete this as well backfill unit tests.
This is raised independently mainly to keep the PR size down of the
upcoming filesystem logger.
> logging: extracts utilities to read parameters and results from memory

- experimental/logging/log_listener_example_test.go
- experimental/logging/log_listener_test.go
- imports/wasi_snapshot_preview1/args_test.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/environ_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/proc_test.go
- imports/wasi_snapshot_preview1/random_test.go
- imports/wasi_snapshot_preview1/sched_test.go
- imports/wasi_snapshot_preview1/sock_test.go
- internal/wasi_snapshot_preview1/wasi.go
This uses logging infrastructure introduced in #938 to show paths and certain result parameters. While further tuning is expected, the main thing this does is show which paths are affected by syscalls.
> logging: reformats wasi filesystem logs to display paths

- cmd/wazero/wazero.go
- experimental/writefs/writefs.go
- experimental/writefs/writefs_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/gojs/compiler_test.go
- internal/gojs/custom/fs.go
- internal/gojs/fs.go
- internal/gojs/fs_test.go
- internal/gojs/state.go
- internal/gojs/syscall.go
- internal/gojs/testdata/fs/main.go
- internal/gojs/testdata/main.go
- internal/gojs/testdata/writefs/main.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/wasm/call_context_test.go
- internal/wasm/namespace_test.go
This adds writefs.FS, allowing functions to create and delete files. This begins by implementing them on `GOARCH=js GOOS=wasm`. The current status is a lot farther than before, even if completing write on WASI is left for a later PR (possibly by another volunteer).
For example, Go os package tests pass all the way up to symlinks now, something that can also be done in a follow-up.
```bash
$ mkdir tmp
$ wazero run  -mount=.:/ os.wasm -test.v
=== RUN   TestExpand
--- PASS: TestExpand (0.00s)
=== RUN   TestConsistentEnviron
--- PASS: TestConsistentEnviron (0.00s)
=== RUN   TestUnsetenv
--- PASS: TestUnsetenv (0.00s)
=== RUN   TestClearenv
--- PASS: TestClearenv (0.00s)
=== RUN   TestLookupEnv
--- PASS: TestLookupEnv (0.00s)
=== RUN   TestEnvironConsistency
--- PASS: TestEnvironConsistency …
```
> Adds experimental write support and implements on gojs

- cmd/wazero/wazero.go
- experimental/writefs/writefs.go
- experimental/writefs/writefs_example_test.go
- internal/gojs/fs_test.go
- internal/sys/fs.go
- internal/writefs/writefs.go
- internal/writefs/writefs_test.go
- namespace_test.go
The type we use to expose write operations is still evolving. It might be a single writefs.FS interface, or similar to go where we have an interface per feature (e.g. writefs.MkdirFS). These choices are all implementation details for DirFS and won't be settled before the end of the month version cutoff. Instead, this only exposes the ability to create a DirFS, not an arbitrary implementation of writefs.FS. This does so by making `writefs.FS` an internal type.
> Exposes experimental writefs.DirFS, but hides implementation

- RATIONALE.md
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
Fixes #958.
This is breaking a zig test, I still haven't been able to figure out why.
> Fix fdPread: shouldn't move file offset

- internal/gojs/fs.go
- internal/gojs/syscall.go
- internal/gojs/testdata/writefs/main.go
- internal/sys/fs.go
- internal/writefs/syscall.go
- internal/writefs/syscall_windows.go
- internal/writefs/writefs.go
- internal/writefs/writefs_test.go
This splits unlink and rmdir from remove, as it is not only more precise in GOOS=js, but it is also needed to implement wasi. I verified this works by running go unit tests with logging.
```
==> go.syscall/js.valueCall(fs.open(name=/tmp/TestErrIsNotExist1062486353,flags=,perm=----------))
<== (err=<nil>,fd=10)
==> go.syscall/js.valueCall(fs.fstat(fd=10))
<== (err=<nil>,stat={isDir=true,mode=-rwx------,size=96,mtimeMs=1672285985206})
==> go.syscall/js.valueCall(fs.readdir(name=/tmp/TestErrIsNotExist1062486353))
<== (err=<nil>,dirents=&{[001]})
==> go.syscall/js.valueCall(fs.unlink(path=/tmp/TestErrIsNotExist1062486353/001))
<== (err=is a directory,ok=true)
==> go.syscall/js.valueCall(fs.rmdir(path=/tmp/TestErrIsNotExist1062486353/001))
<== (err=<nil>,ok=false)
```
> fs: splits unlink and rmdir from remove

- internal/writefs/syscall_windows.go
- internal/writefs/writefs.go
- internal/writefs/writefs_test.go
adding a test case so that we can depend on it.
> writefs: require ENOTEMPTY

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs.go
- internal/wasi_snapshot_preview1/errno.go
- internal/writefs/writefs.go
- internal/writefs/writefs_test.go
This implements path_(create|remove)_directory path_unlink_file in wasi, particularly needed to use TinyGo tests to verify our interpretation of WASI. Use of this requires the experimental `writefs.DirFS`.
After installing via `go install ./cmd/wazero/...`, tinygo os package tests pass except those requiring rename which isn't implemented yet.
```bash
$ ./build/tinygo test -target wasi -c -o os.wasm os
$ mkdir tmp
$ wazero run -hostlogging=filesystem -mount=.:/ os.wasm -test.v
==> wasi_snapshot_preview1.fd_prestat_get(fd=3)
<== (prestat={pr_name_len=1},errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_dir_name(fd=3)
<== (path=/,errno=ESUCCESS)
==> wasi_snapshot_preview1.fd_prestat_get(fd=4)
<== (prestat=,errno=EBADF)
==> wasi_snapshot_preview1.path_unlink_file(fd=3,path=tmp/_os_test_Te …
```
> wasi: implements path_(create|remove)_directory path_unlink_file

- experimental/writefs/writefs.go
- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/custom/fs.go
- internal/gojs/fs.go
- internal/gojs/fs_test.go
- internal/gojs/testdata/fs/main.go
- internal/gojs/testdata/writefs/main.go
- internal/gojs/testdata/writefs/times.go
- internal/gojs/testdata/writefs/times_js.go
- internal/platform/mmap_windows.go
- internal/platform/stat.go
- internal/platform/stat_bsd.go
- internal/platform/stat_linux.go
- internal/platform/stat_test.go
- internal/platform/stat_unsupported.go
- internal/platform/stat_windows.go
- internal/sys/fs.go
- internal/syscallfs/syscall.go
- internal/syscallfs/syscall_windows.go
- internal/syscallfs/syscallfs.go
- internal/syscallfs/syscallfs_test.go
This renames the internal writefs package to syscallfs as it is largely dependent on syscall signatures. This also implements utimes in gojs. WASI will be a follow-up change as it requires more infrastructure. Notably, we also need non-TinyGo tests because TinyGo doesn't yet support os.Chtimes or corresponding syscalls.
> renames writefs to syscallfs and implements utimes in gojs

- RATIONALE.md
- internal/sys/file_table.go
- internal/sys/file_table_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
As discussed on Slack, this PR brings the file table from https://github.com/achille-roussel/wazero/tree/experimental/sys into upstream Wazero.
I added the data structure as `internal/sys.FileTable`, and I made it a generic type despite the single use in `FSContext` in anticipation that:
- I'm going to bring these changes in https://github.com/achille-roussel/wazero/tree/experimental/sys
- we may have to change the key or value type as we work towards full support of writefs
- we may have multiple instances of it for wasi and gojs (and maybe more with wasi2)
If these assumption turn out not to be true we can revisit and 1) unexport the type and 2) drop the generic type parameters.
Please take a look and let me know if anything needs to be changed!
> add internal/sys.FileTable

- experimental/compilation_cache.go
- experimental/compilation_cache_test.go
- internal/compilationcache/file_cache.go
- internal/compilationcache/file_cache_test.go
- internal/version/version.go
This makes the version, arch, os tuple into a subdirectory to help troubleshooting and cache management in general. The version is left inside the binary key regardless.
Note: when installing via `go install ./cmd/wazero/...` the version ends up as `dev`. This helps make that obvious. For example.
```bash
$ wazero version
dev
$ ./build/tinygo test -target wasi -c -o os.wasm os
$ wazero run -cachedir=$HOME/.wazero -mount=.:/ -env=HOME=.  os.wasm -test.v
$ find $HOME/.wazero
/Users/adrian/.wazero
/Users/adrian/.wazero/wazero-dev-amd64-darwin
/Users/adrian/.wazero/wazero-dev-amd64-darwin/1f149f4bf475a33023ce33302780bee29ec08e89bd57cfbdf639c65c6009f1a4
```
See #977
> compilationcache: uses version-specific subdirectory

- imports/go/gojs.go
- internal/gojs/compiler_test.go
- internal/gojs/custom/names.go
- internal/gojs/goarch/wasm.go
- internal/gojs/misc_test.go
- internal/gojs/run/gojs.go
- internal/gojs/runtime.go
- internal/gojs/state.go
- internal/gojs/syscall.go
- internal/gojs/testdata/stdio/main.go
This implements functionality needed for #980. When run with interpreter, `Test_stdio_large` triggers timeout events.
However, interpreter is currently too slow to run large wasm in CI. If the interpreter ever becomes fast, we could consider running it. However, performance of the interpreter is currently not a priority.
> gojs: implements timeout events

- internal/engine/compiler/engine_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/interpreter/interpreter_test.go
- internal/gojs/misc_test.go
- internal/testing/enginetest/enginetest.go
fixes https://github.com/tetratelabs/wazero/issues/978 and supersedes #980 
> compiler: force moduleContext initialization after Go function calls

- api/wasm.go
- internal/integration_test/spectest/spectest.go
- internal/wasm/call_context.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store_test.go
- runtime_test.go
This adds ExportedFunctionDefinitions and ExportedMemoryDefinitions to api.Module so that those who can't access CompileModule can see them.
Fixes #839
> Adds ExportedFunctionDefinitions and ExportedMemoryDefinitions

- cmd/wazero/wazero.go
- experimental/writefs/writefs.go
- experimental/writefs/writefs_example_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/fs_test.go
- internal/sys/fs.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/syscallfs.go
As noted in slack, we are unlikley to long term use fs.FS internally. This ensures we attempt to cast to syscallfs.FS for all I/O by panicing on fs.Open.
> Removes internal dependency on fs.FS

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/custom/fs.go
- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/sys/fs.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/syscall.go
- internal/syscallfs/syscall_windows.go
- internal/syscallfs/syscallfs.go
This implements rename, which is the last function needed to pass TinyGo os package tests:
```bash
$ wazero run  -mount=.:/ os.wasm -test.v
=== RUN   TestExpand
--- PASS: TestExpand (0.00s)
=== RUN   TestConsistentEnviron
--- PASS: TestConsistentEnviron (0.00s)
=== RUN   TestUnsetenv
--- PASS: TestUnsetenv (0.00s)
=== RUN   TestClearenv
--- PASS: TestClearenv (0.00s)
=== RUN   TestLookupEnv
--- PASS: TestLookupEnv (0.00s)
=== RUN   TestEnvironConsistency
--- PASS: TestEnvironConsistency (0.00s)
=== RUN   TestSetenvUnixEinval
--- PASS: TestSetenvUnixEinval (0.00s)
=== RUN   TestExpandEnvShellSpecialVar
--- PASS: TestExpandEnvShellSpecialVar (0.00s)
=== RUN   TestTempDir
--- PASS: TestTempDir (0.00s)
=== RUN   TestChdir
--- PASS: TestChdir (0.00s)
=== RUN   TestStandardFd
--- PASS: …
```
> Implements rename in GOOS=js and WASI

- Makefile
- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/fs.go
- internal/platform/stat.go
- internal/platform/stat_bsd.go
- internal/platform/stat_linux.go
- internal/platform/stat_test.go
- internal/platform/stat_unsupported.go
- internal/platform/stat_windows.go
- internal/sys/fs.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/syscallfs.go
Trivy builds with linux_386, so this adds a check to ensure we cover 386 arch even if it may or may not work in interpreter (definitely not in compiler)
See https://github.com/aquasecurity/trivy/pull/3355
> Ensures 32-bit platforms build

- site/content/languages/go.md
Go's tests are configured to require reading of files like /etc/passwd, which was surprising to me.
> site: Adds notes about how GOARCH=js GOOS=wasm tests work

- imports/wasi_snapshot_preview1/fs_test.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/readfs.go
- internal/syscallfs/readfs_test.go
- internal/syscallfs/syscallfs.go
- internal/syscallfs/syscallfs_test.go
This masks interfaces returned by `fs.File` so that we don't accidentally allow writes when opened for reading. This also adds `syscall.NewReadFS` which can enforce read-only access in general, such as would be ideal for tests that try to read files from the host root filesystem (e.g. /etc/passwd).
Note: this is intentionally not exposed as `experimental` yet. We should wait until user request, or the end of the month before deciding which surviving apis to expose.
> Ensures writes aren't allowed when opening for read

- cmd/wazero/wazero_test.go
- internal/gojs/builtin.go
- internal/gojs/crypto.go
- internal/gojs/custom/fs.go
- internal/gojs/fs.go
- internal/gojs/http.go
- internal/gojs/js.go
- internal/gojs/logging/logging.go
- internal/gojs/syscall.go
- internal/gojs/time.go
- internal/sys/fs.go
This stubs all remaining syscalls for `GOARCH=wasm GOOS=js` to return ENOSYS, instead of panic'ing. This allows us to see the parameters it receives.
For example:
```
==> go.syscall/js.valueCall(fs.truncate(path=/tmp/_Go_TestTruncate135754730,length=0))
<== (err=function not implemented,ok=false)
```
> gojs: stubs all remaining filesystem calls to ENOSYS

- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
improves instantiation perf:
```
Initialization/interpreter-10             34.2µs ± 5%    29.6µs ± 1%  -13.65%  (p=0.000 n=10+8)
Initialization/interpreter-multiple-10    13.7µs ± 3%    12.9µs ± 4%   -6.00%  (p=0.000 n=9+9)
Initialization/interpreter-10              140kB ± 0%     138kB ± 0%   -1.62%  (p=0.000 n=10+10)
Initialization/interpreter-multiple-10     141kB ± 0%     138kB ± 0%   -1.61%  (p=0.000 n=9+9)
name                                    old allocs/op  new allocs/op  delta
Initialization/interpreter-10               93.0 ± 0%      52.0 ± 0%  -44.09%  (p=0.000 n=10+10) …
```
> interpreter: removes unneeded fields from func instances

- imports/assemblyscript/assemblyscript.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/gojs/compiler_test.go
- internal/gojs/fs.go
- internal/gojs/runtime.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- internal/syscallfs/adapter.go
- internal/syscallfs/adapter_test.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/empty.go
- internal/syscallfs/readfs.go
- internal/syscallfs/syscallfs.go
- internal/wasm/call_context_test.go
This consolidates internal code to syscallfs, which removes the fs.FS specific path rules, except when adapting one to syscallfs. For example, this allows the underlying filesystem to decide if relative paths are supported or not, as well any EINVAL related concerns.
> Consolidates internal code to syscallfs

- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/builtin.go
- internal/gojs/fs.go
- internal/gojs/goos/goos.go
- internal/gojs/http.go
- internal/gojs/logging/logging.go
- internal/gojs/state.go
- internal/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging.go
This avoids logging activity on stdio file descriptors, in order to help make troubleshooting easier. Usually, there isn't an issue in these, yet wasm panics are harder to read if there is also logging of the .. logging.
> logging: avoids logging activity to stdio file descriptors

- Makefile
Developers don't commonly think about 32-bit platforms and in one instance we broke a release due to this (quickly fixed in pre.7). This ensures arm and 386, used by dapr and trivy respectively are tested. It also helps prove these are in use to avoid a later developer removing support by thinking they aren't.
Don't read into these results, as they are new releases. This is just an example that shows the output of the commands:
```bash
$ gh release view -R aquasecurity/trivy --json assets --jq 'first(.assets[] | select(.name| test("Linux-32bit.*tar.gz")) | {url, downloadCount})'
{"downloadCount":1,"url":"https://github.com/aquasecurity/trivy/releases/download/v0.36.0/trivy_0.36.0_Linux-32bit.tar.gz"
$ gh release view -R dapr/dapr --json assets --jq 'first(.assets[] | select(.name = …
```
> Adds checks into the Makefile for 32-bit platforms

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/gojs/fs.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
- internal/syscallfs/adapter.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/empty.go
- internal/syscallfs/readfs.go
- internal/syscallfs/syscallfs.go
This adds FS.Path which holds the pre-open path currently only used in WASI. It also fixes a TODO where we didn't know for sure if the FD parameter for `path_` functions must always be a pre-open. The TL;DR; is that usually it is, but it may not be (e.g. in our zig-cc example we can see any directory FD, not just pre-opens).
Finally, this fixes a bug in our path resolution where we mistook paths like "foo/foo" for "foo" because we only considered basenames instead of the full path from the pre-open root.
This also makes pre-open directory lookup lazy because I noticed in Trivy specifically, this is unnecessary for us to do eagerly, as they change the FS at runtime per-call. In other words, any value from init time is invalid later.
> Clarifies at semantics and preopen semantics in WASI

- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/impl_arm64.go
Fixes #1008 
```
$ uname -m
arm64
$ go install ./cmd/wazero
$ echo "\q" | wazero run ./internal/integration_test/engine/testdata/qjs.wasm
QuickJS - Type "\h" for help
qjs > \q
```
> arm64: fixes runtimeValueType for i32.wrap_i64

- internal/engine/compiler/engine.go
> compiler: deletes function.stackPointerCeil to reduce memory size per instance 

- internal/syscallfs/adapter.go
- internal/syscallfs/adapter_test.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/readfs.go
- internal/syscallfs/readfs_test.go
- internal/syscallfs/syscall.go
- internal/syscallfs/syscall_windows.go
- internal/syscallfs/syscallfs.go
- internal/syscallfs/syscallfs_test.go
This ensures those who cannot use `writefs.DirFS` can use a `fs.FS` implementation that creates or opens files as read/write. This does so by making a hacked fs.FS and testing it.
```go
type hackFS string
func (dir hackFS) Open(name string) (fs.File, error) {
path := ensureTrailingPathSeparator(string(dir)) + name
if f, err := os.OpenFile(path, os.O_RDWR, 0); err == nil {
return f, nil
} else if errors.Is(err, syscall.EISDIR) {
return os.OpenFile(path, os.O_RDONLY, 0)
} else {
return nil, err
}
}
```
This also removes type filtering to ensure hacked filesystems aren't accidentally masked. Instead we get more specific on error codes returned by functions such as `os.File.Write`.
---
Note: This is meant to extend the life of fs.FS for custom implementations, though we expect eventually to …
> fs: Adds tests to prove we allow fs.FS to create new files

- internal/syscallfs/readfs.go
- internal/syscallfs/syscallfs_test.go
@achille-roussel mentioned on chat that we have an accident waiting to happen. This fixes it and backfills the missing test.
> fs: fixes timebomb on or'd flags with O_RDONLY

- config_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/fstest/fstest.go
- internal/syscallfs/adapter_test.go
- internal/syscallfs/dirfs.go
- internal/syscallfs/dirfs_test.go
- internal/syscallfs/readfs_test.go
- internal/syscallfs/syscallfs_test.go
- internal/wasi_snapshot_preview1/logging/logging.go
This works around a known glitch in windows where directory entry stat doesn't match its corresponding file stat (namely times don't). It consolidates more test files, in the process, to ensure we are more likely to trigger issues like this earlier.
Future work will finish the last couple places where we still use go's fstest.MapFS internally, as well introduce stat tests at the syscallfs abstraction: right now, most tests are still only defined in WASI.
> fs: fixes windows fstest.FS and consolidates more

- README.md
- site/content/_index.md
This slips our 1.0 date a month while we try to get through implementation issues around filesystems and various bugs.
While not mentioned in the README, we will move our internal syscallfs to an experimental package so that people who are ok with drift can implement it while we try to target it for a 1.x release ideally by June. Meanwhile, our next pre-release will harden the permanent APIs around implementing filesystems with existing directories or go's `fs.FS` implementation.
> Adjust the timeframe for 1.0 from late Feb to late March

- .github/workflows/commit.yaml
The `cargo-fuzz` binary is included in the cache, so no need to re-execute `cargo install`.
This avoids nasty long timeouts related to the cargo index regardless of the actual installation. 
> ci: skip cargo install cargo-fuzz if cache hit

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
This fixes #1027.
WASI-libc prestats every fd from 3 until one returns EBADF. If any other error is returned, the process exits with code 71 (EX_OSERR).
> fs: fd_prestat_get return EBADF for not pre-opened

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/syscallfs/syscall_windows.go
- internal/syscallfs/syscallfs.go
- internal/syscallfs/syscallfs_test.go
- site/content/specs.md
This implements WriterAtOffset, which supports WASI `fd_pwrite` and gojs `fs.write` with offset, which is used to implement `syscall.Pwrite`. I confirmed this passes the corresponding test in wasi-testsuite as well.
Dependent on #1037
> fs: implements WriterAtOffset for WASI and gojs

- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/fs.go
- internal/gojs/fs_test.go
- internal/gojs/testdata/writefs/main.go
- internal/gojs/testdata/writefs/times.go
- internal/gojs/testdata/writefs/times_js.go
- internal/platform/stat.go
- internal/platform/stat_bsd.go
- internal/platform/stat_linux.go
- internal/platform/stat_test.go
- internal/platform/stat_unsupported.go
- internal/platform/stat_windows.go
This implements stat device and inode for WASI and GOOS=js, though it does not implement the host side for windows, yet. Doing windows requires plumbing as the values needed aren't exposed in Go. When we re-do the syscallfs file type to have a stat method, we can address that glitch. Meanwhile, I can find no Go sourcebase that does any better, though the closest is the implementation details of os.SameFile.
I verified this with wasi-testsuite which now passes all but 1 case which is unrelated (we haven't yet implemented `fd_tell`).
```bash
$ python3 test-runner/wasi_test_runner.py -t ./tests/assemblyscript/testsuite/  ./tests/c/testsuite/ -r adapters/wazero.sh
Test environ_get-multiple-variables passed
Test fd_write-to-invalid-fd passed
Test environ_sizes_get-multiple-variables passed …
```
> Implements stat device/inode on WASI and GOOS=js

- cmd/wazero/wazero_test.go
- internal/syscallfs/rootfs.go
- internal/syscallfs/rootfs_test.go
This adds syntax needed for wasi-testsuite, which mounts a path like below without mounting anything for "/".
```
-mount=./tests/c/testsuite/fs-tests.dir:/fs-tests.dir
```
Basically, this creates a virtual root path with fake stat.
With this in, https://github.com/WebAssembly/wasi-testsuite/compare/prod/testsuite-base...codefromthecrypt:wazero?expand=1 passes 100pct cc @achille-roussel 
```bash
$ python3 test-runner/wasi_test_runner.py -t ./tests/assemblyscript/testsuite/  ./tests/c/testsuite/ -r adapters/wazero.sh
Test environ_get-multiple-variables passed
Test fd_write-to-invalid-fd passed
Test environ_sizes_get-multiple-variables passed
Test args_sizes_get-no-arguments passed
Test proc_exit-success passed
Test proc_exit-failure passed
Test args_get-multiple-arguments passed
Test …
```
> fs: allows non-root only mounts

- .github/workflows/integration.yaml
The helps ensure folks running tests also on their workstations are actually running the same tests.
> Makes tinygo tests run in verbose mode

- cmd/wazero/wazero.go
- experimental/writefs/writefs.go
- experimental/writefs/writefs_example_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/gojs/fs_test.go
- internal/sys/fs_test.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- internal/sysfs/adapter.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
- internal/sysfs/rootfs.go
- internal/sysfs/rootfs_test.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/sysfs/unsupported.go
This decouples sysfs.FS from fs.FS by introducing a temporary type FSHolder, which will be removed when we top-level FSConfig (shortly).
This further reduces complexity by consolidating guest path configuration into the only type that uses it: CompositeFS.
The next PR will add FSConfig and be a lot smaller due to extracting this stuff now.
> fs: decouples sysfs from fs.FS and consolidates guest path logic

- Makefile
- internal/integration_test/fuzz/fuzz/Cargo.toml
- internal/integration_test/fuzz/fuzz/fuzz_targets/memory_no_diff.rs
- internal/integration_test/fuzz/fuzz/fuzz_targets/validation.rs
- internal/integration_test/fuzz/fuzz/fuzz_targets/wazero_abi.rs
- internal/integration_test/fuzz/wazerolib/nodiff.go
- internal/integration_test/fuzz/wazerolib/nodiff_test.go
> fuzz: adds target on checking memory state

- .github/workflows/integration.yaml
Checkout `wasi-testsuite` from `tetratelabs/wasi-testsuite@wazero` branch then launch the tests using the wazero adapter. 
It looks fast enough it could run at each PR.
- Windows looks broken, but I think it may be an issue with `-mount` syntax (Windows paths may contain `:`) . I disabled it for now.
> gha: add wasi-testsuite

- internal/sysfs/rootfs.go
- internal/sysfs/rootfs_test.go
This changes the logic inside CompositeFS in preparation of re-using the user-provided input paths for pre-open paths. The main change here is retaining original insertion order until runtime, then just iterating backwards then.
> fs: retains original FS paths

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/assemblyscript/assemblyscript_test.go
- internal/gojs/crypto_test.go
- internal/gojs/logging/logging.go
- internal/gojs/logging/logging_test.go
- internal/logging/logging.go
- internal/logging/logging_test.go
- internal/wasi_snapshot_preview1/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging_test.go
This is to avoid a collision with an emerging wasi-crypto. They will have both wasi-random and wasi-crypto
> logging: rename crypto scope to random

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/wasi_snapshot_preview1/clock_test.go
- internal/gojs/crypto_test.go
- internal/gojs/custom/date.go
- internal/gojs/custom/names.go
- internal/gojs/logging/logging.go
- internal/gojs/time.go
- internal/gojs/time_test.go
- internal/logging/logging.go
- internal/logging/logging_test.go
- internal/wasi_snapshot_preview1/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging_test.go
This allows you to specify the clock scope amongst existing logging scopes, both in API and the CLI.
e.g for the CLI.
```bash
$ wazero run --hostlogging=clock --hostlogging=filesystem --mount=.:/:ro cat.wasm
```
e.g. for Go
```go
loggingCtx := context.WithValue(testCtx, experimental.FunctionListenerFactoryKey{},
logging.NewHostLoggingListenerFactory(&log, logging.LogScopeClock|logging.LogScopeFilesystem))
```
> logging: adds clock scope

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- internal/gojs/logging/logging.go
- internal/gojs/misc_test.go
- internal/gojs/runtime.go
- internal/logging/logging.go
- internal/logging/logging_test.go
- internal/wasi_snapshot_preview1/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging_test.go
This allows you to specify the poll scope amongst existing logging scopes, both in API and the CLI.
e.g for the CLI.
```bash
$ wazero run --hostlogging=poll --hostlogging=filesystem --mount=.:/:ro cat.wasm
```
e.g. for Go
```go
loggingCtx := context.WithValue(testCtx, experimental.FunctionListenerFactoryKey{},
logging.NewHostLoggingListenerFactory(&log, logging.LogScopePoll|logging.LogScopeFilesystem))
```
This is particularly helpful to understand side-effects of GC. For example, in `GOOS=js` GC will trigger events and these have been tricky to troubleshoot in the past.
> logging: adds poll scope

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/assemblyscript/assemblyscript.go
- imports/assemblyscript/assemblyscript_test.go
- internal/assemblyscript/logging/logging.go
- internal/assemblyscript/logging/logging_test.go
- internal/assemblyscript/names.go
- internal/gojs/logging/logging.go
- internal/gojs/logging/logging_test.go
- internal/gojs/misc_test.go
- internal/gojs/runtime.go
- internal/gojs/testdata/main.go
- internal/logging/logging.go
- internal/logging/logging_test.go
- internal/wasi_snapshot_preview1/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging_test.go
This allows you to specify the exit scope amongst existing logging scopes, both in API and the CLI.
e.g for the CLI.
```bash
$ wazero run --hostlogging=exit,filesystem --mount=.:/:ro cat.wasm
```
e.g. for Go
```go
loggingCtx := context.WithValue(testCtx, experimental.FunctionListenerFactoryKey{},
logging.NewHostLoggingListenerFactory(&log, logging.LogScopeExit|logging.LogScopeFilesystem))
```
This is helpful to know if the wasm called exit or if it exited implicitly. This is one of the few host functions that exists in three places: assemblyscript, gojs and wasi.
> logging: adds exit scope and fixes mtim bug

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/emscripten/emscripten_test.go
- internal/assemblyscript/logging/logging.go
- internal/gojs/logging/logging.go
- internal/gojs/logging/logging_test.go
- internal/gojs/misc_test.go
- internal/gojs/runtime.go
- internal/logging/logging.go
This allows you to specify the memory scope amongst existing logging scopes, both in API and the CLI.
e.g for the CLI.
```bash
$ wazero run --hostlogging=memory,filesystem --mount=.:/:ro cat.wasm
```
e.g. for Go
```go
loggingCtx := context.WithValue(testCtx, experimental.FunctionListenerFactoryKey{},
logging.NewHostLoggingListenerFactory(&log, logging.LogScopeMemory|logging.LogScopeFilesystem))
```
This is helpful for emscripten and gojs which have memory reset callbacks. This will be much more interesting once #1075 is implemented.
> logging: adds memory scope

- .github/workflows/examples.yaml
- .github/workflows/integration.yaml
- cmd/wazero/wazero_test.go
- imports/wasi_snapshot_preview1/example/cat_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
This allows wasi to see mounts as individual preopens instead of virtualized under a root. (GOOS=js doesn't use pre-opens so it still sees a virtual root). This allows us to progress wasi-testsuite rust tests, but acknowledges a current glitch in zig support, which is tracked separately as #1077
This feature is employed immediately to run the wasi-testsuite rust, which currently has 7 failures, many of which solved in #1057 https://github.com/tetratelabs/wazero/actions/runs/4041035227/jobs/6947216495
> cli,wasi: passes mounts directly as preopens to run rust wasi-testsuite

- site/content/specs.md
AssemblyScript no longer depends on wasi directly. Also, pretty much everything uses proc_exit
> site: fix wasi chart

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/wasi_snapshot_preview1/errno.go
See https://github.com/WebAssembly/wasi-testsuite/issues/50
> wasi: prohibits closing pre-opens

- internal/platform/open_file.go
- internal/platform/open_file_windows.go
- internal/platform/rename.go
- internal/platform/rename_test.go
- internal/platform/rename_windows.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/syscall.go
- internal/sysfs/sysfs.go
This handles edge cases on rename which were previously skipped in testing. Notably, there are delete flags not possible to propagate in current versions of go, which imply some copy/paste meanwhile.
> fs: handles windows edge cases on rename

- imports/wasi_snapshot_preview1/fs_test.go
- internal/sysfs/adapter.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/syscall.go
- internal/sysfs/syscall_windows.go
> wasi(windows): fixes readdir on written-after-opened directories 

- .github/workflows/commit.yaml
- internal/sysfs/dirfs.go
This fixes the race found on the current main branch.
> dirfs: use os.ReadLink instead of syscall variant

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/file_table.go
- internal/sys/fs.go
- internal/sys/fs_test.go
> wasi: implements fd_renumber

- .github/workflows/commit.yaml
- internal/integration_test/vs/wasmedge/go.mod
- internal/integration_test/vs/wasmedge/go.sum
- internal/integration_test/vs/wasmtime/go.mod
- internal/integration_test/vs/wasmtime/go.sum
- internal/integration_test/vs/wasmtime/wasmtime.go
I tried to run wasmedge locally as they publish arm64 os/x now, but it fails like below even sourcing their env. I left that alone for now
```
dyld[88003]: Library not loaded: @rpath/libwasmedge.0.dylib
Referenced from: <B1821F61-C84A-38EE-BC33-F3DFB1837BEB> /private/var/folders/vd/1cf8zdb1721f4z5rjggy8bp40000gn/T/go-build1872793839/b001/wasmedge.test
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libwasmedge.0.dylib' (no such file), '/usr/local/lib/libwasmedge.0.dylib' (no such file), '/usr/lib/libwasmedge.0.dylib' (no such file, not in dyld cache)
signal: abort trap
FAIL	github.com/tetratelabs/wazero/internal/integration_test/vs/wasmedge	0.240s
FAIL
```
> benchmark: bumps vs tests wasmtime and wasmedge to latest

- .github/workflows/integration.yaml
- .github/workflows/wasi_test_runner-skip.json
- RATIONALE.md
The current fd_readdir test is invalid as it requires dot and dot-dot entries, which both aren't required by POSIX nor returned by go. Once this is addressed upstream, we can remove the skip.
See https://github.com/WebAssembly/wasi-testsuite/issues/52
See #1036
> wasi: skips fd_readdir until fixed upstream

- cmd/wazero/Dockerfile
- cmd/wazero/README.md
It is important for understanding the recent trends in Docker and WebAssembly to see what a Dockerfile looks like in wazero right now. By seeing what they are now, it is easier to understand what's different.
For example, things that natively support wasm right now can take off the 4.5MB our binary costs, as well hide some of the configuration you can see, such as coercing arguments or ENV.
That said, wasm isn't quite prime time in Docker, I suspect some will be happy to see what things look like. This will get even easier in March when we release 1.0, as we'll have formal packages and such.
> cli: adds an example Dockerfile

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/wasi_snapshot_preview1/fs.go
part of #1036. `fd_advise.rs` is still failing due to the unimplemented `fd_allocate`. https://github.com/WebAssembly/wasi-testsuite/blob/main/tests/rust/src/bin/fd_advise.rs#L44-L50
> wasi: makes fd_advise noop, instead of NoSys

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
Part of #1036. With this, only two cases are left to pass 
> Test suites: 1 failed, 0 total
Tests:       2 failed, 8 passed, 1 skipped, 1 total
> wasi: implements filestatset

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
part of #1036. With this only one case left:
> Test suites: 1 failed, 0 total
Tests:       1 failed, 9 passed, 1 skipped, 1 total
> wasi: implements fd_allocate

- .github/workflows/commit.yaml
- .github/workflows/spectest.yaml
- Makefile
- cmd/wazero/wazero_test.go
- go.mod
- imports/go/example/stars/go.mod
- internal/engine/compiler/engine.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/gojs/crypto_test.go
- internal/gojs/syscall_test.go
- internal/gojs/testdata/syscall/main.go
- internal/gojs/time_test.go
- internal/integration_test/vs/time/go.mod
- internal/integration_test/vs/wasmedge/go.mod
- internal/integration_test/vs/wasmer/go.mod
- internal/integration_test/vs/wasmtime/go.mod
- internal/sys/fs.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/syscall_windows.go
- internal/version/testdata/go.mod
- netlify.toml
This moves our floor version to the same we'll release 1.0 with: 1.18. This is congruent with our version policy which is current-2.
Fixes #921
> ci: supports building with Go 1.20 and raises floor version to 1.18

- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/errno_test.go
This also re-organizes the error conversion logic so it is easier to compare what's covered.
> wasi: backfills errno conversion tests

- cmd/wazero/wazero.go
Background: I wanted to evaluate the interpreter like: https://github.com/yamt/toywasm/blob/5b7f8a870a2b8a7600330f0421b14bf01e2249d8/benchmark/ffmpeg.sh#L58-L61
But I couldn't find a convenient way.
Signed-off-by: YAMAMOTO Takashi <imuwoto@gmail.com>
> cli: add an option to force interpreter

- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/errno.go
- internal/gojs/errno_test.go
- internal/platform/open_file_test.go
- internal/platform/open_file_windows.go
- internal/platform/stat_windows.go
- internal/sys/fs.go
- internal/sysfs/adapter.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/syscall.go
- internal/sysfs/syscall_windows.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/errno_test.go
This consolidates the sharable code around syscall.Errno conversion from wasi and gojs and backfills test for the consolidated part.
This also unwraps os.SyscallErr and handles EAGAIN and EINTR.
> sysfs: consolidates errno coersion and maps EAGAIN and EINTR

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
non-shortcut flags should be complete words or abbreviations, not truncated words.
> cli: renames interp flag to interpreter

- cmd/wazero/Dockerfile
- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
This adds an `env-inherit` boolean flag which adds all variables to the guest ENV.
For example, the below `env-reader.wasm` guest will see the variable `STAR` and anything set via the runner (docker, podman, etc.):
```
--snip--
FROM scratch
COPY --from=build /build/wazero/wazero /bin/wazero
ENTRYPOINT ["/bin/wazero", "run", "-env-inherit", "-cachedir=/cache", "-mount=.:/"]
ENV STAR=wazero
COPY --from=wasm / .
CMD ["env-reader.wasm"]
```
Note: This isn't appropriate otherwise as it will also propagate variables like PATH and TMPDIR which aren't likely valid on the guest, or in worst case may risk crashing.
> cli: adds env-inherit flag for SCRATCH images

- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/platform/cpuid_amd64.go
- internal/platform/cpuid_amd64.s
- internal/platform/cpuid_amd64_test.go
fixes #1111, adds setup for fixing #580 
While I haven't tested this on a proper x86 machine (but I do have a dusty core duo laptop which may really be the thing I need, if I manage to turn it on :D) I have sketched a solution by putting together everyone's feedback (including @ncruces' 🚀). In the meantime I have also discovered that `GOARCH=amd64` has the ABM feature flag off on Rosetta2.
- this is in a new `cupid_amd64.{s,go}` because I felt it would pollute too much `impl` and `arch` didn't feel like the right place (that's for runtime)
- For now I have only added the constants that we use and/or plan to use (e.g. SSE3, 4.1, 4.2), and only the related bitmaps
- you still have to carefully pick the right set of flags because there is no proper type checking in place (all are uint64). …
> add support for querying cpuid

- internal/platform/platform.go
- internal/platform/platform_amd64.go
- internal/platform/platform_arm64.go
I am not sure whether we should also add some test case to exercise this code path. Maybe enabling emulated tests as suggested in #581? Even my old Window laptop is newer and passes :D
Fixes #580
> compiler(amd64): return false on SSE4 unsupported CPUs

- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/wasm/call_context.go
- internal/wasm/call_context_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
This is a regression introduced in #1108 and hasn't been well covered in the unit tests with -race.
Thanks to @ckaznocha for reporting this!
> Fixes races around {api.Module, wazero.Runtime}.CloseWithExitCode

- cmd/wazero/wazero_test.go
TestRun clears the environment, which means the os specific temporary directory is also cleared; which then either creates the directory to the wrong place or it doesn't have any access to create the directory altogether.
Move the temporary directory creation before clearing the environment variables.
Signed-off-by: Egon Elbre <egonelbre@gmail.com>
> cmd/wazero: fix temp dir handling in TestRun

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/platform/stat_windows.go
- internal/platform/sync.go
- internal/platform/sync_linux.go
- internal/platform/sync_test.go
- internal/platform/sync_unsupported.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- site/content/specs.md
This implements `fd_datasync` in WASI, falling back to normal `File.Sync` when unsupported. This also backfills missing usage of sync in GOOS=js. Finally, this updates the WASI status chart based on what's implemented.
> Implements fd_datasync in WASI and sync in GOOS=js

- internal/platform/open_file_test.go
- internal/platform/open_file_windows.go
> platform: adjusts errno on dangling symlink on Windows

- RATIONALE.md
- config.go
- config_test.go
- imports/wasi_snapshot_preview1/sched.go
- imports/wasi_snapshot_preview1/sched_test.go
- internal/platform/time.go
- internal/sys/sys.go
- internal/sys/sys_test.go
- site/content/specs.md
- sys/clock.go
This implements WASI `sched_yield` with `sys.Osyield` that defaults to return immediately. This is intentionally left without a built-in alternative as common platforms such as darwin implement `runtime.osyield` by sleeping for a microsecond. If we implemented that, user code would be slowed down without a clear reason why.
Thanks @achille-roussel and @ckaznocha for the brainstorm
> wasi: implements sched_yield with sys.Osyield

- internal/gojs/errno.go
- internal/gojs/errno_test.go
- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/readfs_test.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/sysfs/unsupported.go
- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/errno_test.go
This adds `FS.Chmod` and implements it for `GOOS=js`. This function isn't defined in WASI snapshot01, but it is in [wasi-filesystem](https://github.com/WebAssembly/wasi-filesystem), e.g. [change-file-permissions-at](https://github.com/WebAssembly/wasi-filesystem/blob/main/wasi-filesystem.md#-change-file-permissions-at).
> sysfs: adds chmod

- internal/wasm/func_validation.go
Avoids allocating `bytes.Reader` a lot, but instead use the one `bytes.Reader` at the top.
The following is the bench result for gojs binary.
```
_compile-10     1.12s ± 4%     1.10s ± 3%  -1.67%  (p=0.005 n=20+20)
_compile-10     672MB ± 0%     665MB ± 0%  -1.07%  (p=0.000 n=18+19)
_compile-10     13.5M ± 0%     13.3M ± 0%  -1.11%  (p=0.000 n=19+20)
name          old time/op    new time/op    delta
_validate-10    56.9ms ± 2%    52.6ms ± 2%   -7.60%  (p=0.000 n=19+20)
name          old alloc/op   new alloc/op   delta
_validate-10    36.1MB ± 0%    28.9MB ± 0%  -19.94%  (p=0.000 n=16+19)
name          old allocs/op  new allocs/op  delta …
```
> Reduces allocations in func validation

- runtime.go
If I'm not wrong, with current `Magic` validation in `runtime.CompileModule` never reach this code
https://github.com/tetratelabs/wazero/blob/e2ebce5d230eceff7d89e4d8677a166dd9ebabca/internal/wasm/binary/decoder.go#L29-L31
and will always send `errors.New("invalid binary")` in case of incorrect Magic in wasm .
> Removes redundant Magic validation in runtime

- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/interpreter/interpreter.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
- internal/wazeroir/format.go
- internal/wazeroir/operations.go
The following is the bench result: 
```
_compile-10     1.37s ± 3%     1.35s ± 3%  -1.02%  (p=0.001 n=17+18)
_compile-10     652MB ± 0%     646MB ± 0%  -0.98%  (p=0.000 n=19+19)
_compile-10     11.5M ± 0%     10.7M ± 0%  -6.88%  (p=0.000 n=19+20)
```
> wazeroir: less allocations with Labels

- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/interpreter/interpreter.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
- internal/wazeroir/operations.go
what a low-hanging fruit! 
```
_compile-10     1.04s ± 2%     0.93s ± 2%  -10.52%  (p=0.000 n=18+19)
_compile-10     646MB ± 0%     609MB ± 0%   -5.67%  (p=0.000 n=18+20)
_compile-10     10.7M ± 0%      9.4M ± 0%  -12.59%  (p=0.000 n=20+20)
```
> wazeroir: uses u64 as unique keys for labels

- internal/wazeroir/compiler.go
- internal/wazeroir/signature.go
- internal/wazeroir/signature_test.go
```
_compile-10     897ms ± 2%     891ms ± 1%  -0.66%  (p=0.000 n=43+49)
_compile-10     599MB ± 0%     597MB ± 0%  -0.47%  (p=0.000 n=50+50)
_compile-10     7.53M ± 0%     7.40M ± 0%  -1.70%  (p=0.000 n=50+49)
```
> wazeroir: removes allocations in wasmOpcodeSignature asymptotically

- internal/platform/open_file_js.go
- internal/platform/stat.go
- internal/platform/stat_bsd.go
- internal/platform/stat_linux.go
- internal/platform/stat_unsupported.go
- internal/platform/stat_windows.go
This ensures only windows needs to open a file in order to do a stat. Maybe one day it can also avoid that, but meanwhile darwin and linux should be faster.
```
goos: darwin
goarch: arm64
│    sec/op    │    sec/op     vs base              │
_pathFilestat/embed.FS_fd=root-12        1.399µ ± ∞ ¹   1.388µ ± ∞ ¹       ~ (p=1.000 n=5)
_pathFilestat/embed.FS_fd=directory-12   1.448µ ± ∞ ¹   1.405µ ± ∞ ¹  -2.97% (p=0.008 n=5)
_pathFilestat/os.DirFS_fd=root-12        9.017µ ± ∞ ¹   8.886µ ± ∞ ¹       ~ (p=0.151 n=5)
_pathFilestat/os.DirFS_fd=directory-12   9.338µ ± ∞ ¹   9.375µ ± ∞ ¹       ~ (p=0.548 n=5)
geomean                                  3.614µ         3.570µ …
```
> optimizes non-windows stat to avoid opening a file

- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/fs.go
- internal/platform/dir.go
- internal/platform/dir_test.go
- internal/platform/stat.go
- internal/platform/stat_test.go
- internal/sysfs/rootfs_test.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
This adds `platform.Readdirnames` which is preparation work before doing something similar for reading the directory. We use this in gojs as it doesn't actually need dirents, rather just names.
> adds platform.Readdirnames and uses in gojs

- .github/workflows/integration.yaml
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/sys/fs.go
This manually adds dot and dot-dot directory entries discarded by compilers like Go. Doing so complies with the latest interpretation of wasi preview1 without forcing us to do the same in preview2 or in GOOS=js. There's a cost penalty of one stat per directory list, which will be only measurable when using real file I/O.
This should result in us being able to remove the exclusion here https://github.com/WebAssembly/wasi-testsuite/pull/55/files#diff-8a3ffd323d75a12f8deb01b053f062876d83dda0b89c1fa24b293cee4195bcfd
See https://github.com/WebAssembly/wasi-testsuite/issues/52
> wasi: manually adds dot and dot-dot directory entries

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- internal/platform/dir.go
- internal/platform/dir_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
wasi_snapshot_preview1 recently requires fd_readdir to return actual inode values. On zero, wasi-libc will call fdstat to retrieve them.
This introduces our own `platform.Dirent` type and `Readdir` function which a later change will allow fetching of inodes.
See https://github.com/WebAssembly/wasi-libc/pull/345
> wasi: adds platform.Dirent in preparation of inode fetching

- internal/wasm/call_context.go
- internal/wasm/call_context_test.go
If a context is canceled after a guest func call has returned it could cause the module to close in some cases. This change ensures that a delayed check of the context cancelation is ignored.
I've also reduced the cost of context cancelation a bit.
> Fix issue with a delayed check of the context cancelation

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/dir.go
- internal/platform/dir_test.go
- internal/sys/fs.go
- internal/sys/sys_test.go
- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/logging/logging.go
We formerly cached only the directory type, to avoid re-stat'ing the same directory many times. Since we are there, we can also cache the inode, which is strictly required by wasi and costly to fetch. Note: this only affects the directory: its contents still need a potential fan-out of stats which will be handled in another change.
```
goos: darwin
goarch: arm64
│    old.txt    │               new.txt                │
│    sec/op     │    sec/op     vs base                │
_fdReaddir/embed.FS-12                   1.607µ ± ∞ ¹   1.547µ ± ∞ ¹  -3.73% (p=0.032 n=5)
_fdReaddir/embed.FS_-_continued-12       1.119µ ± ∞ ¹   1.125µ ± ∞ ¹       ~ (p=0.690 n=5)
_fdReaddir/os.DirFS-12                  10.377µ ± ∞ ¹   9.777µ ± ∞ ¹ …
```
> wasi: shares more cached stat info to reduce impact of inode requirement

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/errno.go
- internal/gojs/errno_test.go
- internal/platform/dir.go
- internal/platform/dir_test.go
- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/errno_test.go
This handles EOF even if current and possibly future wasi don't have a way to propagate an EOF signal. This is mainly to match up with go semantics and ensure we don't have any error conditions (by adding tests).
> Readdir: handles io.EOF

- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/compiler_value_location.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
```
_compile-10     870ms ± 0%     863ms ± 1%  -0.79%  (p=0.000 n=18+20)
_compile-10     589MB ± 0%     565MB ± 0%  -4.03%  (p=0.000 n=20+19)
_compile-10     7.22M ± 0%     6.69M ± 0%  -7.24%  (p=0.000 n=20+19)
```
> compiler: pass runtimeValueLocationStack by values to reduce allocations

- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/platform/open_file_windows.go
- internal/platform/stat.go
- internal/platform/stat_bsd.go
- internal/platform/stat_linux.go
- internal/platform/stat_test.go
- internal/platform/stat_unsupported.go
- internal/platform/stat_windows.go
- internal/sys/sys_test.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/sysfs/unsupported.go
This implements platform.Lstat and uses it in GOOS=js. Notably, directory listings need to run lstat on their entries to get the correct inodes back. In GOOS=js, directories are a fan-out of names, then lstat.
This also fixes stat for inodes on directories. We were missing a test so we didn't know it was broken on windows. The approach used now is reliable on go 1.20, and we should suggest anyone using windows to compile with go 1.20.
> implements lstat and fixes inode stat on windows go 1.20

- site/content/community/users.md
This makes the headings mostly in order by tier, like libraries, then middleware before compiled binaries.
This also adds Trivy, which was one of the original end users of wazero!
cc @knqyf263 who I asked permission from.
> site: sorts headings by tier and adds trivy

- .github/workflows/release.yaml
- .github/workflows/release_notes.sh
- Makefile
The adds a job to create a GH release in response to the tag creation event.
This has been verified to work (I did in the private repo) both for rcN tag and real tags:
> ci: GH release job in response to tag creations

- .github/workflows/release.yaml
The CI fails if the secret key for the Windows certificate is not set.
We should fall back to the default value instead -- or, even better, for routine checks, we may _always_ use the default key.
I am submitting this patch, but feel free to close and resolve it in a better way, this is mostly to show where the issue is.
In particular, this would silently fall-back to the default key even when we want it to actually fail!
> ci: do not fail the Windows build if the certificate is missing

- config.go
- config_test.go
- fsconfig_test.go
- internal/sysfs/adapter.go
- internal/sysfs/adapter_test.go
In previous releases, passing a `nil` value as an FS config did not cause any error. However, in 1.0.0-rc.1 this leads
to the creation of an invalid `adapter{fs: nil}`, which eventually leads to a panic (nil):
(f *FileEntry) Stat(st *platform.Stat_t) =>
(r *lazyDir) file() =>
r.fs.OpenFile(".", os.O_RDONLY, 0)
with fs == nil
The backwards-compatible fix is to make Adapt() return UnimplementedFS.
However, we may want to consider returning an error somewhere, because configuring a nil FS may be unintended.
> Ensure `nil` is accepted as FS config

- .github/workflows/commit.yaml
- Makefile
It looks like $(subst from,to,text) works differently on BSD make
vs GNU make. The behavior we expected for
$(subst,$(space),$(comma),$(var))
is instead the behavior of `$(patsubst ...)` on GNU Make.
The alternative syntax `$(var: =,)` seems portable across the two
and shows the same behavior.
(tested on Fedora 37, closes #1171)
> build: fix issue with GNU make vs BSD make

- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
- internal/platform/chown.go
- internal/platform/chown_unix.go
- internal/platform/chown_unix_test.go
- internal/platform/chown_unsupported.go
- internal/platform/chown_windows.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_unix_test.go
- internal/sysfs/rootfs.go
- internal/sysfs/sysfs.go
- internal/sysfs/unsupported.go
This finishes the last remaining syscalls in `GOOS=js`. After this is merged, further bugs are easier to hunt down as we know ENOSYS is not expected on writeable file systems.
> gojs: implements chown

- .github/workflows/integration.yaml
- imports/wasi_snapshot_preview1/fs.go
- internal/gojs/fs.go
- internal/platform/utimes.go
- internal/platform/utimes_test.go
- internal/platform/utimes_unsupported.go
- internal/platform/utimes_windows.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/readfs_test.go
- internal/sysfs/rootfs.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/sysfs/unsupported.go
This implements `platform.UtimesFile` which is similar to futimes. Before, we were using path-based functionality even though the call site was for a file descriptor.
Note: right now, there's no obvious code in Go to invoke the `futimens` syscall. This means non-windows isn't implemented at nanos granularity, so ends up falling back to the path based option.
Finally, this removes tests for the seldom supported updates with negative epoch time. There's little impact to this as setting times on files before 1970 isn't a typical use case.
> wasi: implements platform.UtimesFile for fd_filestat_set_times

- internal/gojs/fs.go
- internal/gojs/logging/logging.go
- internal/gojs/testdata/writefs/main.go
Go has a test that forces us to handle Mkdir with zero as its permissions. In GOOS=js, the result of fs.mkdir is a file descriptor, and to open that, we can't use literally 0. Hence, to solve this we need to coerce 0 to 0500 in GOOS=js.
> gojs: ensures Mkdir(path, 0) works

- internal/engine/compiler/arch_arm64.s
- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/interpreter/interpreter.go
- internal/integration_test/engine/adhoc_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasmdebug/debug.go
- runtime_test.go
Fixes #1211 
Previously, host functions are getting `api.Module` for the "originating" module, which is the module for api.Function currently invoked, except that the api.Module is modified withMemory for the caller's memory instance, therefore there haven't been no problem. The only issues were the methods except `Memory()` of api.Module, and this commit fixes them.
> Pass correct api.Module to host functions

- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/wasm/call_context.go
- internal/wasm/call_context_test.go
Follow up on #1213. We no longer need withMemory.
> Deletes callContext.withMemory

- builder.go
- builder_test.go
- cache_test.go
- config.go
- internal/engine/compiler/engine_test.go
- internal/integration_test/spectest/spectest.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/call_context_test.go
- internal/wasm/global_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- runtime.go
- runtime_test.go
Previously we generated the typeIDs for function types unnecessarily at each instantiation time. 
TypeIDs are unique per Runtime/Store, and we don't need to create slice []FunctionTypeID for each instance.
When generating a typeID, we need to take a lock on store in order to keep uniqueness across
instances and this caused the lock contention on the instantiation heavy use-cases.
tldr is that this improves the concurrent instantiation performance!
```
$ benchstat main.txt new.txt
Initialization/interpreter-10             29.9µs ± 3%    29.6µs ± 1%     ~     (p=0.151 n=5+5)
Initialization/interpreter-multiple-10    17.1µs ± 7%    13.2µs ± 9%  -23.13%  (p=0.008 n=5+5)
Initialization/compiler-10                35.1µs …
```
> Generates typeIDs at compilation time

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/logging/log_listener.go
- imports/assemblyscript/assemblyscript_test.go
- internal/assemblyscript/logging/logging.go
- internal/assemblyscript/logging/logging_test.go
- internal/gojs/builtin.go
- internal/gojs/custom/names.go
- internal/gojs/custom/process.go
- internal/gojs/fs.go
- internal/gojs/logging/logging.go
- internal/gojs/logging/logging_test.go
- internal/gojs/misc_test.go
- internal/logging/logging.go
- internal/logging/logging_test.go
- internal/sysfs/rootfs.go
- internal/wasi_snapshot_preview1/logging/logging.go
- internal/wasi_snapshot_preview1/logging/logging_test.go
Many tests failed in gojs due to needing to be resolved against the CWD, which is atypically stored host side. This fixes that and renames the "exit" scope to "proc" so we can use it for other proc concerns besides exit.
This reduces known failures on GOOS=js from 23 to 14:
```bash
$ wazero run -mount=/usr/local/go/src/os:/:ro -mount=/tmp:/tmp -mount=/etc:/etc:ro -mount=/usr:/usr:ro -mount=/dev:/dev:ro os.wasm |grep '^--- FAIL'|wc -l
14
```
See #1222
> renames exit log scope to proc and resolves gojs files to cwd

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- internal/gojs/fs.go
- internal/gojs/fs_unit_test.go
This fixes a file type mapping bug running go's `TestDevNullFile` test via gojs.
See #1222
> Fixes file type mapping problem identified in /dev/null

- experimental/logging/log_listener_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/function_definition.go
- internal/wasm/function_definition_test.go
- internal/wasm/host.go
- internal/wasm/memory_definition.go
- internal/wasm/memory_definition_test.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- internal/wasm/store_test.go
- internal/wasm/table.go
- internal/wasm/table_test.go
- internal/wazeroir/compiler_test.go
- runtime.go
```
Initialization/interpreter-32             39.2µs ± 4%    38.9µs ± 5%    ~     (p=0.375 n=17+19)
Initialization/interpreter-multiple-32    38.5µs ± 7%    38.1µs ± 6%    ~     (p=0.247 n=19+20)
Initialization/compiler-32                30.4µs ± 4%    30.3µs ± 2%    ~     (p=0.095 n=17+20)
Initialization/compiler-multiple-32       25.6µs ± 5%    25.4µs ± 4%    ~     (p=0.341 n=20+20)
Compilation/with_extern_cache-32           206µs ± 1%     204µs ± 1%  -1.17%  (p=0.000 n=20+20)
Compilation/without_extern_cache-32       6.12ms ± 1%    6.14ms ± 1%    ~     (p=0.127 n=19+20)
Initialization/interpreter-32 …
```
> Holds memory/func defs, and validated elements as values in wasm.Module

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/gojs/gojs.go
- internal/gojs/compiler_test.go
- internal/gojs/fs.go
- internal/gojs/goos/goos.go
- internal/gojs/state.go
- internal/platform/open_file_test.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/dirfs_unix_test.go
- internal/sysfs/sysfs_test.go
When compiled to `GOOS=js`, wasm does not maintain the working directory: it is defined by the host. While not explicitly documented, [os.TestDirFSRootDir](https://github.com/golang/go/blob/master/src/os/os_test.go#L2841) in Go suggests the working directory must be valid to pass (literally the directory holding the file).
This adds an experimental CLI flag that gives the initial working directory. This is experimental because while GOOS=js uses this, current WASI compilers will not, as they maintain working directory in code managed by wasi-libc, or as a convention (e.g. in Zig).
It is not yet known if [wasi-cli](https://github.com/WebAssembly/wasi-cli) will maintain working directory externally or not.
After this change, our GOOS=js implementation is down to less than ten test failures. …
> gojs: introduces `--experimental-workdir` CLI arg

- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
Before, we created invalid directory paths when the host directory was "/", and now we don't!
This brings tests left failing on GOOS=js to 7
```bash
$ wazero run -mount=/:/ --experimental-workdir=$(go env GOROOT)/src/os os.wasm| grep '^--- FAIL'|wc -l
7
```
See #1222
> dirfs: corrects path joining bug when mounting root

- internal/gojs/fs.go
- internal/gojs/testdata/writefs/main.go
```
$ wazero run -mount=/:/ --experimental-workdir=$(go env GOROOT)/src/os os.wasm -test.run '^TestSymlink|^TestLongSymlink|^TestStatRelativeSymlink|^TestLongSymlink'
PASS
```
> gojs: fixes symlink

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
- experimental/gojs/gojs.go
- experimental/gojs/gojs_test.go
- internal/platform/path_test.go
This changes the experimental flag introduced yesterday to `-experimental-workdir-inherit=true`, to reduce edge cases needed to produce the same behavior as go's wasm test runner.
After this, we have the same failure count, though the latter is likely related to my machine:
```bash
$ wasm=$PWD/os.wasm; (cd $(go env GOROOT)/src/os; wazero run -mount=/:/ --experimental-workdir-inherit=true $wasm)
--- FAIL: TestMkdirAllAtSlash (0.00s)
path_test.go:111: MkdirAll "/_go_os_test/dir": mkdir /_go_os_test: I/O error, I/O error
--- FAIL: TestOpenFileLimit (0.01s)
rlimit_test.go:31: open rlimit.go: I/O error
FAIL
```
See https://github.com/golang/go/blob/master/misc/wasm/wasm_exec_node.js#L24
> cli: changes experimental workdir flag to inherit

- internal/gojs/errno.go
- internal/gojs/errno_test.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
- internal/sysfs/unsupported.go
- internal/wasi_snapshot_preview1/errno.go
- internal/wasi_snapshot_preview1/errno_test.go
This passes the last test in gojs (except on my darwin host and windows ;))
```bash
$ wasm=$PWD/os.wasm; (cd $(go env GOROOT)/src/os; wazero run -mount=/:/ --experimental-workdir-inherit=true $wasm)
--- FAIL: TestOpenFileLimit (0.01s)
rlimit_test.go:31: open rlimit.go: I/O error
FAIL
```
> sysfs: maps syscall.EROFS

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/gojs/fs.go
- internal/gojs/testdata/stdio/main.go
- internal/sys/fs.go
- internal/sys/fs_test.go
Found this problem while troubleshooting #1232 because fd zero == stdin, so a logic error can show up as a problem writing to stdin.
> returns EBADF when attempting to write to STDIN

- builder.go
- builder_test.go
- imports/assemblyscript/assemblyscript.go
- imports/assemblyscript/assemblyscript_test.go
- imports/emscripten/emscripten.go
- imports/emscripten/emscripten_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/proc_test.go
- imports/wasi_snapshot_preview1/sock_test.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/interpreter/interpreter.go
- internal/gojs/goarch/wasm.go
- internal/gojs/util/util.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/func_validation.go
- internal/wasm/gofunc.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/module.go
- internal/wasmdebug/debug.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
Since #1213, engines no longer can support the Wasm-body-implemented host functions,
which has been only used to stub out the unimplemented functions. 
Also, this reduces the complexity of the future development of engines.
> Removes usage of host functions with Wasm optocdes

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
This helps keep the CLI forward compatible and also reduces the amount of distraction reading help output.
> cli: removes experimental-workdir-inherit flag

- site/content/_index.md
the installer goes to ./bin by default
to do something else you need something like
`| bash -s -- -b /usr/local/bin`
> site: fixes example bug

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sysfs/adapter.go
- internal/sysfs/adapter_test.go
This PR adds support for passing lookup flags to `path_filestat_get`. The motivation came from the work on https://github.com/golang/go/issues/58141, especially implementing `syscall.Lstat`.
Without this change, an alternative implementation is possible using `path_open` + `fd_filestat_get` + `fd_close` because wazero allows passing stats, however, this fails on OSX because `LOOKUP_SYMLINK_FOLLOW` is translated to `O_NOFOLLOW` which causes `open` to fail with `ELOOP` because wazero doesn't set `O_SYMLINK` (I can follow up with a fix for that in a different PR).
I updates the tests to use the `LOOKUP_SYMLINK_FOLLOW` flag since that was the historical behavior being tested; however, I haven't found a paved path for testing with symbolic links. The tests use `fstest.FS` which ends up …
> path_filestat_get: interpret LOOKUP_SYMLINK_FOLLOW

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
Prior to this change, when reading directory entries, wazero would assume that all files are regular files except directories. This causes issues in client applications that work with symbolic links for example.
The issue was detected while working on passing the `testing/fstest` tests as part of the implementation of https://github.com/golang/go/issues/58141 because `fstest.TestFS` validates that the file type seen by `fs.DirEntry.Type()` and `fs.FileInfo.Mode().Type()` are the same.
Regarding testing this change, to reuse the existing test suite would likely require updating `internal/fstest.FS` to contain a symbolic link, but this fixture object is used in so many places that it may be difficult to land the fix. An alternative could be to make a local copy of `fstest.FS` and add the …
> fix file type of directory entries

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
Following up from our conversation on Slack, this PR demonstrate a fix which can be used to allow client programs to open files in write mode when they provided none of the O_CREATE, O_APPEND, or O_TRUNC flags.
> interpret RIGHT_FD_WRITE to set O_RDWR on files opened by wazero

- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/store_test.go
Previously executConstExpr is called various places, and therefore it was necessary to return `interface{}`
and that resulted in allocation per call.
This commit avoids the allocation by adding `executConstExprI32` which is used by data segment manipulation,
and repurposes `executConstExpr` solely to global instance initialization.
As a result, this completely removes the allocation around const expr execution, and hence the perf improvement
in the instantiation phrase. The improvement diff is proportionate to the number of data segments and globals.
```
Initialization/interpreter-32             36.0µs ± 1%    36.1µs ± 3%    ~     (p=0.481 n=26+26)
Initialization/interpreter-multiple-32 …
```
> Avoides allocation with constExpr execution

- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
realized that the check at the function preamble is not necessary to prevent the infinite loop,
as there's already a guard to check call stack overflow on that point.
> Removes redundant exit code check

- builder.go
It seems `int32` was repeated twice, based on the pattern I assumed the second occurrence was meant to be `int64`.
> fix typo in wazero.HostFunctionBuilder.WithFunc documentation

- api/wasm.go
We were missing documentation around our Closer, specifically that the context parameter won't obviate closing the resource. Thanks @ItalyPaleAle for drawing attention to this.
> Documents api.Closer closes even if a context is canceled

- Makefile
The fix #1195 was incorrect and resulted in insufficient coverage results (you can check by comparing [before 1995](https://github.com/tetratelabs/wazero/actions/runs/4319671295/jobs/7539103651) and [after](https://github.com/tetratelabs/wazero/actions/runs/4488542958/jobs/7893279544)). Notably, the current main only produces the coverage result of the top `wazero` package.
> build: correctly replace space with comma regardless GNU/BSD

- .github/wasi_testsuite_skip.json
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/errno_windows.go
- internal/platform/open_file_test.go
- internal/platform/open_file_windows.go
It seems WASI now forbids root and relative paths on the at file descriptor and returns EPERM otherwise. This enforces the following:
* require EPERM when you escape a directory (../)
* require EPERM if you add a leading slash (absolute path)
* require ENOENT if you add a trailing slash to a file
* require success if you add a trailing slash to a directory
See https://github.com/WebAssembly/wasi-testsuite/pull/67
> wasi: enforce EPERM on malformed paths

- config.go
- config_test.go
- runtime.go
- runtime_test.go
We currently allow clearing other config with nil, such as FSConfig. However, we missed a spot as internally we couldn't differentiate between name never set, or explicitly set to empty. Now, when someone sets the module name to empty, the name in the binary section is ignored.
> Allow ModuleConfig.WithName("") to clear the module name

- internal/sys/fs.go
I noticed browsing our code that lazyDir accidentally opens a directory just to close it.
> ensures we don't open a file to close it

- cmd/wazero/wazero_test.go
- context_done_example_test.go
- imports/assemblyscript/assemblyscript.go
- imports/emscripten/emscripten_test.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/wasi_test.go
- internal/gojs/argsenv_test.go
- internal/gojs/crypto_test.go
- internal/gojs/fs_test.go
- internal/gojs/http_test.go
- internal/gojs/misc_test.go
- internal/gojs/process_test.go
- internal/gojs/time_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/engine/hammer_test.go
- internal/testing/require/require.go
- internal/wasm/call_context.go
- internal/wasm/call_context_test.go
- runtime.go
- runtime_test.go
- sys/error.go
- sys/error_test.go
This removes the need to handle ExitError for success (exit code zero). It also removes the module name from the struct which allows us to re-use the same error object for the common case of success.
Fixes #1283
> Avoids returning ExitError on exit code zero, and optimizes for no allocations

- runtime.go
- runtime_test.go
The last PR over-solved the WASI close problem as it special cased both "_start", used by WASI, and the start section (wasm level) which isn't used by WASI. In the latter case, we ended up returning nil for both the module *and* the error result. We should never do that.. If we coerce exit error zero to nil, we have to return a non-nil module, even if it is unusable as otherwise code like `defer mod.Close(ctx)` will panic.
Note: it would be entirely rare that someone would define a start section and call close in it. This is just something I noticed while looking carefully at the logic.
> fixes nil panic on close

- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/module_instance.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- runtime_test.go
This drops the unnecessary parameters from `NewModuleEngine` and `NewCallEngine` 
interface methods.
> Refactors NewModuleEngine and NewCallEngine

- site/content/community/users.md
I added [pdfium-cli](https://github.com/klippa-app/pdfium-cli) to users with go-pdfium as it brings Wazero to the end-user and is basically also an implementation example.
> Add pdfium-cli to users

- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- internal/wasm/table.go
- internal/wasm/table_test.go
We allocated `[]validatedActiveElementSegment` during compilation, but 
no need to do that at the end of the day.
> Removes validatedActiveElementSegment

- imports/emscripten/emscripten.go
- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/module_instance.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- site/content/docs/how_do_compiler_functions_work.md
Consequently, we can not only avoid the unnecessary allocation in `api.Module.ExportFunction`,
but also nuke the `wasm.CallEngine` interface.
> Implements api.Function directly over engine specific callEngine

- Makefile
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
In preparation to further refactoring on the compiler side,
add `u1, u2 uint64` fields to `interpreterOp` avoid a useless
allocation of a slice when only 2 int64s are needed
> interpreter: add u1, u2 int64 to `interpreterOp`

- config.go
- sys/clock.go
This makes clock source configuration more clear about the timestamps returned. Specifically, that realtime is UTC and the most common consumers.
thx for the suggestion @Xe!
> godoc: clarifies UTC on clock sources

- internal/asm/amd64/impl.go
- internal/asm/arm64/impl.go
small change, huge win
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      139.5µ ± 8%   138.4µ ± 8%       ~ (p=0.620 n=7)
Compilation/without_extern_cache-10   2.608m ± 1%   2.465m ± 2%  -5.48% (p=0.001 n=7)
geomean                               603.1µ        584.2µ       -3.13%
Compilation/with_extern_cache-10      53.38Ki ± 0%   53.39Ki ± 0%       ~ (p=0.512 n=7)
Compilation/without_extern_cache-10   1.073Mi ± 0%   1.058Mi ± 0%  -1.43% (p=0.001 n=7)
geomean …
```
> asm: reuses the slice on SetBranchTargetOnNextNodes

- internal/integration_test/bench/bench_test.go
In the sequential instantiation bench, we've already disabled calling _start.
This makes the same change to the concurrent installation bench so that
we can measure the pure concurrent instantiation time.
> bench: do not call _start in concurrent instantiation

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_staticconst.go
- internal/asm/arm64/impl.go
- internal/asm/assembler.go
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      135.5µ ± 2%   133.0µ ± 2%  -1.81% (p=0.004 n=7)
Compilation/without_extern_cache-10   2.486m ± 1%   2.445m ± 1%  -1.68% (p=0.004 n=7)
geomean                               580.4µ        570.2µ       -1.74%
Compilation/with_extern_cache-10      53.38Ki ± 0%   53.36Ki ± 0%  -0.03% (p=0.023 n=7)
Compilation/without_extern_cache-10   1.073Mi ± 0%   1.069Mi ± 0%  -0.41% (p=0.001 n=7)
geomean                               242.2Ki        241.6Ki …
```
> asm: reuse StaticConstPool

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
small change, but an extraordinarily huge win...
```
goos: darwin
goarch: amd64
cpu: VirtualApple @ 2.50GHz
Compilation/with_extern_cache-10      329.9µ ± 1%   333.5µ ± 2%        ~ (p=0.383 n=7)
Compilation/without_extern_cache-10   6.404m ± 1%   5.430m ± 3%  -15.21% (p=0.001 n=7)
geomean                               1.453m        1.346m        -7.41%
Compilation/with_extern_cache-10      53.90Ki ± 0%   53.66Ki ± 0%   -0.43% (p=0.001 n=7)
Compilation/without_extern_cache-10 …
```
> asm/amd64: avoids map allocation per node

- sys/error.go
- sys/error_test.go
When I saw the text formatted error, I immediately tried to use `errors.Is` to discard the error (since I called the cancel func) and wasn't able to.  This should make it more natural to handle these special exit code errors.
> sys/error: handle errors.Is for common context use-cases

- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
- internal/wazeroir/operations.go
- internal/wazeroir/operations_test.go
- refactor: remove nullary Operation objects, use unified object
- refactor: migrate nullary operations to the new OperationNullary
- refactor: remove commented-out code
While working on #1296 I realized there is a quick win / iterative change that could be merged to `main` already. Instead of creating a number of different instances of empty structs, we instead create a single `OperationNullary` with a `kind` field.
This can be migrated to the unified `interpreterOps` object later. Notice that since these are nullary, we may actually do away even with the constructor and define instead a bunch of vars.
> wazeroir: rm nullary Operations, move interpreterOp to UnionOperation

- internal/engine/compiler/compiler.go
- internal/engine/compiler/compiler_bench_test.go
- internal/engine/compiler/compiler_conditional_save_test.go
- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_conversion_test.go
- internal/engine/compiler/compiler_global_test.go
- internal/engine/compiler/compiler_memory_test.go
- internal/engine/compiler/compiler_numeric_test.go
- internal/engine/compiler/compiler_post1_0_test.go
- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_vec_amd64_test.go
- internal/engine/interpreter/interpreter.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
- internal/wazeroir/operations.go
- internal/wazeroir/operations_test.go
- refactor: OperationCall, OperationGlobalGet, OperationGlobalSet
- refactor: Constant Operations
Refactor some unary operations to use `UnionOperation`. Again, we do this in waves to avoid creating a huge big-bang PR.
Unfortunately I have to do this mostly by hand to ensure that I am not breaking something, and to preserve comments and docs. At least I am double-checking it :D
Continues implementation of #1202
> wazeroir: migrate unary operations to UnionOperation

- internal/engine/compiler/engine.go
- internal/wasm/store.go
ModuleInstance.Closed is an atomic variable meant to be loaded and swapped with sync/atomic. Closed, being a 64 bit integer, requires 64 bit alignment. The simplest way we can get alignment is to place these atomic fields at the top of their struct.
Closed can be moved to a more logical place once support for Go 1.18 is dropped and its type changed to atomic.Uint64.
> wasm: move ModuleInstance.Closed to the top

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_memorylocation_test.go
```
goos: darwin
goarch: amd64
cpu: VirtualApple @ 2.50GHz
Compilation/with_extern_cache-10      263.7µ ± 3%   251.5µ ± 3%  -4.63% (p=0.001 n=7)
Compilation/without_extern_cache-10   4.234m ± 0%   4.225m ± 1%       ~ (p=0.165 n=7)
geomean                               1.057m        1.031m       -2.45%
Compilation/with_extern_cache-10      53.56Ki ± 0%   53.56Ki ± 0%       ~ (p=0.872 n=7)
Compilation/without_extern_cache-10   1.198Mi ± 0%   1.195Mi ± 0%  -0.26% (p=0.001 n=7)
geomean …
```
> asm/amd64: avoids allocation in getting memory location

- internal/engine/compiler/arch_amd64.go
- internal/engine/compiler/arch_arm64.go
- internal/engine/compiler/arch_other.go
- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_drop_test.go
- internal/engine/compiler/compiler_global_test.go
- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_memory_test.go
- internal/engine/compiler/compiler_numeric_test.go
- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/compiler_value_location.go
- internal/engine/compiler/compiler_value_location_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_vec_amd64_test.go
- internal/engine/compiler/impl_vec_arm64_test.go
_arm64_
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      102.6µ ± 3%   103.1µ ± 9%        ~ (p=0.620 n=7)
Compilation/without_extern_cache-10   2.089m ± 1%   1.767m ± 2%  -15.42% (p=0.001 n=7)
geomean                               462.9µ        426.9µ        -7.78%
Compilation/with_extern_cache-10      53.36Ki ± 0%   53.36Ki ± 0%       ~ (p=0.738 n=7)
Compilation/without_extern_cache-10   1.211Mi ± 0%   1.160Mi ± 0%  -4.23% (p=0.001 n=7)
geomean                               257.2Ki …
```
> compiler: bitmask for tracking used registers

- internal/engine/compiler/compiler_value_location.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
```
goos: darwin
goarch: arm64
│   old.txt   │             new2.txt              │
Compilation/with_extern_cache-10      102.6µ ± 3%   102.1µ ± 0%       ~ (p=0.259 n=7)
Compilation/without_extern_cache-10   2.089m ± 1%   2.087m ± 1%       ~ (p=0.620 n=7)
geomean                               462.9µ        461.6µ       -0.27%
│   old.txt    │              new2.txt              │
Compilation/with_extern_cache-10      53.36Ki ± 0%   53.35Ki ± 0%       ~ (p=0.078 n=7)
Compilation/without_extern_cache-10   1.211Mi ± 0%   1.210Mi ± 0%  -0.03% (p=0.001 n=7)
geomean                               257.2Ki        257.1Ki …
```
> compiler: removes takeFreeRegisters fn

- internal/asm/assembler.go
- internal/asm/impl.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
_arm64_
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      132.6µ ± 1%   133.0µ ± 0%       ~ (p=0.165 n=7)
Compilation/without_extern_cache-10   2.225m ± 0%   2.188m ± 1%  -1.68% (p=0.001 n=7)
geomean                               543.2µ        539.4µ       -0.71%
Compilation/with_extern_cache-10      53.40Ki ± 0%   53.40Ki ± 0%       ~ (p=0.511 n=7)
Compilation/without_extern_cache-10   1.159Mi ± 0%   1.144Mi ± 0%  -1.28% (p=0.001 n=7)
geomean                               251.8Ki        250.1Ki …
```
> compiler: avoid allocation in SetJumpTargetOnNext

- internal/asm/amd64/impl.go
- internal/asm/arm64/impl.go
- internal/asm/assembler.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
_arm64_
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      133.8µ ± 1%   134.4µ ± 1%       ~ (p=0.383 n=7)
Compilation/without_extern_cache-10   2.181m ± 0%   2.124m ± 1%  -2.63% (p=0.001 n=7)
geomean                               540.2µ        534.3µ       -1.09%
Compilation/with_extern_cache-10      53.41Ki ± 0%   53.41Ki ± 0%       ~ (p=0.778 n=7)
Compilation/without_extern_cache-10   1.144Mi ± 0%   1.115Mi ± 0%  -2.53% (p=0.001 n=7)
geomean                               250.2Ki        247.0Ki …
```
> compiler: avoids allocation in label resolution

- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/wazeroir/operations.go
- internal/wazeroir/operations_test.go
_arm64_
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      133.9µ ± 1%   134.4µ ± 1%       ~ (p=0.456 n=7)
Compilation/without_extern_cache-10   2.125m ± 1%   2.058m ± 1%  -3.14% (p=0.001 n=7)
geomean                               533.3µ        526.0µ       -1.37%
Compilation/with_extern_cache-10      53.39Ki ± 0%   53.38Ki ± 0%       ~ (p=0.779 n=7)
Compilation/without_extern_cache-10   1.115Mi ± 0%   1.082Mi ± 0%  -2.99% (p=0.001 n=7)
geomean                               246.9Ki        243.2Ki …
```
> compiler: stop using map for label infos

- internal/wasm/func_validation.go
- internal/wasm/func_validation_test.go
- internal/wasm/module.go
```
goos: darwin
goarch: arm64
Compilation/with_extern_cache-10      134.4µ ± 1%   120.5µ ± 1%  -10.36% (p=0.001 n=7)
Compilation/without_extern_cache-10   2.058m ± 1%   2.027m ± 1%   -1.50% (p=0.001 n=7)
geomean                               526.0µ        494.3µ        -6.04%
Compilation/with_extern_cache-10      53.38Ki ± 0%   40.80Ki ± 0%  -23.57% (p=0.001 n=7)
Compilation/without_extern_cache-10   1.082Mi ± 0%   1.070Mi ± 0%   -1.13% (p=0.001 n=7)
geomean                               243.2Ki        211.4Ki …
```
> Reuses allocated slices in func validation 

- .github/workflows/commit.yaml
- config.go
- internal/gojs/compiler_test.go
- internal/wasm/binary/decoder.go
- internal/wasm/binary/memory_test.go
Fixes #1330. This is more of a fix rather than behavioral change left in #1063.
> Allows WithMemoryLimitPages to override the default pages

- internal/engine/compiler/impl_amd64.go
- internal/wasm/module_instance.go
- internal/wasm/module_instance_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
Fixes #1314. Previously, when context cancelation is enabled, the resource is 
also closed in the `closeModuleOnCanceledOrTimeout` function which is 
asynchronously called concurrently to the Wasm function call. On the other hand,
host functions, especially wasi functions, do not check if the module is closed or not
therefore, if we reached the context cancelation while executing wasi functions, we
had race conditions.
This makes change to `closeModuleOnCanceledOrTimeout` so that it won't close resources,
and defer closing them to in `FailIfClosed` which is called synchronously during `api.Function.Call`.
> Defer resource closure on context cancelation to m.FailIfClosed

- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
```
goos: darwin
goarch: arm64
│   old.txt   │             new2.txt              │
Compilation/with_extern_cache-10      90.60µ ± 3%   89.70µ ± 2%  -0.99% (p=0.007 n=7)
Compilation/without_extern_cache-10   1.423m ± 1%   1.415m ± 1%  -0.59% (p=0.001 n=7)
Compilation/interpreter-10            408.3µ ± 0%   408.0µ ± 0%       ~ (p=0.710 n=7)
geomean                               374.8µ        372.7µ       -0.55%
│   old.txt    │              new2.txt              │
Compilation/with_extern_cache-10      38.25Ki ± 0%   38.24Ki ± 0%  -0.03% (p=0.015 n=7)
Compilation/without_extern_cache-10   769.0Ki ± 0%   766.1Ki ± 0% …
```
> compiler: avoid alloc with stack pointer ceil and reuse bytes reader

- internal/engine/compiler/compiler_drop_test.go
- internal/engine/compiler/compiler_stack_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/compiler_value_location.go
- internal/engine/compiler/compiler_value_location_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
_arm64_
```
goos: darwin
goarch: arm64
│  v1.0.1.txt  │           current_main.txt            │               pr1348.txt               │
│    sec/op    │   sec/op     vs base                  │   sec/op     vs base                   │
Compilation_sqlite3/compiler-10       283.2m ± 0%   177.0m ± 4%  -37.49% (p=0.000 n=30+7)   166.7m ± 0%  -41.15% (p=0.000 n=30+10)
Compilation_sqlite3/interpreter-10   114.42m ± 0%   48.50m ± 1%  -57.61% (p=0.000 n=30+7)   48.56m ± 1%  -57.56% (p=0.000 n=30+10)
geomean                               180.0m        92.66m       -48.52%                    89.97m       -50.02%
│  v1.0.1.txt   │            current_main.txt             │               pr1348.txt                │
│     B/op      │ …
```
> compiler: reuses allocated runtimeValueLocation stacks

- builder_test.go
- experimental/logging/log_listener_test.go
- internal/testing/binaryencoding/names.go
- internal/testing/binaryencoding/names_test.go
- internal/testing/proxy/proxy.go
- internal/wasm/binary/names.go
- internal/wasm/function_definition.go
- internal/wasm/host.go
- internal/wasm/module.go
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      215.3m ± 0%   215.6m ± 1%       ~ (p=0.318 n=7)
Compilation_sqlite3/interpreter-10   62.57m ± 1%   62.46m ± 1%       ~ (p=0.383 n=7)
geomean                              116.1m        116.0m       -0.00%
Compilation_sqlite3/compiler-10      51.97Mi ± 0%   51.97Mi ± 0%  -0.01% (p=0.017 n=7)
Compilation_sqlite3/interpreter-10   51.84Mi ± 0%   51.83Mi ± 0%  -0.02% (p=0.001 n=7)
geomean                              51.91Mi        51.90Mi       -0.01%
│ …
```
> binary: makes NameMap and IndirectNameMap slices over values, not ptrs

- internal/wasm/binary/code.go
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      215.6m ± 1%   215.5m ± 3%       ~ (p=0.902 n=7)
Compilation_sqlite3/interpreter-10   62.46m ± 1%   62.12m ± 1%       ~ (p=0.383 n=7)
geomean                              116.0m        115.7m       -0.31%
Compilation_sqlite3/compiler-10      51.97Mi ± 0%   51.93Mi ± 0%  -0.07% (p=0.001 n=7)
Compilation_sqlite3/interpreter-10   51.83Mi ± 0%   51.79Mi ± 0%  -0.07% (p=0.001 n=7)
geomean                              51.90Mi        51.86Mi       -0.07%
│ …
```
> binary: reduces allocation during code section decoding

- experimental/gojs/example/.gitignore
- experimental/gojs/example/stars.go
No need to cache as the compilation perf improved drastically,
plus this prevents crashes when making changes to compiler backends,
which previously forced us to delete the .build dir manually.
```
2023/04/11 13:36:03 gojs.MustInstantiate took 0ms
2023/04/11 13:36:03 CompileModule took 538ms
2023/04/11 13:36:03 gojs.Run took 8ms
```
> gojs: stop file caching in tests

- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      194.7m ± 0%   195.0m ± 0%       ~ (p=0.165 n=7)
Compilation_sqlite3/interpreter-10   62.54m ± 1%   61.90m ± 1%  -1.03% (p=0.001 n=7)
geomean                              110.3m        109.9m       -0.44%
Compilation_sqlite3/compiler-10      51.90Mi ± 0%   51.90Mi ± 0%       ~ (p=0.259 n=7)
Compilation_sqlite3/interpreter-10   51.76Mi ± 0%   51.75Mi ± 0%  -0.02% (p=0.001 n=7)
geomean                              51.83Mi        51.82Mi       -0.01%
│ …
```
> interpreter: use slice of values on functions, not ptrs

- internal/wasm/module_instance.go
- internal/wasm/store.go
- internal/wasm/store_module_list.go
- internal/wasm/store_module_list_test.go
- internal/wasm/store_test.go
```
goos: darwin
goarch: arm64
│   old.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
Initialization/interpreter-10            14.41µ ± 1%   14.47µ ± 1%        ~ (p=0.353 n=10)
Initialization/interpreter-multiple-10   17.87µ ± 2%   15.88µ ± 3%  -11.14% (p=0.000 n=10)
Initialization/compiler-10               14.87µ ± 1%   14.92µ ± 1%        ~ (p=0.218 n=10)
Initialization/compiler-multiple-10      18.68µ ± 1%   17.20µ ± 3%   -7.89% (p=0.000 n=10)
geomean                                  16.35µ        15.58µ        -4.71%
Initialization/interpreter-10 …
```
> wasm: removes name node to simplify instantiation path

- internal/engine/compiler/engine_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/binary/decoder.go
- internal/wasm/binary/decoder_test.go
- internal/wasm/binary/section.go
- internal/wasm/module.go
- internal/wasm/store.go
- internal/wasm/store_module_list.go
- internal/wasm/store_module_list_test.go
- internal/wasm/store_test.go
- internal/wasm/table_test.go
```
goos: darwin
goarch: arm64
Initialization/interpreter-10            14.48µ ± 0%   14.23µ ± 1%  -1.76% (p=0.000 n=30)
Initialization/interpreter-multiple-10   17.90µ ± 5%   17.82µ ± 2%       ~ (p=0.139 n=30)
Initialization/compiler-10               16.69µ ± 1%   15.87µ ± 1%  -4.89% (p=0.000 n=30)
Initialization/compiler-multiple-10      19.53µ ± 1%   18.73µ ± 1%  -4.10% (p=0.000 n=30)
geomean                                  17.05µ        16.57µ       -2.83%
Initialization/interpreter-10            132.5Ki ± …
```
> wasm: reduces allocs during import resolution

- builder.go
The `WithGoFunction` and `WithGoModuleFunction` docs were out of date. It appears that #860 changed the way values are returned, but the docs weren't updated. This is similar to #878.
> Fix HostFunctionBuilder docs

- internal/wasm/store.go
- internal/wasm/store_module_list.go
- internal/wasm/store_module_list_test.go
Putting this out there. Go does not shrink maps when elements are deleted so a long lived map with lots of elements added and deleted can consume a lot of memory.
This change would track the largest size the nameToNode map has grown to and if that size is more than twice the size it needs to be it gets replaced with a new map. Since we wouldn't want to be constantly resizing small maps I've set a floor and set the initial capacity of the map to that floor. I some what arbitrarily chose 10,000 as the floor.
The scenario this helps with is if a long running application has bursty periods of time when it instantiates a lot of named modules but most of the time has a very low volume of named modules.
I think it might be nice to make an option to disable or adjust the floor for applications …
> Shrink the store's nameToModule map

- internal/wasm/store.go
- internal/wasm/store_module_list.go
- internal/wasm/store_module_list_test.go
When a module is deleted which has been aliased, the aliases are not cleaned up meaning the original module will be closed and unusable but never get GC'd. I understand that aliases are currently only used in spect tests however `*store.AliasModule` is an exported method covered by tests so it feels right to fix the bug. This fix should have almost no meaningful impact to normal uses as `Module.aliases` will remain `nil` for all modules if no aliases are ever created.
```
goos: darwin
goarch: arm64
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │
Initialization/interpreter-10            10.94µ ± ∞ ¹   10.84µ ± ∞ ¹       ~ (p=1.000 n=1) ² …
```
> Cleanup aliased modules when the main module is deleted

- builder.go
- builder_test.go
- imports/assemblyscript/assemblyscript.go
- imports/emscripten/emscripten.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/compiler/engine_test.go
- internal/gojs/goarch/wasm.go
- internal/gojs/util/util.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/host.go
- internal/wasm/host_test.go
- internal/wasm/store_test.go
This makes host functions index consistently on insertion order, rather than lexicographic order. This helps with ABI such as Emscripten, which need an expected order.
This also constrains the internal code around host functions to only one export name. More than one was never used. By restricting this, logic is simpler and smaller.
> Makes host function index insertion order

- imports/emscripten/emscripten.go
- imports/wasi_snapshot_preview1/proc.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/gojs/goarch/wasm.go
- internal/gojs/util/util.go
A prior change broke race tests as it lazy set HostFunc.Name even when saved as a field. This sets name in all places we instantiate HostFunc for use in fields.
Fixes #1373
> Fixes race where HostFunc names are needlessly lazy set

- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_1_test.go
- internal/asm/arm64/impl_2_test.go
- internal/asm/arm64/impl_3_test.go
- internal/asm/arm64/impl_4_test.go
- internal/asm/arm64/impl_5_test.go
- internal/asm/arm64/impl_6_test.go
This speeds up the large switch in the assembler.
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      191.9m ± 1%   183.5m ± 1%  -4.39% (p=0.001 n=7)
Compilation_sqlite3/interpreter-10   61.83m ± 0%   61.86m ± 1%       ~ (p=0.902 n=7)
geomean                              108.9m        106.5m       -2.20%
Compilation_sqlite3/compiler-10      42.93Mi ± 0%   42.93Mi ± 0%       ~ (p=0.902 n=7)
Compilation_sqlite3/interpreter-10   51.75Mi ± 0%   51.75Mi ± 0%       ~ (p=0.128 n=7)
geomean …
```
> asm/arm64: uses enum for operand types

- builder.go
I tried to copy/paste the example code but it had some syntax errors so I opened this PR to fix them.
There's a better way to do examples in Go that prevents syntax errors.
https://go.dev/blog/examples
Would you like me to migrate all the examples to Testable Examples after this PR is merged?
> Fixes syntax errors in examples

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_staticconst.go
```
goos: linux
goarch: amd64
Compilation/without_extern_cache-32   4.461m ± 2%   4.439m ± 3%       ~ (p=0.620 n=7)
Compilation_sqlite3/compiler-32       531.5m ± 2%   533.1m ± 2%       ~ (p=1.000 n=7)
geomean                               48.70m        48.65m       -0.10%
Compilation/without_extern_cache-32   678.9Ki ± 0%   665.1Ki ± 0%  -2.03% (p=0.001 n=7)
Compilation_sqlite3/compiler-32       53.09Mi ± 0%   49.46Mi ± 0%  -6.83% (p=0.001 n=7)
geomean …
```
> asm/amd64: avoids allocations in static const offset resolution

- internal/asm/amd64/consts.go
- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/amd64/impl_2_test.go
- internal/asm/amd64/impl_4_test.go
- internal/asm/amd64/impl_memorylocation_test.go
- internal/asm/amd64/impl_staticconst.go
```
goos: linux
goarch: amd64
Compilation/without_extern_cache-32   4.441m ± 3%   4.034m ± 1%  -9.16% (p=0.001 n=7)
Compilation_sqlite3/compiler-32       517.0m ± 3%   478.6m ± 2%  -7.42% (p=0.001 n=7)
geomean                               47.91m        43.94m       -8.29%
Compilation/without_extern_cache-32   665.0Ki ± 0%   665.0Ki ± 0%       ~ (p=0.557 n=7)
Compilation_sqlite3/compiler-32       49.46Mi ± 0%   49.46Mi ± 0%       ~ (p=0.535 n=7)
geomean …
```
> asm/amd64: optimizes register3bits via array

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/amd64/impl_2_test.go
- internal/asm/amd64/impl_4_test.go
- internal/asm/amd64/impl_memorylocation_test.go
- internal/asm/amd64/impl_staticconst.go
```
goos: linux
goarch: amd64
│   old.txt   │              new2.txt              │
Compilation/without_extern_cache-32   4.101m ± 2%   3.974m ± 1%   -3.12% (p=0.001 n=7)
Compilation_sqlite3/compiler-32       488.4m ± 1%   429.5m ± 2%  -12.05% (p=0.001 n=7)
geomean                               44.76m        41.31m        -7.69%
│   old.txt    │              new2.txt              │
Compilation/without_extern_cache-32   665.1Ki ± 0%   664.5Ki ± 0%  -0.09% (p=0.001 n=7)
Compilation_sqlite3/compiler-32       49.46Mi ± 0%   49.40Mi ± 0%  -0.13% (p=0.001 n=7)
geomean …
```
> asm/amd64: removes map access in encoding 

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/amd64/impl_2_test.go
- internal/asm/amd64/impl_3_test.go
- internal/asm/amd64/impl_4_test.go
- internal/asm/amd64/impl_5_test.go
- internal/asm/amd64/impl_memorylocation_test.go
- internal/asm/amd64/impl_staticconst_test.go
counterpart for #1378 
```
goos: linux
goarch: amd64
Compilation/without_extern_cache-32   3.907m ± 1%   3.855m ± 1%  -1.34% (p=0.038 n=7)
Compilation_sqlite3/compiler-32       426.7m ± 4%   398.2m ± 1%  -6.67% (p=0.001 n=7)
geomean                               40.83m        39.18m       -4.04%
Compilation/without_extern_cache-32   664.4Ki ± 0%   664.5Ki ± 0%       ~ (p=0.053 n=7)
Compilation_sqlite3/compiler-32       49.40Mi ± 0%   49.40Mi ± 0%       ~ (p=0.456 n=7) …
```
> asm/amd64: uses enum for operand types

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/descriptor/table.go
- internal/descriptor/table_test.go
- internal/gojs/fs.go
- internal/gojs/goarch/wasm.go
- internal/gojs/goos/goos.go
- internal/gojs/logging/logging.go
- internal/gojs/runtime.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
- internal/wasip1/logging/logging.go
- internal/wasm/module_instance.go
This changes file descriptors from uint32 to int32 and the corresponding file table to reject negative values. This ensures invalid values aren't mistaken for very large descriptor entries, which can use a lot of memory as the table implementation isn't designed to be sparse.
Thanks to @jerbob92 for noticing this!
See https://pubs.opengroup.org/onlinepubs/9699919799/functions/dirfd.html#tag_16_90
> fs: returns EBADF on negative file descriptor

- .github/workflows/release.yaml
each time, I forgot to add this and had to look at the diff manually.
> ci: ensure release notes script can see prior commits

- internal/asm/amd64/impl.go
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 9 3950X 16-Core Processor            
Compilation/without_extern_cache-32   3.833m ± 2%   3.884m ± 3%       ~ (p=0.535 n=7)
Compilation_sqlite3/compiler-32       413.2m ± 1%   398.3m ± 1%  -3.59% (p=0.001 n=7)
geomean                               39.80m        39.33m       -1.16%
Compilation/without_extern_cache-32   664.5Ki ± 0%   664.4Ki ± 0%       ~ (p=0.456 n=7)
Compilation_sqlite3/compiler-32       49.40Mi ± 0%   49.40Mi ± 0%       ~ (p=0.165 n=7)
geomean …
```
> asm/amd64: optimizes initializeNodesForEncoding

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/amd64/impl_4_test.go
- internal/asm/amd64/impl_5_test.go
- internal/asm/amd64/impl_7_test.go
```
goos: linux
goarch: amd64
Compilation/without_extern_cache-32   3.820m ± 3%   3.777m ± 2%       ~ (p=0.535 n=7)
Compilation_sqlite3/compiler-32       395.2m ± 2%   388.6m ± 2%  -1.66% (p=0.038 n=7)
geomean                               38.85m        38.31m       -1.40%
Compilation/without_extern_cache-32   664.4Ki ± 0%   664.5Ki ± 0%  +0.02% (p=0.038 n=7)
Compilation_sqlite3/compiler-32       49.40Mi ± 0%   49.40Mi ± 0%       ~ (p=0.476 n=7)
geomean …
```
> asm/amd64: removes nodeImpl.forwardJumpTarget

- api/wasm.go
- builder.go
- cache.go
- config.go
- fsconfig.go
- imports/assemblyscript/assemblyscript.go
- imports/emscripten/emscripten.go
- imports/wasi_snapshot_preview1/wasi.go
- runtime.go
wazero uses interfaces even when they aren't intended to be implemented by users. We relied on documentation, to suggest what is implementable, and in some cases documented correctly types that weren't for implementation.
However, we didn't add that boilerplate to all types, and we also forgot to recently when it was discussed a week or two ago (don't recall when/where exactly). This finishes the job by boiler-plating all types that aren't for implementation. This also orders to the top when it already existed.
Later, we can choose to enforce by type as well, we didn't know how to do that before. Basically before we just casted to our internal types, which would stop accidental implementation for things except people using the types for wrapping purposes.
> godoc: moves sealed type notes to the top and backfills where missing

- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasmdebug/debug.go
- internal/wasmdebug/debug_test.go
this improves the debuggability of the issues like #1399 
Below is the example output for this change on debugging 1399:
```
2023/04/25 10:35:16 runtime error: invalid memory address or nil pointer dereference (recovered by wazero)
wasm stack trace:
env.hostTalk(i32,i32,i32,i32) i32
.hello(i32,i32) i64
Go runtime stack trace:
goroutine 1 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/tetratelabs/wazero/internal/wasmdebug.(*stackTrace).FromRecovered(0x140001e78d0?, {0x100285760?, 0x100396360?})
/Users/mathetake/wazero/internal/wasmdebug/debug.go:139 +0xc4
github.com/tetratelabs/wazero/internal/engine/compiler.(*callEngine).deferredOnCall(0x14000178900, {0x100285760, 0x100396360})
/Users/mathetake/wazero/internal/engine/compiler/engine.go:803 …
```
> debug: includes Go stack trace in the face of Go runtime errors

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
We should tolerate noop input vs break. This fixes where a zero length iovec would short circuit latter ones.
Thanks again to our bug piper @jerbob92!
> wasi: fixes bug where zero length iovec breaks fd_read

- .github/workflows/integration.yaml
This enables macos-12 plus removes the need to install gotip when the cache exists.
> ci: cleanup GOOS=wasip1

- .github/workflows/commit.yaml
- internal/integration_test/fuzzcases/fuzzcases_test.go
we recently missed two race bugs introduced via PRs but detected on the main branch.
The reason is that previously we had run tests with -race only on main branch.
This enables the race detection on PRs as well.
> ci: run -race on PRs as well

- internal/platform/select_windows.go
- internal/platform/select_windows_test.go
An improved version of the `select(2)` syscall emulation on Windows for Stdin. We use `PeekNamedPipe` when `Stdin` is a FILE_TYPE_CHAR, and we invoke it every 100ms if duration > 0. Follow up to #1346 and #1317.
I checked the examples manually for interactive input and they seem to work for me.
> wasi: improve select(2) impl on Windows

- api/wasm.go
- cmd/wazero/wazero_test.go
- config.go
- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/internalapi/internal.go
- internal/wasm/function_definition.go
- internal/wasm/global.go
- internal/wasm/memory.go
- internal/wasm/memory_definition.go
- internal/wasm/module_instance.go
- internal/wasm/store.go
- internal/wasm/store_test.go
As discussed in https://github.com/tetratelabs/wazero/pull/1332#issuecomment-1510010359, many of the interfaces in [`github.com/tetratelabs/wazero`](https://pkg.go.dev/github.com/tetratelabs/wazero) and [`github.com/tetratelabs/wazero/api`](https://pkg.go.dev/github.com/tetratelabs/wazero/api) are not meant to be externally implemented.
In strict terms, an interface can't be extended after it has been made public. Once made public, alternative implementations may be created, and adding a method to such an interface, means those implementations no longer compile, which breaks semver.
wazero 1.0 shipped with many such interfaces, which we may want to extend (e.g. #1332).
These are the paths available to us:
1. **that ship has sailed**: wazero 1.0 shipped, we simply can't extend these …
> Proposal: "close" certain api interfaces for external implementation

- internal/wasm/func_validation.go
- internal/wasm/func_validation_test.go
- internal/wasm/function_definition_test.go
This adds an internal function `wasm.SplitCallStack` for use in #1407. This is separate because the diff is a lot larger than the destination change ;)
> Adds SplitCallStack for use in CallWithStack

- api/wasm.go
- internal/emscripten/emscripten.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/gofunc.go
- internal/wasm/gofunc_test.go
- internal/wasm/store_test.go
This implements the API discussed in #1332.
It still needs unit tests, and redoing the benchmarks to confirm the improvements.
> api: adds CallWithStack to avoid allocations

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/gojs/fs.go
- internal/platform/chown_unix_test.go
- internal/platform/file.go
- internal/platform/futimens_test.go
- internal/platform/open_file.go
- internal/platform/open_file_js.go
- internal/platform/open_file_sun.go
- internal/platform/open_file_test.go
- internal/platform/open_file_windows.go
- internal/platform/stat.go
- internal/platform/stat_test.go
- internal/platform/wrap_windows.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
- internal/sysfs/adapter.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/dirfs_unix_test.go
- internal/sysfs/readfs.go
- internal/sysfs/rootfs.go
- internal/sysfs/rootfs_test.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
- internal/sysfs/unimplemented.go
- internal/wasm/module_instance_test.go
After the last couple months of thinking, I eventually got to the idea that defining a new file type has two problems:
* What sort of type do we define?
* How in the world do we migrate to a new type?
What this PR does is spike an approach to the latter without solidifying the former. My thinking is that the best way is to incrementally migrate functions one-by-one to a new type. Meanwhile, temporarily expose a `.File()` function to access the `fs.File` we want to rid eventually. This makes it easy to identify what's left as you just look for any calls to `.File()`.
If this approach helps, lemme know and I can polish for merge. I mainly had this branch locally so want to decide to delete it or not!
> sysfs: stubs in approach to defining a new file type

- internal/gojs/fs.go
- internal/platform/chown.go
- internal/platform/chown_unix_test.go
- internal/platform/file.go
- internal/sys/fs.go
- internal/sysfs/dirfs_unix_test.go
This migrates the function `platform.ChownFile` to the work-in-progress `platform.File` type without changing its implementation.
See #1417
> Adds platform.File.Chown

- site/content/languages/tinygo.md
This follows up the change to our example by @lburgazzoli in #1390, which basically switched our guidance to have the host call "free" on strings it receives as results from the guest code.
The notably change was `stringToLeakedPtr` which should be added to [tinymem](https://github.com/tetratelabs/tinymem) soon.
https://github.com/tetratelabs/wazero/blob/main/examples/allocation/tinygo/testdata/greet.go#L87-L94
tinymem should also remove custom memory exports, as they are no longer needed.
One thing missing from this doc are tinygo build flags to explicitly export "malloc" and "free", so that tinygo can eventually stop exporting these by default. If someone knows the syntax, let me know and I will update this.
> Revises instructions to latest guidance from TinyGo

- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/chown_unix_test.go
- internal/platform/datasync_linux.go
- internal/platform/datasync_unsupported.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/futimens_test.go
- internal/platform/open_file.go
- internal/platform/open_file_js.go
- internal/platform/open_file_sun.go
- internal/platform/open_file_test.go
- internal/platform/open_file_windows.go
- internal/platform/stat_test.go
- internal/platform/sync.go
- internal/platform/wrap_windows.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sysfs/adapter.go
- internal/sysfs/dirfs.go
- internal/sysfs/readfs.go
- internal/sysfs/rootfs.go
- internal/sysfs/sysfs.go
This adds Path which is non-empty when the file is a normal file or directory. This immediately supports the re-open use case, and later may make some things in windows easier.
This also adds a platform.NewFsFile function which makes some call sites better.
Finally, this fixes a bug hidden by how our tests were written, where the wrong errno was returned when a file was used after close in windows.
> Adds Path to platform.File and refactors tests

- internal/engine/compiler/RATIONALE.md
Relates to #1409, #1413. Explains why the native check won't work.
> compiler: update RATIONALE.md for native check

- internal/platform/errno_windows.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/sync.go
- internal/platform/sync_windows.go
- internal/platform/unlink_windows.go
On Windows, an access error was mapped to EPERM not EACCES.
> Splits EACCES from EPERM on Windows

- site/content/languages/tinygo.md
The Guest uses `ptrToString` not `stringToPtr` on a Host allocation;
the Guest uses `stringToPtr` when it passes back memory to the Host.
thanks @lburgazzoli for noticing!
> site: fix small mistake in TinyGo doc

- imports/assemblyscript/assemblyscript.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- internal/gojs/fs.go
- internal/gojs/runtime.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/open_file_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sysfs/adapter.go
- internal/sysfs/dirfs.go
- internal/sysfs/readfs.go
- internal/sysfs/rootfs.go
- internal/sysfs/sysfs.go
- internal/sysfs/sysfs_test.go
This adds `file.AccessMode` to substitute for type checking that formerly was used to see if the file might be writeable (e.g. casting to `io.Writer` so that you can check before actually writing).
This allows us to implement `File.Write` and `File.Pwrite` which might return `syscall.ENOSYS` on read-only implementations.
See #1417
> Adds AccessMode Write and Pwrite to platform.File

- experimental/experimental.go
- experimental/logging/log_listener_test.go
- experimental/wazerotest/wazerotest.go
- experimental/wazerotest/wazerotest_test.go
This PR is a proposal to add `experimental/wazerotest` package containing stub implementations of types from the `api` package which are useful to construct tests.
Since https://github.com/tetratelabs/wazero/pull/1396, we added barriers for external packages to provide mocks of the wazero interfaces in contexts such as tests and benchmarks; see for example https://github.com/stealthrocket/wazergo/blob/main/wasm/memory.go
While programs can work around the limitation imposed by `internalapi.WazeroOnly`, doing so requires embedding the `api` interfaces which loosens type safety since the type _inherits_ all the methods and therefore automatically satisfies the interface even if it intended to provide different implementations of the methods. This causes issues that are difficult to catch …
> experimental: add wazerotest package

- imports/wasi_snapshot_preview1/fs.go
- internal/platform/bench_test.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/futimens.go
- internal/platform/futimens_test.go
- internal/sys/fs.go
- internal/sysfs/sysfs.go
This adds `Utimens` to `platform.File`, used to implement `fd_filestat_set_times`.
See #1417
> Adds Utimens to platform.File

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/nonblock_unix.go
- internal/platform/nonblock_windows.go
- internal/sys/fs.go
- internal/sys/fs_test.go
This PR adds the ability to configure non-blocking mode on standard input and output when the underlying files are of type `*os.File`.
This is going to be needed to enable testing the latest Go changes with wazero, see https://go-review.googlesource.com/c/go/+/493356
> wasip1: support non-blocking mode on stdio

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/bench_test.go
- internal/platform/chown_unix_test.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/futimens_test.go
- internal/platform/open_file_test.go
- internal/platform/stat_test.go
- internal/platform/unlink_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/dirfs_unix_test.go
- internal/sysfs/readfs_test.go
- internal/sysfs/rootfs_test.go
- internal/sysfs/sysfs_test.go
This adds `IsDir` and `Seek` to `platform.File`. `IsDir` is used in several places to error early if the file is the wrong type in file or directory. `Seek` replaces where we originally cast to `io.Seeker`, notably for `fd_seek`.
See #1417
> Adds IsDir and Seek to platform.File

- experimental/listener.go
- experimental/listener_example_test.go
- experimental/wazerotest/wazerotest.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
- internal/testing/enginetest/enginetest.go
This change provides a user of `experimental.StackIterator` the ability to retrieve the offset in the Code section of each function call in the frame of the stack. It enables capabilities such as source-mapping to be implemented by the user outside of wazero (removing the need for #1403).
It works by retrieving the return address of each stack frame and using the `irOperationSourceOffsetsInWasmBinary` attached to the function associated with that stack frame.
Though it works in my tests and on the few programs I used, I feel quite out of my depth here; I'd love some guidance and feedback! :) 
Question 1 – This source offsets mapping is only produced by the compiler when DWARF sections are present in the module. In practice, it's a reasonable limitation for us since we currently are only …
> experimental: expose source offset to Listener

- builder.go
- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- internal/testing/enginetest/enginetest.go
- internal/testing/proxy/proxy.go
- runtime.go
As discussed in the #wazero-dev Slack channel, this PR renames `NewListener` to `NewFunctionListener` to keep the method name consistent with its return type.
> experimental: rename NewListener => NewFunctionListener

- builder.go
- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- experimental/wazerotest/wazerotest.go
- internal/testing/enginetest/enginetest.go
- internal/testing/proxy/proxy.go
- runtime.go
This PR adds implementations of the `experimental.FunctionListenerFactory` which have been useful to implement listeners in external projects depending on wazero. Bringing those building blocks to wazero will likely benefit other users.
Please take a look and let me know if you would like to see anything changed!
> experimental: add FunctionListener and FunctionListenerFactory implementations

- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_bench_test.go
- internal/engine/compiler/engine_test.go
This PR changes the context stack used by function listeners to use a vector instead of a linked list in order to reduce the memory footprint; creating the context stack items forced the compiler to put values on the heap, and the extra pointer increased by 50% the memory space needed to track the contexts (3 pointers per item vs 2 now).
```
goos: darwin
goarch: arm64
pkg: github.com/tetratelabs/wazero/internal/engine/compiler
│  /tmp/old   │              /tmp/new               │
│   sec/op    │   sec/op     vs base                │
CallEngine_builtinFunctionFunctionListener   37.45n ± 5%   11.10n ± 1%  -70.37% (p=0.000 n=10)
│  /tmp/old  │              /tmp/new              │
│    B/op    │   B/op     vs base                 │
CallEngine_builtinFunctionFunctionListener   24.00 ± 0% …
```
> experimental: optimize function listener context stack

- experimental/experimental.go
- experimental/listener.go
- experimental/listener_example_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/testing/enginetest/enginetest.go
Quick follow-up to https://github.com/tetratelabs/wazero/pull/1433. When benchmarking our use of `SourceOffset()`, we have noticed that it spends a significant amount of time in the binary search of the IR > offsets mapping:
Guest took ~60% of CPU time, so that's roughly 40% of the host time spent in the search. This makes it difficult for us to use it in a hot code path.
SourceOffset works in two steps: figure out the PC (usually cheap, as it's mostly stored on the stack), and resolve the PC into a source offset (the expensive part using `sort.Search`).
This change proposes to dissociate those two operations so that collecting the PC can be done on a hot code path, and computing the source offset can be done later, in a slower operation. I tried to make it clear in the comment that PC …
> experimental: expose PC

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- imports/wasi_snapshot_preview1/wasi_test.go
- internal/engine/compiler/engine.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/nonblock_unix.go
- internal/platform/nonblock_windows.go
- internal/platform/select.go
- internal/platform/select_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sys/sys.go
- internal/sys/sys_test.go
This adds `IsNonblock`, `SetNonblock` and `PollRead` to `platform.File`
allowing us to implement stdio files with the `platform.File` type
instead of alternate implementations.
> Adds IsNonblock SetNonblock PollRead to platform.File

- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_bench_test.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/testing/enginetest/enginetest.go
Following up on our discussion in #wazero-dev, I would like to suggest we remove the `error` parameter from `FunctionListener.After` since it is currently unused: wazero always passes the value `nil`.
I believe this change is worth it so users of `FunctionListener` do not have to concern themselves with understanding how to deal with the parameter nor write tests for code paths that will never be taken. It also means that we do not need to write documentation explaining why the parameter exists, and why it's currently unused.
Since this is still an experimental API, the breaking change should be acceptable, as well as considering bringing back a form of error handling in the future when we do have the ability to propagate errors to function listeners.
---
As part of this PR, I also made a …
> experimental: remove error parameter from FunctionListener.After

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- internal/gojs/fs.go
- internal/platform/dir.go
- internal/platform/dir_test.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/open_file_windows.go
- internal/platform/wrap_windows.go
- internal/sys/fs.go
- internal/sys/fs_test.go
- internal/sysfs/adapter.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/dirfs_unix_test.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
- internal/sysfs/rootfs.go
- internal/sysfs/rootfs_test.go
- internal/sysfs/sysfs_test.go
This moves the existing semantics of `Readdir` to `platform.File` which allows us to remove internal use of `fs.File` completely.
Notes:
* While this completes feature parity on platform.File, there is still work to do. Notably, we need to packaging more sensible (not split between platform and sysfs), and separate the os.File impls from things generably usable when backed by a `fs.File`. Finally, the windows implementation should be retrofit to our file type. All these work will proceed next and once done we can polish the shape for possibly experimental export. (ETA weeks probably)
* To retrofit the current impl to `fs.File` is a lot of work, so choosing not to do that, especially not in this PR. We can backfill coverage that isn't already redundant to our testslater, when things …
> Adds Readdir to platform.File and removes internal use of fs.FS

- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener.go
- experimental/logging/log_listener_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_bench_test.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/testing/enginetest/enginetest.go
Another follow up from our discussion in #wazero-dev, this PR modifies the signature of `FunctionListener.Before` to remove the returned `context.Context`.
This change aims to remove the internal context stack tracking return values of the `Before` methods. For context, I am copying a quote from the Slack discussion:
> While I find the API somewhat elegant, it has proven to be unusable in most cases where we've used FunctionListener because embedding values in a context requires at least one heap allocation, but sometimes two or more. The listeners often being on hot code paths of the guest program, and this heap allocation ends up being extremely costly.
>
> We worked around the issue by implementing internal stacks within the listeners, in the same way, that the wazero engine keeps …
> experimental: remove return value of FunctionListener.Before

- experimental/logging/log_listener_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/engine/interpreter/interpreter_test.go
- internal/integration_test/bench/hostfunc_bench_test.go
- internal/integration_test/spectest/spectest.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/function_definition.go
- internal/wasm/function_definition_test.go
- internal/wasm/host.go
- internal/wasm/module.go
- internal/wasm/module_instance.go
- internal/wasm/module_test.go
- internal/wasm/store.go
- internal/wasm/store_test.go
- runtime.go
`BuildFunctionDefinitions` is one of the most heavy allocation source during compilation,
which should be deferred when it's actually required (e.g. facing runtime errors).
This refactors the usage of FunctionDefinition, and defer the initialization of `[]FunctionDefinition`
to the time when `Module.FunctionDefinition` is called.
```
goos: darwin
goarch: arm64
Compilation_sqlite3/compiler-10      134.4m ± 1%   134.3m ± 5%       ~ (p=0.620 n=7)
Compilation_sqlite3/interpreter-10   45.75m ± 0%   45.67m ± 1%       ~ (p=0.456 n=7)
geomean                              78.42m        78.30m       -0.16%
│   old.txt    │ …
```
> Bulk Lazy initialization of FunctionDefinitions 

- internal/engine/compiler/arch.go
- internal/engine/compiler/compiler_bench_test.go
- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_memory_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/engine.go
These seem unneeded, so best to avoid.
> compiler: avoid some unsafe.Pointers

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
While testing the latest `python.wasm` from https://github.com/vmware-labs/webassembly-language-runtimes, we were not able to get the python shell working. Turns out this was a rights issue with `fd=0`.
Per https://github.com/WebAssembly/wasi-libc/blob/a6f871343313220b76009827ed0153586361c0d5/libc-bottom-half/sources/isatty.c#L13-L18, "A tty is a character device that we can't seek or tell on.".
This change re-use `fileRightsBase` and remove FD_SEEK and FD_TELL rights for all character devices.
> Fix base rights for character devices

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
Specifically O_CREATE|O_EXCL triggers EEXIST errors when re-opening a file. This ensures we clear the O_CREATE flag, as the goal is to re-create the file descriptor, not the file.
This also fixes a bug where we unconditionally write O_APPEND to any writable file in fdstat results.
> Clears O_CREATE when re-opening a file to set flags

- cmd/wazero/wazero.go
- cmd/wazero/wazero_test.go
This PR adds two new command line options to the `compile` and `run` subcommands: `-cpuprofile` and `-memprofile`.
The intent is to be able to generate CPU and memory profiles of wazero when compiling or running modules. Note that here we are generating profiles for the host (wazero) not the the guest module.
The motivation came from noticing that the compilation of the python version distributed at https://github.com/vmware-labs/webassembly-language-runtimes/releases/tag/python%2F3.11.3%2B20230428-7d1b259 was taking a noticeable amount of time. We can now use the `compile` command to investigate where time is being spent in wazero:
```
$ wazero compile -cpuprofile profile.out python-3.11.3.wasm
```
Performance profiles need to be written when the program exits, so I revisited the …
> wazero: allow cpu and memory profiling when compiling or running modules

- internal/asm/amd64/impl.go
- internal/asm/amd64/impl_1_test.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_1_test.go
This PR modifies the allocation of `nodeImpl` objects in the arm64 and amd64 assemblers to reduce memory utilization.
The core change is to use a slice of pointers instead of a slice of values. The issue with `[][N]nodeImpl` is that when using `append`, the Go runtime may grow the slice which copies the existing content, but the pointers taken to the previous backing array remain, which results in an amplification of memory usage.
This was further impacted by the page size of 1000 items, which quickly crossed the threshold of 1024 values used by the Go runtime to determine the growth factor, resulting in increasing the backing array 1.25x (instead of 2x for small slices). More frequent reallocations of the backing array meant more waste of space due to existing pointers retaining the …
> asm: optimize node allocation

- cmd/wazero/wazero.go
- internal/engine/compiler/engine.go
This PR modifies `compileWasmFunction` to avoid allocation a temporary slice of `asm.Node` for each function, and instead reuse a buffer across compiled functions.
Tested on the compilation of python, the change removes another ~20MB of the ~240MB that are allocated:
```
$ ./wazero compile -memprofile /tmp/profile.out ~/wasm/bin/python-3.11.3.wasm
```
```
$ go tool pprof -alloc_space -text -base /tmp/profile.base wazero /tmp/profile.out
File: wazero
Type: alloc_space
Time: May 14, 2023 at 12:28pm (PDT)
Showing nodes accounting for -17.15MB, 3.91% of 438.67MB total
Dropped 2 nodes (cum <= 2.19MB)
flat  flat%   sum%        cum   cum%
-32.10MB  7.32%  7.32%   -21.99MB  5.01%  github.com/tetratelabs/wazero/internal/engine/compiler.compileWasmFunction
3.52MB   0.8%  6.52%     3.52MB   0.8% …
```
> compiler: reuse asm.Node slice collecting NOP instructions for source mapping

- internal/engine/compiler/engine.go
This PR is a follow up to #1465. A lot of small heap allocations occur when initially growing the scratch space of `asm.Node`, and again when the size of the buffer causes the growth factor to fall from 2x to 1.25x. To reduce the memory footprint, we can pre-size the buffer instead of incrementally appending on each IR operation processed during function compilation.
Overall, the change has a small but measurable impact on the memory footprint when compiling Python:
```
File: wazero
Type: alloc_space
Time: May 15, 2023 at 12:08am (PDT)
Showing nodes accounting for -6408.61kB, 2.06% of 311668.95kB total
flat  flat%   sum%        cum   cum%
-10799.86kB  3.47%  3.47% -5504.92kB  1.77%  github.com/tetratelabs/wazero/internal/engine/compiler.compileWasmFunction
-3616.47kB  1.16%  4.63% …
```
> compiler: optimize allocation of asm.Node slice

- internal/asm/amd64/impl.go
- internal/asm/arm64/impl.go
- internal/asm/arm64/impl_1_test.go
- internal/asm/arm64/impl_3_test.go
- internal/asm/arm64/impl_4_test.go
- internal/asm/arm64/impl_6_test.go
- internal/asm/assembler.go
This PR implements a few optimizations detected by https://pkg.go.dev/golang.org/x/tools@v0.9.1/go/analysis/passes/fieldalignment/cmd/fieldalignment
The one I was most interested in was reducing the size of `arm64.nodeImpl` because it represents a significant source of memory allocations since we create so many of those objects.
```
File: wazero
Type: alloc_space
Time: May 15, 2023 at 1:24am (PDT)
Showing nodes accounting for -8.79MB, 2.99% of 294.14MB total
Dropped 7 nodes (cum <= 1.47MB)
flat  flat%   sum%        cum   cum%
-5.57MB  1.89%  1.89%    -5.57MB  1.89%  github.com/tetratelabs/wazero/internal/asm/arm64.(*nodePool).allocNode (inline)
-1.97MB  0.67%  2.56%    -5.52MB  1.88%  github.com/tetratelabs/wazero/internal/engine/compiler.compileWasmFunction
-1.50MB  0.51%  3.07% …
```
> compiler: optimize struct layout to reduce memory footprint

- internal/bitpack/offset_array.go
- internal/bitpack/offset_array_test.go
- internal/engine/compiler/RATIONALE.md
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
A major source of memory utilization came from the two `[]uint64` used to map source offsets to the native and wasm code https://github.com/tetratelabs/wazero/blob/main/internal/engine/compiler/engine.go#L1566-L1572
I modified the data structure to use a version of frame-of-reference and delta encoding described in https://lemire.me/blog/2012/02/08/effective-compression-using-frame-of-reference-and-delta-coding/
The data structure works well in this case because the values of code offsets are often close by, and since we don't reorder instructions, the offsets are naturally sorted. Ordering is important here, if the offsets were reordered the deltas between consecutive values would overflow, preventing values from being stored in small integers. If we end up reordering instructions (or if …
> compiler: compress code offsets

- cmd/wazero/wazero.go
- internal/version/version.go
This option has been useful to run the compilation multiple times in order to get more samples when recording CPU or memory profiles.
I don't have a lot of context on what the intent was for the `compile` subcommand, so maybe this option is out of place, so feel free to let me know if this should be done differently!
> wazero: add -count option to compile command

- imports/assemblyscript/assemblyscript.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- internal/gojs/fs.go
- internal/gojs/runtime.go
- internal/platform/dir.go
- internal/platform/file.go
- internal/platform/file_test.go
- internal/platform/osfile.go
- internal/sysfs/readfs.go
In the beginning, we checked by type if a command like read or write might succeed. Temporarily, we switched to exposing the AccessMode, which could be incorrect or drift. Now, we use the underlying error instead. Removing `platform.AccessMode` was a TODO left until the code was consolidated enough to address it coherently.
> Removes AccessMode from platform.File

- internal/platform/mremap_other.go
return value is not checked in internal/platform/mremap_other.go
for munmapCodeSegment(code)
Probably we forgot to run `make lint` on this one.
> platform: fix minor linting issue

- internal/testing/hammer/hammer.go
While working with hammer tests, I did notice type mismatch panics here but didn't actually send a fix for it. This will make sure any crashes such as OOM are reported as such instead of just deadlocking by panicing before being able to signal `finished`.
> Generically convert to string in hammer recovery

- .github/workflows/commit.yaml
Fixes #1476.
To be fair, being this a flaky test, we can't really be sure. However, the issue indeed seem to be related to pagefile size:
```
==6264==ERROR: ThreadSanitizer failed to allocate 0x000001000000 (16777216) bytes at 0x0400a2000000 (error code: 1455)
```
This GH issue indicates a GH Action that extends the pagefile size to address this issue https://github.com/actions/runner-images/issues/785
> ci: extend pagefile size on Windows

- .github/workflows/commit.yaml
- Makefile
- internal/engine/compiler/compiler_bench_test.go
- internal/engine/compiler/engine_bench_test.go
Some benchmarks were not running in CI. We enable them,
add them to the Makefile, and ensure that all are up-to-date.
---
looking into this. Essentially, the panic is due to codeSegment not being mmap'd; so this is enough:
```
func (j *compilerEnv) execBench(b *testing.B, codeSegment []byte) {
executable := requireExecutable(codeSegment)
b.StartTimer()
```
(unless you want to measure the mmap overhead too)
once this is done, there is another panic due to the change to how `functionDefintition`s are now loaded; looking into that too. Will open a PR.
as for running this in the CI, shall we add this to the Makefile?
```
bench:
@go test -run=NONE -benchmem -bench=. ./internal/engine/compiler/...
@go test -run=NONE -benchmem …
```
> compiler: fix benchmarks in compiler, engine; add to Makefile, update API calls

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/sys/fs.go
Decouple file fd from ReadDir so that it is possible to return
multiple ReadDir structs for a given fd (one per call to ReadDir).
Future work necessary to support e.g. directory-entry-stream
see https://github.com/WebAssembly/wasi-filesystem/blob/main/wit/types.wit#L787
> wasi: Move ReadDir out of the FileEntry structure.

- internal/asm/arm64/impl.go
- internal/asm/buffer.go
Go uses a scoring mechanism to determine which functions get inlined. Each statement gets assigned a scope and anything with a total below or equal to 80 gets inlined.
This PR modifies the `asm.CodeSegment` and `asm.Buffer` types to reduce the cost of functions that were on the hot path and allow inlining.
Chasing down inlining scores is somewhat of a dark art, but I was able to get the function scores by embedding `*CodeSegment` in `Buffer` so the call sites can see the inline-able leaf functions of `CodeSegment`, and the API remains identical from the standpoint of `Buffer`.
For the record, here's one way to ask the Go compiler to show functions that cannot be inlined in a package:
```
$ go build -gcflags '-m -m' ./internal/asm/ 2>&1 | grep 'cannot inline'
internal/asm/buffer.go:48:6: …
```
> compiler: allow inlining of internal/asm package functions

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- internal/sys/fs.go
- internal/sys/fs_test.go
As suggested [in this comment](https://github.com/tetratelabs/wazero/pull/1482#issuecomment-1554008113), the logic that populates the fields in `Readdir` is moved to methods of the `Readdir` struct. We are not exporting an interface yet.
- The fields are no longer exported. 
- There are new fields that are necessary to maintain the position of the cursor, and `func` fields to avoid embedding a `FileEntry`.
- We export 2 constructors: one takes a `FileEntry`, and it is defined in terms of the other; the other takes 2 `func`s `dirInit` and `dirReader` that are invoked when the initializing, resetting, advancing the cursor and filling the internal buffer.
Notably, for simplicity, entries are read in batches; `dirents` is always at most large `direntBufSize = 16` (currently), which is usually …
> wasi: move Readdir logics from fdReaddirFn to Readdir methods

- internal/platform/mmap_unix.go
- internal/platform/platform.go
zero length RX shouldn't happen and should be handled much earlier so this is unneeded
> platform: removes unnecessary code

- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
I have an `experimental.FunctionListener` like so:
```go
type functionListener struct {
depth int
}
func (f *functionListener) Before(ctx context.Context, mod api.Module, def api.FunctionDefinition, params []uint64, stackIterator experimental.StackIterator) {
fmt.Println(strings.Repeat(" ", f.depth), ">", def.DebugName())
f.depth++
}
func (f *functionListener) After(ctx context.Context, mod api.Module, def api.FunctionDefinition, results []uint64) {
f.depth--
fmt.Println(strings.Repeat(" ", f.depth), "<", def.DebugName())
}
func (f *functionListener) Abort(ctx context.Context, mod api.Module, def api.FunctionDefinition, err error) {
f.depth--
fmt.Println(strings.Repeat(" ", f.depth), "<", def.DebugName(), ":", err)
}
```
I have a simple program that calls `proc_exit`:
```go
// GOOS=wasip1 …
```
> engine: call FunctionListener.Abort in correct order

- internal/engine/compiler/impl_arm64.go
I've been looking at the assembler just for fun, and after a while trying to grok this function, I believe it is actually an issue with the comment and not my understanding. But if not, let me know and close this PR :)
The function does compute `"base + offsetArg + targetSizeInBytes"` for the purpose of a bounds check, but what it returns is `"base + offsetArg"`, I think
> compiled: fix compileMemoryAccessOffsetSetup comment

- site/content/community/users.md
Add https://github.com/stealthrocket/wasi-go to the list of community projects built on wazero.
> site: add wasi-go to the list of community projects

- imports/wasi_snapshot_preview1/testdata/gotip/wasi.go
- imports/wasi_snapshot_preview1/wasi_stdlib_unix_test.go
- internal/sysfs/file_test.go
- internal/sysfs/file_unix.go
- internal/sysfs/file_unsupported.go
- internal/sysfs/open_file_windows.go
- internal/sysfs/osfile.go
Adapt and add the test from [Go's WASI test suite nonblock.go](https://github.com/golang/go/blob/0fcc70ecd56e3b5c214ddaee4065ea1139ae16b5/src/runtime/internal/wasitest/testdata/nonblock.go
) for non-blocking I/O (pipes) to our own suite. Go (almost) straight to the syscall layer for `read()` on supported platforms; i.e., this is currently Unix-only. This also adds the field `fd` to the struct `osFile` because apparently `f.file.Fd()` resets the `O_NONBLOCK` flag on the fd /o\.
> wasi: add nonblock_test.go from gotip, fix nonblock read on Unix-like

- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_arm64_test.go
Fixes #1522 by avoiding the conditional jump to the trap, relying instead on a conditional jump over an unconditional jump.
As discussed in #1522, an alternative solution might be tracking the count of instructions and after a given N re-emit the trap that was cached at the beginning. But currently we don't have a mechanism to count the current number of instructions and iterating them all the time just to count would be costly; so we would need to modify the assembler to keep a count of the instructions.
Draft because I want to add a proper test case
```
❯ benchstat old/before_c.txt old/after_c.txt after_c.txt
goos: darwin
goarch: arm64
pkg: github.com/ncruces/go-sqlite3/vfs/tests/speedtest1
│ old/before_c.txt │          old/after_c.txt           │            after_c.txt             │
│ …
```
> compiler(arm64): avoid conditional jumps to the trap handler

- internal/engine/compiler/impl_amd64.go
As discussed in https://github.com/tetratelabs/wazero/issues/1522#issuecomment-1595028040 we're missing this `return` and emitting code that never runs (fixed for `arm64` in #1524).
> compiler(amd64): avoid emitting useless trap code

- internal/engine/compiler/engine.go
Previouly, each compiledFuction retain one pointer of compiledModule.
> engine: mitigates memory leak

- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/testdata/gotip/wasi.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- Allow nonblocking stdin to go through the "normal" file descriptor flow in `poll_oneoff`.
- Ensure stdio FDs are not closed on `SetAppend`: the default behavior for SetAppend() is to reopen, that is close and then open again: this causes an error on std streams. Just ignore the call on them.
Fixes #1538.
> wasi: improve stdin support for nonblocking, fix stdout

- .github/workflows/integration.yaml
Before, the cache key was based on the runner's version of Go, not gotip. gotip changes too frequently to use commit version, but we should still rebuild occasionally to ensure we are testing updates to the pending Go 1.21 release. This rebuilds weekly.
> Fixes where gotip GOOS=wasip1 tests are never rebuilt

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/wasi_bench_test.go
- internal/fsapi/dir.go
- internal/fsapi/file.go
- internal/sys/fs.go
- internal/sysfs/dir.go
- internal/sysfs/dir_test.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/file.go
- internal/sysfs/open_file.go
- internal/sysfs/open_file_js.go
- internal/sysfs/open_file_sun.go
- internal/sysfs/open_file_windows.go
- internal/sysfs/osfile.go
This performs a number of simplifying changes to files, particularly around directories. Some of them against my earlier advice to @evacchi!
* use POSIX errors only for readdir.
* stop using a separate subtype for windows osFile as the code is simpler with an if statement.
* stop using a separate table for directory stream descriptors. We aren't yet testing this works, so it is distracting. It was my bad advice to start doing this.
> Simplifies filesystem implementations

- internal/fsapi/dir.go
- internal/sysfs/dir_test.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
This defers re-opening the directory on `Seek(0, SeekStart)`.
I noticed that in the current code, [we unconditionally seek to zero before reading a directory](https://github.com/tetratelabs/wazero/blob/main/internal/sys/fs.go#L175-L178). I think this is incorrect and later will try to remove this, but meanwhile we can make the impact less.
Seek 0 costs a syscall or worse re-opening the file, if on windows or `fs.File`. Currently, we already re-open the directory on first call to `Readdir` on windows, so this behavior requires 2 re-opens at the moment.
The errno in `Seek` is mostly about the position/location. Zero is always valid, so we don't need to return an error immediately on that. If we defer a re-open, we get multiple benefits:
* we don't re-open a windows directory twice on …
> readdir: defer re-opening when Seek(0,SeekStart) on a directory

- RATIONALE.md
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/fs_unit_test.go
- internal/fsapi/file.go
- internal/sys/fs.go
- internal/sys/fs_test.go
This reverts to a design similar to, but more performant than 1.2.0+. Due to missing benchmarks, we accidentally regressed performance while attempting to clean the internal implementation of directory pagination.
For reasons described in #1529, the refactoring was going the wrong way anyway. This goes back to the better performing impl we had before, makes it perform even better, and backfills missing documentation.
```
goos: darwin
goarch: arm64
│ before-refactor.txt │             before.txt             │              now.txt               │
│       sec/op        │   sec/op     vs base               │   sec/op     vs base               │
_fdReaddir/embed.FS-12                          2.255µ ± 7%   2.879µ ± 6%  +27.70% …
```
> fd_readdir: reverts to special cased dirent cache

- internal/sys/fs.go
- internal/sys/fs_test.go
Fixes https://github.com/tetratelabs/wazero/issues/1564.
Commit https://github.com/tetratelabs/wazero/commit/53ce5eea830b3100af7ec8caa13bb38310c0afbf#diff-4fb3ce1d291b912fd6aa5e7f790040234a92683e313d1c757c0fce7be9e43320L397-L400 altered the effective behavior of `.WithFS()`; whereas prior to this patch a single, non-composite FS would always bind to "/" :
https://github.com/tetratelabs/wazero/blob/97d0d70b7321e5c16e584bbb6b3169032208bdec/internal/sys/fs.go#L469-L476
now, the `guestPath` is always used:
https://github.com/tetratelabs/wazero/blob/485b9e3ece346c2dd0912e1a54703d70fa10cdcf/internal/sys/fs.go#L420-L425
we resolve by overriding `guestPath` to `"/"` when `StripPrefixesAndTrailingSlash(guestPath) == ""`
> fs: empty guest path should bind to /

- RATIONALE.md
- imports/wasi_snapshot_preview1/fs.go
- internal/fsapi/dir.go
- internal/fsapi/file.go
- internal/fsapi/stat.go
- internal/fsapi/unimplemented.go
- internal/sys/fs.go
- internal/sys/lazy.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- internal/sysfs/readfs.go
- internal/sysfs/stat_bsd.go
- internal/sysfs/stat_linux.go
- internal/sysfs/stat_unsupported.go
- internal/sysfs/stat_windows.go
This centralizes known concerns about `Ino`, specifically `Dirent.Ino` before we expose our `Stat_t` experimental.
> Centralizes docs on Ino, specifically zero

- config.go
- runtime.go
wazero defines a helper function, `Instantiate`, which doesn't accept a `ModuleConfig`. This highlights that the default will call wasip1's `_start` function if it exists.
This does not fix #1561 but it documents the footgun we allow until that is fixed.
> explicitly documents ModuleConfig defaults to _start

- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/sysfs/file_test.go
- internal/sysfs/file_unsupported.go
- internal/sysfs/file_windows.go
- internal/sysfs/nonblock_unix.go
- internal/sysfs/nonblock_windows.go
- internal/sysfs/osfile.go
- internal/sysfs/select_windows.go
- internal/sysfs/select_windows_test.go
Improve #1500 with a simple observation, i.e. we really need non-blocking I/O only for pipes and sockets.
Now, for sockets we can use WinSock select, as for pipes, select_windows.go already imports PeekNamedPipe.
We combine PeekNamedPipe with a blocking Read only for those cases when PeekNamedPipe returns n > 0, which means a Read of n bytes won't block.
We special case n == 0 to return EAGAIN and
ERROR_BROKEN_PIPE as a non-failure (EOF reached).
We also introduce `isNonblock(f)` function, specialized on Windows to also check if the file is ModeNamedPipe; otherwise we would default to blocking anyway.
> wasi: nonblocking pipes on Windows

- internal/platform/mmap_other.go
Noticed this comment which seems to have drifted
- `syscall.Mmap` is called, not `Mprotect`
- The code is for darwin and freebsd, not linux
I tried updating to where I suspect the drift might have happened, but happy to tweak further or remove if it seems unneeded
> Fix drift in comment in mmap_other

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/integration.yaml
- .github/workflows/release.yaml
- .github/workflows/spectest.yaml
- imports/wasi_snapshot_preview1/fs_test.go
- internal/platform/platform.go
- internal/platform/platform_test.go
- internal/sysfs/file_test.go
- internal/sysfs/futimens.go
- internal/sysfs/futimens_windows.go
- internal/sysfs/open_file_windows.go
- internal/sysfs/sysfs_test.go
This is in preparation for the upcoming Go 1.21 release, which will also raise the floor Go version to 1.19.
> Changes build to test go 1.21rc2

- RATIONALE.md
- api/wasm.go
- experimental/wazerotest/wazerotest.go
- internal/wasm/module_instance.go
- internal/wasm/module_instance_test.go
- runtime.go
This adds `Module.IsClosed` to allow callers to prevent calling functions that would fail due to closed state.
Fixes #1561
> Exposes `Module.IsClosed` to prevent calling functions when closed

- internal/sysfs/dirfs.go
- internal/sysfs/file_unix.go
- internal/sysfs/file_unsupported.go
- internal/sysfs/file_windows.go
- internal/sysfs/osfile.go
- internal/sysfs/rename.go
- internal/sysfs/rename_test.go
- internal/sysfs/rename_windows.go
- internal/sysfs/stat_bsd.go
- internal/sysfs/stat_linux.go
- internal/sysfs/stat_test.go
- internal/sysfs/stat_unsupported.go
- internal/sysfs/stat_windows.go
- internal/sysfs/unlink.go
- internal/sysfs/unlink_test.go
- internal/sysfs/unlink_windows.go
- sys/stat.go
This makes windows rename implementation cheaper and also consolidates errno conversion. It is helpful to consolidate more before we expose our own Errno in #1582
Minor note, but this also unexports a few symbols that were only used in the same package.
> sysfs: cleanup windows rename

- imports/wasi_snapshot_preview1/testdata/gotip/wasi.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/sysfs/file_test.go
- internal/sysfs/file_unix.go
- internal/sysfs/file_unsupported.go
- internal/sysfs/file_windows.go
- internal/sysfs/osfile.go
resolves #1538 on non-Windows platforms. Windows will be addressed in #1579.
Using blocking `file.Write` APIs together with nonblocking I/O, causes stdout corruption under certain conditions. 
In particular, a reliable way to reproduce the issue is to capture the stdout of a sub-process running wazero. This PR fixes the writing issue by introducing `writeFd` (similar to `readFd` introduced in #1517), a function that just invokes the syscall directly when I/O is non-blocking. 
It also introduces the constants `nonBlockingFileReadSupported`, `nonBlockingFileWriteSupported`, superseding the generic `nonBlockingFileIoSupported`: the reason is still related to #1579, where Windows-related concerns will be addressed; for now we ignore the issue on that platform. However, because the test is …
> fs: nonblocking writes should use syscall.Write

- RATIONALE.md
- experimental/sys/syscall_errno_windows.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/platform/fdset.go
- internal/platform/fdset_test.go
- internal/platform/fdset_unsupported.go
- internal/platform/fdset_windows.go
- internal/platform/fdset_windows_test.go
- internal/sysfs/file_test.go
- internal/sysfs/file_windows.go
- internal/sysfs/select_test.go
- internal/sysfs/select_windows.go
- internal/sysfs/select_windows_test.go
- internal/sysfs/sock_windows.go
Further addresses #1500. 
Further work to improve the support for nonblocking I/O on Windows. This drops the special-casing for stdin, and instead checks if a handle is a named pipe (which includes sockets and other kinds of pipes); moreover, it further improves `_select` by introducing a proper wrapper for Winsock's select, which is BSD socket's select, and a compatible implementation of FdSet.
Because we need to distinguish between sockets, pipes, and regular files, the `FdSet` struct is actually wrapping 3 `WinSockFdSet`s, one for each type; the correct bucket is picket by probing the fd (win Handle) when it's passed to the `FdSet` method (e.g. `FdSet.Set(fd)`).
I think this can be further simplified, but I think now it is addressing some of the issues with the current implementation. …
> wasi: nonblocking I/O for sockets and pipes on Windows

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/fsapi/fs.go
- internal/fsapi/unimplemented.go
- internal/gojs/fs.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/futimens.go
- internal/sysfs/futimens_darwin.go
- internal/sysfs/futimens_linux.go
- internal/sysfs/futimens_test.go
- internal/sysfs/futimens_unsupported.go
- internal/sysfs/futimens_windows.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
futimes `AT_SYMLINK_NOFOLLOW` isn't universally supported. Before, we attempted to support it, but it was a bit hairy. It is better to take the hit of opening the file in the case we need to *not* follow symlinks than deal with something not very portable by default.
> Emulates AT_SYMLINK_NOFOLLOW instead of sometimes implementing it

- cmd/wazero/README.md
If you run the example of trying the wazero CLI via Docker as is, it will fail.
```
docker: Error response from daemon: create ./testdata/: "./testdata/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'
```
This is because relative paths cannot be specified for docker volumes.
Specifying the `$PWD` environment variable allows the reader to try it out smoothly.
> docs: replace relative path

- imports/wasi_snapshot_preview1/testdata/tinygo/wasi.go
there are a couple places we can't test TinyGo due to compilation fail.
> docs: adds issue links on TinyGo TODO

- internal/engine/compiler/impl_amd64.go
Very minor just happened to notice while reading. I think this was meant to say `, not pop`, but looking through the file, there are far more comments just of the `Note this is peek!` form so aligned with that
> Fix grammar in comment about peeking

- internal/engine/compiler/impl_amd64.go
Just noticed this when copy-pasting the block (and not the dozens of other correct ones XD). Wondering if anyone can help with backfilling a test for it?
> Return err instead of nil in amd64 store impl

- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- internal/fsapi/dir.go
- internal/fsapi/file.go
- internal/fsapi/unimplemented.go
- internal/sys/stdio.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- internal/sysfs/select.go
- internal/sysfs/select_darwin.go
- internal/sysfs/select_linux.go
- internal/sysfs/select_test.go
- internal/sysfs/select_unsupported.go
- internal/sysfs/select_windows.go
- internal/sysfs/select_windows_test.go
This changes `PollRead` to accept int32 timeoutMillis instead of using a pointer. I made a mistake earlier on this API, which wasn't being direct about units and also using nil where it isn't used that way at the syscall layer.
See https://github.com/tetratelabs/wazero/pull/1596
> sysfs: changes PollRead to accept int32 timeoutMillis

- site/content/specs.md
We forgot to update `specs.md` when we introduced support to `sock_*` functions.
> docs: update specs.md with sock_*

- RATIONALE.md
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- internal/fsapi/dir.go
- internal/fsapi/file.go
- internal/fsapi/poll.go
- internal/fsapi/unimplemented.go
- internal/sys/stdio.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- internal/sysfs/poll.go
- internal/sysfs/poll_darwin.go
- internal/sysfs/poll_linux.go
- internal/sysfs/poll_test.go
- internal/sysfs/poll_unsupported.go
- internal/sysfs/poll_windows.go
- internal/sysfs/poll_windows_test.go
- internal/sysfs/sock_windows.go
This migrates PollRead to Poll so that it can support read, write or a combination via flags. This should allow `poll_oneoff` to be implemented even if internally it may need to use a deadline decrementing approach to cycle through each file instead of via multiple at the same time.
The benefit of doing things this way is we don't need to top-level a concept of file descriptor, which complicates the design of `fsapi.FS` which is far easier to implement if there are no "multi-file" apis on it.
This intentionally doesn't implement the approach at the same time, as the goal is to create the api to implement. Doing so also puts a lot less pressure on the task to complete migration off syscall types.
> fsapi: migrates PollRead to Poll with Pflag

- imports/wasi_snapshot_preview1/fs.go
- internal/fsapi/file.go
- internal/fsapi/fs.go
- internal/fsapi/time.go
- internal/fsapi/unimplemented.go
- internal/gojs/fs.go
- internal/sys/lazy.go
- internal/sysfs/adapter_test.go
- internal/sysfs/bench_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/futimens.go
- internal/sysfs/futimens_darwin.go
- internal/sysfs/futimens_linux.go
- internal/sysfs/futimens_test.go
- internal/sysfs/futimens_unsupported.go
- internal/sysfs/futimens_windows.go
- internal/sysfs/osfile.go
- internal/sysfs/poll_windows.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
This decouples FS and File from the syscall package by passing through atim and mtim as numbers instead of structs. This makes it easier to integrate with `os.Chtimes` as well possible to compile with plan9.
In doing so, this unsupports the `UTIME_NOW` constant, which was problematic anyway. wasip1 defines `UTIME_NOW` as the value of the real-time clock, which isn't necessarily the same as the filesystem clock. By unsupporting `UTIME_NOW` we instead read from the correct clock.
> sysfs: decouples FS and File from the syscall package

- internal/sysfs/poll_test.go
- internal/sysfs/poll_windows_test.go
EINTR used to be ignored when `select` was used, but the check was
deleted during the migration to `poll`: looks like this made some tests flaky.
Some time-based tests for Windows also seem flakier, so we try to make them slightly more robust.
Fixes #1601 
> sysfs: restore check for EINTR in poll test, fix Windows tests

- cmd/wazero/wazero.go
- config_test.go
- experimental/sys/unimplemented.go
- experimental/sysfs/config_example_test.go
- experimental/sysfs/sysfs.go
- fsconfig.go
- fsconfig_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sys/fs_test.go
- internal/sys/sys_test.go
- internal/sysfs/adapter.go
- internal/sysfs/adapter_test.go
- internal/sysfs/dirfs.go
- internal/sysfs/dirfs_test.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/ino_windows.go
- internal/sysfs/readfs.go
- internal/sysfs/readfs_test.go
- internal/sysfs/sysfs_test.go
- internal/wasm/module_instance_test.go
This exports the experimental `sysfs.ReadFS` and `sysfs.AdaptFS` types, to developers can choose to embed them. This makes certain decoration use cases easier.
Note: We can't do the same without a risk of drift in `sysfs.DirFS`, but that isn't likely a problem as people are used to `os.DirFS` which also doesn't export its type.
> sysfs: Makes ReadFS and AdaptFS embeddable

- internal/engine/compiler/compiler_controlflow_test.go
- internal/engine/compiler/compiler_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_bench_test.go
- internal/engine/compiler/engine_cache.go
- internal/engine/compiler/engine_cache_test.go
- internal/engine/compiler/engine_test.go
- internal/engine/compiler/impl_amd64_test.go
- internal/engine/compiler/impl_arm64_test.go
- internal/gojs/compiler_test.go
- internal/integration_test/engine/memleak_test.go
Fixes #1600.
I'm not 100% sure why this is needed, but it's being done as well in:
https://github.com/tetratelabs/wazero/blob/1f8c908f1c61c964192c731af495caf1d720418c/internal/engine/compiler/engine.go#L495-L508
Somehow, not doing this prevents the `releaseCompiledModule` finalizer from running.
> compiler: fix compiledModule leak

- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- internal/sysfs/sock_test.go
- internal/sysfs/sock_unix.go
- internal/sysfs/sock_windows.go
follow up to #1606. Cleanup for some logic in `poll_oneoff` and add more test cases+fix nonblocking flags in sockets.
> wasi: add more test cases to poll_oneoff, cleanup impl

- experimental/sys/dir.go
- experimental/sys/file.go
- experimental/sys/unimplemented.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- internal/fsapi/file.go
- internal/fsapi/poll.go
- internal/fsapi/unimplemented.go
- internal/sys/fs.go
- internal/sys/lazy.go
- internal/sys/stdio.go
- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- internal/sysfs/poll.go
- internal/sysfs/poll_unsupported.go
- internal/sysfs/sock_test.go
- internal/sysfs/sock_unix.go
- internal/sysfs/sock_windows.go
Folks aren't currently on the same page on whether or not users should be able to implement the timeout parameter on `File.Poll` or whether it should always be externally controlled via a sleep loop which uses poll (immediate). Until we are sure internally, we shouldn't expose this for implementation, as it would be confusing for the same reason.
This migrates the non-blocking functionality back into the internal package.
One future way out could be to allow the user to decide if the backend is allowed to use the timeout parameter or not. Just as they control the FS, they could control a poller, which would then be able to span across both normal files and sockets. One could then be able to choose in the case of a single file and a specific known wasm, simply use the native timeout. In …
> Re-introduces internal fsapi.File with non-blocking methods

- .github/workflows/commit.yaml
- .github/workflows/examples.yaml
- .github/workflows/integration.yaml
- .github/workflows/release.yaml
- .github/workflows/spectest.yaml
- cmd/wazero/Dockerfile
- go.mod
As Go 1.21 has been released now, this updates the Go version used in the CI. 
Also, this updates our floor Go version to 1.19 following our support policy.
https://go.dev/blog/go1.21
> ci: use the latest Go 1.21

- experimental/wazerotest/wazerotest.go
- internal/engine/compiler/engine.go
- internal/wasm/module_instance.go
- internal/wasm/module_instance_test.go
- internal/wasm/store.go
- runtime.go
Now that we floor on Go 1.19, take advantage of atomic types:
https://tip.golang.org/doc/go1.19#atomic_types
Context #1299, #1321.
> Use atomic.Uint64.

- .github/ISSUE_TEMPLATE/bug-report.md
- RATIONALE.md
- imports/wasi_snapshot_preview1/fs_test.go
- internal/filecache/file_cache_test.go
- internal/gojs/compiler_test.go
- internal/integration_test/fuzz/go.mod
- internal/integration_test/vs/time/go.mod
- internal/integration_test/vs/wasmedge/go.mod
- internal/integration_test/vs/wasmtime/go.mod
- internal/platform/platform_test.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- internal/sysfs/sync_windows.go
- internal/version/testdata/go.mod
Sadly, this is mostly updating docs and comments (and some go.mod here and there), because the shortcomings of 1.18 are mostly still there with 1.19 😬 😅
> Upgrade floor Go version to 1.19 everywhere.

- internal/emscripten/emscripten.go
- internal/emscripten/emscripten_test.go
Fixes #1621 (at least for us in terms of flaky tests)
> emscripten: explicitly checks if an api.Function is not nil

- imports/wasi_snapshot_preview1/example/README.md
Hi :wave: , Just noticed a broken link in the example README
> Fix broken link in example README

- internal/emscripten/emscripten.go
- internal/engine/compiler/engine.go
- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/module_engine.go
- internal/testing/enginetest/enginetest.go
- internal/wasm/engine.go
- internal/wasm/module_instance_lookup.go
- internal/wasm/module_instance_lookup_test.go
- internal/wasm/store_test.go
> Lifts LookupFunction into ModuleInstance from ModuleEngine

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/testcases/testcases.go
Continues #1496.
This introduces the front-end and back-end for clz, ctz (in terms of rbit+clz).
It originally also introduced popcnt for the front-end, but this requires 
VCNT in the backend, which is probably worth its own separate PR.
Contextually, this also introduces a partial implementation for bitRR.
First PR to wazevo, so I am not entirely sure that the generated
code for the SSA and the backend is correct, let me know if there are errors,
I am really figuring out a lot of stuff, including the framework :)
> wazevo: adds bit count instructions clz, ctz

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/basic_block.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/builder_test.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/testcases/testcases.go
> wazevo: adds support for br_table

- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/integration_test/spectest/spectest.go
- internal/integration_test/spectest/v1/spectest.go
> Sets up spectest infra for wazevo

- experimental/sys/errno.go
- experimental/sys/syscall_errno.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/wasip1/errno.go
- Fixes a bug in handling the buffer when the write goes over the given limit. ERANGE should be returned.
- Removes dependency from the syscall package in `fs.go`, `experimentalsys.O_WRONLY` should be used instead (portability)
> wasi: fix symlink-related issues with path handling

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_constant_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_test.go
- internal/engine/wazevo/backend/isa/arm64/reg.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/testcases/testcases.go
adding bitwise ops and, or, xor (eor), rotr and rotl (as neg+rotr)
> wazevo: add bitwise ops and, or, xor, rotr, rotl

- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/ssa/pass.go
this refactors a bit around side effect, and introduces the "trappable" side effect
which represents an instruction that shouldn't be optimized out regardless of whether 
the result is used or not.
> wazevo(ssa): introduce trappable side effect

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/isa/arm64/util_test.go
- internal/engine/wazevo/engine.go
- internal/engine/wazevo/wazevoapi/debug_consts.go
this introduces the new debugging option to ensure that the compilation pipeline is deterministic. This is disabled by default but can be enabled when debugging.
#1496
> wazevo: introduces the deterministic compilation verifier

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/regalloc/assign.go
- internal/engine/wazevo/backend/regalloc/assign_test.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/wazevoapi/debug_consts.go
In preparation for passing "stack-page-guard" spectest,
this refactors a bit of regalloc logic.
#1496
> wazevo(regalloc): sort liveNodes by begin PC

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/compiler_lower_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
- internal/engine/wazevo/backend/regalloc/api.go
- internal/engine/wazevo/backend/regalloc/api_test.go
- internal/engine/wazevo/backend/regalloc/coloring.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/ssa/basic_block.go
This fixes the handling of phi nodes (in our terminology SSA block arguments)
in the register allocation especially by implementing the missing logic in the
liveness analysis. 
As a result, wazevo, our new optimizing compiler #1496, finally has started passing 
all the WebAssembly v1 specification tests on AArch64.
> wazevo(regalloc): fixes phi node handlings

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/testcases/testcases.go
moves forward #1496 with support for non-trapping floating point conversions to integer.
This also changes the signature of `lowerOpcode(op)` to `lowerCurrentOpcode()`. In order to parse `wasm.OpcodeMisc*TruncSat*` etc. it is necessary to parse `wasm.OpcodeMiscPrefix` first, and then advance to the next opcode, which will be in the range `[0x00..0x07]` They cannot be parsed otherwise, because then these opcodes would be mismatched in the `switch` statement for other unrelated opcodes.
Now `lowerCurrentOpcode()` instead moves `pc`itself; for this reason, all the related logic such as the debugging statements are now moved to this procedure, and  `return` statements had had to be changed to `break`s, otherwise the final `pc++` would be skipped in many cases.
> wazevo: add nontrapping fp conversions (wasm v2)

- Makefile
- internal/engine/wazevo/config.go
- internal/engine/wazevo/e2e_test.go
- internal/integration_test/fuzz/README.md
- internal/integration_test/fuzz/fuzz/Cargo.toml
- internal/integration_test/fuzz/fuzz/fuzz_targets/memory_no_diff.rs
- internal/integration_test/fuzz/fuzz/fuzz_targets/no_diff.rs
- internal/integration_test/fuzz/fuzz/fuzz_targets/validation.rs
- internal/integration_test/fuzz/fuzz/fuzz_targets/wazero_abi.rs
- internal/integration_test/fuzz/wazerolib/lib.go
- internal/integration_test/fuzz/wazerolib/nodiff.go
- internal/integration_test/fuzz/wazerolib/validate.go
now we can run the fuzzing by passing the env:
```
$ WAZERO_FUZZ_WAZEVO=1 cargo fuzz run no_diff
```
#1496
> fuzz: make it possible to fuzz wazevo

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_entry.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_constant.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
- internal/engine/wazevo/backend/isa/arm64/reg.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
- internal/engine/wazevo/backend/regalloc/reg.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/module_engine.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/ssa/type.go
This makes wazevo pass the simd_const spectest.
#1496
> wazevo: adds initial support for SIMD vectors

- .github/workflows/commit.yaml
This should make drifts and unnecessary change in spectest dir fail on CI
> ci: builds spectests before check

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go
- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/engine.go
- internal/engine/wazevo/engine_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/module_engine.go
- internal/engine/wazevo/wazevo_test.go
- internal/engine/wazevo/wazevoapi/exitcode.go
- internal/engine/wazevo/wazevoapi/offsetdata.go
- internal/integration_test/engine/adhoc_test.go
> wazevo: adds support for context cancelation

- .github/workflows/integration.yaml
Allows respecting patch version
Interestingly, it seems that based on the randomly selected runner, the go version can be different
https://github.com/tetratelabs/wazero/actions/runs/6180785720/job/16777777783?pr=1709
https://github.com/tetratelabs/wazero/actions/runs/6180785720/job/16778006464?pr=1709
One way to not have this happen is `check-latest`. It's funny how they recommend `false` for stability :P
https://github.com/actions/setup-go#check-latest-version
> Use setup-go output for standard library test key

- internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_call.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go
- internal/engine/wazevo/backend/isa/arm64/unwind_stack.go
- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/call_engine_test.go
- internal/engine/wazevo/engine.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/machine.go
- internal/engine/wazevo/wazevo_test.go
- internal/engine/wazevo/wazevoapi/offsetdata.go
this makes it possible to call Go functions for any length of parameters,
and this enables the function listeners impl in the subsequent PR.
#1496
> wazevo: refactors calling Go convention

- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- internal/engine/compiler/engine.go
- internal/engine/compiler/engine_test.go
- internal/engine/interpreter/interpreter.go
- internal/integration_test/engine/adhoc_test.go
as discussed offline in the Gophers slack, the Parameters API on 
the experimental StackIterator hasn't been used in practice, and 
also is difficult to implement in the optimizing compiler.
Therefore, we've decided to delete it from the API.
> experimental: removes Parameters API from StackIterator

- internal/engine/wazevo/ssa/instructions.go
erroneously merged #1715 without restoring `sideEffectNone` to `Vbitselect` (#1496)
> wazevo: fix side effect for OpcodeVbitselect

- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
continues #1496
passes `simd_boolean` spec tests, adds related instructions: `addv`, `uminv`, `umaxp` `dup`, `ext`, `zip`, `sshr`, `cmeq(zero)`
> wazevo: passes simd_boolean spec tests

- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
continues #1496. Passes min/max/neg/arithmetic tests for f32x4, f64x2, adding the necessary instructions. 
> wazevo: passes f32x4, f64x4 vector arithmetic spec tests

- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- continues #1496 
- addresses an incorrect usage of registers in #1738, removes useless instruction
> wazevo: fix simd bit shift test temp reg usage

- internal/wasm/host.go
- internal/wasm/module.go
- internal/wasm/module_test.go
- runtime.go
Previously the ModuleID only reflected the existence of listeners per module (i.e. len(listeners) >0 or not),
but that might be problematic if a user changes the listeners set before/after compilation.
> Changes ModuleID for listener existence per function

- internal/wasm/memory.go
- internal/wasm/table.go
This was _somehow_ introduced in the past, but the
reality is that the mutex only used during Grow doesn't
solve any concurrent issue at all and still could result in
crash when the module was accessed incorrectly concurrently.
The proper synchronization mechanism must be provided by
threads proposal, and this mutex usage can be removed.
> Removes unnecessary mutex on Table/Memory Instance

- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_test.go
pointed out by the fuzzer
#1496
> wazevo(arm64): do not optimize out Ireduce

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/pass_test.go
detected by the fuzzer that immediate shift with zero cannot be encoded in arm64.
#1496
> wazevo(ssa): eliminates no-op shifts by constant zeros

- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/ssa/instructions.go
This relaxes the assertion in https://github.com/tetratelabs/wazero/pull/1763
#1496
> wazevo(arm64): support for zero imm lsl

- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/call_engine_test.go
> wazevo(arm64): fixes Fcopysign instruction order

- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
> wazevo(arm64): fixes 32bit shifted operand with const amount

- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
This follows up on  #1766 and does some clean-ups.
#1496
> wazevo: adds VZeroExtLoad for type safe SIMD zeros loads

- imports/emscripten/emscripten.go
- imports/emscripten/emscripten_example_test.go
rewrote emscripten examples to use InstantiateForModule.
#1781
> deprecated emscripten.Instantiate and it's related functions in favor of InstantiateForModule

- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
> wazevo(regalloc): removes map usage in real reg tracking

- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/regalloc/reg.go
- internal/engine/wazevo/backend/regalloc/reg_test.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
- internal/engine/wazevo/backend/regalloc/spill_handler_test.go
This PR explores changing the data structure used for _last uses_ in block info.
The change takes the compilation of Python 3.11 with Wazevo from 40s to 28s.
I added a bitset to perform fast checks of virtual registers on the hot code path of `beginUpAndMarkStack`, which yielded most of the gains (changing from a map to a simple array only gave a ~17% improvement).
Note that even with this change, the hottest code path is still `beginUpAndMarkStack`, but we're starting to see a more balanced time spent in various parts:
Based on what I'm seeing in the current profile, we're starting to see the impact of indirect function calls through method interfaces and such (e.g., 7%+ spent in calling `Block.ID`). There is likely some room for reducing the number of those calls on the hottest code …
> wazevo: add VRegTable data structure

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
This a small optimization that I noticed while going through the code: the regalloc `kills` are always derived from `lastUses`, which can avoid tracking the program counters in `kills` and turn the collection into a set that is only tracking virtual registers. When we need the `kills` program counters, we can look them back up into `lastUses`.
On the Python compilation, this saves 55MB of a 248MB cumulative allocation:
```
github.com/tetratelabs/wazero/internal/engine/wazevo/backend/regalloc/regalloc.go
Total:    248.01MB   248.01MB (flat, cum)  1.99%
249            .          .           			if _, ok := outs[use]; !ok { 
250     248.01MB   248.01MB           				info.kills[use] = pc 
251            .          .           			} 
252            .          .           		}) 
253            . …
```
> wazevo: reduce memory footprint of regalloc kills

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
Building on #1804, this PR modifies how block info values are tracked to reduce the memory footprint.
On the compilation of Python, the change reduces by 3.8GB the amount of memory allocated and allocates 61% fewer objects:
```
Type: alloc_space
Time: Oct 19, 2023 at 11:35am (PDT)
Showing nodes accounting for -3827.23MB, 18.33% of 20878.78MB total
Dropped 143 nodes (cum <= 104.39MB)
flat  flat%   sum%        cum   cum%
-2373.80MB 11.37% 11.37% -2362.30MB 11.31%  github.com/tetratelabs/wazero/internal/engine/wazevo/wazevoapi.(*Pool[go.shape.struct { github.com/tetratelabs/wazero/internal/engine/wazevo/ssa.id github.com/tetratelabs/wazero/internal/engine/wazevo/ssa.BasicBlockID; github.com/tetratelabs/wazero/internal/engine/wazevo/ssa.rootInstr …
```
> wazevo: optimize regalloc block info memory

- internal/engine/wazevo/backend/regalloc/reg.go
- internal/engine/wazevo/backend/regalloc/reg_test.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
Based on #1803, this PR changes the data structure used to represent regalloc kills from a map to a bitset, which reduces the memory footprint by 190MB on the compilation of Python:
```
github.com/tetratelabs/wazero/internal/engine/wazevo/backend/regalloc/regalloc.go
Total:   -192.65MB    15.38MB (flat, cum) 0.062%
250    -192.65MB  -192.65MB           			if _, ok := outs[use]; !ok { 
251            .   208.03MB           				info.kills.Insert(use) 
252            .          .           			} 
253            .          .           		}) 
254            .          .            
255            .          .           		if wazevoapi.RegAllocLoggingEnabled { 
256            .          .           			fmt.Printf("\nfinalized info for block[%d]:\n%s\n", blk.ID(), info.Format(a.regInfo)) 
```
> wazevo: repesent regalloc kills with a bitset

- internal/engine/compiler/engine_cache.go
Not sure how this was never noticed, trying to run the same thing over and over in response to request with cache enabled would OOM very quickly…
> compiler: add munmap finalizer on cache hits to avoid memory leak

- internal/filecache/file_cache.go
This prevents e.g. getting killed during writing from leaving incomplete/corrupt data in the cache directory.
> filecache: use rename for an atomic write

- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/integration_test/fuzzcases/fuzzcases_test.go
> wazevo: fuzz, select does not return the correct value for vectors

- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_test.go
> wazevo(arm64): places spill slots below clobbered regs

- internal/engine/wazevo/backend/regalloc/regalloc.go
> wazevo(regalloc): specifies the VReg in swapping

- imports/wasi_snapshot_preview1/fs_test.go
- internal/sysfs/osfile.go
This commit fixes a buf when `fd_fdstat_set_flags` would erroneously truncate an open file if it is opened with the O_TRUNC flag.  This happens because the O_TRUNC flag causes the file to be truncated when it is opened.
This fixes https://github.com/tetratelabs/wazero/issues/1862
> Fix `fd_fdstat_set_flags` truncating with O_TRUNC

- imports/wasi_snapshot_preview1/fs_test.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
This commit fixes `fd_fdstat_set_flags` resetting the fd offset due to it reopening the file every time.  This fix gets the current offset before reopening and restore the offset with seek. This addresses https://github.com/tetratelabs/wazero/issues/1865.
NB: A couple of existing tests are actually spec'd wrong. To fix, I introduced addition `Seek` calls before checking removing append flag.
> wasi: resets offsets in reopen

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
- internal/engine/wazevo/wazevoapi/debug_options.go
> wazevo: cleans up debug options

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
This commit handles potential `EFBIG` returned from the OS and maps it to WASI's `fbig`.  It also fixes an integer truncation bug in the `fd_filestat_set_size` handler.
fixes https://github.com/tetratelabs/wazero/issues/1870
> wasi: Handle EFBIG from OS on`fd_filestat_set_size`

- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_test.go
This allows the optimizing compiler to pass all GOOS=wasip1 tests.
```
>> wazero run -optimizing-compiler -mount=/:/ -env PWD=$PWD ./reflect.test -- -test.short
PASS
```
> wazevo(arm64): relocations for large conditional branches

- .github/workflows/integration.yaml
- internal/engine/wazevo/call_engine.go
This adds QEMU to the stdlib flows for zig, tinygo and go/wasip1. 
QEMU is used to test the optimizing compiler on arm64 (the only arch currently supported).
The new steps set the `-optimizing-compiler` flag on the `wazero` CLI introduced with #1869 and invoke it through a container.
> ci: run integration tests against the optimizing compiler (linux/arm64)

- Makefile
Upgrading to go 1.21.5 causes the following `golangci-lint` error in the source tree `(`max()` new pseudo-function unrecognized):
```
❯ make format lint
../../../../sdk/go/src/net/http/internal/chunked.go:79:14: undefined: max (typecheck)
cr.excess = max(cr.excess, 0)
^
make: *** [lint] Error 1
```
Upgrading to the latest version of `golangci-lint` fixes the problem.
> deps: bump golangci-lint to v1.55.2

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/util_test.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
- internal/engine/wazevo/engine.go
- internal/engine/wazevo/wazevoapi/debug_options.go
- internal/engine/wazevo/wazevoapi/perfmap.go
- internal/engine/wazevo/wazevoapi/perfmap_disabled.go
- internal/engine/wazevo/wazevoapi/perfmap_enabled.go
This allows us to check per-basic block based hot paths perf like the below:
> wazevo: adds `perfmap` build tag to write perf-map

- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
This patch changes the lowering of memory access and introduces a very
simple bounds check elimination which is performed per Basic Block.
For example, the following assembly, which is extracted from 
Zig's memset implementation without bulk-memory feature,
```wat
loop ;; label = @2
local.get 4
local.get 1
i32.store8 offset=7
local.get 4
local.get 1
i32.store8 offset=6
local.get 4
local.get 1
i32.store8 offset=5
local.get 4
local.get 1
i32.store8 offset=4
local.get 4
local.get 1
i32.store8 offset=3
local.get 4
local.get 1
i32.store8 offset=2
local.get 4
local.get 1
i32.store8 offset=1
local.get 4
local.get 1
...
end
```
needs the boundary check only at the first i32.store8 inside the loop because
the access range can be statically known to be lower than the previous ones.
In short, with …
> wazevo(frontend): simple bounds check elimination on mem access

- .github/workflows/integration.yaml
- .gitignore
- internal/integration_test/stdlibs/Makefile
- internal/integration_test/stdlibs/README.md
- internal/integration_test/stdlibs/bench_test.go
Creating in draft for early feedback
> bench: add stdlib benchmark old vs new compiler

- .github/workflows/integration.yaml
- internal/integration_test/stdlibs/bench_test.go
> Flattens std lib test cases

- internal/sysfs/file_windows.go
- internal/sysfs/sock.go
- internal/sysfs/sock_supported.go
- internal/sysfs/sock_unix.go
- internal/sysfs/sock_unsupported.go
- internal/sysfs/sock_windows.go
The current implementation of WASI sockets differs between Unix and Windows. On the Unix version, we save underlying FD to the struct, while on Windows we keep the Listener/Connection as a field, and invoke `Conn.Control(func(fd))`.
The reason for the difference on Windows, is that Windows won't return a valid file handle, because the Dup implementation is a no-op. However, further somewhat related testing (see #1891) highlighted that the Unix strategy does not really work: the FD that is being saved, is not really the underlying FD of the Listener/Connection struct, but rather the FD of a duplicated File. 
Because the duplicate is not being saved, but only the FD, it *looks like* eventually the new File instance is collected, invalidating the underlying FD. This is only visible in …
> wasi: sockets, use Conn.Control on Unix, too; align to Windows

- internal/sysfs/file_windows.go
- internal/sysfs/sock_test.go
Current `readSocket` function for WASI sockets is implemented incorrectly on Windows and WASI polling an async socket for a long time will eventually get `ERROR_WORKING_SET_QUOTA` (1453):
```
Insufficient quota to complete the requested service.
```
A call to `GetOverlappedResult` is expected after each `ERROR_IO_PENDING` returned by `ReadFile` and that is what's missing in the current implementation. Besides that, `ReadFile` would create a background worker to keep on trying reading from the handle into the `buf`, which could result in data loss if we don't keep tracking of it. So we add a call to `WSAPoll` before calling `ReadFile` to observe how many bytes are ready to be read. 
In this pull request, we modify how `readSocket` in `internal/sysfs/file_windows.go` is implemented by …
> wasi: sockets, use WSAPoll and GetOverlappedResult on Windows

- internal/engine/wazevo/backend/isa/amd64/instr.go
- internal/engine/wazevo/backend/isa/amd64/instr_encoding.go
- internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/amd64/operands.go
- arm64: encode unaryRmR
- amd64: encode not,neg
- amd64: introduce encodeEncEnc, rexInfo.encode() accepts arbitrary uint8
- amd64: mulHi, fix formatting for amode + _64
some refactoring as well. E.g. introduce encodeEncEnc and encodeEncMem, which are generalized versions of, respectively encodeRegReg and encodeRegMem, where instead of a `regEnc` a `uint8` is accepted. 
Notice that in some cases it is still necessary to treat the uint8 as registers; instead of arbitrarily casting I have added accessors `regEncoding(uint8)` and `regRexBit(uint8)`; open to suggestions if this makes no sense / alternative approaches are preferred.
> wazevo(amd64): encode unaryRmR, not, neg, mulHi, shiftR

- internal/engine/compiler/compiler_bench_test.go
- internal/engine/compiler/compiler_initialization_test.go
- internal/engine/compiler/compiler_memory_test.go
- internal/engine/compiler/compiler_post1_0_test.go
- internal/engine/compiler/compiler_vec_test.go
- internal/engine/compiler/impl_amd64.go
- internal/engine/compiler/impl_arm64.go
- internal/engine/compiler/impl_vec_amd64_test.go
- internal/engine/compiler/impl_vec_arm64_test.go
- internal/wasm/memory.go
- internal/wazeroir/compiler.go
- internal/wazeroir/compiler_test.go
When looking at arm64 code for threads, I believe this is the only invasive change to current code, then it will be just implementing new ops. So sending this separately first.
Currently, we cache the buffer length into the call engine on every function preamble, which is also updated when calling memory.Grow, but this does not work when there are concurrent accesses. So now, when memory is shared, it is assumed there may be concurrent grows and length is read directly every time.
Unlike wazerox, I have made this happen only with shared memory (there I actually removed the length cache from the call engine) so this code is somewhat new to me, notably the large-ish `MemoryType` change.
> threads: for arm64, when shared memory ignore memory length cache

- experimental/features_example_test.go
- internal/asm/amd64/consts.go
- internal/engine/compiler/engine.go
- internal/wasm/memory.go
- internal/wasm/module_instance.go
When porting code, I thought I was cleaning things up by putting in the nicely named "ensure resources closed" method but just broke it... That function is called when child modules are closed so can't be responsible for memory closing.
Fixes #1936
> threads: close shared memory with store, not child modules

- internal/wasm/memory.go
- internal/wasm/memory_test.go
Also makes sure mmapped buffer is used for munmap, not sliced buffer. Technically sliced buffer is ok, but not if it's still empty `b[:0]` it seems.
> threads: don't use mmap for zero memory

- internal/engine/wazevo/backend/isa/amd64/abi.go
- internal/engine/wazevo/backend/isa/amd64/abi_entry_amd64.s
- internal/engine/wazevo/backend/isa/amd64/abi_entry_preamble.go
- internal/engine/wazevo/backend/isa/amd64/abi_entry_preamble_test.go
- internal/engine/wazevo/backend/isa/amd64/abi_go_call.go
- internal/engine/wazevo/backend/isa/amd64/abi_go_call_test.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/lower.go
there's mismatch in arg/res register order
> wazevo(amd64): fixes calling conv to match Go runtime

- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/e2e_test.go
- internal/engine/wazevo/engine.go
- internal/engine/wazevo/engine_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/module_engine.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/testcases/testcases.go
- internal/engine/wazevo/wazevo_test.go
- internal/engine/wazevo/wazevoapi/exitcode.go
- internal/engine/wazevo/wazevoapi/offsetdata.go
Not too sure what I'm doing so sending out lowering of one atomic op to understand the pattern, hopefully it will be enough to do the rest in the later PR.
I'm trying to compare to wasmtime but not sure if I'm doing something wrong. For this wat file
```
(module
(import "console" "log" (func $log (param i32)))
(func
(i32.const 5)
(i32.const 0)
(i64.const 10)
memory.atomic.wait32
(call $log)
)
(memory 1 1 shared)
(export "" (func 0))
)
```
I get
```
❯ target/debug/clif-util wasm --target aarch64-apple-darwin test.wat -p -t
function u0:1(i64 vmctx) fast {
gv0 = vmctx
gv1 = load.i64 notrap aligned readonly gv0
sig0 = (i32, i64 vmctx) fast
fn0 = u0:0 sig0
block0(v0: i64):
@0038                               v1 = iconst.i32 5
@003a                               v2 = iconst.i32 0
@003c …
```
> wazevo: adds support for memory wait

- .github/workflows/integration.yaml
- internal/integration_test/stdlibs/bench_test.go
somehow tinygo is still not passing yet
> Enables Zig/wasip1 stdlib trests for wazevo on amd64

- internal/engine/wazevo/ssa/basic_block_sort.go
- internal/engine/wazevo/ssa/basic_block_sort_old.go
- internal/engine/wazevo/ssa/pass.go
This starts using `slices.SortFunc` (thanks to @achille-roussel) to avoid
allocations during `ssa.passSortSuccessors`. As a result for zig stdlib compilation,
huge amount of allocations has been eliminated.
```
│    old.txt    │             new.txt              │
│     B/op      │     B/op       vs base           │
Zig/optimizing/Compile/test-opt.wasm-10   513.2Mi ± ∞ ¹   506.6Mi ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│    old.txt    │             new.txt             │
│   allocs/op   │  allocs/op    vs base           │
Zig/optimizing/Compile/test-opt.wasm-10   1201.3k ± ∞ ¹   781.8k ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 …
```
> wazevo(ssa): avoids allocation during natural order sort

- internal/engine/wazevo/ssa/basic_block_sort.go
Follow-up to https://github.com/tetratelabs/wazero/pull/2024; it's possible that this isn't important, but it could prevent pathological cases where the sort algorithm gets confused because the compare function doesn't provide total ordering.
> return 0 is compare function of sortBlocks when blocks are equal

- internal/engine/wazevo/backend/isa/amd64/machine_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/basic_block.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/builder_test.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/pass_test.go
- internal/engine/wazevo/ssa/vs.go
- internal/engine/wazevo/wazevoapi/pool.go
- internal/engine/wazevo/wazevoapi/pool_test.go
cut huge alloc counts: 
```
│   old.txt   │            new.txt             │
│   sec/op    │   sec/op     vs base           │
Zig/optimizing/Compile/test-opt.wasm-10   5.136 ± ∞ ¹   5.130 ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│    old.txt    │             new.txt              │
│     B/op      │     B/op       vs base           │
Zig/optimizing/Compile/test-opt.wasm-10   487.4Mi ± ∞ ¹   472.1Mi ± ∞ ¹  ~ (p=1.000 n=1) ²
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│   old.txt    │             new.txt             │
│  allocs/op   │  allocs/op …
```
> wazevo(ssa): reuse slices

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
With this patch, arm64 backend can lower `Icmp(Band(x,y), 0)` pattern to 
one ANDS instruction.
This patter appears, for example, the alignment check in threads support and 
the old compiler was handling it better than the optimizing compiler:
https://github.com/tetratelabs/wazero/blob/ccf60cb7a9796fdc52ff771c3bc7e7c72e5a0131/internal/engine/compiler/impl_threads_arm64.go#L40
This patch applies the same optimization to a general lowering logic around branching.
For Zig binary, this amounts approximately up to 1% of the total conditional branches.
In other words, one instruction is optimized out for 1% of all conditional branches.
After this, I will port this to amd64 as well.
Special thanks to @anuraaga
> wazevo(arm64): lower Icmp(Band(x,y), 0) to single ANDS instruction

- api/wasm.go
- experimental/wazerotest/wazerotest.go
- imports/wasi_snapshot_preview1/args_test.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/environ_test.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/random_test.go
- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/e2e_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/store_test.go
- runtime_test.go
Fixes https://github.com/tetratelabs/wazero/issues/1852 by changing the signature of
api.Memory.Size to return 64bit int, rather than 32bit to avoid overflow.
This is _kind of_ breaking change but in anyway it should be almost harmless 
plus we are about to release 2.0 next month.
> Changes the type of Size() to uint64

- internal/filecache/file_cache.go
- internal/filecache/file_cache_test.go
This might be a fix for #2039 
Since https://github.com/tetratelabs/wazero/pull/1816, the file cache appended `.tmp` to the file path name to avoid leaving incomplete files in the cache when an error occurs. However, this is the definition of `os.Create`:
```go
func Create(name string) (*File, error) {
return OpenFile(name, O_RDWR|O_CREATE|O_TRUNC, 0666)
}
```
File creation does not include the `O_EXCL` flag, which means that when the file already exists, it is opened and truncated.
This PR changes the file cache to use `os.CreateTemp` instead, which guarantees that the file name will be unique by injecting a random string in the file name and opening the file with `O_EXCL` to prevent racing calls that would accidentally use the same name from both suceeding:
```go
func CreateTemp(dir, …
```
> filecache: use os.CreateTemp to create files

- internal/engine/compiler/engine_cache.go
- internal/engine/compiler/engine_cache_test.go
- internal/engine/wazevo/engine_cache.go
- internal/engine/wazevo/engine_cache_test.go
follow up to #2088. Add a trailing crc field after the serialized executable code in the file cache disk format, to ensure that a corrupt file cache won't cause run-time errors, and fail early.
as suggested by @ncruces we use Castagnoli, since it has hardware support.
> filecache: add trailing crc to serialized executable code

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/isa/amd64/abi.go
- internal/engine/wazevo/backend/isa/amd64/lower_constant.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/lower_constant.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
on arm64, constant block args were loaded via multiple instructions,
which makes it harder for me to optimize the regalloc's bottleneck.
Therefore, this introduces load_const_block_arg pseudo instruction,
which will be lowered at post-regalloc into multiple instructions when needed.
> wazevo(backend): block arg as one instruction before regalloc

- internal/sysfs/osfile.go
This is a tiny fix of a compile-time check on osFile.
It's not like it _matters_ all that much, as the missing method would be caught in other layers anyway, but when the check is there, it should be correct :)
> sysfs: fix compile-time check on osFile

- api/wasm.go
- examples/allocation/rust/greet.go
- examples/allocation/tinygo/greet.go
- examples/allocation/zig/greet.go
- experimental/wazerotest/wazerotest.go
- imports/assemblyscript/assemblyscript.go
- imports/wasi_snapshot_preview1/args_test.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/environ_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/random.go
- imports/wasi_snapshot_preview1/random_test.go
- imports/wasi_snapshot_preview1/sock.go
- imports/wasi_snapshot_preview1/sock_test.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/wazevo/e2e_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/vs/runtime.go
- internal/logging/logging.go
- internal/wasip1/logging/logging.go
- internal/wasm/memory.go
Since #2074 changed the type of `Size() uint64` to we should probably change the type of `Read(offset uint32, byteCount uint64) ([]byte, bool)`. Otherwise, there's no API that gets entire buffer, if it covers the entire address range.
As discussed on [slack](https://gophers.slack.com/messages/C04CG4A2NKX/p1708414573291929?thread_ts=1708401526.868449).
> Changes Read to receive uint64 byte count.

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
This cuts the unnecessary one store instruction per local function call, hence results in the executable size reduction (around 50kb)!
> wazevo(frontend): store module context for only imported calls

- api/wasm.go
- examples/allocation/rust/greet.go
- examples/allocation/tinygo/greet.go
- examples/allocation/zig/greet.go
- experimental/wazerotest/wazerotest.go
- imports/assemblyscript/assemblyscript.go
- imports/wasi_snapshot_preview1/args_test.go
- imports/wasi_snapshot_preview1/clock_test.go
- imports/wasi_snapshot_preview1/environ_test.go
- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- imports/wasi_snapshot_preview1/poll.go
- imports/wasi_snapshot_preview1/poll_test.go
- imports/wasi_snapshot_preview1/random.go
- imports/wasi_snapshot_preview1/random_test.go
- imports/wasi_snapshot_preview1/sock.go
- imports/wasi_snapshot_preview1/sock_test.go
- imports/wasi_snapshot_preview1/wasi.go
- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/e2e_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/vs/runtime.go
- internal/logging/logging.go
- internal/wasip1/logging/logging.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/store_test.go
- runtime_test.go
This commit reverts the only/first ever breaking change we committed 
towards 2.0 release, #2085 and #2074.
These commits were made to fix a bug in our API which is described well in
https://github.com/tetratelabs/wazero/issues/1852 but the reality is that it will 
cause users to modify their existing code when they upgrade to 2.0 whose main
focus is to introduce the optimizing compiler just by updating wazero, not to fix
the bug. 
Note that this doesn't mean that we won't make any breaking change never, but this 
is more about dedicating 2.0 to the optimizing compiler, not fixing the bug which 
is highly likely that existing users will never encounter.
> api: reverts the uint32->uint64 breaking change for 2.0 release

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/engine.go
sqlite speedtest executable:
amd64: 11972703->11952159
arm64: 9913108->9902868
> wazevo(regalloc): adds missing desiredUpdated

- internal/engine/wazevo/backend/isa/amd64/instr.go
- internal/engine/wazevo/backend/isa/amd64/instr_encoding.go
- internal/engine/wazevo/backend/isa/amd64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/e2e_test.go
> wazevo(amd64): support for memory fence

- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
amd64: 8478767 bytes on main.
amd64: 8337167 bytes with predecessor check.
amd64: 8345407 bytes without predecessor check.
arm64: 8624468 on main.
arm64: 8465156 bytes with predecessor check.
arm64: 8474788 bytes without predecessor check.
amd64: 8345407 - 8337167 = 141600 bytes: ~1.6% of 8.3MB
arm64: 8624468 - 8465156 = 159312 bytes: ~1.8% of 8.6MB
amd64: 47128091 bytes on main.
amd64: 45244091 bytes with predecessor check.
arm64: 48182088 bytes on main.
arm64: 46195880 bytes with predecessor check.
amd64: 47128091 - 45244091 = 1884000 bytes: ~4.0% of 47MB
arm64: 48182088 - 46195880 = 1986208 bytes: ~4.1% of 48MB
> wazevo(frontend): stricter BCE

- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
This reduces the executable roughly 0.5%~0.7% for sqlite and zig stdlib binary.
arm64: 46195880 --> 45877240: 318640 bytes
amd64: 45244091 --> 44953739: 290352 bytes
arm64: 8465316 --> 8419684: 45632 bytes
amd64: 8337167 --> 8295535: 41632 bytes
> wazevo(frontend): stricter BCE part2

- experimental/features_example_test.go
Also has thread pointer write happen through child for readability, though since memory is shared shouldn't matter in practice
> threads: fix example should lock when creating child module

- .github/workflows/release.yaml
Do not hardcode the path to WiX toolset as it contains the version number. A recent GHA change updated 3.11 to 3.14 breaking the build.
Note for the future: when these issues arise I generally work on my own fork and use [`tmate` GHA](https://github.com/marketplace/actions/debugging-with-tmate) so that it is possible to SSH into a GHA worker and debug the issue interactively: life saver.
> ci: fix WiX toolset path for release (msi build)

- internal/wasmdebug/debug_test.go
The `TestErrorBuilderGoRuntimeError` test fails if the directory with the repository is named anything but `wazero`. The PR removes this assumption.
> Fix TestErrorBuilderGoRuntimeError

- .github/workflows/release.yaml
Fix MSI version tags for pre-releases (candle.exe won't accept version numbers with alphabetic chars in it), but also skip publishing artifacts for pre-releases.
> ci: do not upload artifacts for pre-releases

- internal/integration_test/engine/hammer_test.go
- internal/integration_test/engine/threads_test.go
- internal/testing/hammer/hammer.go
- internal/wasm/function_definition_test.go
- internal/wasm/module_instance_test.go
- internal/wasm/store_test.go
- internal/wasmdebug/dwarf_test.go
This reduces the testing time drastically for the `TestThreadsCompiler_hammer`
> testing: pass N, P into Run of hammer

- imports/wasi_snapshot_preview1/wasi_snapshot_preview1_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_test.go
- imports/wasi_snapshot_preview1/wasi_stdlib_unix_test.go
> wasi: uses the shared compilation cache in tests

- .github/workflows/integration.yaml
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/pass_blk_layouts_test.go
- internal/engine/wazevo/wazevoapi/pool.go
- internal/engine/wazevo/wazevoapi/pool_test.go
- internal/integration_test/stdlibs/bench_test.go
```
>> benchstat old.txt new8.txt
goos: darwin
goarch: arm64
│   old.txt   │              new8.txt               │
│   sec/op    │   sec/op     vs base                │
Zig/Compile/test-opt.wasm-10   4.750 ± ∞ ¹   4.842 ± ∞ ¹       ~ (p=1.000 n=1) ²
Zig/Compile/test.wasm-10       5.931 ± ∞ ¹   5.899 ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                        5.308         5.345        +0.69%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│    old.txt    │               new8.txt                │
│     B/op      │     B/op       vs base                │
Zig/Compile/test-opt.wasm-10   464.0Mi ± ∞ ¹   455.0Mi ± ∞ ¹       ~ (p=1.000 n=1) ² …
```
> wazevo: fixes accidental heap allocation in VarLengthPool.Allocate

- Makefile
- internal/integration_test/fuzz/README.md
This speeds up the fuzzing drastically at the cost of worse coverage (I think we don't care).
> fuzz: adds --no-trace-compares flag by default

- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/sort_id.go
- internal/engine/wazevo/frontend/sort_id_old.go
``` 
goos: darwin
goarch: arm64
Zig/Compile/test-opt.wasm-10   4.749 ± 2%   4.732 ± 2%       ~ (p=1.000 n=7)
Zig/Compile/test.wasm-10       5.792 ± 2%   5.798 ± 2%       ~ (p=0.383 n=7)
geomean                        5.245        5.238       -0.13%
Zig/Compile/test-opt.wasm-10   454.9Mi ± 0%   448.1Mi ± 0%  -1.50% (p=0.001 n=7)
Zig/Compile/test.wasm-10       703.8Mi ± 0%   694.7Mi ± 0%  -1.29% (p=0.001 n=7)
geomean                        565.8Mi        557.9Mi       -1.40%
│   old.txt   │ …
```
> wazevo(frontend): allocation free initializeCurrentBlockKnownBounds

- internal/engine/wazevo/entrypoint_amd64.go
- internal/engine/wazevo/entrypoint_arm64.go
- internal/engine/wazevo/entrypoint_others.go
- internal/platform/cpuid_amd64.go
- internal/platform/cpuid_unsupported.go
- internal/platform/mmap_unix.go
- internal/platform/mmap_unsupported.go
- internal/platform/mremap_other.go
- internal/platform/mremap_unix.go
Use build tags to skip some platform-specific Go code when building the project using TinyGo.
Together with my other recent PRs into the project, this one completes the set of changes required to build the project with TinyGo. When all of them are merged, I'll make sure to do one final check that it works as intended and then I'll add the TinyGo builds on CI.
Related open PRs: #2161 and #2160
> internal: skip platform-specific code when building with TinyGo

- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/ssa/basic_block.go
tl;dr: I propose to propagate the memory address only for **sealed** blocks, where we know that no predecessors will be added at a later time.
This originated from an issue raised by @jerbob92 for go-pdfium.
Essentially, it looks like block 4 of function `5011` (local ID = 4960) in go-pdfium references some values that *may* not be visibile on by some of its predecessors.
We are propagating known bounds _while_ we are creating basic blocks; which means that, at a give time, we _might not know_ all of the possible predecessors to a given block. In the case of that block 4, the SSA dump shows:
```
blk4: (v305:i32,v341:i32) <-- (blk3,blk62)
```
which means that one of the predecessors in `blk62`. However, when we enter function `initializeCurrentBlockKnownBounds()` we enter `case 1` because …
> wazevo(frontend): BCE should not propagate the memory address to unsealed blocks

- internal/wasm/memory.go
Use `hasSize` as it handles overflow: `uint32(len(m.Buffer))` overflows if a memory has 65536 pages of 65536 bytes.
Related: #1852
> fix: allow ReadByte/WriteByte to get last byte of 4GB memory

- api/wasm.go
- experimental/wazerotest/wazerotest.go
- internal/wasm/memory.go
> fix: workaround Memory.Size() overflow with 4GB memory

- api/wasm.go
- experimental/wazerotest/wazerotest.go
- internal/engine/interpreter/interpreter.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
@ncruces  `PageSize` is not appropriate name as it's defined in the spec as 65536 bytes.
> Renames PageSize -> Pages

- cmd/wazero/wazero.go
- experimental/checkpoint.go
- experimental/checkpoint_example_test.go
- experimental/checkpoint_test.go
- experimental/close.go
- experimental/close_test.go
- experimental/listener.go
- experimental/listener_example_test.go
- experimental/listener_test.go
- experimental/logging/log_listener_example_test.go
- imports/assemblyscript/assemblyscript_test.go
- imports/emscripten/emscripten_test.go
- imports/wasi_snapshot_preview1/wasi_test.go
- internal/ctxkey/checkpoint.go
- internal/ctxkey/close.go
- internal/ctxkey/listener.go
- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/e2e_test.go
- internal/integration_test/engine/adhoc_test.go
- internal/integration_test/filecache/filecache_test.go
- internal/logging/logging.go
- internal/testing/nodiff/nodiff.go
- internal/wasm/store.go
- runtime.go
We follow 2 different models in wazero for context keys:
1. one where we make the key type public and the user is supposed to do `context.WithValue(ctx, key, value)`
2. another where we expose `experimental.WithBlargh(ctx, blargh)`
The second doesn't expose the key, and is more typesafe because it ensures `blargh` is of the expected type.
This PR refactors to use *2* everywhere.
Old code left deprecated, but we can remove (since it's experimental).
> experimental: cleanup context keys

- experimental/checkpoint.go
@ncruces Thanks for the cleanup in #2175, was randomly skimming it and found this copy-paste typo.
> Fix WithSnapshotter doc to reference non-deprecated method

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/isa/amd64/abi_go_call_test.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/amd64/machine_pro_epi_logue_test.go
- internal/engine/wazevo/backend/isa/amd64/util_test.go
- internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble_test.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_call_test.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue_test.go
- internal/engine/wazevo/backend/isa/arm64/machine_relocation.go
- internal/engine/wazevo/backend/isa/arm64/machine_relocation_test.go
- internal/engine/wazevo/backend/isa/arm64/util_test.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
- internal/engine/wazevo/engine.go
- internal/integration_test/engine/adhoc_test.go
Obviates https://github.com/tetratelabs/wazero/pull/2169 and fixes #2158
> compiler(arm64): fixes overflow in huge executable relocations

- experimental/memory.go
- imports/assemblyscript/assemblyscript_test.go
- internal/ctxkey/memory.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/module.go
- internal/wasm/module_instance.go
- internal/wasm/module_test.go
- internal/wasm/store.go
Still draft, missing tests, but you can see it put to good use in https://github.com/ncruces/go-sqlite3/pull/71.
It passes extensive tests on Linux (`amd64` native, `arm64` emulated) and macOS (`amd64`/`arm64` native), and solves a long standing issue with SQLite (on those platforms).
Happy to redesign the API, putting the PR up precisely to collect early feedback!
> experimental: configure custom memory allocator

- experimental/memory.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
Addresses post submit comments in #2177.
> experimental: custom memory allocator API tweaks

- internal/wasm/memory.go
- internal/wasm/memory_test.go
/cc @ncruces 
When trying to use the custom allocator interface, I was getting crashes since the capacity wasn't being applied to the internal `m.Buffer` itself
```
[recovered]
panic: runtime error: slice bounds out of range [::266304] with capacity 196608 (recovered by wazero)
wasm stack trace:
wasi_snapshot_preview1.fd_write(i32,i32,i32,i32) i32
.$21(i32,i32,i32) i32
.$22(i32,i32,i32) i32
.$31(i32,i32,i32)
.$787(i32)
.$783(i32,i32,i32)
.$806(i32,i32,i32) i32
Go runtime stack trace:
goroutine 37 [running]:
runtime/debug.Stack()
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/debug/stack.go:24 +0x6c
github.com/tetratelabs/wazero/internal/wasmdebug.(*stackTrace).FromRecovered(0xc000a0c798, {0x101482be0, 0xc000212048})
/Users/anuraag/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.1/interna …
```
> experimental: reflect custom allocated buffer capacity to internal buffer

- internal/wasm/module_instance_test.go
- internal/wasm/store.go
Addresses https://github.com/tetratelabs/wazero/pull/2177#discussion_r1558599295 which is the only place
where we didn't assume ctx is not nil.
> Assumes ctx is not nil

- internal/wasmdebug/debug.go
- internal/wasmdebug/debug_test.go
I noticed this while debugging https://github.com/tetratelabs/wazero/issues/2198
```
wasm stack trace:
.__rust_start_panic(i32,i32) i32
0xa5a99: /rustc/ef71f1047e04438181d7cb925a833e2ada6ab390/library/panic_abort/src/lib.rs:96:17 (inlined)
/rustc/ef71f1047e04438181d7cb925a833e2ada6ab390/library/panic_abort/src/lib.rs:38:5
.rust_panic(i32,i32)
0xa5682: /rustc/ef71f1047e04438181d7cb925a833e2ada6ab390/library/std/src/panicking.rs:833:25
._ZN3std9panicking20rust_panic_with_hook17h173ea7d6a1f035f0E(i32,i32,i32,i32,i32,i32)
0xa55b5: /rustc/ef71f1047e04438181d7cb925a833e2ada6ab390/library/std/src/panicking.rs:803:5
._ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17h62f35ba2527ec452E(i32)
0xa44cf: /rustc/ef71f1047e04438181d7cb925a833e2ada6ab390/library/std/src/panicking.rs:659 …
```
> debug: do not include inlined sources in frame counts

- internal/engine/wazevo/backend/isa/amd64/instr.go
- internal/engine/wazevo/backend/isa/amd64/instr_encoding.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/instructions.go
- internal/integration_test/fuzzcases/fuzzcases_test.go
fixes https://github.com/tetratelabs/wazero/issues/2198
> amd64: saves clobbered xmm8-xmm15 beyond runtime.memmove

- internal/engine/wazevo/backend/regalloc/regalloc.go
This yields better perf on compilation as you see in the following bench result for 
compiling the wazero CLI compiled as a Wasm binary:
```
goos: darwin
goarch: arm64
│  old.txt   │           new.txt           │
│   sec/op   │   sec/op    vs base         │
Compilation-10   3.467 ± 1%   3.523 ± 4%  ~ (p=0.073 n=7)
Compilation-10   396.2Mi ± 0%   392.7Mi ± 0%  -0.89% (p=0.001 n=7)
Compilation-10   718.9k ± 0%   693.2k ± 0%  -3.58% (p=0.001 n=7)
```
> regalloc: removes map use for less memory pressure

- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/isa/arm64/abi_entry_preamble.go
- internal/engine/wazevo/backend/isa/arm64/abi_go_call.go
- internal/engine/wazevo/backend/isa/arm64/instr.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding.go
- internal/engine/wazevo/backend/isa/arm64/instr_encoding_test.go
- internal/engine/wazevo/backend/isa/arm64/instr_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_constant.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_pro_epi_logue.go
- internal/engine/wazevo/backend/isa/arm64/machine_regalloc.go
- internal/engine/wazevo/backend/isa/arm64/machine_test.go
This makes arm64's instruction data structure smaller, and 
makes it more aligned with amd64. As a result, the compilation 
gets slightly faster and uses 10% less memory space for 
compiling wazero itself.
```
goos: darwin
goarch: arm64
Compilation-10   3.444 ± 2%   3.315 ± 1%  -3.75% (p=0.001 n=7)
Compilation-10   391.2Mi ± 0%   354.7Mi ± 0%  -9.35% (p=0.001 n=7)
Compilation-10   693.3k ± 0%   695.3k ± 0%  +0.28% (p=0.001 n=7)
```
> arm64: reduces the struct size of instructions

- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/call_engine.go
- internal/engine/wazevo/module_engine.go
- internal/integration_test/engine/adhoc_test.go
- internal/wasm/engine.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
- internal/wasm/module.go
- internal/wasm/store_test.go
Since the introduction of optimizing compiler, the Memory.Grow by the users,
which has the different call path than `memory.grow` instruction, didn't propagate 
the growth result onto compiler's ModuleInstance.
Fixes #2215
> Propagates api.Memory.Grow by users to ModuleEngine

- internal/platform/mmap_unix.go
- internal/platform/mmap_unsupported.go
- internal/platform/mmap_windows.go
platform.MmapSupported hasn't been used since a while
> mmap: eliminates dead flag

- config.go
This comes up in the discussion in the slack channel,
so this commit clarifies what exactly is closed on context cancelation.
cc @lthibault
> doc: clarify WithCloseOnContextDone closes api.Module

- internal/engine/wazevo/backend/isa/amd64/machine_test.go
- internal/engine/wazevo/engine_cache.go
- internal/platform/cpuid.go
- internal/platform/cpuid_amd64.go
- internal/platform/cpuid_amd64_test.go
- internal/platform/cpuid_unsupported.go
there's a discussion about "offline" compilation, and if that happens, 
the CPU feature incompatibility becomes the problem.
This hardens the cache against it by including the cpu id in the file cache keys 
so that the content will be used exactly on the same CPUs.
Note that this impacts only amd64 target.
> cache: includes cpu features in cache keys

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
This commit makes `path_open` return `inval` when passed an empty path. This behavior is consistent with other Wasm runtimes (Wasmtime, Wasmer, Node, WAMR, WasmEdge).
fixes #2222
> Disallow empty path on path_open

- internal/integration_test/fuzzcases/fuzzcases_test.go
This case has been skipped due to a bug I found in Rosetta 2.
The bug was fixed in the latest macOS, so enable it now.
See https://x.com/mathetake/status/1761175001070477392
> Runs the test case previously failing due to a bug in Rosseta 2

- internal/engine/wazevo/backend/regalloc/regalloc.go
This refactors `fixMergeState` function to remove the last use of map,
which previously caused a lot of allocations.
As a result, this improves the compilation time ~2% and makes it to use
less memory allocations. The blow is the benchmark results for the 
standard libraries as well as compiling wazero itself.
```
goos: darwin
goarch: arm64
│ old_zig.txt │           new_zig.txt            │
│   sec/op    │   sec/op    vs base              │
Zig/Compile/test-opt.wasm-10    4.503 ± 1%   4.497 ± 1%       ~ (p=0.902 n=7)
Zig/Run/test-opt.wasm-10        19.09 ± 1%   18.79 ± 1%  -1.56% (p=0.001 n=7)
Zig/Compile/test.wasm-10        5.739 ± 2%   5.712 ± 0%  -0.47% (p=0.002 n=7)
Zig/Run/test.wasm-10            19.36 ± 1%   19.17 …
```
> regalloc: removes the last use of map for faster allocation

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
- internal/engine/wazevo/backend/regalloc/regset.go
This makes the compilation slightly faster and simplifies the codebase.
```
goos: darwin
goarch: arm64
Compilation-10   2.499 ± 0%   2.478 ± 2%  -0.84% (p=0.026 n=7)
│   old.txt    │            new.txt            │
│     B/op     │     B/op      vs base         │
Compilation-10   341.0Mi ± 0%   341.1Mi ± 0%  ~ (p=0.128 n=7)
│   old.txt   │           new.txt            │
│  allocs/op  │  allocs/op   vs base         │
Compilation-10   606.9k ± 0%   606.9k ± 0%  ~ (p=0.383 n=7)
```
> regalloc: simplifies regInUseSet

- internal/engine/wazevo/backend/executable_context.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_test.go
This makes the compilation slightly more faster with less memory:
```
benchstat old.txt new.txt
goos: darwin
goarch: arm64
Compilation-10   2.488 ± 0%   2.438 ± 0%  -2.00% (p=0.001 n=7)
Compilation-10   341.1Mi ± 0%   340.3Mi ± 0%  -0.23% (p=0.001 n=7)
Compilation-10   607.0k ± 0%   605.5k ± 0%  -0.26% (p=0.001 n=7)
```
#2182
> backend: removes the map use in ExecutableContext[Instr]

- internal/engine/wazevo/ssa/basic_block.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/pass_cfg.go
- internal/engine/wazevo/ssa/pass_cfg_test.go
loopNestingForestChildren is non-empty only when the basic block
is a loop header, and hence previously the slice hasn't been reused much.
This resolves it, and as a result, the compilation uses slightly less memory.
```
goos: darwin
goarch: arm64
│  old.txt   │           new.txt           │
│   sec/op   │   sec/op    vs base         │
Compilation-10   2.423 ± 0%   2.436 ± 2%  ~ (p=0.097 n=7)
Compilation-10   340.3Mi ± 0%   339.9Mi ± 0%  -0.10% (p=0.001 n=7)
Compilation-10   605.5k ± 0%   603.9k ± 0%  -0.27% (p=0.001 n=7)
```
#2182
> ssa: reuses slice on basicBlock.loopNestingForestChildren

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
This commit fixes `path_symlink` not working when `-mount` is not supplied with a mapped directory.
fixes #2228
> Fix path_symlink only works when dir mounted to /

- internal/engine/wazevo/backend/backend_test.go
- internal/engine/wazevo/frontend/frontend.go
- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/type.go
This avoids the unnecessary duplicated zero initial value definitions 
for Wasm function locals. As a result, for certain binaries which
have huge number of locals like Zig standard libraries,  we can see
1~10% improvements in compilation performance without impacting 
other cases like the below.
```
│ old_zig.txt │            new_zig.txt            │
│   sec/op    │   sec/op    vs base               │
Zig/Compile/test-opt.wasm-10    4.466 ± 2%   4.399 ± 0%   -1.50% (p=0.007 n=7)
Zig/Run/test-opt.wasm-10        18.86 ± 0%   18.84 ± 0%        ~ (p=0.535 n=7)
Zig/Compile/test.wasm-10        5.684 ± 1%   5.084 ± 1%  -10.55% (p=0.001 n=7)
Zig/Run/test.wasm-10            19.28 ± 1%   19.25 ± 1%        ~ (p=0.535 n=7)
geomean                         9.802        9.490        -3.18%
│ …
```
> ssa: memory usage optimization around lastDefinitions

- internal/engine/wazevo/ssa/basic_block.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/pass_blk_layouts.go
- internal/engine/wazevo/ssa/pass_blk_layouts_test.go
- internal/engine/wazevo/ssa/pass_cfg.go
This removes the use of map in basic block traversals.
As a result, overall compilation perf improves like the below:
```
goos: darwin
goarch: arm64
│ old_zig.txt │            new_zig.txt            │
│   sec/op    │   sec/op    vs base               │
Zig/Compile/test-opt.wasm-10    4.438 ± 1%   3.778 ± 0%  -14.87% (p=0.002 n=6)
Zig/Run/test-opt.wasm-10        18.77 ± 1%   18.76 ± 0%        ~ (p=0.818 n=6)
Zig/Compile/test.wasm-10        5.083 ± 0%   4.673 ± 0%   -8.07% (p=0.002 n=6)
Zig/Run/test.wasm-10            19.27 ± 1%   19.30 ± 1%        ~ (p=0.699 n=6)
geomean                         9.504        8.941        -5.92%
│ old_zig.txt  │            new_zig.txt             │
│     B/op     │     B/op      vs base …
```
> ssa: removes map use for block traversals

- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/builder.go
- internal/wasm/func_validation.go
- internal/wasm/module.go
This stops gathering `NonStaticLocals` during validation phase,
which was previously used to do the "fast pass" on variable search
by the frontend. However, it had no impact after the last mile refactoring
included in 1.7.0 and caused tons of allocations.
As as result, you can see the compilation perf improvements especially
around memory pressure without any impacts on the runtime perf
```
goos: darwin
goarch: arm64
│ old_zig.txt │           new_zig.txt            │
│   sec/op    │   sec/op    vs base              │
Zig/Compile/test-opt.wasm-10    3.769 ± 1%   3.761 ± 1%       ~ (p=0.485 n=6)
Zig/Run/test-opt.wasm-10        18.78 ± 1%   18.74 ± 0%  -0.21% (p=0.041 n=6)
Zig/Compile/test.wasm-10        4.677 ± 1%   4.515 …
```
> Removes non-static locals collection

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/wazevoapi/pool.go
This also early stops resetting IDedPool.
```
goos: darwin
goarch: arm64
│ old_zig.txt │           new_zig.txt            │
│   sec/op    │   sec/op    vs base              │
Compilation-10    4.540 ± 0%   4.380 ± 1%  -3.51% (p=0.001 n=7)
│ old_zig.txt  │          new_zig.txt          │
│     B/op     │     B/op      vs base         │
Compilation-10   599.3Mi ± 0%   599.3Mi ± 0%  ~ (p=0.383 n=7)
│ old_zig.txt │         new_zig.txt          │
│  allocs/op  │  allocs/op   vs base         │
Compilation-10   288.0k ± 0%   288.0k ± 0%  ~ (p=0.805 n=7)
```
```
goos: darwin
goarch: arm64
Compilation-10   2.264 ± 1%   2.224 ± 0% …
```
> regalloc: removes unnecessary Instruction.Uses

- cache_example_test.go
In the cache example test, the function `newRuntimeCompileClose` had a doc comment named: `newRuntimeCompileDestroy`.
> fix typo in the cache example test function name

- internal/engine/wazevo/backend/regalloc.go
This improves the compilation slightly as below:
```
goos: darwin
goarch: arm64
│ old_zig.txt │           new_zig.txt            │
│   sec/op    │   sec/op    vs base              │
Compilation-10    2.227 ± 0%   2.184 ± 1%  -1.96% (p=0.001 n=7)
│ old_zig.txt  │            new_zig.txt             │
Compilation-10   337.2Mi ± 0%   337.3Mi ± 0%  +0.02% (p=0.001 n=7)
│ old_zig.txt │            new_zig.txt            │
Compilation-10   593.5k ± 0%   592.9k ± 0%  -0.10% (p=0.001 n=7)
```
```
goos: darwin
goarch: arm64 …
```
> regalloc: removes map from RegAllocFunction

- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/pass_cfg.go
This makes the compilation faster and use less memory:
```
goos: darwin
goarch: arm64
Compilation/wazero-10   2.184 ± 0%   2.110 ± 0%  -3.40% (p=0.001 n=7)
Compilation/zig-10      4.331 ± 1%   4.187 ± 1%  -3.31% (p=0.001 n=7)
geomean                 3.075        2.972       -3.36%
Compilation/wazero-10   337.3Mi ± 0%   301.9Mi ± 0%  -10.49% (p=0.001 n=7)
Compilation/zig-10      599.3Mi ± 0%   594.3Mi ± 0%   -0.84% (p=0.001 n=7)
geomean                 449.6Mi        423.6Mi        -5.79%
│ …
```
> ssa: optimizes slice allocations

- internal/engine/wazevo/frontend/frontend_test.go
- internal/engine/wazevo/ssa/builder.go
This removes the unnecessary search and addition of block params.
As a result, the compilation gets faster up to 30% while having no
impacts on the runtime performance like the below
```
goos: darwin
goarch: arm64
│ old_tinygo.txt │            new_tinygo.txt             │
│     sec/op     │     sec/op      vs base               │
TinyGo/Compile/container_heap.test-10      389.2m ± 0%   305.5m ±  0%    -21.50% (p=0.001 n=7)
TinyGo/Run/container_heap.test-10          14.80m ± 4%   14.24m ±  1%          ~ (p=0.053 n=7)
TinyGo/Compile/container_list.test-10      387.1m ± 0%   304.8m ±  1%    -21.26% (p=0.001 n=7)
TinyGo/Run/container_list.test-10          14.11m ± 1%   14.06m ±  1%          ~ (p=0.902 n=7) …
```
> ssa: optimizes findValue function

- imports/wasi_snapshot_preview1/fs.go
- imports/wasi_snapshot_preview1/fs_test.go
- internal/sysfs/file.go
This commit fixes a `path_open` behavior that allows a directory to be `path_open`ed with the `rights::fd_write` flag.  Since Wazero considers it to be an error to open a directory with the write flag normally, it is safe to treat this as a bug.  Although rights/capability system is being scrapped, we still use the `fd_read` and `fd_write` flag to determine if write permission needs to be set.
fixes #2243
> wasi: `path_open` should accept a dir with RIGHT_FD_WRITE

- .github/workflows/commit.yaml
- .github/workflows/integration.yaml
- .github/workflows/release.yaml
This removes amd64/macOS test environments.
Each dimension is tested separately even after this, 
so this saves the CI resources.
> ci: removes amd64/macOS tests

- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/isa/arm64/util_test.go
- internal/engine/wazevo/frontend/lower.go
- internal/engine/wazevo/ssa/basic_block.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/instructions.go
- internal/engine/wazevo/ssa/pass_blk_layouts.go
- internal/engine/wazevo/ssa/pass_blk_layouts_test.go
This optimizes the memory usage during compilation for 
br_table instructions. As you can see in the bench results below,
for some cases where lots of br_tables exists (the case named `zz`),
the compilation uses 10% less allocations and 5% less memory, hence
the slightly faster compilation.
```
goos: darwin
goarch: arm64
Compilation/wazero-10   2.015 ± 2%   1.993 ± 0%  -1.09% (p=0.002 n=6)
Compilation/zig-10      4.200 ± 0%   4.161 ± 1%  -0.93% (p=0.004 n=6)
Compilation/zz-10       18.70 ± 0%   18.57 ± 0%  -0.69% (p=0.002 n=6)
geomean                 5.409        5.360       -0.90%
│     B/op     │ …
```
> compiler: memory usage optimization around br_table

- internal/wasm/func_validation.go
This eliminates the allocation that previously happened
per br_table instruction during function validation.
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.993 ± 0%   1.995 ± 0%       ~ (p=0.485 n=6)
Compilation/zig-10      4.161 ± 1%   4.169 ± 0%       ~ (p=0.699 n=6)
Compilation/zz-10       18.57 ± 0%   18.55 ± 0%       ~ (p=0.240 n=6)
geomean                 5.360        5.363       +0.06%
Compilation/wazero-10   287.1Mi ± 0%   286.8Mi ± 0%  -0.13% (p=0.002 n=6)
Compilation/zig-10      590.3Mi ± 0%   590.3Mi ± 0%  -0.01% (p=0.002 n=6) …
```
> validation: avoids allocation per br_table

- internal/engine/wazevo/frontend/lower.go
Previously, the `tmpForBrTable` slice hadn't been
correctly reused, and this fixes it.
As a result, for br_table heavy cases, we see the huge
drop in the number of allocations:
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.995 ± 0%   1.999 ± 1%       ~ (p=0.394 n=6)
Compilation/zig-10      4.169 ± 0%   4.168 ± 1%       ~ (p=0.589 n=6)
Compilation/zz-10       18.55 ± 0%   18.55 ± 0%       ~ (p=0.818 n=6)
geomean                 5.363        5.367       +0.06%
Compilation/wazero-10   286.8Mi ± 0%   285.4Mi ± 0%  -0.46% (p=0.002 n=6) …
```
> frontend: reuses br_table tmp slice correctly

- internal/engine/wazevo/backend/regalloc/regalloc.go
This eliminates the unnecessary Instructions loop in
register allocation by sacrificing an almost negligible 
memory space. As a result,  overall compilation gets
1% faster than before.
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.973 ± 1%   1.945 ± 0%  -1.42% (p=0.002 n=6)
Compilation/zig-10      4.128 ± 0%   4.068 ± 1%  -1.45% (p=0.002 n=6)
Compilation/zz-10       18.32 ± 0%   18.08 ± 1%  -1.27% (p=0.002 n=6)
geomean                 5.303        5.230       -1.38%
Compilation/wazero-10   284.4Mi ± 0%   284.8Mi ± 0%  +0.13% (p=0.002 n=6) …
```
> regalloc: eliminates unnecessary Instr loop

- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
- internal/engine/wazevo/backend/regalloc/regset.go
This refactors the regalloc code and makes the access to
vrState pointers really fast and reduce the unnecessary 
function calls that cannot be inlined. As a result, overall
compilation perfomance improves +10% with a slight cost
of memory usage without any impact on the runtime performance.
```
goos: darwin
goarch: arm64
│    old.txt    │              new.txt               │
│    sec/op     │   sec/op     vs base               │
Zig/Compile/test-opt.wasm-10                           3.280 ±  1%    2.976 ± 1%   -9.25% (p=0.001 n=7)
Zig/Compile/test.wasm-10                               4.078 ±  1%    3.771 ± 2%   -7.51% (p=0.001 n=7)
TinyGo/Compile/container_heap.test-10                 299.6m ±  2%   266.1m ± 1% …
```
> regalloc: fast access to vrState

- internal/engine/wazevo/backend/regalloc/regalloc.go
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.721 ± 0%   1.721 ± 0%       ~ (p=0.818 n=6)
Compilation/zig-10      3.764 ± 3%   3.765 ± 0%       ~ (p=0.818 n=6)
Compilation/zz-10       16.06 ± 5%   16.00 ± 0%  -0.40% (p=0.015 n=6)
geomean                 4.703        4.697       -0.13%
Compilation/wazero-10   291.0Mi ± 0%   286.8Mi ± 0%  -1.47% (p=0.002 n=6)
Compilation/zig-10      610.0Mi ± 0%   601.7Mi ± 0%  -1.37% (p=0.002 n=6)
Compilation/zz-10       538.8Mi ± 0%   538.2Mi ± 0%  -0.12% (p=0.002 n=6)
geomean                 457.3Mi …
```
> regalloc: use less memory in liveness analysis

- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine.go
- internal/engine/wazevo/backend/regalloc/regalloc.go
- internal/engine/wazevo/backend/regalloc/regalloc_test.go
- internal/engine/wazevo/backend/regalloc/regset.go
This is a follow-up on https://github.com/tetratelabs/wazero/pull/2265.
It basically removes the interface invocation completely, but the 
benchmark result doesn't show any diff, so this is more of a cleanup 
and consistency in the codebase.
> regalloc: complete de-virtualization

- internal/engine/interpreter/compiler.go
This makes the interpreter's compilation faster by removing the 
unnecessary stack walks. As a result, for some binary, we observe
93% drops in the compilation performance(!) with an additional 
but negligible memory usage.
```
goos: darwin
goarch: arm64
│    sec/op    │   sec/op     vs base               │
Compilation/wazero-10    130.1m ± 1%   124.7m ± 1%   -4.12% (p=0.002 n=6)
Compilation/zig-10      9097.2m ± 0%   549.0m ± 1%  -93.96% (p=0.002 n=6)
Compilation/zz-10         1.159 ± 5%    1.145 ± 3%   -1.20% (p=0.041 n=6)
TinyGo/Compile/container_heap.test-10     16.54m ± 1%   15.60m ± 4%  -5.66% (p=0.002 n=6)
TinyGo/Compile/container_list.test-10     16.36m ± 1%   15.42m ± 1%  -5.74% (p=0.002 n=6) …
```
> interpreter: removes unneeded stack walks

- config.go
Anonymous modules are introduced like a few years ago 
to allow multiple/concurrent instantiations from a single
binary. That was not documented enough well, so this
adds doc comments in the API.
> doc: adds comments on anonymous module names

- internal/wasm/memory.go
Fixes #2278 
I have rerun tests with race in go-re2 a few times, it was a flaky repro, but for now haven't seen any race after this
> threads: lock around invocations of memory.Grow

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/vdef.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/builder_test.go
- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/pass_test.go
- internal/engine/wazevo/ssa/vs.go
This improves the compilation perf by up to ~30% without 
runtime perf impacts.
```
goos: darwin
goarch: arm64
│    sec/op    │   sec/op     vs base               │
Zig/Compile/test-opt.wasm-10                    2.683 ± 1%    2.591 ± 1%   -3.44% (p=0.002 n=6)
Zig/Run/test-opt.wasm-10                        18.75 ± 0%    19.03 ± 1%   +1.48% (p=0.004 n=6)
Zig/Compile/test.wasm-10                        3.529 ± 0%    3.516 ± 1%        ~ (p=0.180 n=6)
Zig/Run/test.wasm-10                            19.55 ± 2%    19.48 ± 1%        ~ (p=0.310 n=6)
TinyGo/Compile/container_heap.test-10          298.1m ± 1%   210.1m ± 0%  -29.51% (p=0.002 n=6) …
```
> ssa: removes map use for Value aliasing

- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/pass.go
- internal/engine/wazevo/ssa/vs.go
- internal/engine/wazevo/ssa/vs_test.go
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.564 ± 0%   1.536 ± 1%  -1.78% (p=0.002 n=6)
Compilation/zig-10      3.461 ± 0%   3.421 ± 0%  -1.13% (p=0.002 n=6)
Compilation/zz-10       14.28 ± 0%   14.06 ± 1%  -1.57% (p=0.002 n=6)
geomean                 4.260        4.196       -1.49%
Compilation/wazero-10   286.2Mi ± 0%   283.0Mi ± 0%  -1.13% (p=0.002 n=6)
Compilation/zig-10      598.2Mi ± 0%   596.7Mi ± 0%  -0.25% (p=0.002 n=6)
Compilation/zz-10       538.0Mi ± 0%   536.5Mi ± 0%  -0.28% (p=0.002 n=6)
geomean                 451.6Mi …
```
> ssa: removes valueIDToInstruction slice

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/isa/amd64/lower_mem.go
- internal/engine/wazevo/backend/isa/amd64/lower_mem_test.go
- internal/engine/wazevo/backend/isa/amd64/machine_test.go
- internal/engine/wazevo/backend/isa/amd64/operands.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
- internal/engine/wazevo/backend/vdef.go
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.541 ± 0%   1.535 ± 0%  -0.37% (p=0.015 n=6)
Compilation/zig-10      3.422 ± 0%   3.413 ± 0%  -0.27% (p=0.004 n=6)
Compilation/zz-10       14.10 ± 0%   14.08 ± 0%       ~ (p=0.310 n=6)
geomean                 4.205        4.194       -0.25%
Compilation/wazero-10   283.0Mi ± 0%   273.4Mi ± 0%  -3.38% (p=0.002 n=6)
Compilation/zig-10      596.7Mi ± 0%   594.7Mi ± 0%  -0.32% (p=0.002 n=6)
Compilation/zz-10       536.5Mi ± 0%   532.4Mi ± 0%  -0.76% (p=0.002 n=6)
geomean                 449.1Mi …
```
> backend: removes unnecessary ValueDefinition fields

- internal/engine/wazevo/backend/compiler.go
- internal/engine/wazevo/backend/compiler_lower.go
- internal/engine/wazevo/backend/compiler_lower_test.go
- internal/engine/wazevo/backend/isa/amd64/lower_mem.go
- internal/engine/wazevo/backend/isa/amd64/lower_mem_test.go
- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/amd64/machine_test.go
- internal/engine/wazevo/backend/isa/amd64/operands.go
- internal/engine/wazevo/backend/isa/amd64/util_test.go
- internal/engine/wazevo/backend/isa/arm64/abi.go
- internal/engine/wazevo/backend/isa/arm64/abi_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_operands_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_instr_test.go
- internal/engine/wazevo/backend/isa/arm64/lower_mem_test.go
- internal/engine/wazevo/backend/isa/arm64/util_test.go
- internal/engine/wazevo/backend/vdef.go
- internal/engine/wazevo/ssa/builder.go
- internal/engine/wazevo/ssa/pass.go
```
goos: darwin
goarch: arm64
Compilation/wazero-10   1.536 ± 1%   1.535 ± 0%       ~ (p=0.589 n=6)
Compilation/zig-10      3.405 ± 1%   3.411 ± 0%       ~ (p=0.240 n=6)
Compilation/zz-10       14.03 ± 0%   14.05 ± 0%       ~ (p=0.310 n=6)
geomean                 4.186        4.190       +0.09%
Compilation/wazero-10   273.4Mi ± 0%   257.4Mi ± 0%  -5.84% (p=0.002 n=6)
Compilation/zig-10      594.7Mi ± 0%   592.2Mi ± 0%  -0.42% (p=0.002 n=6)
Compilation/zz-10       532.4Mi ± 0%   525.7Mi ± 0%  -1.26% (p=0.002 n=6)
geomean                 442.4Mi …
```
> backend: stop allocating ValueDefinitions

- examples/concurrent-instantiation/main.go
Helps showcase best practises by having each instance release it's resources when no longer needed.
> Show close for concurrent-instantiation example

- internal/engine/interpreter/interpreter.go
- internal/engine/wazevo/module_engine.go
- internal/engine/wazevo/module_engine_test.go
- internal/wasm/engine.go
- internal/wasm/store.go
- internal/wasm/store_test.go
Fixes #2313.
This changes the signature for `ResolveImportedFunction()` so that it takes an additional index into the typeID section of the "current" module, i.e. the subject of the import.
The current behavior is to search for the import recursively into the chain of dependencies; however, this resolves to a typeID that is specific to _that_ module. For instance:
- consider the case of a module `m` declaring an import `m2inst.sym`.
- let be `m2inst.sym` an import with type `t` with ID `tid` 
- let be `m2inst` be linked to an instance of module `m2` with type `t2` and ID `t2id`.
Now: we want `t` to be compatible with `t2`; this we verify at:
https://github.com/tetratelabs/wazero/blob/6bb9899ea4c745a4ae23179a34fac0540c2ce551/internal/wasm/store.go#L441-L447
The current behavior is for …
> compiler: ResolveImportedFunction should infer the typeID from the importing module

- experimental/memory.go
- internal/wasm/memory.go
- internal/wasm/memory_test.go
Hey! 👋
This is just an idea, but the change was small enough that I decided to just try it.
How would we feel about allowing the custom allocator to return `nil` to signal it can't grow the linear memory?
In Go, a failure to allocate memory is a fatal condition, so it makes sense that we don't think about this when using `append` to grow the linear memory.
But custom allocators can handle this, it doesn't need to be a fatal condition. Also Wasm modules can deal with it: e.g. for `wasi-lib`, if `sbrk` fails, `malloc` just returns `NULL`, and (e.g.) SQLite can deal with that by freeing caches and trying again (if configured to do so).
cc: @anuraaga
> Allow custom memory allocator Reallocate to fail

- internal/sysfs/file.go
- internal/sysfs/file_test.go
- internal/sysfs/osfile.go
- sys/stat.go
Fixes #2318.
Reopening the file was erroneously not updating the `fd` field.
Also, reopening is risky, because the file have been deleted/renamed (yes, even on Windows, because we're using `FILE_SHARE_DELETE`).
In theory, on POSIX, we'd never need to reopen (hence why WASI provides this, it tries to offer much of what POSIX allows, neglecting that lots of it is hard to emulate). But... reopen is only is only really used in two places: seeking directories (to rewind them), and setting the file's append flag.
For directory rewind, it's _already_ just a fallback:
https://github.com/tetratelabs/wazero/blob/6bb9899ea4c745a4ae23179a34fac0540c2ce551/internal/sysfs/osfile.go#L196-L209
If seeking works, it's used. So, no point in trying to "fix" that one.
For setting the append flag, reopen is …
> sysfs: reopening file doesn't update fd

- internal/sysfs/dirfs_supported.go
- internal/sysfs/dirfs_test.go
This implements this bit of the [path resolution specification](https://github.com/WebAssembly/wasi-filesystem/blob/v0.2.0/path-resolution.md#symlinks) (see #2323), and seems like a good idea regardless.
> sysfs: disallow absolute symlinks

- experimental/memory.go
I should know this code better but did manage to mess it up anyways...
https://github.com/wasilibs/go-pgquery/pull/32
> experimental: clarify memory allocator context is for module instantiation

- .github/actions/vmactions/template.yml
- .github/workflows/commit.yaml
- README.md
Hot on the heels of #2338, this adds more OSes using a different action.
The only note compared to the previous one is that, compared to [`cross-platform-actions/action`](https://github.com/cross-platform-actions/action), [`vmactions`](https://github.com/vmactions) has one action per OS, which is harder to configure, because [GitHub doesn't allow matrix runs to configure `uses` dependencies](https://github.com/orgs/community/discussions/9049).
So I had to create a custom action `template.yml`, and use `envsubst` to change the `uses` dependency.
The stretch goal is to, as a follow up, enable the compiler in many of these, confident that it works: https://github.com/ncruces/wazero/pull/3
I also fixed up the `README` because we're erroneously claiming we test macOS on `amd64`, but moving to …
> Add DragonFly, illumos, Solaris to CI.

- README.md
- config_supported.go
- config_unsupported.go
- internal/platform/mmap_other.go
- internal/platform/mmap_unix.go
- internal/platform/mmap_unsupported.go
- internal/platform/mprotect_bsd.go
- internal/platform/mprotect_syscall.go
- internal/platform/mprotect_unsupported.go
- internal/platform/platform.go
This culminates this series of changes, enabling the compiler on:
- NetBSD `amd64` and `arm64`
- DragonFly BSD `amd64`
- illumos `amd64`
- Solaris `amd64`
We're not currently testing `arm64` for either FreeBSD or NetBSD, but I've tested them. The emulation is slow, I'm not sure if it's worth it. The others are not supported Go `arm64` targets.
OpenBSD was not added because it failed with an SIGSEGV. If anyone wants to take a stab at this, I'd welcome it.
> Enable compiler on NetBSD, DragonFly, illumos and Solaris

- config_supported.go
- internal/platform/cpuid.go
- internal/platform/cpuid_amd64.go
- internal/platform/cpuid_amd64.s
- internal/platform/cpuid_arm64.go
- internal/platform/cpuid_arm64.s
- internal/platform/cpuid_unsupported.go
- internal/platform/platform.go
- internal/platform/platform_arm64.go
This checks that [Large System Extensions](https://learn.arm.com/learning-paths/servers-and-cloud-computing/lse/intro/) (atomic instructions) are supported on `arm64`. These are included in many processors, and are part of ARMv8.1, which is required by macOS and Windows.
This is similar to the check that the `amd64` CPUs support SSE4.1 (which is part of x86-64-v2, and available on most processors).
Biggest behavioral change is using `platform.CompilerSupported()` to decide whether to (not) use the compiler on `wazero.NewRuntimeConfig()`, but I think this makes sense.
> compiler: require ARMv8.1

- internal/engine/wazevo/backend/isa/amd64/machine.go
- internal/engine/wazevo/backend/isa/arm64/machine_relocation.go
- internal/engine/wazevo/backend/isa/arm64/machine_relocation_test.go
- internal/engine/wazevo/backend/machine.go
- internal/engine/wazevo/backend/machine_test.go
- internal/engine/wazevo/engine.go
Fixes #2340 
Thanks @davidmdm for reporting the issue. Please do confirm if this solves your problem!
Here's a summary for the lazy. On arm64, when we compute the offsets in a trampoline, the following function is given a mapping between **all** function refs (basically Indexes in the original Wasm file) and offsets (`refToBinaryOffset`).
```go
func encodeCallTrampolineIsland(refToBinaryOffset []int, islandOffset int, executable []byte) {
for i := 0; i < len(refToBinaryOffset); i++ {
trampolineOffset := islandOffset + trampolineCallSize*i
```
Wasm function indexes account for _all_ functions, including _imported_ functions. However, we do not need to allocate space for such functions in the "trampoline island". In fact, _we do not account for them_:
```go
trampolineInterval, …
```
> arm64: account for imported functions when encoding relocation islands

- .github/workflows/integration.yaml
libsodium was failing across the board because of a not explicit dependency on tinygo.
> Fix integration tests.

- internal/sysfs/osfile.go
As POSIX states, if a file is removed from or added to the directory after the most recent call to `opendir()` or `rewinddir()`, whether a subsequent call to `readdir()` returns an entry for that file is unspecified.
So there is no guarantee that files added after `opendir()` will be visible in `readdir()`. We need to `reopendir()` to get the new state of the directory before `readdir()`.
`Btrfs` was modified to track the last index number in `opendir()` and make `readdir()` never process beyond that index number (https://github.com/torvalds/linux/commit/9b378f6ad48cfa195ed868db9123c09ee7ec5ea2). This change was introduced in Linux 6.4.12 (see https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.4.12). I think this change is the reason of the test failures in #2335.
I noticed that …
> sysfs: always reopen directory before readdir

- .github/workflows/commit.yaml
These just entered public preview:
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> CI: use Linux ARM runners.

- runtime.go
Fixes #2353, supersedes #2354.
Returning a `nil` pointer to a struct implementing the interface is bad form, and a bug (the `nil` doesn't actually implement the interface: it panics).
I don't love naked returns in this big a function either, but the rest of the assumptions in #2354 were problematic, and were blocking the fix.
> runtime: return nil interface not nil pointer on error

- site/content/community/users.md
Context from the wazero slack channel: https://gophers.slack.com/archives/C040AKTNTE0/p1739635237444679
Abridged version:
> The project is called [Yoke](https://github.com/yokecd/yoke), and it is a [Candidate to become a CNCF Sandbox project](https://github.com/cncf/sandbox/issues/317).
>Yoke is a modern alternative to helm. It is a package manager for Kubernetes, but instead of writing Helm charts (which are collections of templated YAML files), you define your package's logic in code. The code is then packaged into a single portable executable wasip1/wasm executable.
I would be honoured if my project could be added to the list of wazero community projects.
> docs: add yoke to community users

- internal/engine/wazevo/backend/isa/amd64/machine.go
Fixes #2375
Go 1.24 changed memmove implementation on amd64, which resulted in an extra register allocation. This makes sure to reserve it for memmove invocation. While this could be a regression on go 1.23, it seems not significant enough to have version-specific code for this especially since it will go out-of-date soon.
Originally, @mathetake had suggested vendoring in the working go 1.23's memmove implementation, which both fixes and ensures forward compatibility, but I couldn't let go of the 30% perf gain from the change. After this, someone may want to try vendoring 1.24's implementation (it's not trivial due to needing to read many cpu flags), for forward compatibility, but before it I would check whether it's worth using the direct call to save on host function call overhead if …
> wazevo(amd64): reserve dx when calling memmove to support go 1.24

- internal/integration_test/engine/adhoc_test.go
> Fixes testHostFunctionNumericParameter

- internal/integration_test/stdlibs/bench_test.go
this test will not resolve DevNull to NUL on WASI, failing on Windows, so it is safe to skip.
It's a new test introduced with Go 1.24.1 released on March 4 (see https://github.com/golang/go/commit/30f4d9e117ba66f77bf9dc507da4ad35c747d0cb)
The CI implicitly picked up the update, causing other unrelated PRs to fail.
> bench: skip TestOpenFileDevNull on Windows

- internal/engine/wazevo/backend/isa/arm64/machine_relocation.go
- internal/engine/wazevo/backend/isa/arm64/machine_relocation_test.go
Fixes #2382, follow up to #2346 
In #2346 we forgot that the unconditional relative jump to the relocation island should account for the imported functions as well.
> arm64: account for imported funcs in the branch to a relocation island

- internal/engine/wazevo/frontend/lower.go
PR https://github.com/tetratelabs/wazero/pull/2395 was merged with a typo.
I also compared this with the conditional move approach (i.e. `chunk := min(i, 8192)` instead of `chunk := ((i - 1) & 8191) + 1`). In terms of performance and code size it's a wash.
But if you prefer it for clarity (and consistency with [`bytes.Repeat`](https://github.com/golang/go/blob/go1.24.0/src/bytes/bytes.go#L664-L673)), I can happily do the change here.
> Fix typo in memory fill.

- internal/integration_test/stdlibs/bench_test.go
test is currently failing consistently, let's disable it for now
> bench: disable TestOpenFileCreateExclDanglingSymlink on Windows

- internal/sysfs/file_test.go
The default pipe size is 1M (see `man 7 pipe`), and this test is only trying to fill it with 100K, so increase the fill size so it isn't so flaky.
> TST: Increase buffer size of TestWriteFdNonblock
